--- Comando que apunta a la base de datos apropiada ---
USE ${var:base_datos};
SET DECIMAL_V2=FALSE;

ALTER TABLE MIS_DWH_MANUAL_ADJ_ACC
DROP IF EXISTS PARTITION (DATA_DATE = '${var:periodo}');

ALTER TABLE MIS_DWH_MANUAL_ADJ_ACC
ADD IF NOT EXISTS PARTITION (DATA_DATE = '${var:periodo}');

ALTER TABLE MIS_DWH_MANUAL_ADJ_SPE_ACC
DROP IF EXISTS PARTITION (DATA_DATE = '${var:periodo}');

ALTER TABLE MIS_DWH_MANUAL_ADJ_SPE_ACC
ADD IF NOT EXISTS PARTITION (DATA_DATE = '${var:periodo}');

--- Llenado de Tabla de Ajustes Manuales Contables ---
LOAD DATA INPATH '${var:ruta_fuentes_ajustes}/Ajustes_Manuales_Contables.csv' INTO TABLE MIS_DWH_MANUAL_ADJ_ACC PARTITION (DATA_DATE = '${var:periodo}');

--- Llenado de Tabla de Ajustes Manuales Contables Especiales---
LOAD DATA INPATH '${var:ruta_fuentes_ajustes}/Ajustes_Manuales_Contables_Especiales.csv' INTO TABLE MIS_DWH_MANUAL_ADJ_SPE_ACC PARTITION (DATA_DATE = '${var:periodo}');

--- Limpieza de tabla de rechazos por ajustes manuales contables ---
TRUNCATE TABLE MIS_DWH_MANUAL_ADJ_OPER_REJECTIONS;

---Rechazo de registros ingresados sin alguna de las dimensiones principales
INSERT INTO MIS_DWH_MANUAL_ADJ_OPER_REJECTIONS
SELECT 'CONT', 'Rechazo: existen dimensiones vacías', '', a.AGRUPADOR_CONTABLE, a.ENTIDAD, a.DIVISA, '', '', a.PRODUCTO_BALANCE, a.CUENTA_PYG, '', '', '', 
    a.IMPORTE_ML, a.IMPORTE_MO, a.SALDO_MEDIO_ML, a.SALDO_MEDIO_MO, a.PL_ML, a.PL_MO
FROM MIS_DWH_MANUAL_ADJ_ACC a
WHERE TRIM(a.AGRUPADOR_CONTABLE) = '' OR TRIM(a.CUENTA_PYG) = '' OR TRIM(a.PRODUCTO_BALANCE) = '' OR TRIM(a.LINEA_NEGOCIO) = '' 
    OR TRIM(a.ENTIDAD) = '' OR TRIM(a.DIVISA) = '';

---Validación de cierre: Agrupador Contable no existe o es diferente del definido en la parametria
INSERT INTO MIS_DWH_MANUAL_ADJ_OPER_REJECTIONS
SELECT 'CONT', 'Validación: AGRUPADOR CONTABLE no encontrado en tablas de parametria', '', 
    a.AGRUPADOR_CONTABLE, a.ENTIDAD, a.DIVISA, '', '', a.PRODUCTO_BALANCE, a.CUENTA_PYG, '', '', '', 
    a.IMPORTE_ML, a.IMPORTE_MO, a.SALDO_MEDIO_ML, a.SALDO_MEDIO_MO, a.PL_ML, a.PL_MO
FROM MIS_DWH_MANUAL_ADJ_ACC a
LEFT JOIN MIS_PAR_REL_CAF_ACC b
ON b.COD_ENTITY = a.ENTIDAD AND b.COD_CURRENCY = a.DIVISA AND b.COD_GL_GROUP = a.AGRUPADOR_CONTABLE
WHERE b.COD_GL_GROUP IS NULL;

---Validación de cierre: Cuenta PyG no existe o es diferente del definido en la parametria
INSERT INTO MIS_DWH_MANUAL_ADJ_OPER_REJECTIONS
SELECT 'CONT', 'Validación: CUENTA DE GESTION no encontrada en tablas de parametria', '', 
    a.AGRUPADOR_CONTABLE, a.ENTIDAD, a.DIVISA, '', '', a.PRODUCTO_BALANCE, a.CUENTA_PYG, '', '', '', 
    a.IMPORTE_ML, a.IMPORTE_MO, a.SALDO_MEDIO_ML, a.SALDO_MEDIO_MO, a.PL_ML, a.PL_MO
FROM MIS_DWH_MANUAL_ADJ_ACC a
LEFT JOIN MIS_PAR_REL_PL_ACC b
ON b.COD_ENTITY = a.ENTIDAD AND b.COD_CURRENCY = a.DIVISA AND b.COD_GL_GROUP = a.AGRUPADOR_CONTABLE 
WHERE b.COD_PL_ACC IS NULL;

---Validación de cierre: Producto de Balance no existe o es diferente del definido en la parametria
INSERT INTO MIS_DWH_MANUAL_ADJ_OPER_REJECTIONS
SELECT 'CONT', 'Validación: PRODUCTO DE BALANCE no encontrado en tablas de parametria', '', 
    a.AGRUPADOR_CONTABLE, a.ENTIDAD, a.DIVISA, '', '', a.PRODUCTO_BALANCE, a.CUENTA_PYG, '', '', '', 
    a.IMPORTE_ML, a.IMPORTE_MO, a.SALDO_MEDIO_ML, a.SALDO_MEDIO_MO, a.PL_ML, a.PL_MO
FROM MIS_DWH_MANUAL_ADJ_ACC a
LEFT JOIN MIS_PAR_REL_BP_ACC b
ON b.COD_ENTITY = a.ENTIDAD AND b.COD_CURRENCY = a.DIVISA AND b.COD_GL_GROUP = a.AGRUPADOR_CONTABLE 
WHERE b.COD_BLCE_PROD IS NULL;

---Validación de cierre: Línea de Negocio no existe o es diferente del definido en la parametria
INSERT INTO MIS_DWH_MANUAL_ADJ_OPER_REJECTIONS
SELECT 'CONT', 'Validación: LINEA DE NEGOCIO no encontrada en tablas de parametria', '', 
    a.AGRUPADOR_CONTABLE, a.ENTIDAD, a.DIVISA, '', '', a.PRODUCTO_BALANCE, a.CUENTA_PYG, '', '', '', 
    a.IMPORTE_ML, a.IMPORTE_MO, a.SALDO_MEDIO_ML, a.SALDO_MEDIO_MO, a.PL_ML, a.PL_MO
FROM MIS_DWH_MANUAL_ADJ_ACC a
LEFT JOIN MIS_PAR_REL_BL_ACC b
ON b.COD_ENTITY = a.ENTIDAD AND b.COD_GL_GROUP = a.AGRUPADOR_CONTABLE 
WHERE b.COD_BUSINESS_LINE IS NULL;


---Registros que cumplen con la validación (La llave Entidad - Agrupador contable - Divisa, existe)
INSERT INTO MIS_DM_BALANCE_RESULT_M
(COD_CONT,COD_CURRENCY,COD_ENTITY,IDF_CTO,COD_GL,DES_GL,COD_ACCO_CENT,COD_OFFI,COD_NAR,COD_BLCE_STATUS,COD_PRODUCT,COD_SUBPRODUCT,
EOPBAL_TOT,EOPBAL_CAP,EOPBAL_INT,AVGBAL_TOT,AVGBAL_CAP,AVGBAL_INT,PL,PL_TOT,
COD_TYP_FEE,IDF_CLI,TYP_DOC_ID,NUM_DOC_ID,NOM_NAME,NOM_LASTN,COD_RES_COUNT,COD_TYP_CLNT,COD_COND_CLNT,COD_ENG,VAL_SEX,COD_SEGMENT,DES_SEGMENT,
IND_EMPL_GRUP,DATE_CLNT_REG,DATE_CLNT_WITHDRAW,COD_MANAGER,COD_SECTOR,DES_SECTOR,RATING_CLI,COD_BCA_INT,COD_AMRT_MET,COD_RATE_TYPE,
RATE_INT,DATE_ORIGIN,DATE_LAST_REV,DATE_PRX_REV,EXP_DATE,FREQ_INT_PAY,COD_UNI_FREQ_INT_PAY,FRE_REV_INT,COD_UNI_FRE_REV_INT,
AMRT_TRM,COD_UNI_AMRT_TRM,INI_AM,CUO_AM,CREDIT_LIM_AM,PREDEF_RATE_IND,PREDEF_RATE,IND_CHANNEL,
EOPBAL_TOT_RPT,AVGBAL_TOT_RPT,PL_RPT,PL_TOT_RPT,
EOPBAL_TOT_USD,EOPBAL_TOT_REG,AVGBAL_TOT_USD,AVGBAL_TOT_REG,PL_TOT_USD,PL_TOT_REG,
FTP_RESULT_RPT,
COD_GL_GROUP,DES_GL_GROUP,ACCOUNT_CONCEPT,COD_PL_ACC,DES_PL_ACC,COD_BLCE_PROD,DES_BLCE_PROD,COD_BUSINESS_LINE,DES_BUSINESS_LINE,FTP,FTP_RESULT,IND_POOL,COD_SUBSEGMENT,COD_GROUP_EC, PL_REG)
PARTITION (DATA_DATE,COD_INFO_SOURCE)
SELECT 'RCTB', a.DIVISA, a.ENTIDAD, '', '', '', ISNULL(a.CENTRO_COSTO,''), '', '', '',  '', '', 
    CAST(IFNULL(a.IMPORTE_MO, a.IMPORTE_ML) AS DECIMAL(30,10)) AS EOPBAL_TOT, 
    CAST(IFNULL(a.IMPORTE_MO, a.IMPORTE_ML) AS DECIMAL(30,10)) AS EOPBAL_CAP, 
    0 AS EOPBAL_INT, 
    CAST(IFNULL(a.SALDO_MEDIO_MO, a.IMPORTE_ML) AS DECIMAL(30,10)) AS AVGBAL_TOT,  
    CAST(IFNULL(a.SALDO_MEDIO_MO, a.IMPORTE_ML) AS DECIMAL(30,10)) AS AVGBAL_CAP, 
    0 AS AVGBAL_INT, 
    CAST(IFNULL(a.PL_MO, a.PL_ML) AS DECIMAL(30,10)) AS PL, 
    CAST(IFNULL(a.PL_MO, a.PL_ML) AS DECIMAL(30,10)) AS PL_TOT, 
    '' AS COD_TYP_FEE, '' AS IDF_CLI, '' AS TYP_DOC_ID, '' AS NUM_DOC_ID, '' AS NOM_NAME, '' AS NOM_LASTN, '' AS COD_RES_COUNT, '' AS COD_TYP_CLNT, 
    '' AS COD_COND_CLNT, '' AS COD_ENG, '' AS VAL_SEX, '' AS COD_SEGMENT, '' AS DES_SEGMENT, '' AS IND_EMPL_GRUP, '' AS DATE_CLNT_REG, '' AS DATE_CLNT_WITHDRAW, 
    '' AS COD_MANAGER, '' AS COD_SECTOR, '' AS DES_SECTOR, '' AS RATING_CLI, '' AS COD_BCA_INT, '' AS COD_AMRT_MET, '' AS COD_RATE_TYPE,
    NULL AS RATE_INT, '' AS DATE_ORIGIN, '' AS DATE_LAST_REV, '' AS DATE_PRX_REV, '' AS EXP_DATE,  NULL AS FREQ_INT_PAY, '' AS COD_UNI_FREQ_INT_PAY, NULL AS FRE_REV_INT, '' AS COD_UNI_FRE_REV_INT,
    NULL AS AMRT_TRM, '' AS COD_UNI_AMRT_TRM, NULL AS INI_AM, NULL AS CUO_AM,
    NULL AS CREDIT_LIM_AM, NULL AS PREDEF_RATE_IND, NULL AS PREDEF_RATE, NULL AS IND_CHANNEL,
    CAST(a.IMPORTE_ML AS DECIMAL(30,10)) AS EOPBAL_TOT_RPT, 
    CAST(a.SALDO_MEDIO_ML AS DECIMAL(30,10)) AS AVGBAL_TOT_RPT, 
    CAST(a.PL_ML AS DECIMAL(30,10)) AS PL_RPT, 
    CAST(a.PL_ML AS DECIMAL(30,10)) AS PL_TOT_RPT, 
    CAST(IFNULL(a.IMPORTE_ML / j.EXCH_RATE, 0) AS decimal(30, 10)) AS EOPBAL_TOT_USD,
    CAST(IFNULL(a.IMPORTE_ML / k.EXCH_RATE, 0) AS decimal(30, 10)) AS EOPBAL_TOT_REG,
    CAST(IFNULL(a.SALDO_MEDIO_ML / j.EXCH_RATE, 0) AS decimal(30, 10)) AS AVGBAL_TOT_USD,
    CAST(IFNULL(a.SALDO_MEDIO_ML / k.EXCH_RATE, 0) AS decimal(30, 10)) AS AVGBAL_TOT_REG,
    CAST(IFNULL(a.PL_ML / l.EXCH_RATE, 0) AS decimal(30, 10)) AS PL_TOT_USD,
    CAST(IFNULL(a.PL_ML / m.EXCH_RATE, 0) AS decimal(30, 10)) AS PL_TOT_REG,
    NULL, 
    a.AGRUPADOR_CONTABLE,  c.DES_GL_GROUP, c.ACCOUNT_CONCEPT, a.CUENTA_PYG, g.DES_PL_ACC, a.PRODUCTO_BALANCE, e.DES_BLCE_PROD, a.LINEA_NEGOCIO, i.DES_BUSINESS_LINE, 
    NULL, NULL, '', '', '', CAST(IFNULL(a.PL_ML / m.EXCH_RATE, 0) AS decimal(30, 10)) AS PL_REG,
'${var:periodo}' AS DATA_DATE, 
CASE WHEN a.CRITERIO_DE_AJUSTE LIKE 'Dis%' THEN CONCAT('AJUSTE_','Distribucion LdN')
ELSE CONCAT('AJUSTE_',a.CRITERIO_DE_AJUSTE) END AS COD_INFO_SOURCE
FROM MIS_DWH_MANUAL_ADJ_ACC a 
LEFT JOIN MIS_PAR_EXCH_RATE j
ON a.DATA_DATE=j.DATA_DATE AND j.COD_CONT = 'TC_FOTO' AND j.COD_CURRENCY = 'USD'
AND IF(ISNULL(TRIM(j.COD_ENTITY),'') = '' ,'1',a.ENTIDAD) = IF(ISNULL(TRIM(j.COD_ENTITY),'') = '','1',j.COD_ENTITY)
LEFT JOIN MIS_PAR_EXCH_RATE k
ON a.DATA_DATE=k.DATA_DATE AND k.COD_CONT = 'REG_FOTO' AND k.COD_CURRENCY = 'USD'
AND IF(ISNULL(TRIM(k.COD_ENTITY),'') = '' ,'1',a.ENTIDAD) = IF(ISNULL(TRIM(k.COD_ENTITY),'') = '','1',k.COD_ENTITY)
LEFT JOIN MIS_PAR_EXCH_RATE l
ON a.DATA_DATE=l.DATA_DATE AND l.COD_CONT = 'TC_PROMEDIO' AND l.COD_CURRENCY = 'USD'
AND IF(ISNULL(TRIM(l.COD_ENTITY),'') = '' ,'1',a.ENTIDAD) = IF(ISNULL(TRIM(l.COD_ENTITY),'') = '','1',l.COD_ENTITY)
LEFT JOIN MIS_PAR_EXCH_RATE m
ON a.DATA_DATE=m.DATA_DATE AND m.COD_CONT = 'REG_PROMEDIO' AND m.COD_CURRENCY = 'USD'
AND IF(ISNULL(TRIM(m.COD_ENTITY),'') = '' ,'1',a.ENTIDAD) = IF(ISNULL(TRIM(m.COD_ENTITY),'') = '','1',m.COD_ENTITY)
LEFT JOIN MIS_PAR_REL_CAF_ACC b
ON b.COD_ENTITY = a.ENTIDAD AND b.COD_GL = a.AGRUPADOR_CONTABLE AND b.COD_CURRENCY = a.DIVISA
LEFT JOIN MIS_PAR_CAT_CAF AS c
ON a.AGRUPADOR_CONTABLE = c.COD_GL_GROUP
LEFT JOIN MIS_PAR_REL_BP_ACC d
ON d.COD_ENTITY = a.ENTIDAD AND d.COD_BLCE_PROD = a.PRODUCTO_BALANCE AND d.COD_CURRENCY = a.DIVISA AND d.COD_GL_GROUP = a.AGRUPADOR_CONTABLE
LEFT JOIN MIS_PAR_CAT_BP e
ON a.PRODUCTO_BALANCE = e.COD_BLCE_PROD
LEFT JOIN MIS_PAR_REL_PL_ACC f
ON f.COD_ENTITY = a.ENTIDAD AND f.COD_PL_ACC = a.CUENTA_PYG AND f.COD_CURRENCY = a.DIVISA AND f.COD_GL_GROUP = a.AGRUPADOR_CONTABLE
LEFT JOIN MIS_PAR_CAT_PL g
ON a.CUENTA_PYG = g.COD_PL_ACC
LEFT JOIN MIS_PAR_REL_BL_ACC h
ON h.COD_ENTITY = a.ENTIDAD AND h.COD_GL_GROUP = a.AGRUPADOR_CONTABLE AND h.COD_BUSINESS_LINE = a.LINEA_NEGOCIO
LEFT JOIN MIS_PAR_CAT_BL i
ON i.COD_BUSINESS_LINE = a.LINEA_NEGOCIO
WHERE a.DATA_DATE='${var:periodo}' AND 
TRIM(UPPER(a.CONTENIDO)) = 'CONTABLE' AND TRIM(a.AGRUPADOR_CONTABLE) != '' AND TRIM(a.CUENTA_PYG) != '' AND TRIM(a.PRODUCTO_BALANCE) != '' AND TRIM(a.LINEA_NEGOCIO) != '' 
    AND TRIM(a.ENTIDAD) != '' AND TRIM(a.DIVISA) != '' 
;



--- AJUSTES MANUALES ESPECIALES ---

---Rechazo de registros ingresados sin alguna de las dimensiones principales
INSERT INTO MIS_DWH_MANUAL_ADJ_OPER_REJECTIONS
SELECT 'CONT_ESPE', 'Rechazo: existen dimensiones vacías', '', a.AGRUPADOR_CONTABLE, a.ENTIDAD, a.DIVISA, '', '', a.PRODUCTO_BALANCE, a.CUENTA_PYG, '', '', '', 
    a.IMPORTE_ML, a.IMPORTE_MO, a.SALDO_MEDIO_ML, a.SALDO_MEDIO_MO, a.PL_ML, a.PL_MO
FROM MIS_DWH_MANUAL_ADJ_SPE_ACC a
WHERE TRIM(a.AGRUPADOR_CONTABLE) = '' OR TRIM(a.CUENTA_PYG) = '' OR TRIM(a.PRODUCTO_BALANCE) = '' OR TRIM(a.LINEA_NEGOCIO) = '' 
    OR TRIM(a.ENTIDAD) = '' OR TRIM(a.DIVISA) = '';

---Validación de cierre: Agrupador Contable no existe o es diferente del definido en la parametria
INSERT INTO MIS_DWH_MANUAL_ADJ_OPER_REJECTIONS
SELECT 'CONT_ESPE', 'Validación: AGRUPADOR CONTABLE no encontrado en tablas de parametria', '', 
    a.AGRUPADOR_CONTABLE, a.ENTIDAD, a.DIVISA, '', '', a.PRODUCTO_BALANCE, a.CUENTA_PYG, '', '', '', 
    a.IMPORTE_ML, a.IMPORTE_MO, a.SALDO_MEDIO_ML, a.SALDO_MEDIO_MO, a.PL_ML, a.PL_MO
FROM MIS_DWH_MANUAL_ADJ_SPE_ACC a
LEFT JOIN MIS_PAR_REL_CAF_ACC b
ON b.COD_ENTITY = a.ENTIDAD AND b.COD_CURRENCY = a.DIVISA AND b.COD_GL_GROUP = a.AGRUPADOR_CONTABLE
WHERE b.COD_GL_GROUP IS NULL;

---Validación de cierre: Cuenta PyG no existe o es diferente del definido en la parametria
INSERT INTO MIS_DWH_MANUAL_ADJ_OPER_REJECTIONS
SELECT 'CONT_ESPE', 'Validación: CUENTA DE GESTION no encontrada en tablas de parametria', '', 
    a.AGRUPADOR_CONTABLE, a.ENTIDAD, a.DIVISA, '', '', a.PRODUCTO_BALANCE, a.CUENTA_PYG, '', '', '', 
    a.IMPORTE_ML, a.IMPORTE_MO, a.SALDO_MEDIO_ML, a.SALDO_MEDIO_MO, a.PL_ML, a.PL_MO
FROM MIS_DWH_MANUAL_ADJ_SPE_ACC a
LEFT JOIN MIS_PAR_REL_PL_ACC b
ON b.COD_ENTITY = a.ENTIDAD AND b.COD_CURRENCY = a.DIVISA AND b.COD_GL_GROUP = a.AGRUPADOR_CONTABLE 
WHERE b.COD_PL_ACC IS NULL;

---Validación de cierre: Producto de Balance no existe o es diferente del definido en la parametria
INSERT INTO MIS_DWH_MANUAL_ADJ_OPER_REJECTIONS
SELECT 'CONT_ESPE', 'Validación: PRODUCTO DE BALANCE no encontrado en tablas de parametria', '', 
    a.AGRUPADOR_CONTABLE, a.ENTIDAD, a.DIVISA, '', '', a.PRODUCTO_BALANCE, a.CUENTA_PYG, '', '', '', 
    a.IMPORTE_ML, a.IMPORTE_MO, a.SALDO_MEDIO_ML, a.SALDO_MEDIO_MO, a.PL_ML, a.PL_MO
FROM MIS_DWH_MANUAL_ADJ_SPE_ACC a
LEFT JOIN MIS_PAR_REL_BP_ACC b
ON b.COD_ENTITY = a.ENTIDAD AND b.COD_CURRENCY = a.DIVISA AND b.COD_GL_GROUP = a.AGRUPADOR_CONTABLE 
WHERE b.COD_BLCE_PROD IS NULL;

---Validación de cierre: Línea de Negocio no existe o es diferente del definido en la parametria
INSERT INTO MIS_DWH_MANUAL_ADJ_OPER_REJECTIONS
SELECT 'CONT_ESPE', 'Validación: LINEA DE NEGOCIO no encontrada en tablas de parametria', '', 
    a.AGRUPADOR_CONTABLE, a.ENTIDAD, a.DIVISA, '', '', a.PRODUCTO_BALANCE, a.CUENTA_PYG, '', '', '', 
    a.IMPORTE_ML, a.IMPORTE_MO, a.SALDO_MEDIO_ML, a.SALDO_MEDIO_MO, a.PL_ML, a.PL_MO
FROM MIS_DWH_MANUAL_ADJ_SPE_ACC a
LEFT JOIN MIS_PAR_REL_BL_ACC b
ON b.COD_ENTITY = a.ENTIDAD AND b.COD_GL_GROUP = a.AGRUPADOR_CONTABLE 
WHERE b.COD_BUSINESS_LINE IS NULL;


---Registros que cumplen con la validación (La llave Entidad - Agrupador contable - Divisa, existe)
INSERT INTO MIS_DM_BALANCE_RESULT_M
(COD_CONT, COD_CURRENCY, COD_ENTITY, COD_ACCO_CENT,
EOPBAL_TOT, EOPBAL_CAP, EOPBAL_INT, AVGBAL_TOT, AVGBAL_CAP, AVGBAL_INT, PL, PL_TOT,
EOPBAL_TOT_RPT, AVGBAL_TOT_RPT, PL_RPT, PL_TOT_RPT,
EOPBAL_TOT_USD, EOPBAL_TOT_REG, AVGBAL_TOT_USD, AVGBAL_TOT_REG, PL_TOT_USD, PL_TOT_REG,
COD_GL_GROUP, DES_GL_GROUP, ACCOUNT_CONCEPT, COD_PL_ACC, DES_PL_ACC, COD_BLCE_PROD, DES_BLCE_PROD,
COD_BUSINESS_LINE, DES_BUSINESS_LINE, PL_REG)
PARTITION (DATA_DATE,COD_INFO_SOURCE)
SELECT 'RCTB', a.DIVISA, a.ENTIDAD, a.CENTRO_COSTO AS COD_ACCO_CENT,
    CAST(IFNULL(a.IMPORTE_MO, a.IMPORTE_ML) AS DECIMAL(30,10)) AS EOPBAL_TOT, 
    CAST(IFNULL(a.IMPORTE_MO, a.IMPORTE_ML) AS DECIMAL(30,10)) AS EOPBAL_CAP, 
    0 AS EOPBAL_INT, 
    CAST(IFNULL(a.SALDO_MEDIO_MO, a.IMPORTE_ML) AS DECIMAL(30,10)) AS AVGBAL_TOT,  
    CAST(IFNULL(a.SALDO_MEDIO_MO, a.IMPORTE_ML) AS DECIMAL(30,10)) AS AVGBAL_CAP, 
    0 AS AVGBAL_INT, 
    CAST(IFNULL(a.PL_MO, a.PL_ML) AS DECIMAL(30,10)) AS PL, 
    CAST(IFNULL(a.PL_MO, a.PL_ML) AS DECIMAL(30,10)) AS PL_TOT,   
    CAST(a.IMPORTE_ML AS DECIMAL(30,10)) AS EOPBAL_TOT_RPT, 
    CAST(a.SALDO_MEDIO_ML AS DECIMAL(30,10)) AS AVGBAL_TOT_RPT, 
    CAST(a.PL_ML AS DECIMAL(30,10)) AS PL_RPT, 
    CAST(a.PL_ML AS DECIMAL(30,10)) AS PL_TOT_RPT, 
    CAST(IFNULL(a.IMPORTE_ML / j.EXCH_RATE, 0) AS decimal(30, 10)) AS EOPBAL_TOT_USD,
    CAST(IFNULL(a.IMPORTE_ML / k.EXCH_RATE, 0) AS decimal(30, 10)) AS EOPBAL_TOT_REG,
    CAST(IFNULL(a.SALDO_MEDIO_ML / j.EXCH_RATE, 0) AS decimal(30, 10)) AS AVGBAL_TOT_USD,
    CAST(IFNULL(a.SALDO_MEDIO_ML / k.EXCH_RATE, 0) AS decimal(30, 10)) AS AVGBAL_TOT_REG,
    CAST(IFNULL(a.PL_ML / l.EXCH_RATE, 0) AS decimal(30, 10)) AS PL_TOT_USD,
    CAST(IFNULL(a.PL_ML / m.EXCH_RATE, 0) AS decimal(30, 10)) AS PL_TOT_REG,
    a.AGRUPADOR_CONTABLE,  c.DES_GL_GROUP, c.ACCOUNT_CONCEPT, a.CUENTA_PYG, g.DES_PL_ACC, a.PRODUCTO_BALANCE, e.DES_BLCE_PROD, 
    a.LINEA_NEGOCIO, i.DES_BUSINESS_LINE, CAST(IFNULL(a.PL_ML / m.EXCH_RATE, 0) AS decimal(30, 10)) AS PL_REG,
    '${var:periodo}' AS DATA_DATE, 
    CASE WHEN a.CRITERIO_DE_AJUSTE LIKE 'Dis%' THEN CONCAT('AJUSTE_','Distribucion LdN')
    ELSE CONCAT('AJUSTE_',a.CRITERIO_DE_AJUSTE) END AS COD_INFO_SOURCE
FROM MIS_DWH_MANUAL_ADJ_SPE_ACC a 
LEFT JOIN MIS_PAR_EXCH_RATE j
ON a.DATA_DATE=j.DATA_DATE AND j.COD_CONT = 'TC_FOTO' AND j.COD_CURRENCY = 'USD'
AND IF(ISNULL(TRIM(j.COD_ENTITY),'') = '' ,'1',a.ENTIDAD) = IF(ISNULL(TRIM(j.COD_ENTITY),'') = '','1',j.COD_ENTITY)
LEFT JOIN MIS_PAR_EXCH_RATE k
ON a.DATA_DATE=k.DATA_DATE AND k.COD_CONT = 'REG_FOTO' AND k.COD_CURRENCY = 'USD'
AND IF(ISNULL(TRIM(k.COD_ENTITY),'') = '' ,'1',a.ENTIDAD) = IF(ISNULL(TRIM(k.COD_ENTITY),'') = '','1',k.COD_ENTITY)
LEFT JOIN MIS_PAR_EXCH_RATE l
ON a.DATA_DATE=l.DATA_DATE AND l.COD_CONT = 'TC_PROMEDIO' AND l.COD_CURRENCY = 'USD'
AND IF(ISNULL(TRIM(l.COD_ENTITY),'') = '' ,'1',a.ENTIDAD) = IF(ISNULL(TRIM(l.COD_ENTITY),'') = '','1',l.COD_ENTITY)
LEFT JOIN MIS_PAR_EXCH_RATE m
ON a.DATA_DATE=m.DATA_DATE AND m.COD_CONT = 'REG_PROMEDIO' AND m.COD_CURRENCY = 'USD'
AND IF(ISNULL(TRIM(m.COD_ENTITY),'') = '' ,'1',a.ENTIDAD) = IF(ISNULL(TRIM(m.COD_ENTITY),'') = '','1',m.COD_ENTITY)
LEFT JOIN MIS_PAR_REL_CAF_ACC b
ON b.COD_ENTITY = a.ENTIDAD AND b.COD_GL = a.AGRUPADOR_CONTABLE AND b.COD_CURRENCY = a.DIVISA
LEFT JOIN MIS_PAR_CAT_CAF AS c
ON a.AGRUPADOR_CONTABLE = c.COD_GL_GROUP
LEFT JOIN MIS_PAR_REL_BP_ACC d
ON d.COD_ENTITY = a.ENTIDAD AND d.COD_BLCE_PROD = a.PRODUCTO_BALANCE AND d.COD_CURRENCY = a.DIVISA AND d.COD_GL_GROUP = a.AGRUPADOR_CONTABLE
LEFT JOIN MIS_PAR_CAT_BP e
ON a.PRODUCTO_BALANCE = e.COD_BLCE_PROD
LEFT JOIN MIS_PAR_REL_PL_ACC f
ON f.COD_ENTITY = a.ENTIDAD AND f.COD_PL_ACC = a.CUENTA_PYG AND f.COD_CURRENCY = a.DIVISA AND f.COD_GL_GROUP = a.AGRUPADOR_CONTABLE
LEFT JOIN MIS_PAR_CAT_PL g
ON a.CUENTA_PYG = g.COD_PL_ACC
LEFT JOIN MIS_PAR_REL_BL_ACC h
ON h.COD_ENTITY = a.ENTIDAD AND h.COD_GL_GROUP = a.AGRUPADOR_CONTABLE AND h.COD_BUSINESS_LINE = a.LINEA_NEGOCIO
LEFT JOIN MIS_PAR_CAT_BL i
ON i.COD_BUSINESS_LINE = a.LINEA_NEGOCIO
WHERE a.DATA_DATE='${var:periodo}' AND 
TRIM(UPPER(a.CONTENIDO)) = 'CONTABLE' AND TRIM(a.AGRUPADOR_CONTABLE) != '' AND TRIM(a.CUENTA_PYG) != '' AND TRIM(a.PRODUCTO_BALANCE) != '' AND TRIM(a.LINEA_NEGOCIO) != '' 
    AND TRIM(a.ENTIDAD) != '' AND TRIM(a.DIVISA) != '' 
;