------------------------------- AJUSTES MANUALES DE TTI -------------------------------

--- Comando que apunta a la base de datos apropiada ---
USE ${var:base_datos};
SET DECIMAL_V2=FALSE;

--- Llenado de Tabla de Ajustes Manuales de TTI ---
ALTER TABLE MIS_DWH_MANUAL_ADJ_TTI
DROP IF EXISTS PARTITION (DATA_DATE = '${var:periodo}');

ALTER TABLE MIS_DWH_MANUAL_ADJ_TTI
ADD IF NOT EXISTS PARTITION (DATA_DATE = '${var:periodo}');

LOAD DATA INPATH '${var:ruta_fuentes_ajustes}/Ajustes_Manuales_TTI.csv' INTO TABLE MIS_DWH_MANUAL_ADJ_TTI PARTITION (DATA_DATE = '${var:periodo}');


--- Inserción de Ajuste Manual de TTI ---
INSERT INTO MIS_DM_BALANCE_RESULT_M (COD_CONT, COD_PL_ACC, DES_PL_ACC, COD_BLCE_PROD, DES_BLCE_PROD, COD_BUSINESS_LINE, DES_BUSINESS_LINE, 
    COD_SEGMENT, COD_ENTITY, COD_CURRENCY, FTP_RESULT, FTP_RESULT_RPT, PL_TOT, PL_TOT_RPT, IND_POOL)
PARTITION (DATA_DATE, COD_INFO_SOURCE)
SELECT 'RCTB' AS COD_CONT, A.COD_PL_ACC, PL.DES_PL_ACC, A.COD_BLCE_PROD, BP.DES_BLCE_PROD, A.COD_BUSINESS_LINE, BL.DES_BUSINESS_LINE, 
	A.COD_SEGMENT, A.COD_ENTITY, A.COD_CURRENCY, CAST(A.FTP_RESULT AS decimal(30, 10)) AS FTP_RESULT, CAST(A.FTP_RESULT_RPT AS decimal(30, 10)) FTP_RESULT_RPT, 
    CAST(A.FTP_RESULT AS decimal(30, 10)) AS PL_TOT, CAST(A.FTP_RESULT_RPT AS decimal(30, 10)) AS PL_TOT_RPT, 
    'N' AS IND_POOL, A.DATA_DATE, 'AJUSTE_TTI' AS COD_INFO_SOURCE
FROM MIS_DWH_MANUAL_ADJ_TTI A
LEFT JOIN MIS_PAR_CAT_PL PL
ON A.COD_PL_ACC = PL.COD_PL_ACC
LEFT JOIN MIS_PAR_CAT_BP BP
ON A.COD_BLCE_PROD = BP.COD_BLCE_PROD
LEFT JOIN MIS_PAR_CAT_BL BL
ON A.COD_BUSINESS_LINE = BL.COD_BUSINESS_LINE
WHERE A.DATA_DATE='${var:periodo}' AND STRLEFT(TRIM(A.COD_PL_ACC), 7) IN ('MAR_ACT', 'MAR_PAS');

--- Inserción de Contrapartida de Ajuste Manual de TTI ---
INSERT INTO MIS_DM_BALANCE_RESULT_M (COD_CONT, COD_PL_ACC, DES_PL_ACC, COD_BLCE_PROD, DES_BLCE_PROD, COD_BUSINESS_LINE, DES_BUSINESS_LINE, 
    COD_SEGMENT, COD_ENTITY, COD_CURRENCY, FTP_RESULT, FTP_RESULT_RPT, PL_TOT, PL_TOT_RPT, IND_POOL)
PARTITION (DATA_DATE, COD_INFO_SOURCE)
SELECT 'RCTB' AS COD_CONT, A.COD_PL_ACC, PL.DES_PL_ACC, A.COD_BLCE_PROD, BP.DES_BLCE_PROD, 'UNIDAD_FONDEO' AS COD_BUSINESS_LINE, 'UNIDAD DE FONDEO' AS DES_BUSINESS_LINE, 
    'UNIDAD_FONDEO' AS COD_SEGMENT, A.COD_ENTITY, A.COD_CURRENCY, CAST(-1 * ROUND(A.FTP_RESULT, 10) AS decimal(30, 10)) AS FTP_RESULT, CAST(-1 * ROUND(A.FTP_RESULT_RPT, 10) AS decimal(30, 10)) AS FTP_RESULT_RPT, 
    CAST(-1 * ROUND(A.FTP_RESULT, 10) AS decimal(30, 10)) AS PL_TOT, CAST(-1 * ROUND(A.FTP_RESULT_RPT, 10) AS decimal(30, 10)) AS PL_TOT_RPT, 
    'Y' AS IND_POOL, A.DATA_DATE, 'AJUSTE_TTI' AS COD_INFO_SOURCE
FROM MIS_DWH_MANUAL_ADJ_TTI A
LEFT JOIN MIS_PAR_CAT_PL PL
ON A.COD_PL_ACC = PL.COD_PL_ACC
LEFT JOIN MIS_PAR_CAT_BP BP
ON A.COD_BLCE_PROD = BP.COD_BLCE_PROD
LEFT JOIN MIS_PAR_CAT_BL BL
ON A.COD_BUSINESS_LINE = BL.COD_BUSINESS_LINE
WHERE A.DATA_DATE='${var:periodo}' AND STRLEFT(TRIM(A.COD_PL_ACC), 7) IN ('MAR_ACT', 'MAR_PAS');