--------------------------------------------------------------- MIS_APR_CLIENT_DT -----------------------------------------------------------

--- Comando que dirige las consultas a la base de datos apropiada ---
USE ${var:base_datos};
SET DECIMAL_V2=FALSE;

--COMPUTE STATS MIS_LOAD_CUP00301;
--COMPUTE STATS MIS_APR_CLIENT_DT;

----Carga de tablas load
TRUNCATE TABLE IF EXISTS MIS_LOAD_CUP00301;
LOAD DATA INPATH '${var:ruta_fuentes_activos}/CUP00301.csv' INTO TABLE MIS_LOAD_CUP00301;

----Carga de tablas load
TRUNCATE TABLE IF EXISTS MIS_LOAD_CUP00901;
LOAD DATA INPATH '${var:ruta_fuentes_activos}/CUP00901.csv' INTO TABLE MIS_LOAD_CUP00901; 

----Carga de tablas load banca empresas
TRUNCATE TABLE IF EXISTS MIS_LOAD_BANCA_EMPRESAS;
LOAD DATA INPATH '${var:ruta_fuentes_activos}/SEGMENTO_BANCA_EMPRESAS.csv' INTO TABLE MIS_LOAD_BANCA_EMPRESAS;

----Carga de tablas load banca personas
TRUNCATE TABLE IF EXISTS MIS_LOAD_BANCA_PERSONAS;
LOAD DATA INPATH '${var:ruta_fuentes_activos}/MIS_SEGMENTO_BANCA_PERSONAS.csv' INTO TABLE MIS_LOAD_BANCA_PERSONAS; 


ALTER TABLE MIS_APR_CLIENT_DT
DROP IF EXISTS PARTITION (DATA_DATE = '${var:periodo}');

----Aprovisionamiento de Clientes
--DROP TABLE IF EXISTS MIS_TMP_CLIENT_DT;
--CREATE TABLE MIS_TMP_CLIENT_DT AS 
INSERT INTO MIS_APR_CLIENT_DT
PARTITION (DATA_DATE='${var:periodo}') 
SELECT TRIM(a.CUNBR) AS IDF_CLI, 'PASSP' AS TYP_DOC_ID, TRIM(a.CUSSNR) AS NUM_DOC_ID, TRIM(a.CUSHRT) AS NOM_NAME, 
NULL AS NOM_LASTN,
 CASE 
 WHEN TRIM(a.CUCNCD) = '1' THEN 'HN' WHEN TRIM(a.CUCNCD) = '2' THEN 'NIC' 
 WHEN TRIM(a.CUCNCD) = '3' THEN 'SV' WHEN TRIM(a.CUCNCD) = '4' THEN 'GT' 
 WHEN TRIM(a.CUCNCD) = '5' THEN 'CR' WHEN TRIM(a.CUCNCD) = '6' THEN 'PA' 
 WHEN TRIM(a.CUCNCD) = '7' THEN 'BL' WHEN TRIM(a.CUCNCD) = '8' THEN 'USA' 
 WHEN TRIM(a.CUCNCD) = '9' THEN 'CND' WHEN TRIM(a.CUCNCD) = '10' THEN 'MX' ELSE TRIM(a.CUCNCD) END AS COD_RES_COUNT, 
 ISNULL(TRIM(a.CUPERS),'P') AS COD_TYP_CLNT, NULL AS COD_COND_CLNT, TRIM(a.CUSTAT) AS COD_ENG,
    TRIM(a.CUSEX) AS VAL_SEX, NULL AS COD_COUNTRY, NULL AS COD_SECTOR, NULL AS DES_SECTOR, 
    ISNULL(b.UNIDAD,c.SEGMENTO) AS COD_SEGMENT,
    ISNULL(b.UNIDAD,c.SEGMENTO) AS DES_SEGMENT,
    '' AS COD_SUBSEGMENT, '' AS COD_SUBSEGMENT, NULL AS IND_EMPL_GRUP, a.CUOPDT AS DATE_CLNT_REG, NULL AS DATE_CLNT_WITHDRAW, TRIM(a.CUPOFF) AS COD_MANAGER, 
TRIM(d.DES_MANAGER) AS DES_MANAGER, NULL AS RATING_CLI, NULL AS COD_GROUP_EC, NULL AS ID_ECO_GRO, NULL AS COU_ECO_GRO, NULL AS IND_MUL_LAT, NULL AS FIELD1_CLI, 
NULL AS FIELD2_CLI, NULL AS FIELD3_CLI, NULL AS FIELD4_CLI, NULL AS FIELD5_CLI, NULL AS FIELD6_CLI, NULL AS FIELD7_CLI, NULL AS FIELD8_CLI, NULL AS FIELD9_CLI, 
NULL AS FIELD10_CLI, NULL AS COD_SECTOR_LOCAL, NULL AS COD_SECTOR_REG, NULL AS DES_SECTOR_LOCAL, NULL AS DES_SECTOR_REG
FROM MIS_LOAD_CUP00301 a
LEFT JOIN MIS_LOAD_BANCA_EMPRESAS b
ON TRIM(a.CUNBR) = TRIM(b.CIF)
LEFT JOIN MIS_LOAD_BANCA_PERSONAS c
ON TRIM(a.CUNBR) = TRIM(c.CUNBR)
LEFT JOIN MIS_PAR_CAT_MANAGER d
ON TRIM(a.CUPOFF) = TRIM(d.COD_MANAGER)
--LEFT JOIN MIS_PAR_REL_SECTOR c        --Asignación de sector
--ON TRIM(a.CUSOFC) = TRIM(c.COD_MANAGER) 
--LEFT JOIN MIS_PAR_REL_SEGMENT d       --Asignación de segmento
--ON TRIM(a.CUSOFC) = TRIM(d.COD_MANAGER) AND TRIM(a.CUSTID) = TRIM(d.TYP_DOC_ID)
;

COMPUTE INCREMENTAL STATS MIS_APR_CLIENT_DT partition (data_date = '${var:periodo}');

INSERT INTO MIS_APR_CLIENT_DT
PARTITION (DATA_DATE='${var:periodo}')
SELECT '99999999' AS IDF_CLI, 'DEFECTO' AS TYP_DOC_ID, '99999999' AS NUM_DOC_ID, 'CLIENTE POR DEFECTO' AS NOM_NAME, 
NULL AS NOM_LASTN, NULL AS COD_RES_COUNT, 'D' AS COD_TYP_CLNT, NULL AS COD_COND_CLNT, NULL AS COD_ENG,
NULL AS VAL_SEX, NULL AS COD_COUNTRY, NULL AS COD_SECTOR, NULL AS DES_SECTOR, NULL AS COD_SEGMENT, NULL AS DES_SEGMENT, 
NULL AS COD_SEGMENT, NULL AS COD_SUBSEGMENT, NULL AS IND_EMPL_GRUP, NULL AS DATE_CLNT_REG, NULL AS DATE_CLNT_WITHDRAW, NULL AS COD_MANAGER, NULL AS DES_MANAGER, NULL AS RATING_CLI, NULL AS COD_GROUP_EC, NULL AS ID_ECO_GRO, NULL AS COU_ECO_GRO, NULL AS IND_MUL_LAT, NULL AS FIELD1_CLI, NULL AS FIELD2_CLI, NULL AS FIELD3_CLI, NULL AS FIELD4_CLI, NULL AS FIELD5_CLI, NULL AS FIELD6_CLI, NULL AS FIELD7_CLI, NULL AS FIELD8_CLI, NULL AS FIELD9_CLI, NULL AS FIELD10_CLI,NULL AS COD_SECTOR_LOCAL, NULL AS COD_SECTOR_REG, NULL AS DES_SECTOR_LOCAL, NULL AS DES_SECTOR_REG

/*
--Inserción en tabla de Clientes y asignación de Subsegmento
INSERT INTO MIS_APR_CLIENT_DT 
    (IDF_CLI, TYP_DOC_ID, NUM_DOC_ID, NOM_NAME, NOM_LASTN, COD_RES_COUNT, COD_TYP_CLNT, COD_COND_CLNT, COD_ENG, 
    VAL_SEX, COD_COUNTRY, COD_SECTOR, DES_SECTOR, COD_SEGMENT, DES_SEGMENT, COD_SUBSEGMENT, DES_SUBSEGMENT, 
    IND_EMPL_GRUP, DATE_CLNT_REG, DATE_CLNT_WITHDRAW, COD_MANAGER, DES_MANAGER, RATING_CLI, COD_GROUP_EC)
PARTITION (DATA_DATE='${var:periodo}') 
SELECT a.IDF_CLI, a.TYP_DOC_ID, a.NUM_DOC_ID, a.NOM_NAME, a.NOM_LASTN, a.COD_RES_COUNT, a.COD_TYP_CLNT, a.COD_COND_CLNT, 
    a.COD_ENG, a.VAL_SEX, a.COD_COUNTRY, a.COD_SECTOR, a.DES_SECTOR, a.COD_SEGMENT, a.DES_SEGMENT, 
    TRIM(COALESCE(b.COD_SUBSEGMENT, c.COD_SUBSEGMENT, d.COD_SUBSEGMENT, e.COD_SUBSEGMENT)) AS COD_SUBSEGMENT,
    TRIM(COALESCE(b.DES_SUBSEGMENT, c.DES_SUBSEGMENT, d.DES_SUBSEGMENT, e.DES_SUBSEGMENT)) AS DES_SUBSEGMENT,
    a.IND_EMPL_GRUP, a.DATE_CLNT_REG, a.DATE_CLNT_WITHDRAW, a.COD_MANAGER, a.DES_MANAGER, a.RATING_CLI, a.COD_GROUP_EC
FROM MIS_TMP_CLIENT_DT a 
LEFT JOIN MIS_TMP_PAR_SUBSEGMENT b
ON b.TYPE_REL = 1 AND TRIM(a.COD_SEGMENT)= TRIM(b.COD_SEGMENT) AND TRIM(a.COD_COUNTRY) = TRIM(b.COD_COUNTRY) AND TRIM(a.COD_MANAGER) = TRIM(b.COD_MANAGER)
LEFT JOIN MIS_TMP_PAR_SUBSEGMENT c
ON c.TYPE_REL = 2 AND TRIM(a.COD_SEGMENT)= TRIM(c.COD_SEGMENT) AND TRIM(a.COD_COUNTRY) = TRIM(c.COD_COUNTRY)
LEFT JOIN MIS_TMP_PAR_SUBSEGMENT d
ON d.TYPE_REL = 3 AND TRIM(a.COD_SEGMENT)= TRIM(d.COD_SEGMENT) AND TRIM(a.COD_MANAGER) = TRIM(d.COD_MANAGER)
LEFT JOIN MIS_TMP_PAR_SUBSEGMENT e
ON e.TYPE_REL = 4 AND TRIM(a.COD_SEGMENT)= TRIM(e.COD_SEGMENT); 

TRUNCATE TABLE IF EXISTS MIS_TMP_PAR_SUBSEGMENT;
DROP TABLE IF EXISTS MIS_TMP_PAR_SUBSEGMENT;
TRUNCATE TABLE IF EXISTS MIS_TMP_CLIENT_DT;
DROP TABLE IF EXISTS MIS_TMP_CLIENT_DT;
*/