--------------------------------------------------------------- MIS_APR_ASSETS ------------------------------------------------------------

--- Comando que apunta a la base de datos apropiada ---
USE ${var:base_datos};
SET DECIMAL_V2=FALSE;

----Carga de tablas load
TRUNCATE TABLE IF EXISTS MIS_LOAD_CR01; 
LOAD DATA INPATH '${var:ruta_fuentes_activos}/CR_01.csv' INTO TABLE MIS_LOAD_CR01;
TRUNCATE TABLE IF EXISTS MIS_LOAD_CR91; 
LOAD DATA INPATH '${var:ruta_fuentes_activos}/CR_91.csv' INTO TABLE MIS_LOAD_CR91;
TRUNCATE TABLE IF EXISTS MIS_LOAD_LNP00301; 
LOAD DATA INPATH '${var:ruta_fuentes_activos}/LNP00301.csv' INTO TABLE MIS_LOAD_LNP00301;
TRUNCATE TABLE IF EXISTS MIS_LOAD_MAESTTARJ; 
LOAD DATA INPATH '${var:ruta_fuentes_activos}/MAESTTARJ.csv' INTO TABLE MIS_LOAD_MAESTTARJ;
TRUNCATE TABLE IF EXISTS MIS_LOAD_IN_10MST; 
LOAD DATA INPATH '${var:ruta_fuentes_activos}/IN_10MST.csv' INTO TABLE MIS_LOAD_IN_10MST;
TRUNCATE TABLE IF EXISTS MIS_LOAD_GLC002; 
LOAD DATA INPATH '${var:ruta_fuentes_activos}/GLC002.csv' INTO TABLE MIS_LOAD_GLC002;
TRUNCATE TABLE IF EXISTS MIS_LOAD_S95TRA; 
LOAD DATA INPATH '${var:ruta_fuentes_activos}/S95TRA.csv' INTO TABLE MIS_LOAD_S95TRA;
TRUNCATE TABLE IF EXISTS MIS_LOAD_INE10MST; 
LOAD DATA INPATH '${var:ruta_fuentes_activos}/INE10MST.csv' INTO TABLE MIS_LOAD_INE10MST;
TRUNCATE TABLE IF EXISTS MIS_LOAD_SGBTRA; 
LOAD DATA INPATH '${var:ruta_fuentes_activos}/SGBTRA.csv' INTO TABLE MIS_LOAD_SGBTRA;
TRUNCATE TABLE IF EXISTS MIS_LOAD_TN1DET07; 
LOAD DATA INPATH '${var:ruta_fuentes_activos}/TN1DET07.csv' INTO TABLE MIS_LOAD_TN1DET07;
TRUNCATE TABLE IF EXISTS MIS_LOAD_PREMIACION; 
LOAD DATA INPATH '${var:ruta_fuentes_activos}/MIS_PREMIACION.csv' INTO TABLE MIS_LOAD_PREMIACION;
TRUNCATE TABLE IF EXISTS MIS_LOAD_CFP50301;
LOAD DATA INPATH '${var:ruta_fuentes_activos}/CFP50301.csv' INTO TABLE MIS_LOAD_CFP50301;
TRUNCATE TABLE IF EXISTS MIS_LOAD_SJ0TRA; 
LOAD DATA INPATH '${var:ruta_fuentes_activos}/SJ0TRA.csv' INTO TABLE MIS_LOAD_SJ0TRA;
TRUNCATE TABLE IF EXISTS MIS_LOAD_SGWTRA; 
LOAD DATA INPATH '${var:ruta_fuentes_activos}/SGWTRA.csv' INTO TABLE MIS_LOAD_SGWTRA;
TRUNCATE TABLE IF EXISTS MIS_LOAD_INPLA031;
LOAD DATA INPATH '${var:ruta_fuentes_activos}/INPLA031.csv' INTO TABLE MIS_LOAD_INPLA031;

--- Aprovisionamiento tarjetas adicionales ---
DROP TABLE IF EXISTS MIS_TMP_TDC_ADICIONALES;
CREATE TABLE MIS_TMP_TDC_ADICIONALES AS
SELECT A.INPLNOTAR as "IDF_CTO",A.INPLNOMCLI as "NOM_CLI",A.INPLIDCLI as "IDF_CLI",A.INPLFCHAPE as "DATE_ORIGIN",A.INPLACTFCH AS "DATE_DISB",B.LIMIT1 AS "INI_AM",B.JVTYP AS "TIPO" 
FROM MIS_LOAD_INPLA031 A
LEFT JOIN MIS_LOAD_MAESTTARJ B
ON B.ACCT=A.INPLNOTAR
WHERE A.INPLSTSPLA = '99'
AND A.INPLIDENTI ='T'
AND B.JVTYP ='SCA'
AND A.INPLACTFCH = '${var:periodo}'
ORDER BY  A.INPLACTFCH
;

DROP TABLE IF EXISTS MIS_TMP_TIT_ADICIONALES;
CREATE TABLE MIS_TMP_TIT_ADICIONALES AS
SELECT A.SJ0NUM AS IDF_CTO, A.SJ0NO1 AS NOM_CLI, A.SJ0EST AS ESTATUSTDC, A.SJ0LI1 AS INI_AM_ADC, A.SJ0TIP AS TIPO, B.SGWNU1 AS CARD_NUMBER,
B.SGWNOM AS NOM_CLI_TIT, B.SGWLIM AS INI_AM_TIT, B.SGWSAL AS SALDOACTUAL, B.SGWCAP AS SALDOCAP, B.SGWINT AS SALDOINT, B.SGWOTR AS SALDOTS
FROM MIS_LOAD_SJ0TRA A
LEFT JOIN MIS_LOAD_SGWTRA B
ON CONCAT (A.SJ0COD,A.SJ0NU3) = CONCAT (B.SGWCOD,B.SGWNUM) 
WHERE A.SJ0TIP = 'A'
;

ALTER TABLE MIS_DWH_MANUAL_ADJ_OPER_ADD_CRED_CARD
DROP IF EXISTS PARTITION (DATA_DATE = '${var:periodo}');

INSERT INTO MIS_DWH_MANUAL_ADJ_OPER_ADD_CRED_CARD
PARTITION (DATA_DATE='${var:periodo}')
SELECT 'Operacional' AS CONTENIDO, 'ADJ_ADD' AS CRITERIO_DE_AJUSTE, A.IDF_CTO AS CONTRATO, B.CARD_NUMBER, A.TIPO AS CARD_TYPE, 
'HNL' AS DIVISA, NULL AS AGRUPADOR_CONTABLE, '1' AS ENTIDAD, NULL AS PRODUCTO_BALANCE, NULL AS CUENTA_PG, NULL AS LINEA_DE_NEGOCIO, NULL AS COD_SEGMENT, NULL AS IMPORTE_ML, NULL AS IMPORTE_MO, NULL AS SALDO_MEDIO_ML, NULL AS SALDO_MEDIO_MO, NULL AS PL_ML, NULL AS PL_MO, B.INI_AM_ADC AS INI_AM_ML, B.INI_AM_ADC AS INI_AM_MO, A.DATE_DISB
FROM MIS_TMP_TDC_ADICIONALES A
LEFT JOIN MIS_TMP_TIT_ADICIONALES B
ON A.IDF_CTO = B.IDF_CTO
;

DROP TABLE IF EXISTS MIS_TMP_CR91;
CREATE TABLE MIS_TMP_CR91 AS
SELECT b.CR01_37, a.* FROM MIS_LOAD_CR91 a
LEFT JOIN (SELECT * FROM MIS_LOAD_CR01 WHERE to_timestamp(CR01_75,'yyyyMMdd') = last_day(to_timestamp('${var:periodo}','yyyyMMdd'))) b
ON CR91_04 = CR01_04 and CR01_03 = cr91_10
WHERE cr91_10 = '${var:periodo}';

DROP TABLE IF EXISTS MIS_TMP_EX_ASSETS;
CREATE TABLE MIS_TMP_EX_ASSETS AS
SELECT CR91_06 AS IDF_CTO, CR91_05 AS EXTRA, CR01_30 AS REFINAN, SUM(CR01_41) AS EOPBAL, SUM(CR01_48) AS INTERESES
FROM MIS_LOAD_CR01
INNER JOIN (SELECT * FROM MIS_TMP_CR91 WHERE CR01_37 ='VIG') b
ON CR91_05 = CR01_04 and CR01_03 = cr91_10
WHERE to_timestamp(CR01_75,'yyyyMMdd') = last_day(to_timestamp('${var:periodo}','yyyyMMdd'))
GROUP BY CR91_06, CR91_05, CR01_30;

DROP TABLE IF EXISTS MIS_TMP_ASSETS_INTRA;
CREATE TABLE MIS_TMP_ASSETS_INTRA AS
select cr01_04, sum(TN1MON) as TN1MON from(
select isnull(TN1MON,0) as TN1MON, TN1COD, TN1NUM, tn1pl1, a.cr01_04 from mis_load_cr01 a
left join mis_load_sgbtra b
on SGBNUM = CR01_04 and b.sgbmon = 'HNL'
left join (SELECT * FROM mis_load_tn1det07 WHERE strleft(tn1fec,6) = strleft('${var:periodo}',6)) c
on concat(SGBEMI,SGBCUE) = concat(TN1COD,TN1NUM)
left join (select * from mis_load_cr93 where cr93_08 = 'I') d
on c.tn1pl1 = d.cr93_01
where a.cr01_75 = '${var:periodo}' and a.cr01_14 = '130000' and c.tn1cod is not null
)a
group by cr01_04
;

ALTER TABLE MIS_APR_ASSETS
DROP IF EXISTS PARTITION (DATA_DATE = '${var:periodo}');

----Aprovisionamiento de Activos Capital banda
INSERT INTO MIS_APR_ASSETS 
PARTITION (DATA_DATE='${var:periodo}')
SELECT 'PREST' AS COD_CONT, CAST(a.CR01_04 AS string) AS IDF_CTO, NULL AS COD_GL, NULL AS DES_GL, CAST(a.CR01_56 AS string) AS COD_ACCO_CENT, 
    CAST(a.CR01_56 AS string) AS COD_OFFI, CAST(a.CR01_37 AS string) AS COD_BLCE_STATUS, 'CAP' AS COD_VALUE, CASE WHEN TRIM(a.CR01_15) = '1' THEN 'HNL' WHEN TRIM(a.CR01_15) = '2' THEN 'USD' ELSE 'HNL' END AS COD_CURRENCY, '1' AS COD_ENTITY,
    CASE WHEN a.cr01_30 IN ('F','G') THEN CONCAT(TRIM(a.CR01_55),'_REFINAN') WHEN CR01_14 IN ('130000') THEN strleft(a.cr01_04,8) WHEN CR01_14 IN ('130100') THEN isnull(isnull(strleft(d.IDF_CTO,8),strleft(c.IDF_CTO,8)),strleft(a.cr01_04,8)) WHEN b.IDF_CTO IS NOT NULL THEN b.COD_PRODUCT
         ELSE TRIM(a.CR01_55) END AS COD_PRODUCT, CASE WHEN a.cr01_30 IN ('F','G') THEN IFNULL(TRIM(a.CR01_17),'') WHEN CR01_14 IN ('130000') THEN IFNULL(TRIM(a.CR01_14),'') WHEN CR01_14 IN ('130100') THEN CONCAT(IFNULL(TRIM(a.CR01_14),''),'_EXT') ELSE CONCAT(IFNULL(TRIM(a.CR01_14),''),'_',IFNULL(TRIM(a.CR01_17),'')) END AS COD_SUBPRODUCT, IFNULL(NULL, '') AS COD_ACT_TYPE, CAST(CASE WHEN a.CR01_37 = 'VIG' THEN a.CR01_41 - ISNULL(TN1MON,0) WHEN a.CR01_37 = 'VEN' THEN a.CR01_43 - ISNULL(TN1MON,0) WHEN a.CR01_37 = 'CAS' THEN a.CR01_46 - ISNULL(TN1MON,0) WHEN a.CR01_37 = 'EJE' THEN a.CR01_44 - ISNULL(TN1MON,0) WHEN a.CR01_37 = 'MOR' THEN a.cr01_42 - ISNULL(TN1MON,0) ELSE a.CR01_41 - ISNULL(TN1MON,0) END AS DECIMAL(11,2)) AS EOPBAL_CAP, 
    NULL AS EOPBAL_INT, a.CR01_07 AS AVGBAL_CAP, NULL AS AVGBAL_INT, NULL AS PL, 'CR01' AS COD_INFO_SOURCE 
FROM MIS_LOAD_CR01 a 
LEFT JOIN MIS_PAR_REL_PROD_SPE b 
ON CAST(a.CR01_04 AS string) = B.IDF_CTO
LEFT JOIN (SELECT DISTINCT IDF_CTO, REFINAN FROM MIS_TMP_EX_ASSETS) c
ON c.IDF_CTO = a.CR01_04 AND a.CR01_30 = c.REFINAN
LEFT JOIN MIS_TMP_EX_ASSETS d
ON d.EXTRA = a.CR01_04 AND a.CR01_30 = d.REFINAN
LEFT JOIN MIS_TMP_ASSETS_INTRA intr
ON a.CR01_04 = intr.CR01_04
WHERE to_timestamp(a.CR01_75,'yyyyMMdd') = last_day(to_timestamp('${var:periodo}','yyyyMMdd')) /*AND strleft(a.CR01_04,2) <> 'EF'*/ AND (a.CR01_14 not like '240%' OR a.CR01_14 not in ('999999'))
;

----Aprovisionamiento de Activos Capital intra
INSERT INTO MIS_APR_ASSETS 
PARTITION (DATA_DATE='${var:periodo}') 
SELECT 'PREST' AS COD_CONT, CONCAT(CAST(a.CR01_04 AS string),'I') AS IDF_CTO, NULL AS COD_GL, NULL AS DES_GL, CAST(a.CR01_56 AS string) AS COD_ACCO_CENT, 
CAST(a.CR01_56 AS string) AS COD_OFFI, CAST(a.CR01_37 AS string) AS COD_BLCE_STATUS, 'CAP' AS COD_VALUE, CASE WHEN TRIM(a.CR01_15) = '1' THEN 'HNL' WHEN TRIM(a.CR01_15) = '2' THEN 'USD' ELSE 'HNL' END AS COD_CURRENCY, '1' AS COD_ENTITY, strleft(a.cr01_04,8) AS COD_PRODUCT, 
CONCAT(TRIM(a.CR01_14),'_INT') AS COD_SUBPRODUCT, IFNULL(NULL, '') AS COD_ACT_TYPE, CAST(ISNULL(TN1MON,0) AS DECIMAL(11,2)) AS EOPBAL_CAP, NULL AS EOPBAL_INT, a.CR01_07 AS AVGBAL_CAP, NULL AS AVGBAL_INT, NULL AS PL, 'TN1' AS COD_INFO_SOURCE 
FROM MIS_LOAD_CR01 a 
LEFT JOIN MIS_PAR_REL_PROD_SPE b 
ON CAST(a.CR01_04 AS string) = B.IDF_CTO
LEFT JOIN MIS_TMP_ASSETS_INTRA intr
ON a.CR01_04 = intr.CR01_04
WHERE to_timestamp(a.CR01_75,'yyyyMMdd') = last_day(to_timestamp('${var:periodo}','yyyyMMdd')) AND a.CR01_14 = '130000'
;


ALTER TABLE MIS_APR_CONTRACT_DT
DROP IF EXISTS PARTITION (DATA_DATE = '${var:periodo}', COD_INFO_SOURCE='TN1');

----Aprovisionamiento de Contratos asociados a Activos
INSERT INTO MIS_APR_CONTRACT_DT 
PARTITION (DATA_DATE='${var:periodo}', COD_INFO_SOURCE='TN1') 
SELECT DISTINCT CONCAT(CAST(a.CR01_04 AS string),'I') AS IDF_CTO, '1' AS COD_ENTITY, strleft(a.cr01_04,8) AS COD_PRODUCT, CONCAT(TRIM(a.CR01_14),'_INT') AS COD_SUBPRODUCT, IFNULL(NULL, '') AS COD_ACT_TYPE, CASE WHEN TRIM(a.CR01_15) = '1' THEN 'HNL' WHEN TRIM(a.CR01_15) = '2' THEN 'USD' ELSE 'HNL' END AS COD_CURRENCY, CAST(a.CR01_54 AS string) AS IDF_CLI, CAST(a.CR01_56 AS string) AS COD_ACCO_CENT, CAST(a.CR01_56 AS string) AS COD_OFFI, NULL AS COD_BCA_INT, NULL AS COD_AMRT_MET, 
    'A' AS COD_RATE_TYPE, CAST(a.CR01_22/100 AS decimal(30, 10)) AS RATE_INT, a.CR01_05 AS DATE_ORIGIN, NULL AS DATE_LAST_REV, NULL DATE_PRX_REV,
    a.CR01_06 AS EXP_DATE, NULL AS FREQ_INT_PAY, NULL AS COD_UNI_FREQ_INT_PAY, NULL AS FRE_REV_INT, NULL AS COD_UNI_FRE_REV_INT, CAST(a.CR01_23 as BIGINT) AS AMRT_TRM, 
    NULL AS COD_UNI_AMRT_TRM, a.CR01_47 AS INI_AM, a.CR01_58 AS CUO_AM, NULL AS CREDIT_LIM_AM, NULL AS PREDEF_RATE_IND, NULL AS PREDEF_RATE, 
    NULL AS IND_CHANNEL, NULL COD_TYP_LIC, NULL AS COD_SELLER, NULL AS DES_SELLER, NULL AS COU_CAR_OFF, NULL AS COD_CONV, NULL AS COD_EXEC_CTO, NULL AS COD_COVID_PORT, a.CR01_05 AS DATE_DISB, NULL AS FIELD1_CTO, NULL AS FIELD2_CTO, NULL AS FIELD3_CTO, NULL AS FIELD4_CTO, NULL AS FIELD5_CTO, NULL AS FIELD6_CTO, NULL AS FIELD7_CTO, NULL AS FIELD8_CTO, NULL AS FIELD9_CTO, NULL AS FIELD10_CTO, 
    a.CR01_04 AS CARD_NUMBER, le.COD_PROG_CARD, le2.DES_PROG_CARD
FROM MIS_LOAD_CR01 a
LEFT JOIN MIS_LOAD_PREMIACION le
ON CAST(a.CR01_04 AS string) = le.IDF_CTO
LEFT JOIN MIS_PAR_REL_PROG_CARD le2
ON le.COD_PROG_CARD = le2.COD_PROG_CARD
WHERE to_timestamp(a.CR01_75,'yyyyMMdd') = last_day(to_timestamp('${var:periodo}','yyyyMMdd')) AND a.CR01_14 = '130000'
;

----Aprovisionamiento de Activos Intereses
INSERT INTO MIS_APR_ASSETS 
PARTITION (DATA_DATE='${var:periodo}') 
SELECT 'PREST' AS COD_CONT, CAST(a.CR01_04 AS string) AS IDF_CTO, RPAD( case when cr01_48 = cast(lnidue as decimal(11,2))
        then case when a.cr01_30 IN ('F','G') 
                    then e.cr100_06 
                  else d.cfal06 
             end 
     when cr01_48 > cast(lnidue as decimal(11,2))
        then d.cfal06
     else NULL
end ,16, '0') as cod_gl, NULL AS DES_GL, CAST(a.CR01_56 AS string) AS COD_ACCO_CENT, 
    CAST(a.CR01_56 AS string) AS COD_OFFI, CAST(a.CR01_37 AS string) AS COD_BLCE_STATUS, 'INT' AS COD_VALUE, CASE WHEN TRIM(a.CR01_15) = '1' THEN 'HNL' WHEN TRIM(a.CR01_15) = '2' THEN 'USD' ELSE 'HNL' END AS COD_CURRENCY, '1' AS COD_ENTITY,
    CASE WHEN a.cr01_30 IN ('F','G') THEN CONCAT(TRIM(a.CR01_55),'_REFINAN') WHEN CR01_14 IN ('130000') THEN strleft(a.cr01_04,8) WHEN CR01_14 IN ('130100') THEN isnull(isnull(strleft(ex.IDF_CTO,8),strleft(c.IDF_CTO,8)),strleft(a.cr01_04,8)) WHEN b.IDF_CTO IS NOT NULL THEN b.COD_PRODUCT
         ELSE TRIM(a.CR01_55) END AS COD_PRODUCT, CASE WHEN a.cr01_30 IN ('F','G') THEN IFNULL(TRIM(a.CR01_17),'') WHEN CR01_14 IN ('130000','130100') THEN IFNULL(TRIM(a.CR01_14),'') ELSE  CONCAT(IFNULL(TRIM(a.CR01_14),''),'_',IFNULL(TRIM(a.CR01_17),'')) END AS COD_SUBPRODUCT, IFNULL(NULL, '') AS COD_ACT_TYPE, CASE WHEN CR01_14 IN ('130000','130100') THEN CAST(a.cr01_48 AS DECIMAL(11,2)) ELSE case when cr01_48 = cast(lnidue as decimal(11,2))
        then cr01_48
     when cr01_48 > cast(lnidue as decimal(11,2))
        then cast(lnidue as decimal(11,2))
     else cr01_48
end END AS EOPBAL_CAP, NULL AS EOPBAL_INT, NULL AS AVGBAL_CAP, NULL AS AVGBAL_INT, NULL AS PL, 'CR01' AS COD_INFO_SOURCE 
FROM MIS_LOAD_CR01 a 
LEFT JOIN MIS_PAR_REL_PROD_SPE b 
ON CAST(a.CR01_04 AS string) = B.IDF_CTO
LEFT JOIN (SELECT DISTINCT IDF_CTO, REFINAN FROM MIS_TMP_EX_ASSETS) c
ON c.IDF_CTO = a.CR01_04 AND a.CR01_30 = c.REFINAN
LEFT JOIN MIS_TMP_EX_ASSETS ex
ON ex.EXTRA = a.CR01_04 AND a.CR01_30 = ex.REFINAN
left join (SELECT * FROM MIS_LOAD_LNP00301 WHERE LNNONF NOT IN ('X','V')) lnp
on CAST(lnp.LNNOTE AS string) = CAST(a.CR01_04 AS string) and cr01_48 >= cast(lnidue as decimal(11,2))
left join mis_load_cfp50301 d
on a.cr01_55 = d.cftyp
left join (select * from mis_load_cr100 where cr100_04 = '00') e
on a.cr01_17 = e.cr100_02 and CAST(a.CR01_37 AS string) = e.cr100_03
WHERE to_timestamp(a.CR01_75,'yyyyMMdd') = last_day(to_timestamp('${var:periodo}','yyyyMMdd')) /*AND strleft(CR01_04,2) <> 'EF'*/ AND (a.CR01_14 not like '240%' OR a.CR01_14 not in ('999999'))
;

DROP TABLE IF EXISTS MIS_TMP_GLC002;
CREATE TABLE MIS_TMP_GLC002 AS
select *, from_timestamp(DATE_ADD(TO_TIMESTAMP(concat(strleft(GBEFDT,4),'0101'), 'yyyyMMdd'),CAST(strright(GBEFDT,3) AS INT) - 1), 'yyyyMMdd') as DATA_DATE from MIS_LOAD_GLC002
where from_timestamp(DATE_ADD(TO_TIMESTAMP(concat(strleft(GBEFDT,4),'0101'), 'yyyyMMdd'),CAST(strright(GBEFDT,3) AS INT) - 1), 'yyyyMMdd') <= '${var:periodo}'
order by GBEFDT desc
limit 20;

insert into mis_par_exch_rate
partition (data_date, cod_cont)
select distinct cod_currency, exch_rate, NULL AS COD_ENTITY, data_date, 'TC_FOTO' AS COD_CONT from(
select '${var:periodo}' as data_date, 'USD' as cod_currency, cast(gbbkxr as decimal(30,10)) as exch_rate
from mis_tmp_glc002 
where data_date in (SELECT MAX(DATA_DATE) FROM mis_tmp_glc002) and gbcode in ('1','2') 
and NOT EXISTS (SELECT 1 FROM mis_par_exch_rate WHERE data_date = '${var:periodo}' AND cod_cont = 'TC_FOTO' and cod_currency = 'USD')
)a;

insert into mis_par_exch_rate
partition (data_date, cod_cont)
select distinct cod_currency, exch_rate, NULL AS COD_ENTITY, data_date, 'TC_FOTO' AS COD_CONT from(
select '${var:periodo}' as data_date, 'EUR' as cod_currency, cast(gbbkxr as decimal(30,10)) as exch_rate
from mis_tmp_glc002 
where data_date in (SELECT MAX(DATA_DATE) FROM mis_tmp_glc002) and gbcode in ('3','4')
and NOT EXISTS (SELECT 1 FROM mis_par_exch_rate WHERE data_date = '${var:periodo}' AND cod_cont = 'TC_FOTO' and cod_currency = 'EUR')
)a;

insert into mis_par_exch_rate
partition (data_date, cod_cont)
select 'HNL', 1, NULL AS COD_ENTITY, '${var:periodo}', 'TC_FOTO'
union all
select 'HNL', 1, NULL AS COD_ENTITY, '${var:periodo}', 'REG_FOTO'
union all
select 'HNL', 1, NULL AS COD_ENTITY, '${var:periodo}', 'TC_PROMEDIO'
union all
select 'HNL', 1, NULL AS COD_ENTITY, '${var:periodo}', 'PPTO_PROMEDIO'
union all
select 'HNL', 1, NULL AS COD_ENTITY, '${var:periodo}', 'REG_PROMEDIO'
union all
select 'HNL', 1, NULL AS COD_ENTITY, '${var:periodo}', 'PPTO_FOTO'
;

COMPUTE INCREMENTAL STATS MIS_APR_ASSETS partition (data_date = '${var:periodo}');

----Aprovisionamiento de Activos Resultados
INSERT INTO MIS_APR_ASSETS 
PARTITION (DATA_DATE='${var:periodo}') 
SELECT 'PREST' AS COD_CONT, CAST(a.CR01_04 AS string) AS IDF_CTO, NULL AS COD_GL, NULL AS DES_GL, CAST(a.CR01_56 AS string) AS COD_ACCO_CENT, 
     CAST(a.CR01_56 AS string) AS COD_OFFI, CAST(a.CR01_37 AS string) AS COD_BLCE_STATUS, 'RSL' AS COD_VALUE, CASE WHEN TRIM(a.CR01_15) = '1' THEN 'HNL' WHEN TRIM(a.CR01_15) = '2' THEN 'USD' ELSE 'HNL' END AS COD_CURRENCY, '1' AS COD_ENTITY,
    CASE WHEN a.cr01_30 IN ('F','G') THEN CONCAT(TRIM(a.CR01_55),'_REFINAN') WHEN CR01_14 IN ('130000') THEN strleft(a.cr01_04,8) WHEN CR01_14 IN ('130100') THEN strleft(d.CR91_04,8) WHEN b.IDF_CTO IS NOT NULL THEN b.COD_PRODUCT
         ELSE TRIM(a.CR01_55) END AS COD_PRODUCT, CASE WHEN a.cr01_30 IN ('F','G') THEN IFNULL(TRIM(a.CR01_17),'') WHEN CR01_14 IN ('130000','130100') THEN CONCAT(IFNULL(TRIM(a.CR01_14),''),'_EI') ELSE CONCAT(IFNULL(TRIM(a.CR01_14),''),'_',IFNULL(TRIM(a.CR01_17),'')) END AS COD_SUBPRODUCT, IFNULL(NULL, '') AS COD_ACT_TYPE, NULL AS EOPBAL_CAP, 
    NULL AS EOPBAL_INT, NULL AS AVGBAL_CAP, NULL AS AVGBAL_INT, CASE WHEN CR01_14 IN ('130000','130100') THEN CASE WHEN STRRIGHT('${var:periodo}',2) = '01' THEN CAST(isnull(e.S95MON,0) * -1 AS DECIMAL(11,2)) ELSE CAST((isnull(e.S95MON,0) * -1) + ISNULL(g.PL,0) AS DECIMAL(11,2)) END ELSE cast(cast(c.LNACMD as decimal(11,2)) * -1 as decimal(11,2)) END AS PL, 'CR01' AS COD_INFO_SOURCE 
FROM MIS_LOAD_CR01 a 
LEFT JOIN MIS_PAR_REL_PROD_SPE b 
ON CAST(a.CR01_04 AS string) = B.IDF_CTO
LEFT JOIN (SELECT * FROM MIS_LOAD_LNP00301 WHERE LNNONF NOT IN ('X','V')) c 
ON CAST(c.LNNOTE AS string) = CAST(a.CR01_04 AS string)
LEFT JOIN MIS_LOAD_CR91 d 
ON d.CR91_05 = a.CR01_04 and a.CR01_75 = d.cr91_09
LEFT JOIN (SELECT S95NU1, SUM(S95MON) AS S95MON FROM MIS_LOAD_S95TRA WHERE S95FE1 = '${var:periodo}' AND S95COD IN ('EI','88') GROUP BY S95NU1) e 
ON S95NU1 = CAST(a.CR01_04 AS string)
--LEFT JOIN (select * FROM mis_tmp_glc002 where data_date in (SELECT MAX(DATA_DATE) FROM mis_tmp_glc002)) f
--ON lncmcn = GBCODE
LEFT JOIN (SELECT * FROM MIS_APR_ASSETS WHERE TO_TIMESTAMP(DATA_DATE,'yyyyMMdd') = date_sub(TO_TIMESTAMP('${var:periodo}','yyyyMMdd'),1) AND STRRIGHT('${var:periodo}',2) <> '01' AND COD_VALUE = 'RSL') g
ON a.CR01_04 = g.IDF_CTO and CONCAT(IFNULL(TRIM(a.CR01_14),''),'_EI') = g.COD_SUBPRODUCT and a.CR01_37 = g.COD_BLCE_STATUS  AND strleft(a.cr01_04,6) = strleft(g.cod_product,6) AND a.CR01_56 = g.COD_ACCO_CENT
WHERE to_timestamp(a.CR01_75,'yyyyMMdd') = last_day(to_timestamp('${var:periodo}','yyyyMMdd')) AND (a.CR01_14 not like '240%' OR a.CR01_14 not in ('999999'));

ALTER TABLE MIS_APR_CONTRACT_DT
DROP IF EXISTS PARTITION (DATA_DATE = '${var:periodo}', COD_INFO_SOURCE='CR01');

----Aprovisionamiento de Contratos asociados a Activos
INSERT INTO MIS_APR_CONTRACT_DT 
PARTITION (DATA_DATE='${var:periodo}', COD_INFO_SOURCE='CR01') 
SELECT DISTINCT CAST(a.CR01_04 AS string) AS IDF_CTO, '1' AS COD_ENTITY, 
    CASE WHEN a.cr01_30 IN ('F','G') THEN CONCAT(TRIM(a.CR01_55),'_REFINAN') WHEN CR01_14 IN ('130000') THEN strleft(a.cr01_04,8) WHEN CR01_14 IN ('130100') THEN strleft(d.CR91_04,8) WHEN b.IDF_CTO IS NOT NULL THEN b.COD_PRODUCT
         ELSE TRIM(a.CR01_55) END AS COD_PRODUCT, CASE WHEN a.cr01_30 IN ('F','G') THEN IFNULL(TRIM(a.CR01_17),'') WHEN CR01_14 IN ('130000','130100') THEN IFNULL(TRIM(a.CR01_14),'') ELSE  CONCAT(IFNULL(TRIM(a.CR01_14),''),'_',IFNULL(TRIM(a.CR01_17),'')) END AS COD_SUBPRODUCT, IFNULL(NULL, '') AS COD_ACT_TYPE, 
    CASE WHEN TRIM(a.CR01_15) = '1' THEN 'HNL' WHEN TRIM(a.CR01_15) = '2' THEN 'USD' ELSE 'HNL' END AS COD_CURRENCY, CAST(a.CR01_54 AS string) AS IDF_CLI, CAST(a.CR01_56 AS string) AS COD_ACCO_CENT, 
    CAST(a.CR01_56 AS string) AS COD_OFFI, TRIM(c.LNYRBS) AS COD_BCA_INT, TRIM(c.LNSCTY) AS COD_AMRT_MET, 
    'A' AS COD_RATE_TYPE, 
    CAST(a.CR01_22/100 AS decimal(30, 10)) AS RATE_INT, 
    a.CR01_05 AS DATE_ORIGIN, 
    NULL AS DATE_LAST_REV, 
    NULL DATE_PRX_REV,
    a.CR01_06 AS EXP_DATE, 
    CAST(c.LNINTF as BIGINT) AS FREQ_INT_PAY, NULL AS COD_UNI_FREQ_INT_PAY, 
    NULL AS FRE_REV_INT, NULL AS COD_UNI_FRE_REV_INT, CAST(a.CR01_23 as BIGINT) AS AMRT_TRM, c.LNSCF AS COD_UNI_AMRT_TRM, a.CR01_47 AS INI_AM, a.CR01_58 AS CUO_AM, CAST(c.LNFACE as DECIMAL(30,10)) AS CREDIT_LIM_AM, NULL AS PREDEF_RATE_IND, NULL AS PREDEF_RATE, 
    NULL AS IND_CHANNEL, NULL COD_TYP_LIC, NULL AS COD_SELLER, NULL AS DES_SELLER, NULL AS COU_CAR_OFF, NULL AS COD_CONV, c.LNOFF AS COD_EXEC_CTO, NULL AS COD_COVID_PORT, a.CR01_05 AS DATE_DISB, NULL AS FIELD1_CTO, NULL AS FIELD2_CTO, NULL AS FIELD3_CTO, NULL AS FIELD4_CTO, NULL AS FIELD5_CTO, NULL AS FIELD6_CTO, NULL AS FIELD7_CTO, NULL AS FIELD8_CTO, NULL AS FIELD9_CTO, NULL AS FIELD10_CTO,
    CASE WHEN CR01_14 IN ('130000') THEN a.CR01_04 WHEN CR01_14 IN ('130100') THEN ex.IDF_CTO ELSE NULL END AS CARD_NUMBER, 
    ISNULL(le.COD_PROG_CARD,leex.COD_PROG_CARD) AS COD_PROG_CARD, ISNULL(le2.DES_PROG_CARD,leex2.DES_PROG_CARD) AS DES_PROG_CARD
FROM MIS_LOAD_CR01 a
LEFT JOIN MIS_PAR_REL_PROD_SPE b 
ON CAST(a.CR01_04 AS string) = B.IDF_CTO 
LEFT JOIN MIS_LOAD_LNP00301 c
ON TRIM(c.LNNOTE) = TRIM(a.CR01_04)
LEFT JOIN MIS_LOAD_CR91 d 
ON d.CR91_05 = a.CR01_04 and a.CR01_75 = d.cr91_09
LEFT JOIN MIS_LOAD_PREMIACION le
ON CAST(a.CR01_04 AS string) = le.IDF_CTO
LEFT JOIN MIS_TMP_EX_ASSETS ex
ON CAST(a.CR01_04 AS string) = ex.EXTRA
LEFT JOIN MIS_LOAD_PREMIACION leex
ON ex.IDF_CTO = leex.IDF_CTO
LEFT JOIN MIS_PAR_REL_PROG_CARD le2
ON le.COD_PROG_CARD = le2.COD_PROG_CARD
LEFT JOIN MIS_PAR_REL_PROG_CARD leex2
ON leex.COD_PROG_CARD = leex2.COD_PROG_CARD
WHERE to_timestamp(a.CR01_75,'yyyyMMdd') = last_day(to_timestamp('${var:periodo}','yyyyMMdd')) AND a.CR01_14 not like '240%';

--- Carga de Activos - Inversiones ---

--- Aprovisionamiento de inversiones capital ---
INSERT INTO MIS_APR_ASSETS
PARTITION (DATA_DATE = '${var:periodo}')
SELECT 'INV' AS COD_CONT, CONCAT(a.IN01_COD, a.IN10_COD, a.IN05_COD) AS IDF_CTO, NULL AS COD_GL, NULL AS DES_GL, NULL AS COD_ACCO_CENT, '172' AS COD_OFFI, 
CASE WHEN a.IN10_STS = 'A' THEN 'VIG' ELSE 'VEN' END AS COD_BLCE_STATUS, 'CAP' AS COD_VALUE, CASE WHEN CAST(IN10_MON AS STRING) = '0' THEN 'HNL' WHEN CAST(IN10_MON AS STRING) = '1' THEN 'USD' ELSE 'HNL' END AS COD_CURRENCY, '1' AS COD_ENTITY, CASE WHEN b.IDF_CTO IS NOT NULL THEN b.COD_PRODUCT
ELSE a.IN05_COD END AS COD_PRODUCT, a.IN01_COD AS COD_SUBPRODUCT, NULL AS COD_ACT_TYPE, CAST(CASE WHEN CAST(IN10_MON AS STRING) = '0' THEN a.IN10_SDA ELSE a.IN10_SDA * GBBKXR END + ISNULL(IN10_DEP,0) - ISNULL(INEGFITACU,0) AS DECIMAL(11,2)) AS EOPBAL_CAP, NULL AS EOPBAL_INT, NULL AS AVGBAL_CAP, 
NULL AS AVGBAL_INT, NULL AS PL, 'IN01' AS COD_INFO_SOURCE
FROM MIS_LOAD_IN_10MST a
LEFT JOIN MIS_PAR_REL_PROD_SPE b
ON CAST(CONCAT(a.IN01_COD, a.IN05_COD, a.IN10_COD) AS STRING) = b.IDF_CTO
LEFT JOIN (select * FROM mis_tmp_glc002 where data_date in (SELECT MAX(DATA_DATE) FROM mis_tmp_glc002)) c
ON CAST(IN10_MON AS STRING) = GBCODE
LEFT JOIN MIS_LOAD_INE10MST
ON IN01_COD = INE01COD AND IN05_COD = INE05COD AND IN10_COD = INE10COD
WHERE a.IN10_STS = 'A'
;

--- Aprovisionamiento de inversiones resultados para institucion 1 ---
INSERT INTO MIS_APR_ASSETS
PARTITION (DATA_DATE = '${var:periodo}')
SELECT 'INV' AS COD_CONT, CONCAT(a.IN01_COD, a.IN10_COD, a.IN05_COD) AS IDF_CTO, NULL AS COD_GL, NULL AS DES_GL, NULL AS COD_ACCO_CENT, '172' AS COD_OFFI, 
CASE WHEN a.IN10_STS = 'A' THEN 'VIG' ELSE 'VEN' END AS COD_BLCE_STATUS, 'RSL' AS COD_VALUE, CASE WHEN CAST(IN10_MON AS STRING) = '0' THEN 'HNL' WHEN CAST(IN10_MON AS STRING) = '1' THEN 'USD' ELSE 'HNL' END AS COD_CURRENCY, '1' AS COD_ENTITY, CASE WHEN b.IDF_CTO IS NOT NULL THEN b.COD_PRODUCT ELSE a.IN05_COD END AS COD_PRODUCT, a.IN01_COD AS COD_SUBPRODUCT, NULL AS COD_ACT_TYPE, NULL AS EOPBAL_CAP, NULL AS EOPBAL_INT, NULL AS AVGBAL_CAP, NULL AS AVGBAL_INT, CASE WHEN strright('${var:periodo}',2) = '01' then CAST(a.IN10_DDE * -1 AS DECIMAL(11,2))
ELSE CASE WHEN dayofweek(TO_TIMESTAMP('${var:periodo}', 'yyyyMMdd')) IN (1,7) THEN CAST(isnull(d.PL,0) AS DECIMAL(11,2)) ELSE CAST(isnull(d.PL,0) + a.IN10_DDE * -1 AS DECIMAL(11,2)) END END AS PL, 'IN01' AS COD_INFO_SOURCE
FROM MIS_LOAD_IN_10MST a
LEFT JOIN MIS_PAR_REL_PROD_SPE b
ON CAST(CONCAT(a.IN01_COD, a.IN05_COD, a.IN10_COD) AS STRING) = b.IDF_CTO
--LEFT JOIN (select * FROM mis_tmp_glc002 where data_date in (SELECT MAX(DATA_DATE) FROM mis_tmp_glc002)) c
--ON CAST(IN10_MON AS STRING) = GBCODE
left join (select * from mis_apr_assets 
where cod_info_source = 'IN01' and cod_value = 'RSL' and TO_TIMESTAMP(data_date, 'yyyyMMdd') = DATE_SUB(TO_TIMESTAMP('${var:periodo}','yyyyMMdd'), 1)) d
on CONCAT(a.IN01_COD, a.IN10_COD, a.IN05_COD) = d.idf_cto
WHERE a.IN10_STS = 'A' AND a.IN01_COD = '1'
;

--- Aprovisionamiento de inversiones resultados para institucion 2 ---
INSERT INTO MIS_APR_ASSETS
PARTITION (DATA_DATE = '${var:periodo}')
SELECT 'INV' AS COD_CONT, CONCAT(a.INE01COD, a.INE10COD, a.INE05COD) AS IDF_CTO, NULL AS COD_GL, NULL AS DES_GL, NULL AS COD_ACCO_CENT, '172' AS COD_OFFI, 
'VIG' AS COD_BLCE_STATUS, 'RSL' AS COD_VALUE, CASE WHEN CAST(z.IN10_MON AS STRING) = '0' THEN 'HNL' WHEN CAST(z.IN10_MON AS STRING) = '1' THEN 'USD' ELSE 'HNL' END AS COD_CURRENCY, '1' AS COD_ENTITY, CASE WHEN b.IDF_CTO IS NOT NULL THEN b.COD_PRODUCT ELSE a.INE05COD END AS COD_PRODUCT, a.INE01COD AS COD_SUBPRODUCT, NULL AS COD_ACT_TYPE, NULL AS EOPBAL_CAP, NULL AS EOPBAL_INT, NULL AS AVGBAL_CAP, NULL AS AVGBAL_INT, CASE WHEN strright('${var:periodo}',2) = '01' THEN CASE WHEN dayofweek(TO_TIMESTAMP('${var:periodo}', 'yyyyMMdd')) IN (1,7) THEN 0 ELSE CAST(a.INEINTDIA - INEGFIDIA AS DECIMAL(11,2)) END ELSE CASE WHEN dayofweek(TO_TIMESTAMP('${var:periodo}', 'yyyyMMdd')) IN (1,7) THEN CAST(isnull(d.PL,0) AS DECIMAL(11,2)) ELSE CAST(isnull(d.PL,0) + (a.INEINTDIA - INEGFIDIA) * -1 AS DECIMAL(11,2)) END END AS PL, 'INE10' AS COD_INFO_SOURCE
FROM MIS_LOAD_INE10MST a
INNER JOIN (SELECT * FROM MIS_LOAD_IN_10MST WHERE IN10_STS = 'A') z
ON z.IN01_COD = a.INE01COD AND z.IN05_COD = a.INE05COD AND z.IN10_COD = a.INE10COD
LEFT JOIN MIS_PAR_REL_PROD_SPE b
ON CAST(CONCAT(a.INE01COD, a.INE10COD, a.INE05COD) AS STRING) = b.IDF_CTO
--LEFT JOIN (select * FROM mis_tmp_glc002 where data_date in (SELECT MAX(DATA_DATE) FROM mis_tmp_glc002)) c
--ON CAST(IN10_MON AS STRING) = GBCODE
left join (select * from mis_apr_assets 
where cod_info_source = 'INE10' and cod_value = 'RSL' and TO_TIMESTAMP(data_date, 'yyyyMMdd') = DATE_SUB(TO_TIMESTAMP('${var:periodo}','yyyyMMdd'), 1)) d
on CONCAT(a.INE01COD, a.INE10COD, a.INE05COD) = d.idf_cto
WHERE a.INE01COD = '2'
;

--- Carga de Contratos Asociados a Inversiones ---

--COMPUTE STATS MIS_LOAD_CUP00901;

DROP TABLE IF EXISTS MIS_TMP_CUP00901;
CREATE TABLE MIS_TMP_CUP00901 AS
select cux1ac, max(cux1ap) as cux1ap, max(cux1cs) as cux1cs, max(cux1ty) as cux1ty, max(cuxbk) as cuxbk, max(cuxrec) as cuxrec, max(cuxrel) as cuxrel, fecha_control
from mis_load_cup00901 group by cux1ac, fecha_control;

ALTER TABLE MIS_APR_CONTRACT_DT
DROP IF EXISTS PARTITION (DATA_DATE = '${var:periodo}', COD_INFO_SOURCE = 'IN01');

--COMPUTE STATS MIS_TMP_CUP00901;

INSERT INTO MIS_APR_CONTRACT_DT
PARTITION (DATA_DATE = '${var:periodo}', COD_INFO_SOURCE = 'IN01')
SELECT DISTINCT CAST(CONCAT(a.IN01_COD, a.IN10_COD, a.IN05_COD) AS STRING) AS IDF_CTO, '1' AS COD_ENTITY, CASE WHEN b.IDF_CTO IS NOT NULL THEN b.COD_PRODUCT
ELSE a.IN05_COD END AS COD_PRODUCT, a.IN01_COD AS COD_SUBPRODUCT, NULL AS COD_ACT_TYPE, CASE WHEN CAST(IN10_MON AS STRING) = '0' THEN 'HNL' WHEN CAST(IN10_MON AS STRING) = '1' THEN 'USD' ELSE 'HNL' END AS COD_CURRENCY, isnull(isnull(c.CUX1CS,cl.CUX1CS),'99999999') AS IDF_CLI, NULL AS COD_ACCO_CENT, '172' AS COD_OFFI,
CAST(a.IN10_BAS AS STRING) AS COD_BCA_INT, NULL AS COD_AMRT_MET, 'A' AS COD_RATE_TYPE, CAST(a.IN10_TAS AS DECIMAL(30,10)) AS RATE_INT, a.IN10_FHI AS DATE_ORIGIN, NULL AS DATE_LAST_REV, NULL AS DATE_PRX_REV, 
a.IN10_FHV AS EXP_DATE, NULL AS FREQ_INT_PAY, NULL AS COD_UNI_FREQ_INT_PAY, NULL AS FRE_REV_INT, NULL AS COD_UNI_FRE_REV_INT, NULL AS AMRT_TRM, NULL AS COD_UNI_AMRT_TRM,
CAST(a.IN10_MNO AS DECIMAL(30,10)) AS INI_AM, NULL AS CUO_AM, NULL AS CREDIT_LIM_AM, NULL AS PREDEF_RATE_IND, NULL AS PREDEF_RATE, NULL AS IND_CHANNEL, NULL AS COD_TYP_LIC, NULL AS COD_SELLER, NULL AS DES_SELLER, NULL AS COU_CAR_OFF, NULL AS COD_CONV, NULL AS COD_EXEC_CTO, NULL AS COD_COVID_PORT, a.IN10_FHI AS DATE_DISB, NULL AS FIELD1_CTO, NULL AS FIELD2_CTO, NULL AS FIELD3_CTO, NULL AS FIELD4_CTO, NULL AS FIELD5_CTO, NULL AS FIELD6_CTO, NULL AS FIELD7_CTO, NULL AS FIELD8_CTO, NULL AS FIELD9_CTO, NULL AS FIELD10_CTO, NULL AS CARD_NUMBER, NULL AS COD_PROG_CARD, NULL AS DES_PROG_CARD
FROM MIS_LOAD_IN_10MST a
LEFT JOIN MIS_PAR_REL_PROD_SPE b
ON CAST(CONCAT(a.IN01_COD, a.IN05_COD, a.IN10_COD) AS STRING) = b.IDF_CTO
LEFT JOIN MIS_TMP_CUP00901 c
ON CONCAT(a.IN01_COD, a.IN05_COD, a.IN10_COD) = CAST(c.CUX1AC AS string)
LEFT JOIN MIS_TMP_CUP00901 cl
ON CONCAT(a.IN01_COD, a.IN05_COD, a.IN10_COD) = strright(cl.CUX1AC,length(cl.CUX1AC)-1)
WHERE a.IN10_STS = 'A'
;

COMPUTE INCREMENTAL STATS MIS_APR_CONTRACT_DT partition (data_date = '${var:periodo}');

DROP TABLE IF EXISTS MIS_TMP_CONTRACT;
CREATE TABLE MIS_TMP_CONTRACT AS
select idf_cto, cod_entity, cod_product, cod_subproduct, cod_act_type, cod_currency, max(idf_cli), cod_acco_cent, cod_offi, cod_bca_int, cod_amrt_met, cod_rate_type,rate_int, date_origin, date_last_rev, date_prx_rev, exp_date, freq_int_pay, cod_uni_freq_int_pay, fre_rev_int, cod_uni_fre_rev_int, amrt_trm, cod_uni_amrt_trm,ini_am, cuo_am, credit_lim_am, predef_rate_ind, predef_rate, ind_channel, cod_typ_lic, cod_seller, des_seller, COU_CAR_OFF, COD_CONV, COD_EXEC_CTO, COD_COVID_PORT, DATE_DISB, FIELD1_CTO, FIELD2_CTO, FIELD3_CTO, FIELD4_CTO, FIELD5_CTO, FIELD6_CTO, FIELD7_CTO, FIELD8_CTO, FIELD9_CTO, FIELD10_CTO, CARD_NUMBER, COD_PROG_CARD, DES_PROG_CARD
from mis_apr_contract_dt 
where data_date = '${var:periodo}' and cod_info_source = 'IN01'
group by idf_cto, cod_entity, cod_product, cod_subproduct, cod_act_type, cod_currency, cod_acco_cent, cod_offi, cod_bca_int, cod_amrt_met, cod_rate_type,rate_int, date_origin, date_last_rev, date_prx_rev, exp_date, freq_int_pay, cod_uni_freq_int_pay, fre_rev_int, cod_uni_fre_rev_int, amrt_trm, cod_uni_amrt_trm,ini_am, cuo_am, credit_lim_am, predef_rate_ind, predef_rate, ind_channel, cod_typ_lic, cod_seller, des_seller, COU_CAR_OFF, COD_CONV, COD_EXEC_CTO, COD_COVID_PORT, DATE_DISB, FIELD1_CTO, FIELD2_CTO, FIELD3_CTO, FIELD4_CTO, FIELD5_CTO, FIELD6_CTO, FIELD7_CTO, FIELD8_CTO, FIELD9_CTO, FIELD10_CTO, CARD_NUMBER, COD_PROG_CARD, DES_PROG_CARD;

ALTER TABLE MIS_APR_CONTRACT_DT
DROP IF EXISTS PARTITION (DATA_DATE = '${var:periodo}', COD_INFO_SOURCE='IN01');

--COMPUTE STATS MIS_TMP_CONTRACT;

INSERT INTO MIS_APR_CONTRACT_DT PARTITION (DATA_DATE='${var:periodo}', COD_INFO_SOURCE='IN01') SELECT * FROM MIS_TMP_CONTRACT;