--------------------------------------------------------- MIS_APR_OFF_BALANCE --------------------------------------------------------
USE ${var:base_datos};
SET DECIMAL_V2=FALSE;

----Carga de tablas load

TRUNCATE TABLE IF EXISTS mis_load_cdif03; 
LOAD DATA INPATH '${var:ruta_fuentes_comisiones}/CDIF03.csv' INTO TABLE mis_load_cdif03;

TRUNCATE TABLE IF EXISTS mis_load_cdif07; 
LOAD DATA INPATH '${var:ruta_fuentes_comisiones}/CDIF07.csv' INTO TABLE mis_load_cdif07;

DROP TABLE IF EXISTS MIS_TMP_GLC002;
CREATE TABLE MIS_TMP_GLC002 AS
select *, from_timestamp(DATE_ADD(TO_TIMESTAMP(concat(strleft(GBEFDT,4),'0101'), 'yyyyMMdd'),CAST(strright(GBEFDT,3) AS INT) - 1), 'yyyyMMdd') as DATA_DATE from MIS_LOAD_GLC002
where from_timestamp(DATE_ADD(TO_TIMESTAMP(concat(strleft(GBEFDT,4),'0101'), 'yyyyMMdd'),CAST(strright(GBEFDT,3) AS INT) - 1), 'yyyyMMdd') <= '${var:periodo}'
order by GBEFDT desc
limit 20;

ALTER TABLE MIS_APR_FEES 
DROP IF EXISTS PARTITION (DATA_DATE = '${var:periodo}');

----Aprovisionamiento de Comisiones de desembolso Capital
INSERT INTO MIS_APR_FEES 
PARTITION (DATA_DATE='${var:periodo}') 
SELECT 'COM' AS COD_CONT, a.C3NUMP AS IDF_CTO, NULL AS COD_GL, NULL AS DES_GL, NULL AS COD_ACCO_CENT, 
NULL AS COD_OFFI, 'VIG' AS COD_BLCE_STATUS, 'CAP' AS COD_VALUE, CASE WHEN CAST(c3mone AS STRING) IN ('1','2') THEN 'USD' ELSE 'HNL' END AS COD_CURRENCY, '1' AS COD_ENTITY, 
CAST(a.C3PROD AS STRING) AS COD_PRODUCT, 'COM' AS COD_SUBPRODUCT, IFNULL(NULL, '') AS COD_ACT_TYPE, CASE WHEN CAST(c3mone AS STRING) IN ('0','00') THEN CAST(a.C3INPE * -1 AS DECIMAL(30,10)) ELSE CAST((a.C3INPE * GBBKXR) * -1 AS DECIMAL(30,10)) END AS EOPBAL_CAP,
NULL AS EOPBAL_INT, NULL AS AVGBAL_CAP, NULL AS AVGBAL_INT, NULL AS PL, 'CDIF03' AS COD_INFO_SOURCE
FROM MIS_LOAD_CDIF03 a
LEFT JOIN (select * FROM mis_tmp_glc002 where data_date in (SELECT MAX(DATA_DATE) FROM mis_tmp_glc002)) b
ON CAST(c3mone AS STRING) = GBCODE
;
/*
----Aprovisionamiento de Comisiones de desembolso Resultados
INSERT INTO MIS_APR_FEES
PARTITION (DATA_DATE='${var:periodo}') 
SELECT 'COM' AS COD_CONT, a.C3NUMP AS IDF_CTO, NULL AS COD_GL, NULL AS DES_GL, NULL AS COD_ACCO_CENT, 
NULL AS COD_OFFI, 'VIG' AS COD_BLCE_STATUS, 'RSL' AS COD_VALUE, CASE WHEN CAST(c3mone AS STRING) IN ('1','2') THEN 'USD' ELSE 'HNL' END AS COD_CURRENCY, '1' AS COD_ENTITY,
CAST(a.C3PROD AS STRING) AS COD_PRODUCT, 'COM' AS COD_SUBPRODUCT, IFNULL(NULL, '') AS COD_ACT_TYPE, NULL AS EOPBAL_CAP, 
NULL AS EOPBAL_INT, NULL AVGBAL_CAP, NULL AS AVGBAL_INT, CASE WHEN CAST(c3mone AS STRING) IN ('0','00') THEN CAST(a.C3IMAR * -1 AS DECIMAL(30,10)) ELSE CAST((a.C3IMAR * -1) * GBBKXR AS DECIMAL(30,10)) END AS PL, 'CDIF03' AS COD_INFO_SOURCE 
FROM MIS_LOAD_CDIF03 a 
LEFT JOIN (select * FROM mis_tmp_glc002 where data_date in (SELECT MAX(DATA_DATE) FROM mis_tmp_glc002)) b
ON CAST(c3mone AS STRING) = GBCODE
;
*/

----Aprovisionamiento de Comisiones de desembolso Resultados
INSERT INTO MIS_APR_FEES
PARTITION (DATA_DATE='${var:periodo}') 
SELECT 'COM' AS COD_CONT, a.C3NUMP AS IDF_CTO, NULL AS COD_GL, NULL AS DES_GL, NULL AS COD_ACCO_CENT, 
CAST(C7AGEN AS STRING) AS COD_OFFI, 'VIG' AS COD_BLCE_STATUS, 'RSL' AS COD_VALUE, CASE WHEN CAST(C7MONE AS STRING) IN ('1','2') THEN 'USD' ELSE 'HNL' END AS COD_CURRENCY, '1' AS COD_ENTITY,
CAST(a.C7PROD AS STRING) AS COD_PRODUCT, 'COM' AS COD_SUBPRODUCT, IFNULL(NULL, '') AS COD_ACT_TYPE, NULL AS EOPBAL_CAP, 
NULL AS EOPBAL_INT, NULL AVGBAL_CAP, NULL AS AVGBAL_INT, CAST(SUM(a.C7MONT * -1) AS DECIMAL(30,10)) AS PL, 'CDIF07' AS COD_INFO_SOURCE 
FROM MIS_LOAD_CDIF07 a 
--LEFT JOIN (select * FROM mis_tmp_glc002 where data_date in (SELECT MAX(DATA_DATE) FROM mis_tmp_glc002)) b
--ON CAST(C7MONE AS STRING) = GBCODE
WHERE STRLEFT(C7FEPR,6) = STRLEFT('${var:periodo}',6)
GROUP BY C3NUMP, C7AGEN, C7MONE, C7PROD
;

----Aprovisionamiento de Comisiones otras
INSERT INTO MIS_APR_FEES
PARTITION (DATA_DATE='${var:periodo}') 
SELECT 'COM' AS COD_CONT, a.S95TAR AS IDF_CTO, NULL AS COD_GL, NULL AS DES_GL, NULL AS COD_ACCO_CENT, 
NULL AS COD_OFFI, 'VIG' AS COD_BLCE_STATUS, 'RSL' AS COD_VALUE, 'HNL' AS COD_CURRENCY, '1' AS COD_ENTITY,
STRLEFT(a.S95CO1,8) AS COD_PRODUCT, CONCAT('COM_',a.S95COD) AS COD_SUBPRODUCT, IFNULL(NULL, '') AS COD_ACT_TYPE, NULL AS EOPBAL_CAP, 
NULL AS EOPBAL_INT, NULL AVGBAL_CAP, NULL AS AVGBAL_INT, CASE WHEN STRRIGHT('${var:periodo}',2) = '01' THEN CAST(isnull(a.S95MON,0) * -1 AS DECIMAL(30,10)) ELSE CAST((isnull(a.S95MON,0) * -1) + ISNULL(b.PL,0) AS DECIMAL(30,10)) END AS PL, 'S95TRA' AS COD_INFO_SOURCE 
FROM (SELECT S95COD, S95TAR, S95CO1, SUM(S95MON) AS S95MON FROM MIS_LOAD_S95TRA WHERE S95FE1 = '${var:periodo}' AND TRIM(S95COD) IN ('LI','29','MT','13','55','KD','I*','*I') GROUP BY S95COD, S95TAR, S95CO1) a
LEFT JOIN (SELECT * FROM MIS_APR_FEES WHERE TO_TIMESTAMP(DATA_DATE,'yyyyMMdd') = DATE_SUB(TO_TIMESTAMP('${var:periodo}','yyyyMMdd'),1) AND STRRIGHT('${var:periodo}',2) <> '01' AND COD_VALUE = 'RSL' AND COD_INFO_SOURCE = 'S95TRA') b
ON a.S95TAR = b.IDF_CTO AND CONCAT('COM_',a.S95COD) = b.COD_SUBPRODUCT
;

ALTER TABLE MIS_APR_CONTRACT_DT
DROP IF EXISTS PARTITION (DATA_DATE = '${var:periodo}', COD_INFO_SOURCE='CDIF03');

/*
----Aprovisionamiento de Contratos asociados a Contingentes
INSERT INTO MIS_APR_CONTRACT_DT 
PARTITION (DATA_DATE='${var:periodo}', COD_INFO_SOURCE='CDIF03') 
SELECT a.C3NUMP AS IDF_CTO, '1' AS COD_ENTITY, CAST(a.C3PROD AS STRING) AS COD_PRODUCT, 'COM' AS COD_SUBPRODUCT, IFNULL(NULL, '') AS COD_ACT_TYPE, CASE WHEN CAST(c3mone AS STRING) IN ('1','2') THEN 'USD' ELSE 'HNL' END AS COD_CURRENCY, ISNULL(CUX1CS,'99999999') AS IDF_CLI, NULL AS COD_ACCO_CENT, NULL AS COD_OFFI, 
NULL AS COD_BCA_INT, NULL AS COD_AMRT_MET, 'A' AS COD_RATE_TYPE, NULL AS RATE_INT,
NULL AS DATE_ORIGIN, NULL AS DATE_LAST_REV, NULL AS DATE_PRX_REV, 
NULL AS EXP_DATE, NULL AS FREQ_INT_PAY, NULL AS COD_UNI_FREQ_INT_PAY, NULL AS FRE_REV_INT, 
NULL AS COD_UNI_FRE_REV_INT, NULL AS AMRT_TRM, NULL AS COD_UNI_AMRT_TRM, NULL AS INI_AM, NULL AS CUO_AM, 
NULL AS CREDIT_LIM_AM, NULL AS PREDEF_RATE_IND, NULL AS PREDEF_RATE, NULL AS IND_CHANNEL, NULL AS COD_TYP_LIC,
NULL AS COD_SELLER, NULL AS DES_SELLER, NULL AS COU_CAR_OFF, NULL AS COD_CONV, NULL AS COD_EXEC_CTO, NULL AS COD_COVID_PORT, NULL AS DATE_DISB, NULL AS FIELD1_CTO, NULL AS FIELD2_CTO, NULL AS FIELD3_CTO, NULL AS FIELD4_CTO, NULL AS FIELD5_CTO, NULL AS FIELD6_CTO, NULL AS FIELD7_CTO, NULL AS FIELD8_CTO, NULL AS FIELD9_CTO, NULL AS FIELD10_CTO, NULL AS CARD_NUMBER, NULL AS COD_PROG_CARD, NULL AS DES_PROG_CARD
FROM MIS_LOAD_CDIF03 a
LEFT JOIN (select * from mis_load_cup00901 where cast(cux1ap as string) in ('50','51') and CUXREL in ('SOW', 'JAF', 'JOF', 'OWN')) b
on C3NUMP  =  CUX1AC
WHERE C3NUMP NOT IN (SELECT DISTINCT IDF_CTO FROM MIS_APR_CONTRACT_DT WHERE DATA_DATE = '${var:periodo}')
;
*/