------------------------------------------------------------- MIS_APR_OFF_BALANCE ---------------------------------------------------------

--- Comando que apunta a la base de datos apropiada ---
USE ${var:base_datos};
SET DECIMAL_V2=FALSE;

----Carga de tablas load
TRUNCATE TABLE IF EXISTS MIS_LOAD_SU_OPERACION; 
LOAD DATA INPATH '${var:ruta_fuentes_contingentes}/SU_OPERACION.CSV' INTO TABLE MIS_LOAD_SU_OPERACION;

--- Limpieza de partición ----
ALTER TABLE MIS_APR_OFF_BALANCE_M 
DROP IF EXISTS PARTITION (DATA_DATE = '${var:periodo}');

----Aprovisionamiento de Contingentes
INSERT INTO MIS_APR_OFF_BALANCE_M  
PARTITION (DATA_DATE='${var:periodo}') 
SELECT 'CTG' AS COD_CONT, 
    CASE WHEN STRLEFT(TRIM(a.OP_ID_OPERACION), 2)='LC' THEN REGEXP_REPLACE(TRIM(a.OP_ID_OPERACION), '/', '-') 
        ELSE TRIM(a.OP_ID_OPERACION) END AS IDF_CTO, 
    NULL AS COD_GL, NULL AS DES_GL, NULL AS COD_ACCO_CENT, NULL AS COD_OFFI,
    a.OP_ESTADO_OP AS COD_BLCE_STATUS, 'CAP' AS COD_VALUE,
    CASE TRIM(a.OP_TMONEDA) 
        WHEN '1' THEN 'CRC'
        WHEN '2' THEN 'USD' 
        WHEN '3' THEN 'EUR' END AS COD_CURRENCY, 
    '4' AS COD_ENTITY, 
    COALESCE(TRIM(SPE.COD_PRODUCT), TRIM(a.OP_PRODUCTO)) AS COD_PRODUCT,
    CASE 
        WHEN TRIM(a.OP_PRODUCTO) IN ('LRC', 'DC') THEN TRIM(a.OP_CTA_CBLE_SALDO_SC)
        WHEN TRIM(a.OP_PRODUCTO) = 'TCR' THEN TRIM(a.OP_CTA_DESEM_C)
        WHEN TRIM(a.OP_PRODUCTO) = 'CEX' AND STRLEFT(TRIM(a.OP_CTA_CTBLE_CAP), 2)='61' THEN TRIM(a.OP_CTA_CTBLE_CAP)
    END AS COD_SUBPRODUCT, NULL AS COD_ACT_TYPE,
    CAST((CASE 
        WHEN TRIM(a.OP_PRODUCTO) IN ('LRC', 'DC') THEN a.OP_SALDO_P_SC
        WHEN TRIM(a.OP_PRODUCTO) = 'TCR' THEN a.OP_SALDO_DESEM_C
        WHEN TRIM(a.OP_PRODUCTO) = 'CEX' AND STRLEFT(TRIM(a.OP_CTA_CTBLE_CAP), 2)='61' THEN a.OP_SALDO_CAP
    END) / IFNULL(b.EXCH_RATE, 1) AS decimal(30, 10)) AS EOPBAL_CAP,
    NULL AS EOPBAL_INT, NULL AS AVGBAL_CAP, NULL AS AVGBAL_INT,
    NULL AS PL, 'SU_OPERACION' AS COD_INFO_SOURCE
FROM MIS_LOAD_SU_OPERACION a 
LEFT JOIN MIS_PAR_EXCH_RATE b 
ON b.COD_CONT='TC_FOTO' AND b.DATA_DATE = '${var:periodo}' AND 
    b.COD_CURRENCY = CASE TRIM(a.OP_TMONEDA) 
                     WHEN '1' THEN 'CRC'
                     WHEN '2' THEN 'USD' 
                     WHEN '3' THEN 'EUR' END 
LEFT JOIN MIS_PAR_REL_PROD_SPE SPE 
ON TRIM(SPE.IDF_CTO) = CASE WHEN STRLEFT(TRIM(a.OP_ID_OPERACION), 2)='LC' THEN REGEXP_REPLACE(TRIM(a.OP_ID_OPERACION), '/', '-') 
                            ELSE TRIM(a.OP_ID_OPERACION) END 
WHERE (TRIM(a.OP_PRODUCTO) = 'LRC') OR (TRIM(a.OP_PRODUCTO) = 'DC') OR 
   (TRIM(a.OP_PRODUCTO) = 'TCR' AND TRIM(a.OP_ID_LINEA)=TRIM(a.OP_ID_OPERACION)) OR 
   (TRIM(a.OP_PRODUCTO) = 'CEX' AND STRLEFT(TRIM(a.OP_CTA_CTBLE_CAP), 2)='61') 
;


--- Limpieza de partición ----
ALTER TABLE MIS_APR_CONTRACT_DT
DROP IF EXISTS PARTITION (DATA_DATE = '${var:periodo}', COD_INFO_SOURCE='SU_OPERACION');

----Aprovisionamiento de Contingentes Contrato
INSERT INTO MIS_APR_CONTRACT_DT
PARTITION (DATA_DATE='${var:periodo}', COD_INFO_SOURCE='SU_OPERACION') 
SELECT 
    CASE WHEN STRLEFT(TRIM(a.OP_ID_OPERACION), 2)='LC' THEN REGEXP_REPLACE(a.OP_ID_OPERACION, '/', '-') 
         ELSE TRIM(a.OP_ID_OPERACION) END AS IDF_CTO, '4' AS COD_ENTITY, 
    COALESCE(TRIM(SPE.COD_PRODUCT), TRIM(a.OP_PRODUCTO)) AS COD_PRODUCT, 
    CASE 
        WHEN TRIM(a.OP_PRODUCTO) IN ('LRC', 'DC') THEN TRIM(a.OP_CTA_CBLE_SALDO_SC)
        WHEN TRIM(a.OP_PRODUCTO) = 'TCR' THEN TRIM(a.OP_CTA_DESEM_C)
        WHEN TRIM(a.OP_PRODUCTO) = 'CEX' AND STRLEFT(TRIM(a.OP_CTA_CTBLE_CAP), 2)='61' THEN TRIM(a.OP_CTA_CTBLE_CAP)
    END AS COD_SUBPRODUCT, NULL AS COD_ACT_TYPE, 
    CASE TRIM(a.OP_TMONEDA) 
         WHEN '1' THEN 'CRC'
         WHEN '2' THEN 'USD' 
         WHEN '3' THEN 'EUR' END AS COD_CURRENCY, 
    TRIM(a.OP_CLIENTE) AS IDF_CLI, 
    NULL AS COD_ACCO_CENT, NULL AS COD_OFFI, NULL AS COD_BCA_INT, NULL AS COD_AMRT_MET, 
    a.OP_TIPO_TASA AS COD_RATE_TYPE, 
    CAST(a.OP_TASA_INT_VIG/100 AS decimal(30, 10)) AS RATE_INT, 
    FROM_TIMESTAMP(TO_TIMESTAMP(a.OP_FECHA_FORMALIZA, 'yyyy/MM/dd'),'yyyyMMdd') AS DATE_ORIGIN, 
    NULL AS DATE_LAST_REV, 
    FROM_TIMESTAMP(TO_TIMESTAMP(a.OP_FCAMB_TASA_V, 'yyyy/MM/dd'),'yyyyMMdd') AS DATE_PRX_REV, 
    FROM_TIMESTAMP(TO_TIMESTAMP(a.OP_FECHA_VENCE, 'yyyy/MM/dd'),'yyyyMMdd') AS EXP_DATE, 
    CAST(a.OP_FREC_PGO_INT AS smallint) AS FREQ_INT_PAY, 'D' AS COD_UNI_FREQ_INT_PAY, 
    NULL AS FRE_REV_INT, NULL AS COD_UNI_FRE_REV_INT, 
    NULL AS AMRT_TRM, NULL AS COD_UNI_AMRT_TRM, 
    NULL AS INI_AM, NULL AS CUO_AM, NULL AS CREDIT_LIM_AM, 
    NULL AS PREDEF_RATE_IND, NULL AS PREDEF_RATE, NULL AS IND_CHANNEL, NULL AS COD_TYP_LIC, 
    NULL AS COU_CAR_OFF, NULL AS COD_CONV, 
    NULL AS COD_EXEC_CTO, NULL AS COD_COVID_PORT, 
    FROM_TIMESTAMP(TO_TIMESTAMP(a.OP_FECHA_FORMALIZA, 'yyyy/MM/dd'),'yyyyMMdd') AS DATE_DISB, 
    NULL AS CARD_NUMBER, NULL AS FIELD1_CTO, NULL AS FIELD2_CTO, NULL AS FIELD3_CTO, NULL AS FIELD4_CTO, 
    NULL AS FIELD5_CTO, NULL AS FIELD6_CTO, NULL AS FIELD7_CTO, NULL AS FIELD8_CTO, 
    NULL AS FIELD9_CTO, NULL AS FIELD10_CTO, NULL AS COD_PROG_CARD, NULL AS DES_PROG_CARD
FROM MIS_LOAD_SU_OPERACION a 
LEFT JOIN MIS_PAR_REL_PROD_SPE SPE 
ON TRIM(SPE.IDF_CTO) = CASE WHEN STRLEFT(TRIM(a.OP_ID_OPERACION), 2)='LC' THEN REGEXP_REPLACE(TRIM(a.OP_ID_OPERACION), '/', '-') 
                            ELSE TRIM(a.OP_ID_OPERACION) END 
WHERE (TRIM(a.OP_PRODUCTO) = 'LRC') OR (TRIM(a.OP_PRODUCTO) = 'DC') OR 
   (TRIM(a.OP_PRODUCTO) = 'TCR' AND TRIM(a.OP_ID_LINEA)=TRIM(a.OP_ID_OPERACION)) OR 
   (TRIM(a.OP_PRODUCTO) = 'CEX' AND STRLEFT(TRIM(a.OP_CTA_CTBLE_CAP), 2)='61') 
;