--------------------------------------------------------------- MIS_APR_CLIENT_DT ---------------------------------------------------------

--- Comando que dirige las consultas a la base de datos apropiada ---
USE ${var:base_datos};
SET DECIMAL_V2=FALSE;

--COMPUTE STATS MIS_APR_CLIENT_DT;

----Carga de tablas load
TRUNCATE TABLE IF EXISTS MIS_LOAD_CUMST;  
LOAD DATA INPATH '${var:ruta_fuentes_activos}/CUMST.CSV' INTO TABLE MIS_LOAD_CUMST; 

TRUNCATE TABLE MIS_PAR_CAT_ECO_GRO;
INSERT INTO MIS_PAR_CAT_ECO_GRO
select cuscun AS ID_ECO_GRO, 'PA' AS COU_ECO_GRO, CUSNA1 AS DES_ECO_GRO 
from MIS_LOAD_CUMST a
inner join (select distinct CUSGRP from MIS_LOAD_CUMST where CUSGRP <> '0') b
on a.cuscun = b.CUSGRP
;

ALTER TABLE MIS_APR_CLIENT_DT
DROP IF EXISTS PARTITION (DATA_DATE = '${var:periodo}');

DROP TABLE IF EXISTS MIS_TMP_PAR_SUBSEGMENT;
CREATE TABLE MIS_TMP_PAR_SUBSEGMENT AS
SELECT a.*,
    CASE 
    WHEN TRIM(a.COD_SEGMENT) != '' AND TRIM(a.COD_COUNTRY) != '' AND TRIM(a.COD_MANAGER) != '' THEN 1  --Subsegmento considerando Segmento, País, Oficina
    WHEN TRIM(a.COD_SEGMENT) != '' AND TRIM(a.COD_COUNTRY) != '' THEN 2                                --Subsegmento considerando Segmento, País 
    WHEN TRIM(a.COD_SEGMENT) != '' AND TRIM(a.COD_MANAGER) != '' THEN 3                                --Subsegmento considerando Segmento, Oficina
    ELSE 4 END AS TYPE_REL                                                                             --Subsegmento considerando Segmento
FROM MIS_PAR_REL_SUBSEGMENT a;

--COMPUTE STATS MIS_LOAD_CUMST;
--COMPUTE STATS 50100_PLAN_FINAN_PA.fact_seg_ingresos;

----Aprovisionamiento de Clientes
DROP TABLE IF EXISTS MIS_TMP_CLIENT_DT;
CREATE TABLE MIS_TMP_CLIENT_DT AS 
SELECT TRIM(a.CUSCUN) AS IDF_CLI, TRIM(a.CUSTID) AS TYP_DOC_ID, TRIM(a.CUSLN3) AS NUM_DOC_ID, CASE WHEN a.CUSLGT = '1' THEN TRIM(a.CUSNA1) ELSE TRIM(a.CUSFNA) END AS NOM_NAME, 
    TRIM(CONCAT(TRIM(a.CUSLN1)," ",TRIM(a.CUSLN2))) AS NOM_LASTN, TRIM(a.CUSCTR) AS COD_RES_COUNT, a.CUSLGT AS COD_TYP_CLNT, a.CUSSTS AS COD_COND_CLNT, 
    TRIM(a.CUSSEX) AS VAL_SEX, TRIM(a.CUSGEC) AS COD_COUNTRY, c.COD_SECTOR, c.DES_SECTOR, isnull(e.segmentacion,'SIN_SEGMENTAR') AS COD_SEGMENT, isnull(e.segmentacion,'SIN_SEGMENTAR') AS DES_SEGMENT, 
    TRIM(a.CUSSTF) AS IND_EMPL_GRUP, 
    CASE WHEN a.CUSIDY=0 AND a.CUSIDM=0 AND a.CUSIDD=0 THEN NULL
        WHEN a.CUSIDM>12 OR a.CUSIDD>31 THEN NULL 
        ELSE CONCAT(CASE WHEN CAST(STRRIGHT(CAST(YEAR(NOW()) AS string), 2) AS smallint) < a.CUSIDY 
                        THEN CONCAT('19', LPAD(CAST(a.CUSIDY AS string), 2, '0')) 
                        ELSE CONCAT('2', LPAD(CAST(a.CUSIDY AS string), 3, '0')) END, 
                    LPAD(CAST(a.CUSIDM AS string), 2, '0'), LPAD(CAST(a.CUSIDD  AS string), 2, '0'))
        END AS DATE_CLNT_REG, 
    CASE WHEN a.CUSLDY=0 AND a.CUSLDM=0 AND a.CUSLDD=0 THEN NULL
        WHEN a.CUSLDM>12 OR a.CUSLDD>31 THEN NULL 
        ELSE CONCAT(CASE WHEN CAST(STRRIGHT(CAST(YEAR(NOW()) AS string), 2) AS smallint) < a.CUSLDY 
                        THEN CONCAT('19', LPAD(CAST(a.CUSLDY AS string), 2, '0')) 
                        ELSE CONCAT('2', LPAD(CAST(a.CUSLDY AS string), 3, '0')) END, 
                    LPAD(CAST(a.CUSLDM AS string), 2, '0'), LPAD(CAST(a.CUSLDD  AS string), 2, '0'))
        END AS DATE_CLNT_WITHDRAW, TRIM(a.CUSOFC) AS COD_MANAGER, TRIM(b.CNODSC) AS DES_MANAGER,
    TRIM(a.CUSRSL) AS RATING_CLI, TRIM(a.CUSGRP) AS COD_GROUP_EC, a.CUSUC1 AS COD_SECTOR_LOCAL, 
    z.CNODSC AS DES_SECTOR_LOCAL, 
    CAST(NULL AS STRING) AS COD_SECTOR_REG, CAST(NULL AS STRING) AS DES_SECTOR_REG
FROM MIS_LOAD_CUMST a
LEFT JOIN (SELECT * FROM MIS_LOAD_CNOFC WHERE TRIM(CNOCFL) = '15') b
ON TRIM(a.CUSOFC) = TRIM(b.CNORCD) 
LEFT JOIN (SELECT * FROM MIS_LOAD_CNOFC WHERE TRIM(CNOCFL) = '2A') z
ON TRIM(a.CUSUC1) = TRIM( z.CNORCD)
LEFT JOIN MIS_PAR_REL_SECTOR c        --Asignación de sector
ON TRIM(a.CUSOFC) = TRIM(c.COD_MANAGER) 
LEFT JOIN MIS_PAR_REL_SEGMENT d       --Asignación de segmento
ON TRIM(a.CUSOFC) = TRIM(d.COD_MANAGER) AND TRIM(a.CUSTID) = TRIM(d.TYP_DOC_ID)
LEFT JOIN 50100_PLAN_FINAN_PA.fact_seg_ingresos e
ON e.CUSCUN = a.CUSCUN
;

--COMPUTE STATS MIS_TMP_CLIENT_DT;
--COMPUTE STATS MIS_TMP_PAR_SUBSEGMENT;

--Inserción en tabla de Clientes y asignación de Subsegmento
INSERT INTO MIS_APR_CLIENT_DT 
    (IDF_CLI, TYP_DOC_ID, NUM_DOC_ID, NOM_NAME, NOM_LASTN, COD_RES_COUNT, COD_TYP_CLNT, COD_COND_CLNT, COD_ENG, 
    VAL_SEX, COD_COUNTRY, COD_SECTOR, DES_SECTOR, COD_SEGMENT, DES_SEGMENT, COD_SUBSEGMENT, DES_SUBSEGMENT, 
    IND_EMPL_GRUP, DATE_CLNT_REG, DATE_CLNT_WITHDRAW, COD_MANAGER, DES_MANAGER, RATING_CLI, COD_GROUP_EC, ID_ECO_GRO, COU_ECO_GRO,COD_SECTOR_LOCAL, DES_SECTOR_LOCAL,COD_SECTOR_REG,DES_SECTOR_REG, FIELD1_CLI, FIELD2_CLI, FIELD3_CLI, FIELD4_CLI, FIELD5_CLI, FIELD6_CLI, FIELD7_CLI, FIELD8_CLI, FIELD9_CLI, FIELD10_CLI)
PARTITION (DATA_DATE='${var:periodo}') 
SELECT a.IDF_CLI, a.TYP_DOC_ID, a.NUM_DOC_ID, a.NOM_NAME, a.NOM_LASTN, a.COD_RES_COUNT, a.COD_TYP_CLNT, a.COD_COND_CLNT, 
    NULL AS COD_ENG, a.VAL_SEX, a.COD_COUNTRY, a.COD_SECTOR, a.DES_SECTOR, a.COD_SEGMENT, a.DES_SEGMENT, 
    TRIM(COALESCE(b.COD_SUBSEGMENT, c.COD_SUBSEGMENT, d.COD_SUBSEGMENT, e.COD_SUBSEGMENT)) AS COD_SUBSEGMENT,
    TRIM(COALESCE(b.DES_SUBSEGMENT, c.DES_SUBSEGMENT, d.DES_SUBSEGMENT, e.DES_SUBSEGMENT)) AS DES_SUBSEGMENT,
    a.IND_EMPL_GRUP, a.DATE_CLNT_REG, a.DATE_CLNT_WITHDRAW, a.COD_MANAGER, a.DES_MANAGER, a.RATING_CLI, a.COD_GROUP_EC, a.COD_GROUP_EC, 'PA', a.COD_SECTOR_LOCAL, a.DES_SECTOR_LOCAL, a.COD_SECTOR_REG, a.DES_SECTOR_REG, NULL AS FIELD1_CLI, NULL AS FIELD2_CLI, NULL AS FIELD3_CLI, NULL AS FIELD4_CLI, NULL AS FIELD5_CLI, NULL AS FIELD6_CLI, NULL AS FIELD7_CLI, NULL AS FIELD8_CLI, NULL AS FIELD9_CLI, NULL AS FIELD10_CLI
FROM MIS_TMP_CLIENT_DT a 
LEFT JOIN MIS_TMP_PAR_SUBSEGMENT b
ON b.TYPE_REL = 1 AND TRIM(a.COD_SEGMENT)= TRIM(b.COD_SEGMENT) AND TRIM(a.COD_COUNTRY) = TRIM(b.COD_COUNTRY) AND TRIM(a.COD_MANAGER) = TRIM(b.COD_MANAGER)
LEFT JOIN MIS_TMP_PAR_SUBSEGMENT c
ON c.TYPE_REL = 2 AND TRIM(a.COD_SEGMENT)= TRIM(c.COD_SEGMENT) AND TRIM(a.COD_COUNTRY) = TRIM(c.COD_COUNTRY)
LEFT JOIN MIS_TMP_PAR_SUBSEGMENT d
ON d.TYPE_REL = 3 AND TRIM(a.COD_SEGMENT)= TRIM(d.COD_SEGMENT) AND TRIM(a.COD_MANAGER) = TRIM(d.COD_MANAGER)
LEFT JOIN MIS_TMP_PAR_SUBSEGMENT e
ON e.TYPE_REL = 4 AND TRIM(a.COD_SEGMENT)= TRIM(e.COD_SEGMENT); 

TRUNCATE TABLE IF EXISTS MIS_TMP_PAR_SUBSEGMENT;
DROP TABLE IF EXISTS MIS_TMP_PAR_SUBSEGMENT;
TRUNCATE TABLE IF EXISTS MIS_TMP_CLIENT_DT;
DROP TABLE IF EXISTS MIS_TMP_CLIENT_DT;