--- Comando que apunta a la base de datos apropiada ---
USE ${var:base_datos};
SET DECIMAL_V2=FALSE;

--- Aprovisionamiento de Tabla atributos para tarjetas adicionales ---

INSERT INTO MIS_DM_BALANCE_RESULT_M
(COD_CONT, IDF_CTO, COD_CURRENCY, COD_ENTITY, IDF_CLI, TYP_DOC_ID, NUM_DOC_ID, NOM_NAME, 
COD_RES_COUNT, COD_TYP_CLNT, VAL_SEX,
COD_SEGMENT, DES_SEGMENT, COD_MANAGER, DATE_ORIGIN, INI_AM, COD_GL_GROUP, DES_GL_GROUP, COD_PL_ACC, DES_PL_ACC, 
COD_BLCE_PROD, DES_BLCE_PROD,
COD_BUSINESS_LINE, DES_BUSINESS_LINE, INI_AM_RPT, DATE_DISB, CARD_NUMBER)
PARTITION (DATA_DATE, COD_INFO_SOURCE)
SELECT CONTENIDO AS COD_CONT, IDF_CTO, DIVISA AS COD_CURRENCY, CT.COD_ENTITY, CT.IDF_CLI,
CT.TYP_DOC_ID, CT.NUM_DOC_ID, CT.NOM_NAME, CT.COD_RES_COUNT, CT.COD_TYP_CLNT, CT.VAL_SEX, CT.COD_SEGMENT, CT.DES_SEGMENT, CT.COD_MANAGER,
B.DATE_DISB AS DATE_ORIGIN, B.INI_AM_ADD AS INI_AM, COD_GL_GROUP, DES_GL_GROUP, COD_PL_ACC, DES_PL_ACC, 
COD_BLCE_PROD, DES_BLCE_PROD, COD_BUSINESS_LINE, 
DES_BUSINESS_LINE, B.INI_AM_ADD AS INI_AM_RPT, B.DATE_DISB, A.CARD_NUMBER, 
'${var:periodo}' AS DATA_DATE, CRITERIO_DE_AJUSTE AS COD_INFO_SOURCE
FROM MIS_DWH_MANUAL_ADJ_OPER_ADD_CRED_CARD A
INNER JOIN MIS_APR_CARD_ADD B
ON A.CARD_NUMBER_ADD = B.CARD_NUMBER_ADD
LEFT JOIN (SELECT DISTINCT CARD_NUMBER, COD_CURRENCY, COD_ENTITY, IDF_CLI, TYP_DOC_ID, NUM_DOC_ID, NOM_NAME, COD_RES_COUNT, COD_TYP_CLNT, VAL_SEX, 
COD_SEGMENT, DES_SEGMENT, COD_MANAGER, COD_GL_GROUP, DES_GL_GROUP, COD_PL_ACC, DES_PL_ACC, COD_BLCE_PROD, DES_BLCE_PROD, COD_BUSINESS_LINE, DES_BUSINESS_LINE
FROM MIS_DM_BALANCE_RESULT_M 
WHERE DATA_DATE = '${var:periodo}' AND COD_VALUE = 'CAP' AND IND_POOL IS NULL AND COD_CONT = 'PREST' AND COD_SUBPRODUCT = '130000') CT
ON A.CARD_NUMBER = CT.CARD_NUMBER
;