------------------------------------------- ACUMULACION DE SALDOS -------------------------------------------------------

--- Comando que dirige las consultas a la base de datos apropiada ---
USE ${var:base_datos};
SET DECIMAL_V2=FALSE;

--COMPUTE STATS MIS_DM_BALANCE_RESULT_M;
COMPUTE INCREMENTAL STATS MIS_DM_BALANCE_RESULT_M partition (data_date = '${var:periodo}');

ALTER TABLE MIS_DM_ACCUMULATED
DROP IF EXISTS PARTITION (DATA_DATE = '${var:periodo}');

INSERT INTO MIS_DM_ACCUMULATED
(COD_CONT,COD_ACCO_CENT,COD_BLCE_STATUS,COD_CURRENCY,COD_ENTITY,COD_PRODUCT,COD_SUBPRODUCT,COD_SEGMENT,DES_SEGMENT,COD_MANAGER,COD_GL_GROUP,COD_PL_ACC,COD_BLCE_PROD,COD_BUSINESS_LINE,IND_POOL,AVGBAL_TOT,AVGBAL_CAP,AVGBAL_INT,PL,FTP_RESULT,PL_TOT,AVGBAL_TOT_RPT,PL_TOT_RPT,PL_RPT,FTP_RESULT_RPT,AVGBAL_TOT_YTD,PL_YTD,FTP_RESULT_YTD,PL_TOT_YTD,AVGBAL_TOT_YTD_RPT,PL_YTD_RPT,PL_RPT_TRI_1,PL_RPT_TRI_2,PL_RPT_TRI_3,PL_RPT_TRI_4,PL_RPT_SEM_1,PL_RPT_SEM_2,ftp_result_ytd_rpt,pl_tot_ytd_rpt,
PL_TOT_RPT_TRI_1,PL_TOT_RPT_TRI_2,PL_TOT_RPT_TRI_3,PL_TOT_RPT_TRI_4,PL_TOT_RPT_SEM_1,PL_TOT_RPT_SEM_2,PL_RPT_MOB_YEAR,PL_TOT_RPT_MOB_YEAR,AVGBAL_TOT_RPT_TRI_1,AVGBAL_TOT_RPT_TRI_2,AVGBAL_TOT_RPT_TRI_3,AVGBAL_TOT_RPT_TRI_4,AVGBAL_TOT_RPT_SEM_1,AVGBAL_TOT_RPT_SEM_2,
PL_YTD_USD, PL_USD, PL_TOT_YTD_USD, PL_TOT_USD, FTP_RESULT_YTD_USD, FTP_RESULT_USD, 
PL_YTD_REG, PL_REG, PL_TOT_YTD_REG, PL_TOT_REG, FTP_RESULT_YTD_REG, FTP_RESULT_REG, 
PL_TOT_USD_TRI_1, PL_TOT_USD_TRI_2, PL_TOT_USD_TRI_3, PL_TOT_USD_TRI_4, PL_TOT_USD_SEM_1, PL_TOT_USD_SEM_2, 
PL_TOT_REG_TRI_1, PL_TOT_REG_TRI_2, PL_TOT_REG_TRI_3, PL_TOT_REG_TRI_4, PL_TOT_REG_SEM_1, PL_TOT_REG_SEM_2, 
COD_SECTOR_LOCAL, DES_SECTOR_LOCAL, COD_SECTOR_REG, DES_SECTOR_REG,COD_OFFI, DES_OFFI, 
EOPBAL_TOT_RPT, EOPBAL_TOT_USD, EOPBAL_TOT_REG, AVGBAL_TOT_USD, AVGBAL_TOT_REG,
COD_INFO_SOURCE, EXP_FAMILY, EXP_TYPE, COD_VALUE, COD_SECTOR, DES_PRODUCT, DES_SUBPRODUCT)
PARTITION (DATA_DATE)

SELECT 
    X.COD_CONT, X.COD_ACCO_CENT, X.COD_BLCE_STATUS, X.COD_CURRENCY, X.COD_ENTITY, X.COD_PRODUCT, X.COD_SUBPRODUCT, X.COD_SEGMENT, X.DES_SEGMENT, X.COD_MANAGER, X.COD_GL_GROUP,
    X.COD_PL_ACC, X.COD_BLCE_PROD, X.COD_BUSINESS_LINE, X.IND_POOL, CAST(ROUND(SUM(X.AVGBAL_TOT), 10) AS decimal(30,10)) AS AVGBAL_TOT, 
    CAST(ROUND(SUM(X.AVGBAL_CAP), 10) AS decimal(30,10)) AS AVGBAL_CAP, CAST(ROUND(SUM(X.AVGBAL_INT), 10) AS decimal(30,10)) AS AVGBAL_INT, CAST(ROUND(SUM(X.PL), 10) AS decimal(30,10)) AS PL, 
    CAST(ROUND(SUM(X.FTP_RESULT), 10) AS decimal(30, 10)) AS FTP_RESULT, CAST(ROUND(SUM(X.PL_TOT), 10) AS decimal(30,10)) AS PL_TOT, 
    CAST(ROUND(SUM(X.AVGBAL_TOT_RPT), 10) AS decimal(30,10)) AS AVGBAL_TOT_RPT, CAST(ROUND(SUM(X.PL_TOT_RPT), 10) AS decimal(30,10)) AS PL_TOT_RPT, 
    CAST(ROUND(SUM(X.PL_RPT), 10) AS decimal(30,10)) AS PL_RPT, CAST(ROUND(SUM(X.FTP_RESULT_RPT), 10) AS decimal(30, 10)) AS FTP_RESULT_RPT, 
    CAST(ROUND(SUM(X.AVGBAL_TOT_YTD)/MONTH(TO_TIMESTAMP(X.DATA_DATE, 'yyyyMMdd')), 10) AS decimal(30,10)) AVGBAL_TOT_YTD,
    CAST(ROUND(SUM(X.PL_YTD), 10) AS decimal(30,10)) AS PL_YTD,
    CAST(ROUND(SUM(X.FTP_RESULT_YTD), 10) AS decimal(30, 10)) AS FTP_RESULT_YTD,
    CAST(ROUND(SUM(X.PL_TOT_YTD), 10) AS decimal(30,10)) AS PL_TOT_YTD, 
    CAST(ROUND(SUM(X.AVGBAL_TOT_YTD_RPT)/MONTH(TO_TIMESTAMP(X.DATA_DATE, 'yyyyMMdd')), 10) AS decimal(30,10)) AS AVGBAL_TOT_YTD_RPT,
    CAST(ROUND(SUM(X.PL_YTD_RPT), 10) AS decimal(30,10)) AS PL_YTD_RPT,
    CAST(SUM(PL_RPT_TRI_1)  AS decimal(30,10)) AS PL_RPT_TRI_1, CAST(SUM(PL_RPT_TRI_2)  AS decimal(30,10)) AS PL_RPT_TRI_2, CAST(SUM(PL_RPT_TRI_3) AS decimal(30,10)) AS PL_RPT_TRI_3, CAST(SUM(PL_RPT_TRI_4) AS decimal(30,10)) AS 
    PL_RPT_TRI_4, CAST(SUM(PL_RPT_SEM_1) AS decimal(30,10)) AS PL_RPT_SEM_1, CAST(SUM(PL_RPT_SEM_2) AS decimal(30,10)) AS PL_RPT_SEM_2,
    CAST(ROUND(SUM(X.FTP_RESULT_YTD_RPT), 10) AS decimal(30, 10)) AS FTP_RESULT_YTD_RPT,
    CAST(ROUND(SUM(X.PL_TOT_YTD_RPT), 10) AS decimal(30,10)) AS PL_TOT_YTD_RPT,
    CAST(SUM(PL_TOT_RPT_TRI_1) AS decimal(30,10)) AS PL_TOT_RPT_TRI_1, CAST(SUM(PL_TOT_RPT_TRI_2) AS decimal(30,10)) AS PL_TOT_RPT_TRI_2, CAST(SUM(PL_TOT_RPT_TRI_3) AS decimal(30,10)) AS PL_TOT_RPT_TRI_3, 
    CAST(SUM(PL_TOT_RPT_TRI_4) AS decimal(30,10)) AS PL_TOT_RPT_TRI_4, CAST(SUM(PL_TOT_RPT_SEM_1) AS decimal(30,10)) AS PL_TOT_RPT_SEM_1, CAST(SUM(PL_TOT_RPT_SEM_2) AS decimal(30,10)) AS PL_TOT_RPT_SEM_2,CAST(ROUND(SUM(X.PL_RPT_MOB_YEAR), 10) AS decimal(30,10)) AS PL_RPT_MOB_YEAR, CAST(ROUND(SUM(PL_TOT_RPT_MOB_YEAR), 10) AS decimal(30,10)) AS PL_TOT_RPT_MOB_YEAR,
    CAST(ROUND(SUM(X.AVGBAL_TOT_RPT_TRI_1)/IF(CEILING(MONTH(TO_TIMESTAMP(X.DATA_DATE, 'yyyyMMdd'))/3) = 1, MOD(MONTH(TO_TIMESTAMP(X.DATA_DATE, 'yyyyMMdd'))-1,3)+1, 3), 10) AS decimal(30,10)) AS AVGBAL_TOT_RPT_TRI_1, 
    CAST(ROUND(SUM(X.AVGBAL_TOT_RPT_TRI_2)/IF(CEILING(MONTH(TO_TIMESTAMP(X.DATA_DATE, 'yyyyMMdd'))/3) = 2, MOD(MONTH(TO_TIMESTAMP(X.DATA_DATE, 'yyyyMMdd'))-1,3)+1, 3), 10) AS decimal(30,10)) AS AVGBAL_TOT_RPT_TRI_2, 
    CAST(ROUND(SUM(X.AVGBAL_TOT_RPT_TRI_3)/IF(CEILING(MONTH(TO_TIMESTAMP(X.DATA_DATE, 'yyyyMMdd'))/3) = 3, MOD(MONTH(TO_TIMESTAMP(X.DATA_DATE, 'yyyyMMdd'))-1,3)+1, 3), 10) AS decimal(30,10)) AS AVGBAL_TOT_RPT_TRI_3, 
    CAST(ROUND(SUM(X.AVGBAL_TOT_RPT_TRI_4)/IF(CEILING(MONTH(TO_TIMESTAMP(X.DATA_DATE, 'yyyyMMdd'))/3) = 4, MOD(MONTH(TO_TIMESTAMP(X.DATA_DATE, 'yyyyMMdd'))-1,3)+1, 3), 10) AS decimal(30,10)) AS AVGBAL_TOT_RPT_TRI_4, 
    CAST(ROUND(SUM(X.AVGBAL_TOT_RPT_SEM_1)/IF(CEILING(MONTH(TO_TIMESTAMP(X.DATA_DATE, 'yyyyMMdd'))/6) = 1, MOD(MONTH(TO_TIMESTAMP(X.DATA_DATE, 'yyyyMMdd'))-1,6)+1, 6), 10) AS decimal(30,10)) AS AVGBAL_TOT_RPT_SEM_1, 
    CAST(ROUND(SUM(X.AVGBAL_TOT_RPT_SEM_2)/IF(CEILING(MONTH(TO_TIMESTAMP(X.DATA_DATE, 'yyyyMMdd'))/6) = 2, MOD(MONTH(TO_TIMESTAMP(X.DATA_DATE, 'yyyyMMdd'))-1,6)+1, 6), 10) AS decimal(30,10)) AS AVGBAL_TOT_RPT_SEM_2,
    CAST(ROUND(SUM(X.PL_YTD_USD), 10) AS decimal(30,10)) AS PL_YTD_USD, CAST(ROUND(SUM(X.PL_USD), 10) AS decimal(30,10)) AS PL_USD,
    CAST(ROUND(SUM(X.PL_TOT_YTD_USD), 10) AS decimal(30,10)) AS PL_TOT_YTD_USD,
    CAST(ROUND(IF(SUM(X.PL_TOT_RPT)=0,0,SUM(X.PL_TOT_USD)), 10) AS decimal(30,10)) AS PL_TOT_USD,
    CAST(ROUND(SUM(X.FTP_RESULT_YTD_USD), 10) AS decimal(30,10)) AS FTP_RESULT_YTD_USD,
    CAST(ROUND(SUM(X.FTP_RESULT_USD), 10) AS decimal(30,10)) AS FTP_RESULT_USD,
    CAST(ROUND(SUM(X.PL_YTD_REG), 10) AS decimal(30,10)) AS PL_YTD_REG,
    CAST(ROUND(SUM(X.PL_REG), 10) AS decimal(30,10)) AS PL_REG,
    CAST(ROUND(SUM(X.PL_TOT_YTD_REG), 10) AS decimal(30,10)) AS PL_TOT_YTD_REG,
    CAST(ROUND(IF(SUM(X.PL_TOT_RPT)=0,0,SUM(X.PL_TOT_REG)), 10) AS decimal(30,10)) AS PL_TOT_REG,
    CAST(ROUND(SUM(X.FTP_RESULT_YTD_REG), 10) AS decimal(30,10)) AS FTP_RESULT_YTD_REG,
    CAST(ROUND(SUM(X.FTP_RESULT_REG), 10) AS decimal(30,10)) AS FTP_RESULT_REG,    
    CAST(ROUND(SUM(X.PL_TOT_USD_TRI_1), 10) AS decimal(30,10)) AS PL_TOT_USD_TRI_1, 
    CAST(ROUND(SUM(X.PL_TOT_USD_TRI_2), 10) AS decimal(30,10)) AS PL_TOT_USD_TRI_2, 
    CAST(ROUND(SUM(X.PL_TOT_USD_TRI_3), 10) AS decimal(30,10)) AS PL_TOT_USD_TRI_3, 
    CAST(ROUND(SUM(X.PL_TOT_USD_TRI_4), 10) AS decimal(30,10)) AS PL_TOT_USD_TRI_4, 
    CAST(ROUND(SUM(X.PL_TOT_USD_SEM_1), 10) AS decimal(30,10)) AS PL_TOT_USD_SEM_1, 
    CAST(ROUND(SUM(X.PL_TOT_USD_SEM_2), 10) AS decimal(30,10)) AS PL_TOT_USD_SEM_2,
    CAST(ROUND(SUM(X.PL_TOT_REG_TRI_1), 10) AS decimal(30,10)) AS PL_TOT_REG_TRI_1, 
    CAST(ROUND(SUM(X.PL_TOT_REG_TRI_2), 10) AS decimal(30,10)) AS PL_TOT_REG_TRI_2, 
    CAST(ROUND(SUM(X.PL_TOT_REG_TRI_3), 10) AS decimal(30,10)) AS PL_TOT_REG_TRI_3, 
    CAST(ROUND(SUM(X.PL_TOT_REG_TRI_4), 10) AS decimal(30,10)) AS PL_TOT_REG_TRI_4, 
    CAST(ROUND(SUM(X.PL_TOT_REG_SEM_1), 10) AS decimal(30,10)) AS PL_TOT_REG_SEM_1, 
    CAST(ROUND(SUM(X.PL_TOT_REG_SEM_2), 10) AS decimal(30,10)) AS PL_TOT_REG_SEM_2,
    X.COD_SECTOR_LOCAL, X.DES_SECTOR_LOCAL, X.COD_SECTOR_REG, X.DES_SECTOR_REG, X.COD_OFFI, X.DES_OFFI,
    CAST(ROUND(SUM(X.EOPBAL_TOT_RPT), 10) AS decimal (30, 10)) AS EOPBAL_TOT_RPT,
    CAST(ROUND(SUM(X.EOPBAL_TOT_USD), 10) AS decimal (30, 10)) AS EOPBAL_TOT_USD,
    CAST(ROUND(SUM(X.EOPBAL_TOT_REG), 10) AS decimal (30, 10)) AS EOPBAL_TOT_REG,
    CAST(ROUND(SUM(X.AVGBAL_TOT_USD), 10) AS decimal (30, 10)) AS AVGBAL_TOT_USD,
    CAST(ROUND(SUM(X.AVGBAL_TOT_REG), 10) AS decimal (30, 10)) AS AVGBAL_TOT_REG,
    X.COD_INFO_SOURCE, X.EXP_FAMILY, X.EXP_TYPE, X.COD_VALUE, X.COD_SECTOR, X.DES_PRODUCT, X.DES_SUBPRODUCT, X.DATA_DATE
FROM
    (SELECT 
        A.COD_CONT, A.COD_ACCO_CENT, A.COD_BLCE_STATUS, A.COD_CURRENCY, A.COD_ENTITY, A.COD_PRODUCT, A.COD_SUBPRODUCT, A.COD_SEGMENT, A.DES_SEGMENT, A.COD_MANAGER, A.COD_GL_GROUP, A.COD_PL_ACC, A.COD_BLCE_PROD, 
        A.COD_BUSINESS_LINE, A.IND_POOL, SUM(A.EOPBAL_TOT) AS EOPBAL_TOT, SUM(A.EOPBAL_CAP) AS EOPBAL_CAP, SUM(A.EOPBAL_INT) AS EOPBAL_INT, SUM(A.AVGBAL_TOT) AS AVGBAL_TOT, 
        SUM(A.AVGBAL_CAP) AS AVGBAL_CAP, SUM(A.AVGBAL_INT) AS AVGBAL_INT, SUM(A.PL) AS PL, SUM(A.FTP) AS FTP, SUM(A.FTP_RESULT) AS FTP_RESULT, SUM(A.PL_TOT) AS PL_TOT, 
        SUM(A.EOPBAL_TOT_RPT) AS EOPBAL_TOT_RPT, SUM(A.AVGBAL_TOT_RPT) AS AVGBAL_TOT_RPT, SUM(A.PL_TOT_RPT) AS PL_TOT_RPT, SUM(A.PL_RPT) AS PL_RPT, SUM(A.FTP_RESULT_RPT) AS FTP_RESULT_RPT,
        SUM(A.AVGBAL_TOT) AS AVGBAL_TOT_YTD,
        SUM(A.PL) AS PL_YTD, 
        SUM(A.FTP_RESULT) AS FTP_RESULT_YTD, 
        SUM(A.PL_TOT) AS PL_TOT_YTD, 
        SUM(A.AVGBAL_TOT_RPT) AS AVGBAL_TOT_YTD_RPT, 
        SUM(A.PL_RPT) AS PL_YTD_RPT,
        SUM(A.FTP_RESULT_RPT)  AS FTP_RESULT_YTD_RPT, 
        SUM(A.PL_TOT_RPT) AS PL_TOT_YTD_RPT, 
        SUM(IF(MONTH(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd')) IN (1, 2, 3), PL_RPT, 0)) AS PL_RPT_TRI_1,
        SUM(IF(MONTH(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd')) IN (4, 5, 6), PL_RPT, 0)) AS PL_RPT_TRI_2,
        SUM(IF(MONTH(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd')) IN (7, 8, 9), PL_RPT, 0)) AS PL_RPT_TRI_3,
        SUM(IF(MONTH(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd')) IN (10, 11, 12), PL_RPT, 0)) AS PL_RPT_TRI_4,
        SUM(IF(MONTH(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd')) IN (1, 2, 3, 4, 5, 6), PL_RPT, 0)) AS PL_RPT_SEM_1,
        SUM(IF(MONTH(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd')) IN (7, 8, 9, 10, 11, 12), PL_RPT, 0)) AS PL_RPT_SEM_2,
        SUM(IF(MONTH(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd')) IN (1, 2, 3), PL_TOT_RPT, 0)) AS PL_TOT_RPT_TRI_1,
        SUM(IF(MONTH(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd')) IN (4, 5, 6), PL_TOT_RPT, 0)) AS PL_TOT_RPT_TRI_2,
        SUM(IF(MONTH(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd')) IN (7, 8, 9), PL_TOT_RPT, 0)) AS PL_TOT_RPT_TRI_3,
        SUM(IF(MONTH(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd')) IN (10, 11, 12), PL_TOT_RPT, 0)) AS PL_TOT_RPT_TRI_4,
        SUM(IF(MONTH(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd')) IN (1, 2, 3, 4, 5, 6), PL_TOT_RPT, 0)) AS PL_TOT_RPT_SEM_1,
        SUM(IF(MONTH(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd')) IN (7, 8, 9, 10, 11, 12), PL_TOT_RPT, 0)) AS PL_TOT_RPT_SEM_2,
        SUM(A.PL_RPT) AS PL_RPT_MOB_YEAR, SUM(A.PL_TOT_RPT) AS PL_TOT_RPT_MOB_YEAR,
        SUM(IF(MONTH(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd')) IN (1, 2, 3), A.AVGBAL_TOT_RPT, 0)) AS AVGBAL_TOT_RPT_TRI_1,
        SUM(IF(MONTH(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd')) IN (4, 5, 6), A.AVGBAL_TOT_RPT, 0)) AS AVGBAL_TOT_RPT_TRI_2,
        SUM(IF(MONTH(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd')) IN (7, 8, 9), A.AVGBAL_TOT_RPT, 0)) AS AVGBAL_TOT_RPT_TRI_3,
        SUM(IF(MONTH(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd')) IN (10, 11, 12), A.AVGBAL_TOT_RPT, 0)) AS AVGBAL_TOT_RPT_TRI_4,
        SUM(IF(MONTH(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd')) IN (1, 2, 3, 4, 5, 6), A.AVGBAL_TOT_RPT, 0)) AS AVGBAL_TOT_RPT_SEM_1,
        SUM(IF(MONTH(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd')) IN (7, 8, 9, 10, 11, 12), A.AVGBAL_TOT_RPT, 0)) AS AVGBAL_TOT_RPT_SEM_2,
        SUM(CAST(A.PL_RPT/b.EXCH_RATE AS DECIMAL(30,10))) AS PL_YTD_USD,
        SUM(CAST(A.PL_RPT/b.EXCH_RATE AS DECIMAL(30,10))) AS PL_USD,
        SUM(CAST(A.PL_TOT_RPT/b.EXCH_RATE AS DECIMAL(30,10))) AS PL_TOT_YTD_USD,
        SUM(CAST(A.PL_TOT_RPT/b.EXCH_RATE AS DECIMAL(30,10))) AS PL_TOT_USD,
        SUM(CAST(A.FTP_RESULT_RPT/b.EXCH_RATE AS DECIMAL(30,10))) AS FTP_RESULT_YTD_USD,
        SUM(CAST(A.FTP_RESULT_RPT/b.EXCH_RATE AS DECIMAL(30,10))) AS FTP_RESULT_USD,
        SUM(CAST(A.PL_RPT/c.EXCH_RATE AS DECIMAL(30,10))) AS PL_YTD_REG,
        SUM(CAST(A.PL_RPT/c.EXCH_RATE AS DECIMAL(30,10))) AS PL_REG,
        SUM(CAST(A.PL_TOT_RPT/c.EXCH_RATE AS DECIMAL(30,10))) AS PL_TOT_YTD_REG,
        SUM(CAST(A.PL_TOT_RPT/c.EXCH_RATE AS DECIMAL(30,10))) AS PL_TOT_REG,
        SUM(CAST(A.FTP_RESULT_RPT/c.EXCH_RATE AS DECIMAL(30,10))) AS FTP_RESULT_YTD_REG,
        SUM(CAST(A.FTP_RESULT_RPT/c.EXCH_RATE AS DECIMAL(30,10))) AS FTP_RESULT_REG,      
        SUM(IF(MONTH(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd')) IN (1, 2, 3), A.PL_TOT_RPT, 0)) AS PL_TOT_USD_TRI_1,
        SUM(IF(MONTH(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd')) IN (4, 5, 6), A.PL_TOT_RPT, 0)) AS PL_TOT_USD_TRI_2,
        SUM(IF(MONTH(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd')) IN (7, 8, 9), A.PL_TOT_RPT, 0)) AS PL_TOT_USD_TRI_3,
        SUM(IF(MONTH(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd')) IN (10, 11, 12), A.PL_TOT_RPT, 0)) AS PL_TOT_USD_TRI_4,
        SUM(IF(MONTH(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd')) IN (1, 2, 3, 4, 5, 6), A.PL_TOT_RPT, 0)) AS PL_TOT_USD_SEM_1,
        SUM(IF(MONTH(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd')) IN (7, 8, 9, 10, 11, 12), A.PL_TOT_RPT, 0)) AS PL_TOT_USD_SEM_2,
        SUM(IF(MONTH(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd')) IN (1, 2, 3), A.PL_TOT_RPT, 0)) AS PL_TOT_REG_TRI_1,
        SUM(IF(MONTH(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd')) IN (4, 5, 6), A.PL_TOT_RPT, 0)) AS PL_TOT_REG_TRI_2,
        SUM(IF(MONTH(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd')) IN (7, 8, 9), A.PL_TOT_RPT, 0)) AS PL_TOT_REG_TRI_3,
        SUM(IF(MONTH(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd')) IN (10, 11, 12), A.PL_TOT_RPT, 0)) AS PL_TOT_REG_TRI_4,
        SUM(IF(MONTH(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd')) IN (1, 2, 3, 4, 5, 6), A.PL_TOT_RPT, 0)) AS PL_TOT_REG_SEM_1,
        SUM(IF(MONTH(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd')) IN (7, 8, 9, 10, 11, 12), A.PL_TOT_RPT, 0)) AS PL_TOT_REG_SEM_2,
        A.COD_SECTOR_LOCAL, A.DES_SECTOR_LOCAL, A.COD_SECTOR_REG, A.DES_SECTOR_REG, A.COD_OFFI, A.DES_OFFI,
        SUM(A.EOPBAL_TOT_RPT/b.EXCH_RATE) AS EOPBAL_TOT_USD,
        SUM(A.EOPBAL_TOT_RPT/c.EXCH_RATE) AS EOPBAL_TOT_REG,
        SUM(A.AVGBAL_TOT_RPT/b.EXCH_RATE) AS AVGBAL_TOT_USD,
        SUM(A.AVGBAL_TOT_RPT/c.EXCH_RATE) AS AVGBAL_TOT_REG,
        A.COD_INFO_SOURCE, A.EXP_FAMILY, A.EXP_TYPE, A.COD_VALUE, A.COD_SECTOR, A.DES_PRODUCT, A.DES_SUBPRODUCT, A.DATA_DATE
    FROM MIS_DM_BALANCE_RESULT_M AS A
    LEFT JOIN MIS_PAR_EXCH_RATE b   
    ON b.DATA_DATE = '${var:periodo}' AND b.COD_CONT = 'TC_FOTO' AND b.COD_CURRENCY = 'USD' AND A.cod_entity = b.cod_entity
LEFT JOIN MIS_PAR_EXCH_RATE c   
    ON c.DATA_DATE = '${var:periodo}' /*AND c.COD_CONT = 'TC_PROMEDIO'*/ AND c.COD_CURRENCY = 'USD' AND A.cod_entity = c.cod_entity
    WHERE A.DATA_DATE = '${var:periodo}'
    GROUP BY A.COD_CONT, A.COD_ACCO_CENT, A.COD_BLCE_STATUS, A.COD_CURRENCY, A.COD_ENTITY, A.COD_PRODUCT, A.COD_SUBPRODUCT, A.COD_SEGMENT, A.DES_SEGMENT, A.COD_MANAGER, A.COD_GL_GROUP, 
    A.COD_PL_ACC, A.COD_BLCE_PROD, A.COD_BUSINESS_LINE, A.IND_POOL, A.COD_SECTOR_LOCAL, A.DES_SECTOR_LOCAL, A.COD_SECTOR_REG, A.DES_SECTOR_REG, A.COD_OFFI, A.DES_OFFI,
A.COD_INFO_SOURCE, A.EXP_FAMILY, A.EXP_TYPE, A.COD_VALUE, A.COD_SECTOR, A.DES_PRODUCT, A.DES_SUBPRODUCT, A.DATA_DATE
UNION ALL 
    SELECT 
        A.COD_CONT, A.COD_ACCO_CENT, A.COD_BLCE_STATUS, A.COD_CURRENCY, A.COD_ENTITY, A.COD_PRODUCT, A.COD_SUBPRODUCT, A.COD_SEGMENT, A.DES_SEGMENT, A.COD_MANAGER, A.COD_GL_GROUP, A.COD_PL_ACC, A.COD_BLCE_PROD, 
        A.COD_BUSINESS_LINE, A.IND_POOL, 0 AS EOPBAL_TOT, 0 AS EOPBAL_CAP, 0 AS EOPBAL_INT, 0 AS AVGBAL_TOT, 0 AS AVGBAL_CAP, 0 AS AVGBAL_INT, 0 AS PL, 0 AS FTP, 0 AS FTP_RESULT, 0 AS PL_TOT, 0 AS EOPBAL_TOT_RPT, 
        0 AS AVGBAL_TOT_RPT, 0 AS PL_TOT_RPT, 0 AS PL_RPT, 0 AS FTP_RESULT_RPT, 
        SUM(IF(YEAR(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd'))=YEAR(TO_TIMESTAMP('${var:periodo}', 'yyyyMMdd')), A.AVGBAL_TOT, 0)) AS AVGBAL_TOT_YTD, 
        SUM(IF(YEAR(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd'))=YEAR(TO_TIMESTAMP('${var:periodo}', 'yyyyMMdd')), A.PL, 0)) AS PL_YTD, 
        SUM(IF(YEAR(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd'))=YEAR(TO_TIMESTAMP('${var:periodo}', 'yyyyMMdd')), A.FTP_RESULT, 0)) AS FTP_RESULT_YTD, 
        SUM(IF(YEAR(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd'))=YEAR(TO_TIMESTAMP('${var:periodo}', 'yyyyMMdd')), A.PL_TOT, 0)) AS PL_TOT_YTD, 
        SUM(IF(YEAR(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd'))=YEAR(TO_TIMESTAMP('${var:periodo}', 'yyyyMMdd')), A.AVGBAL_TOT_RPT, 0)) AS AVGBAL_TOT_YTD_RPT, 
        SUM(IF(YEAR(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd'))=YEAR(TO_TIMESTAMP('${var:periodo}', 'yyyyMMdd')), A.PL_RPT, 0)) AS PL_YTD_RPT, 
        SUM(IF(YEAR(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd'))=YEAR(TO_TIMESTAMP('${var:periodo}', 'yyyyMMdd')), A.FTP_RESULT, 0)) AS FTP_RESULT_YTD_RPT, 
        SUM(IF(YEAR(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd'))=YEAR(TO_TIMESTAMP('${var:periodo}', 'yyyyMMdd')), A.PL_TOT_RPT, 0)) AS PL_TOT_YTD_RPT, 
        SUM(IF(YEAR(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd'))=YEAR(TO_TIMESTAMP('${var:periodo}', 'yyyyMMdd')) AND MONTH(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd')) IN (1, 2, 3), A.PL_RPT, 0)) AS PL_RPT_TRI_1,
        SUM(IF(YEAR(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd'))=YEAR(TO_TIMESTAMP('${var:periodo}', 'yyyyMMdd')) AND MONTH(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd')) IN (4, 5, 6), A.PL_RPT, 0)) AS PL_RPT_TRI_2,
        SUM(IF(YEAR(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd'))=YEAR(TO_TIMESTAMP('${var:periodo}', 'yyyyMMdd')) AND MONTH(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd')) IN (7, 8, 9), A.PL_RPT, 0)) AS PL_RPT_TRI_3,
        SUM(IF(YEAR(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd'))=YEAR(TO_TIMESTAMP('${var:periodo}', 'yyyyMMdd')) AND MONTH(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd')) IN (10, 11, 12), A.PL_RPT, 0)) AS PL_RPT_TRI_4,
        SUM(IF(YEAR(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd'))=YEAR(TO_TIMESTAMP('${var:periodo}', 'yyyyMMdd')) AND MONTH(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd')) IN (1, 2, 3, 4, 5, 6), A.PL_RPT, 0)) AS PL_RPT_SEM_1,
        SUM(IF(YEAR(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd'))=YEAR(TO_TIMESTAMP('${var:periodo}', 'yyyyMMdd')) AND MONTH(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd')) IN (7, 8, 9, 10, 11, 12), A.PL_RPT, 0)) AS PL_RPT_SEM_2,
        SUM(IF(YEAR(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd'))=YEAR(TO_TIMESTAMP('${var:periodo}', 'yyyyMMdd')) AND MONTH(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd')) IN (1, 2, 3), A.PL_TOT_RPT, 0)) AS PL_TOT_RPT_TRI_1,
        SUM(IF(YEAR(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd'))=YEAR(TO_TIMESTAMP('${var:periodo}', 'yyyyMMdd')) AND MONTH(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd')) IN (4, 5, 6), A.PL_TOT_RPT, 0)) AS PL_TOT_RPT_TRI_2,
        SUM(IF(YEAR(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd'))=YEAR(TO_TIMESTAMP('${var:periodo}', 'yyyyMMdd')) AND MONTH(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd')) IN (7, 8, 9), A.PL_TOT_RPT, 0)) AS PL_TOT_RPT_TRI_3,
        SUM(IF(YEAR(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd'))=YEAR(TO_TIMESTAMP('${var:periodo}', 'yyyyMMdd')) AND MONTH(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd')) IN (10, 11, 12), A.PL_TOT_RPT, 0)) AS PL_TOT_RPT_TRI_4,
        SUM(IF(YEAR(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd'))=YEAR(TO_TIMESTAMP('${var:periodo}', 'yyyyMMdd')) AND MONTH(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd')) IN (1, 2, 3, 4, 5, 6), A.PL_TOT_RPT, 0)) AS PL_TOT_RPT_SEM_1,
        SUM(IF(YEAR(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd'))=YEAR(TO_TIMESTAMP('${var:periodo}', 'yyyyMMdd')) AND MONTH(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd')) IN (7, 8, 9, 10, 11, 12), A.PL_TOT_RPT, 0)) AS PL_TOT_RPT_SEM_2,
        SUM(A.PL_RPT) AS PL_RPT_MOB_YEAR, SUM(A.PL_TOT_RPT) AS PL_TOT_RPT_MOB_YEAR,
        SUM(IF(MONTH(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd')) IN (1, 2, 3) AND YEAR(TO_TIMESTAMP(A.DATA_DATE, 
        'yyyyMMdd'))=YEAR(TO_TIMESTAMP('${var:periodo}', 'yyyyMMdd')), A.AVGBAL_TOT_RPT, 0)) AS AVGBAL_TOT_RPT_TRI_1,
        SUM(IF(MONTH(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd')) IN (4, 5, 6) AND YEAR(TO_TIMESTAMP(A.DATA_DATE, 
        'yyyyMMdd'))=YEAR(TO_TIMESTAMP('${var:periodo}', 'yyyyMMdd')), A.AVGBAL_TOT_RPT, 0)) AS AVGBAL_TOT_RPT_TRI_2,
        SUM(IF(MONTH(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd')) IN (7, 8, 9) AND YEAR(TO_TIMESTAMP(A.DATA_DATE, 
        'yyyyMMdd'))=YEAR(TO_TIMESTAMP('${var:periodo}', 'yyyyMMdd')), A.AVGBAL_TOT_RPT, 0)) AS AVGBAL_TOT_RPT_TRI_3,
        SUM(IF(MONTH(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd')) IN (10, 11, 12) AND YEAR(TO_TIMESTAMP(A.DATA_DATE, 
        'yyyyMMdd'))=YEAR(TO_TIMESTAMP('${var:periodo}', 'yyyyMMdd')), A.AVGBAL_TOT_RPT, 0)) AS AVGBAL_TOT_RPT_TRI_4,
        SUM(IF(MONTH(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd')) IN (1, 2, 3, 4, 5, 6) AND YEAR(TO_TIMESTAMP(A.DATA_DATE, 
        'yyyyMMdd'))=YEAR(TO_TIMESTAMP('${var:periodo}', 'yyyyMMdd')), A.AVGBAL_TOT_RPT, 0)) AS AVGBAL_TOT_RPT_SEM_1,
        SUM(IF(MONTH(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd')) IN (7, 8, 9, 10, 11, 12) AND YEAR(TO_TIMESTAMP(A.DATA_DATE, 
        'yyyyMMdd'))=YEAR(TO_TIMESTAMP('${var:periodo}', 'yyyyMMdd')), A.AVGBAL_TOT_RPT, 0)) AS AVGBAL_TOT_RPT_SEM_2,
        CAST(SUM(IF(YEAR(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd'))=YEAR(TO_TIMESTAMP('${var:periodo}', 'yyyyMMdd')), A.PL_RPT/b.EXCH_RATE, 0)) AS DECIMAL(30,10)) AS PL_YTD_USD, 
        CAST(SUM(IF(YEAR(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd'))=YEAR(TO_TIMESTAMP('${var:periodo}', 'yyyyMMdd')), (A.PL_RPT/b.EXCH_RATE), 0))
        - SUM(IF(YEAR(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd'))=YEAR(TO_TIMESTAMP('${var:periodo}', 'yyyyMMdd')) AND 
             MONTH(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd'))=MONTH(ADD_MONTHS(TO_TIMESTAMP('${var:periodo}', 'yyyyMMdd'),-1)), A.PL_YTD_USD, 0)) AS DECIMAL(30,10)) AS PL_USD, 
        CAST(SUM(IF(YEAR(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd'))=YEAR(TO_TIMESTAMP('${var:periodo}', 'yyyyMMdd')), A.PL_TOT_RPT/b.EXCH_RATE, 0)) AS DECIMAL(30,10)) AS PL_TOT_YTD_USD, 
        CAST(SUM(IF(YEAR(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd'))=YEAR(TO_TIMESTAMP('${var:periodo}', 'yyyyMMdd')), (A.PL_TOT_RPT/b.EXCH_RATE), 0))
        - SUM(IF(YEAR(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd'))=YEAR(TO_TIMESTAMP('${var:periodo}', 'yyyyMMdd')) AND 
             MONTH(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd'))=MONTH(ADD_MONTHS(TO_TIMESTAMP('${var:periodo}', 'yyyyMMdd'),-1)), A.PL_TOT_YTD_USD, 0)) AS DECIMAL(30,10)) AS PL_TOT_USD, 
        CAST(SUM(IF(YEAR(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd'))=YEAR(TO_TIMESTAMP('${var:periodo}', 'yyyyMMdd')), A.FTP_RESULT_RPT/b.EXCH_RATE, 0)) AS DECIMAL(30,10)) AS FTP_RESULT_YTD_USD, 
        CAST(SUM(IF(YEAR(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd'))=YEAR(TO_TIMESTAMP('${var:periodo}', 'yyyyMMdd')), (A.FTP_RESULT_RPT/b.EXCH_RATE), 0))
        - SUM(IF(YEAR(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd'))=YEAR(TO_TIMESTAMP('${var:periodo}', 'yyyyMMdd')) AND 
             MONTH(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd'))=MONTH(ADD_MONTHS(TO_TIMESTAMP('${var:periodo}', 'yyyyMMdd'),-1)), A.FTP_RESULT_YTD_USD, 0)) AS DECIMAL(30,10)) AS FTP_RESULT_USD, 
        CAST(SUM(IF(YEAR(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd'))=YEAR(TO_TIMESTAMP('${var:periodo}', 'yyyyMMdd')), A.PL_RPT/c.EXCH_RATE, 0)) AS DECIMAL(30,10)) AS PL_YTD_REG, 
        CAST(SUM(IF(YEAR(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd'))=YEAR(TO_TIMESTAMP('${var:periodo}', 'yyyyMMdd')), (A.PL_RPT/c.EXCH_RATE), 0))
        - SUM(IF(YEAR(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd'))=YEAR(TO_TIMESTAMP('${var:periodo}', 'yyyyMMdd')) AND 
             MONTH(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd'))=MONTH(ADD_MONTHS(TO_TIMESTAMP('${var:periodo}', 'yyyyMMdd'),-1)), A.PL_YTD_REG, 0)) AS DECIMAL(30,10)) AS PL_REG, 
        CAST(SUM(IF(YEAR(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd'))=YEAR(TO_TIMESTAMP('${var:periodo}', 'yyyyMMdd')), A.PL_TOT_RPT/c.EXCH_RATE, 0)) AS DECIMAL(30,10)) AS PL_TOT_YTD_REG, 
        CAST(SUM(IF(YEAR(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd'))=YEAR(TO_TIMESTAMP('${var:periodo}', 'yyyyMMdd')), (A.PL_TOT_RPT/c.EXCH_RATE), 0))
        - SUM(IF(YEAR(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd'))=YEAR(TO_TIMESTAMP('${var:periodo}', 'yyyyMMdd')) AND 
             MONTH(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd'))=MONTH(ADD_MONTHS(TO_TIMESTAMP('${var:periodo}', 'yyyyMMdd'),-1)), A.PL_TOT_YTD_REG, 0)) AS DECIMAL(30,10)) AS PL_TOT_REG, 
        CAST(SUM(IF(YEAR(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd'))=YEAR(TO_TIMESTAMP('${var:periodo}', 'yyyyMMdd')), A.FTP_RESULT_RPT/c.EXCH_RATE, 0)) AS DECIMAL(30,10)) AS FTP_RESULT_YTD_REG, 
        CAST(SUM(IF(YEAR(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd'))=YEAR(TO_TIMESTAMP('${var:periodo}', 'yyyyMMdd')), (A.FTP_RESULT_RPT/c.EXCH_RATE), 0))
        - SUM(IF(YEAR(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd'))=YEAR(TO_TIMESTAMP('${var:periodo}', 'yyyyMMdd')) AND 
             MONTH(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd'))=MONTH(ADD_MONTHS(TO_TIMESTAMP('${var:periodo}', 'yyyyMMdd'),-1)), A.FTP_RESULT_YTD_REG, 0)) AS DECIMAL(30,10)) AS FTP_RESULT_REG, 
             
        SUM(IF(YEAR(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd'))=YEAR(TO_TIMESTAMP('${var:periodo}', 'yyyyMMdd')) AND MONTH(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd')) IN (1, 2, 3), A.PL_TOT_RPT, 0)) AS PL_TOT_USD_TRI_1,
        SUM(IF(YEAR(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd'))=YEAR(TO_TIMESTAMP('${var:periodo}', 'yyyyMMdd')) AND MONTH(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd')) IN (4, 5, 6), A.PL_TOT_RPT, 0)) AS PL_TOT_USD_TRI_2,
        SUM(IF(YEAR(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd'))=YEAR(TO_TIMESTAMP('${var:periodo}', 'yyyyMMdd')) AND MONTH(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd')) IN (7, 8, 9), A.PL_TOT_RPT, 0)) AS PL_TOT_USD_TRI_3,
        SUM(IF(YEAR(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd'))=YEAR(TO_TIMESTAMP('${var:periodo}', 'yyyyMMdd')) AND MONTH(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd')) IN (10, 11, 12), A.PL_TOT_RPT, 0)) AS PL_TOT_USD_TRI_4,
        SUM(IF(YEAR(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd'))=YEAR(TO_TIMESTAMP('${var:periodo}', 'yyyyMMdd')) AND MONTH(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd')) IN (1, 2, 3, 4, 5, 6), A.PL_TOT_RPT, 0)) AS PL_TOT_USD_SEM_1,
        SUM(IF(YEAR(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd'))=YEAR(TO_TIMESTAMP('${var:periodo}', 'yyyyMMdd')) AND MONTH(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd')) IN (7, 8, 9, 10, 11, 12), A.PL_TOT_RPT, 0)) AS PL_TOT_USD_SEM_2,
        SUM(IF(YEAR(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd'))=YEAR(TO_TIMESTAMP('${var:periodo}', 'yyyyMMdd')) AND MONTH(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd')) IN (1, 2, 3), A.PL_TOT_RPT, 0)) AS PL_TOT_REG_TRI_1,
        SUM(IF(YEAR(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd'))=YEAR(TO_TIMESTAMP('${var:periodo}', 'yyyyMMdd')) AND MONTH(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd')) IN (4, 5, 6), A.PL_TOT_RPT, 0)) AS PL_TOT_REG_TRI_2,
        SUM(IF(YEAR(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd'))=YEAR(TO_TIMESTAMP('${var:periodo}', 'yyyyMMdd')) AND MONTH(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd')) IN (7, 8, 9), A.PL_TOT_RPT, 0)) AS PL_TOT_REG_TRI_3,
        SUM(IF(YEAR(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd'))=YEAR(TO_TIMESTAMP('${var:periodo}', 'yyyyMMdd')) AND MONTH(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd')) IN (10, 11, 12), A.PL_TOT_RPT, 0)) AS PL_TOT_REG_TRI_4,
        SUM(IF(YEAR(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd'))=YEAR(TO_TIMESTAMP('${var:periodo}', 'yyyyMMdd')) AND MONTH(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd')) IN (1, 2, 3, 4, 5, 6), A.PL_TOT_RPT, 0)) AS PL_TOT_REG_SEM_1,
        SUM(IF(YEAR(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd'))=YEAR(TO_TIMESTAMP('${var:periodo}', 'yyyyMMdd')) AND MONTH(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd')) IN (7, 8, 9, 10, 11, 12), A.PL_TOT_RPT, 0)) AS PL_TOT_REG_SEM_2,
       A.COD_SECTOR_LOCAL, A.DES_SECTOR_LOCAL, A.COD_SECTOR_REG, A.DES_SECTOR_REG, A.COD_OFFI, A.DES_OFFI,
        0 AS EOPBAL_TOT_USD,
        0 AS EOPBAL_TOT_REG,
        0 AS AVGBAL_TOT_USD,
        0 AS AVGBAL_TOT_REG,
        A.COD_INFO_SOURCE, A.EXP_FAMILY, A.EXP_TYPE, A.COD_VALUE, A.COD_SECTOR, A.DES_PRODUCT, A.DES_SUBPRODUCT, '${var:periodo}' AS DATA_DATE
    FROM MIS_DM_ACCUMULATED AS A
    LEFT JOIN MIS_PAR_EXCH_RATE b   
    ON b.DATA_DATE = '${var:periodo}' AND b.COD_CONT = 'TC_FOTO' AND b.COD_CURRENCY = 'USD' AND A.cod_entity = b.cod_entity
    LEFT JOIN MIS_PAR_EXCH_RATE c   
    ON c.DATA_DATE = '${var:periodo}' /*AND c.COD_CONT = 'TC_PROMEDIO'*/ AND c.COD_CURRENCY = 'USD' AND A.cod_entity = c.cod_entity
    WHERE TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd') BETWEEN ADD_MONTHS(TO_TIMESTAMP('${var:periodo}', 'yyyyMMdd'),-11) AND TO_TIMESTAMP('${var:periodo}', 'yyyyMMdd') AND YEAR(TO_TIMESTAMP(A.DATA_DATE, 'yyyyMMdd'))=YEAR(TO_TIMESTAMP('${var:periodo}', 'yyyyMMdd'))
    GROUP BY A.COD_CONT, A.COD_ACCO_CENT, A.COD_BLCE_STATUS, A.COD_CURRENCY, A.COD_ENTITY, A.COD_PRODUCT, A.COD_SUBPRODUCT, 
    A.COD_SEGMENT, A.DES_SEGMENT, A.COD_MANAGER, A.COD_GL_GROUP, A.COD_PL_ACC, A.COD_BLCE_PROD, A.COD_BUSINESS_LINE, A.IND_POOL,
A.COD_SECTOR_LOCAL, A.DES_SECTOR_LOCAL, A.COD_SECTOR_REG, A.DES_SECTOR_REG, A.COD_OFFI, A.DES_OFFI, A.COD_INFO_SOURCE, A.EXP_FAMILY, A.EXP_TYPE, A.COD_VALUE, A.COD_SECTOR, A.DES_PRODUCT, A.DES_SUBPRODUCT
) X 
GROUP BY X.COD_CONT, X.COD_ACCO_CENT, X.COD_BLCE_STATUS, X.COD_CURRENCY, X.COD_ENTITY, X.COD_PRODUCT, X.COD_SUBPRODUCT, 
X.COD_SEGMENT, X.DES_SEGMENT, X.COD_MANAGER, X.COD_GL_GROUP, X.COD_PL_ACC, X.COD_BLCE_PROD, X.COD_BUSINESS_LINE, X.IND_POOL,
X.COD_SECTOR_LOCAL, X.DES_SECTOR_LOCAL, X.COD_SECTOR_REG, X.DES_SECTOR_REG, X.COD_OFFI, X.DES_OFFI, X.COD_INFO_SOURCE, X.EXP_FAMILY, X.EXP_TYPE, X.COD_VALUE, X.COD_SECTOR, X.DES_PRODUCT, X.DES_SUBPRODUCT, X.DATA_DATE
;