--------------------------------------------------------------- SEGMENTO ----------------------------------------------------------
USE ${var:base_datos};
SET DECIMAL_V2=FALSE;

--Limpieza de partición del día en ejecución
ALTER TABLE MIS_LOAD_BANCA_EMPRESAS
DROP IF EXISTS PARTITION (DATA_DATE = '${var:periodo}');

ALTER TABLE MIS_LOAD_BANCA_PERSONAS
DROP IF EXISTS PARTITION (DATA_DATE = '${var:periodo}');

ALTER TABLE MIS_LOAD_BANCA_EMPRESAS
ADD IF NOT EXISTS PARTITION (DATA_DATE = '${var:periodo}');

ALTER TABLE MIS_LOAD_BANCA_PERSONAS
ADD IF NOT EXISTS PARTITION (DATA_DATE = '${var:periodo}');

----Carga de tablas load
LOAD DATA INPATH '${var:ruta_fuentes_activos}/SEGMENTO_BANCA_EMPRESAS.csv' INTO TABLE MIS_LOAD_BANCA_EMPRESAS PARTITION (DATA_DATE = '${var:periodo}');

LOAD DATA INPATH '${var:ruta_fuentes_activos}/MIS_SEGMENTO_BANCA_PERSONAS.csv' INTO TABLE MIS_LOAD_BANCA_PERSONAS PARTITION (DATA_DATE = '${var:periodo}');


----Aprovisionamiento de Provisiones Capital
TRUNCATE TABLE IF EXISTS MIS_APR_CLIENT_DT_TMP;
DROP TABLE IF EXISTS MIS_APR_CLIENT_DT_TMP;
CREATE TABLE MIS_APR_CLIENT_DT_TMP AS
SELECT IDF_CLI, TYP_DOC_ID, NUM_DOC_ID, NOM_NAME, NOM_LASTN, COD_RES_COUNT, COD_TYP_CLNT, COD_COND_CLNT, COD_ENG, VAL_SEX, COD_COUNTRY, COD_SECTOR, DES_SECTOR, ISNULL(ISNULL(b.UNIDAD,c.SEGMENTO),a.COD_SEGMENT) AS COD_SEGMENT, DES_SEGMENT, COD_SUBSEGMENT, COD_SUBSEGMENT, IND_EMPL_GRUP, DATE_CLNT_REG, DATE_CLNT_WITHDRAW, COD_MANAGER, DES_MANAGER, RATING_CLI, COD_GROUP_EC, ID_ECO_GRO, COU_ECO_GRO, IND_MUL_LAT, DATA_DATE
FROM MIS_APR_CLIENT_DT a
LEFT JOIN MIS_LOAD_BANCA_EMPRESAS b
ON a.IDF_CLI = b.CIF
LEFT JOIN MIS_LOAD_BANCA_PERSONAS c
ON a.IDF_CLI = c.CUNBR
WHERE a.DATA_DATE = '${var:periodo}'
;


INSERT INTO MIS_APR_CLIENT_DT
PARTITION (DATA_DATE='${var:periodo}')
SELECT SELECT IDF_CLI, TYP_DOC_ID, NUM_DOC_ID, NOM_NAME, NOM_LASTN, COD_RES_COUNT, COD_TYP_CLNT, COD_COND_CLNT, COD_ENG, VAL_SEX, COD_COUNTRY, COD_SECTOR, DES_SECTOR, COD_SEGMENT, DES_SEGMENT, COD_SUBSEGMENT, COD_SUBSEGMENT, IND_EMPL_GRUP, DATE_CLNT_REG, DATE_CLNT_WITHDRAW, COD_MANAGER, DES_MANAGER, RATING_CLI, COD_GROUP_EC, ID_ECO_GRO, COU_ECO_GRO, IND_MUL_LAT
FROM MIS_APR_CLIENT_DT_TMP
WHERE DATA_DATE = '${var:periodo}'
;