--------------------------------------------------------------- Motor de Saldos Medios y Arrastre de Muertos --------------------------------

--- Comando que apunta a la base de datos apropiada ---
USE ${var:base_datos};
SET DECIMAL_V2=FALSE;

--COMPUTE STATS MIS_TBL_AVGBAL;

------------ Cálculo de Saldos Medios ------------

TRUNCATE TABLE MIS_LOAD_AVGBAL_ASSETS_M;

INSERT INTO MIS_LOAD_AVGBAL_ASSETS_M  
	SELECT IDF_CTO, COD_BLCE_STATUS, COD_VALUE, COD_INFO_SOURCE, 
	CAST(SUM((CASE WHEN DATEDIFF(to_timestamp('${var:periodo}','yyyyMMdd'),TRUNC(to_timestamp('${var:periodo}','yyyyMMdd'),'MM'))+1 = 28 THEN ISNULL(EOPBAL_CAP_1, 0)+ISNULL(EOPBAL_CAP_2, 0)+ISNULL(EOPBAL_CAP_3, 0)+ISNULL(EOPBAL_CAP_4, 0)+ISNULL(EOPBAL_CAP_5, 0)+ISNULL(EOPBAL_CAP_6, 0)+ISNULL(EOPBAL_CAP_7, 0)+ISNULL(EOPBAL_CAP_8, 0)+ISNULL(EOPBAL_CAP_9, 0)+ISNULL(EOPBAL_CAP_10, 0)+ISNULL(EOPBAL_CAP_11, 0)+ISNULL(EOPBAL_CAP_12, 0)+ISNULL(EOPBAL_CAP_13, 0)+ISNULL(EOPBAL_CAP_14, 0)+ISNULL(EOPBAL_CAP_15, 0)+ISNULL(EOPBAL_CAP_16, 0)+ISNULL(EOPBAL_CAP_17, 0)+ISNULL(EOPBAL_CAP_18, 0)+ISNULL(EOPBAL_CAP_19, 0)+ISNULL(EOPBAL_CAP_20, 0)+ISNULL(EOPBAL_CAP_21, 0)+ISNULL(EOPBAL_CAP_22, 0)+ISNULL(EOPBAL_CAP_23, 0)+ISNULL(EOPBAL_CAP_24, 0)+ISNULL(EOPBAL_CAP_25, 0)+ISNULL(EOPBAL_CAP_26, 0)+ISNULL(EOPBAL_CAP_27, 0)+ISNULL(EOPBAL_CAP_28, 0)
		WHEN DATEDIFF(to_timestamp('${var:periodo}','yyyyMMdd'),TRUNC(to_timestamp('${var:periodo}','yyyyMMdd'),'MM'))+1 = 29 THEN ISNULL(EOPBAL_CAP_1, 0)+ISNULL(EOPBAL_CAP_2, 0)+ISNULL(EOPBAL_CAP_3, 0)+ISNULL(EOPBAL_CAP_4, 0)+ISNULL(EOPBAL_CAP_5, 0)+ISNULL(EOPBAL_CAP_6, 0)+ISNULL(EOPBAL_CAP_7, 0)+ISNULL(EOPBAL_CAP_8, 0)+ISNULL(EOPBAL_CAP_9, 0)+ISNULL(EOPBAL_CAP_10, 0)+ISNULL(EOPBAL_CAP_11, 0)+ISNULL(EOPBAL_CAP_12, 0)+ISNULL(EOPBAL_CAP_13, 0)+ISNULL(EOPBAL_CAP_14, 0)+ISNULL(EOPBAL_CAP_15, 0)+ISNULL(EOPBAL_CAP_16, 0)+ISNULL(EOPBAL_CAP_17, 0)+ISNULL(EOPBAL_CAP_18, 0)+ISNULL(EOPBAL_CAP_19, 0)+ISNULL(EOPBAL_CAP_20, 0)+ISNULL(EOPBAL_CAP_21, 0)+ISNULL(EOPBAL_CAP_22, 0)+ISNULL(EOPBAL_CAP_23, 0)+ISNULL(EOPBAL_CAP_24, 0)+ISNULL(EOPBAL_CAP_25, 0)+ISNULL(EOPBAL_CAP_26, 0)+ISNULL(EOPBAL_CAP_27, 0)+ISNULL(EOPBAL_CAP_28, 0)+ISNULL(EOPBAL_CAP_29, 0)
		WHEN DATEDIFF(to_timestamp('${var:periodo}','yyyyMMdd'),TRUNC(to_timestamp('${var:periodo}','yyyyMMdd'),'MM'))+1 = 30 THEN ISNULL(EOPBAL_CAP_1, 0)+ISNULL(EOPBAL_CAP_2, 0)+ISNULL(EOPBAL_CAP_3, 0)+ISNULL(EOPBAL_CAP_4, 0)+ISNULL(EOPBAL_CAP_5, 0)+ISNULL(EOPBAL_CAP_6, 0)+ISNULL(EOPBAL_CAP_7, 0)+ISNULL(EOPBAL_CAP_8, 0)+ISNULL(EOPBAL_CAP_9, 0)+ISNULL(EOPBAL_CAP_10, 0)+ISNULL(EOPBAL_CAP_11, 0)+ISNULL(EOPBAL_CAP_12, 0)+ISNULL(EOPBAL_CAP_13, 0)+ISNULL(EOPBAL_CAP_14, 0)+ISNULL(EOPBAL_CAP_15, 0)+ISNULL(EOPBAL_CAP_16, 0)+ISNULL(EOPBAL_CAP_17, 0)+ISNULL(EOPBAL_CAP_18, 0)+ISNULL(EOPBAL_CAP_19, 0)+ISNULL(EOPBAL_CAP_20, 0)+ISNULL(EOPBAL_CAP_21, 0)+ISNULL(EOPBAL_CAP_22, 0)+ISNULL(EOPBAL_CAP_23, 0)+ISNULL(EOPBAL_CAP_24, 0)+ISNULL(EOPBAL_CAP_25, 0)+ISNULL(EOPBAL_CAP_26, 0)+ISNULL(EOPBAL_CAP_27, 0)+ISNULL(EOPBAL_CAP_28, 0)+ISNULL(EOPBAL_CAP_29, 0)+ISNULL(EOPBAL_CAP_30, 0)
		ELSE ISNULL(EOPBAL_CAP_1, 0)+ISNULL(EOPBAL_CAP_2, 0)+ISNULL(EOPBAL_CAP_3, 0)+ISNULL(EOPBAL_CAP_4, 0)+ISNULL(EOPBAL_CAP_5, 0)+ISNULL(EOPBAL_CAP_6, 0)+ISNULL(EOPBAL_CAP_7, 0)+ISNULL(EOPBAL_CAP_8, 0)+ISNULL(EOPBAL_CAP_9, 0)+ISNULL(EOPBAL_CAP_10, 0)+ISNULL(EOPBAL_CAP_11, 0)+ISNULL(EOPBAL_CAP_12, 0)+ISNULL(EOPBAL_CAP_13, 0)+ISNULL(EOPBAL_CAP_14, 0)+ISNULL(EOPBAL_CAP_15, 0)+ISNULL(EOPBAL_CAP_16, 0)+ISNULL(EOPBAL_CAP_17, 0)+ISNULL(EOPBAL_CAP_18, 0)+ISNULL(EOPBAL_CAP_19, 0)+ISNULL(EOPBAL_CAP_20, 0)+ISNULL(EOPBAL_CAP_21, 0)+ISNULL(EOPBAL_CAP_22, 0)+ISNULL(EOPBAL_CAP_23, 0)+ISNULL(EOPBAL_CAP_24, 0)+ISNULL(EOPBAL_CAP_25, 0)+ISNULL(EOPBAL_CAP_26, 0)+ISNULL(EOPBAL_CAP_27, 0)+ISNULL(EOPBAL_CAP_28, 0)+ISNULL(EOPBAL_CAP_29, 0)+ISNULL(EOPBAL_CAP_30, 0)+ISNULL(EOPBAL_CAP_31, 0)
		END)/(DATEDIFF(to_timestamp('${var:periodo}','yyyyMMdd'),TRUNC(to_timestamp('${var:periodo}','yyyyMMdd'),'MM'))+1)
	 ) AS DECIMAL(30,10)) AS AVGBAL_CAP, CAST(0 AS DECIMAL(30,10)) AS AVGBAL_INT,
	COD_CONT
	FROM MIS_TBL_AVGBAL
	WHERE DATA_DATE = SUBSTR('${var:periodo}', 1, 6)
	GROUP BY IDF_CTO, COD_BLCE_STATUS, COD_VALUE, COD_INFO_SOURCE, COD_CONT;