--------------------------------------------------------------- MIS_LIABILITIES -----------------------------------------------------------

USE ${var:base_datos};
SET DECIMAL_V2=FALSE;

----Carga de tablas load
TRUNCATE TABLE IF EXISTS MIS_LOAD_TMP003; 
LOAD DATA INPATH '${var:ruta_fuentes_pasivos}/TMP003.csv' INTO TABLE MIS_LOAD_TMP003;

TRUNCATE TABLE IF EXISTS MIS_LOAD_TAP00201; 
LOAD DATA INPATH '${var:ruta_fuentes_pasivos}/TAP00201.csv' INTO TABLE MIS_LOAD_TAP00201;

--TRUNCATE TABLE IF EXISTS MIS_LOAD_CFP31001; 
--LOAD DATA INPATH '${var:ruta_fuentes_pasivos}/CFP31001.csv' INTO TABLE MIS_LOAD_CFP31001;

--TRUNCATE TABLE IF EXISTS MIS_LOAD_CFP21001; 
--LOAD DATA INPATH '${var:ruta_fuentes_pasivos}/CFP21001.csv' INTO TABLE MIS_LOAD_CFP21001;

--- Eliminación de Información Previa ---

--COMPUTE STATS MIS_APR_LIABILITIES;
--COMPUTE STATS MIS_APR_CONTRACT_DT;

ALTER TABLE MIS_APR_LIABILITIES
DROP IF EXISTS PARTITION (DATA_DATE = '${var:periodo}');


-------------------------------------------- PLAZO --------------------------------------------

----Aprovisionamiento de Pasivos Capital
INSERT INTO MIS_APR_LIABILITIES 
PARTITION (DATA_DATE='${var:periodo}') 
SELECT 'PLZ' AS COD_CONT, CAST(a.TMACCT AS string) AS IDF_CTO, NULL AS COD_GL, NULL AS DES_GL, CAST(TMBRCH AS STRING) AS COD_ACCO_CENT, 
CAST(TMBRCH AS STRING) AS COD_OFFI, 'VIG' AS COD_BLCE_STATUS, 'CAP' AS COD_VALUE, CASE WHEN CAST(TMCMCN AS STRING) IN ('0','00') THEN 'HNL' WHEN CAST(TMCMCN AS STRING) IN ('1','2') THEN 'USD' WHEN CAST(TMCMCN AS STRING) IN ('3','4') THEN 'EUR' ELSE 'HNL' END AS COD_CURRENCY, CAST(a.TMBK AS STRING) AS COD_ENTITY,
CASE WHEN b.IDF_CTO IS NOT NULL THEN b.COD_PRODUCT ELSE CONCAT(TRIM(CAST(TMTYPE AS STRING)),'_TMP') END AS COD_PRODUCT,  
TRIM(CAST(TMTYPE AS STRING)) AS COD_SUBPRODUCT, IFNULL(NULL, '') AS COD_ACT_TYPE, CASE WHEN CAST(TMCMCN AS STRING) = '0' THEN CAST((a.TMCBAL * (-1)) as DECIMAL(30,10)) ELSE CAST((a.TMLCYB * (-1)) as DECIMAL(30,10)) END AS EOPBAL_CAP, 
NULL AS EOPBAL_INT, 0 AS AVGBAL_CAP, NULL AS AVGBAL_INT, NULL AS PL, 'TMP' AS COD_INFO_SOURCE 
FROM MIS_LOAD_TMP003 a
LEFT JOIN MIS_PAR_REL_PROD_SPE b 
ON CAST(a.TMACCT AS string) = B.IDF_CTO 
WHERE TMSTAT NOT IN ('4')
;

DROP TABLE IF EXISTS MIS_TMP_GLC002;
CREATE TABLE MIS_TMP_GLC002 AS
select *, from_timestamp(DATE_ADD(TO_TIMESTAMP(concat(strleft(GBEFDT,4),'0101'), 'yyyyMMdd'),CAST(strright(GBEFDT,3) AS INT) - 1), 'yyyyMMdd') as DATA_DATE from MIS_LOAD_GLC002
where from_timestamp(DATE_ADD(TO_TIMESTAMP(concat(strleft(GBEFDT,4),'0101'), 'yyyyMMdd'),CAST(strright(GBEFDT,3) AS INT) - 1), 'yyyyMMdd') <= '${var:periodo}'
order by GBEFDT desc
limit 20;

----Aprovisionamiento de Pasivos Intereses
INSERT INTO MIS_APR_LIABILITIES 
PARTITION (DATA_DATE='${var:periodo}') 
SELECT 'PLZ' AS COD_CONT, CAST(a.TMACCT AS string) AS IDF_CTO, NULL AS COD_GL, NULL AS DES_GL, CAST(TMBRCH AS STRING) AS COD_ACCO_CENT, 
CAST(TMBRCH AS STRING) AS COD_OFFI, 'VIG' AS COD_BLCE_STATUS, 'INT' AS COD_VALUE, CASE WHEN CAST(TMCMCN AS STRING) IN ('0','00') THEN 'HNL' WHEN CAST(TMCMCN AS STRING) IN ('1','2') THEN 'USD' WHEN CAST(TMCMCN AS STRING) IN ('3','4') THEN 'EUR' ELSE 'HNL' END AS COD_CURRENCY, CAST(a.TMBK AS STRING) AS COD_ENTITY,
CASE WHEN b.IDF_CTO IS NOT NULL THEN b.COD_PRODUCT ELSE CONCAT(TRIM(CAST(TMTYPE AS STRING)),'_TMP') END AS COD_PRODUCT,  
TRIM(CAST(TMTYPE AS STRING)) AS COD_SUBPRODUCT, IFNULL(NULL, '') AS COD_ACT_TYPE, CASE WHEN CAST(TMCMCN AS STRING) = '0' THEN CAST((TMTACC-TMTIPD) * -1 as DECIMAL(30,10)) ELSE CAST(((TMTACC-TMTIPD) * -1)  * GBBKXR as DECIMAL(30,10)) END AS EOPBAL_CAP, 0 AS EOPBAL_INT, NULL AS AVGBAL_CAP, NULL AS AVGBAL_INT, NULL AS PL, 'TMP' AS COD_INFO_SOURCE
FROM MIS_LOAD_TMP003 a
LEFT JOIN MIS_PAR_REL_PROD_SPE b 
ON CAST(a.TMACCT AS string) = B.IDF_CTO 
LEFT JOIN (select * FROM mis_tmp_glc002 where data_date in (SELECT MAX(DATA_DATE) FROM mis_tmp_glc002)) c
ON CAST(TMCMCN AS STRING) = GBCODE
WHERE TMSTAT NOT IN ('4')
;


----Aprovisionamiento de Pasivos Resultados
INSERT INTO MIS_APR_LIABILITIES 
PARTITION (DATA_DATE='${var:periodo}') 
SELECT 'PLZ' AS COD_CONT, CAST(a.TMACCT AS string) AS IDF_CTO, NULL AS COD_GL, NULL AS DES_GL, CAST(TMBRCH AS STRING) AS COD_ACCO_CENT, 
CAST(TMBRCH AS STRING) AS COD_OFFI, 'VIG' AS COD_BLCE_STATUS, 'RSL' AS COD_VALUE, CASE WHEN CAST(TMCMCN AS STRING) IN ('0','00') THEN 'HNL' WHEN CAST(TMCMCN AS STRING) IN ('1','2') THEN 'USD' WHEN CAST(TMCMCN AS STRING) IN ('3','4') THEN 'EUR' ELSE 'HNL' END AS COD_CURRENCY, CAST(a.TMBK AS STRING) AS COD_ENTITY,
CASE WHEN b.IDF_CTO IS NOT NULL THEN b.COD_PRODUCT ELSE CONCAT(TRIM(CAST(TMTYPE AS STRING)),'_TMP') END AS COD_PRODUCT,  
TRIM(CAST(TMTYPE AS STRING)) AS COD_SUBPRODUCT, IFNULL(NULL, '') AS COD_ACT_TYPE, 0 AS EOPBAL_CAP,
0 AS EOPBAL_INT, NULL AS AVGBAL_CAP, NULL AS AVGBAL_INT, CAST(TMMACC AS DECIMAL(30,10)) AS PL, 'TMP' AS COD_INFO_SOURCE
FROM MIS_LOAD_TMP003 a
LEFT JOIN MIS_PAR_REL_PROD_SPE b 
ON CAST(a.TMACCT AS string) = B.IDF_CTO 
--LEFT JOIN (select * FROM mis_tmp_glc002 where data_date in (SELECT MAX(DATA_DATE) FROM mis_tmp_glc002)) c
--ON CAST(TMCMCN AS STRING) = GBCODE
WHERE TMSTAT NOT IN ('4')
;

-------------------------------------------- CUENTAS --------------------------------------------

----Aprovisionamiento de Pasivos Capital
INSERT INTO MIS_APR_LIABILITIES
PARTITION (DATA_DATE='${var:periodo}')
SELECT 'CTA' AS COD_CONT, TRIM(CAST(CONCAT(a.DMACCT, a.DMTYP) AS STRING)) AS IDF_CTO, NULL AS COD_GL, NULL AS DES_GL, TRIM(CAST(a.DMBRCH AS STRING)) AS COD_ACCO_CENT, DMBRCH AS COD_OFFI, 'VIG' AS COD_BLCE_STATUS, 'CAP' AS COD_VALUE, CASE WHEN CAST(DMCMCN AS STRING) = '0' THEN 'HNL' WHEN CAST(DMCMCN AS STRING) IN ('1','2') THEN 'USD' WHEN CAST(DMCMCN AS STRING) IN ('3','4') THEN 'EUR' ELSE 'HNL' END AS COD_CURRENCY, TRIM(CAST(a.DMBK AS STRING)) AS COD_ENTITY, 
CONCAT(TRIM(CAST(DMTYP AS STRING)),'_TAP') AS COD_PRODUCT, TRIM(CAST(a.DMTYPE AS STRING)) AS COD_SUBPRODUCT, IFNULL(NULL, '') AS COD_ACT_TYPE,
    CAST((a.DMLCYB * -1) AS decimal(30, 10)) AS EOPBAL_CAP, NULL AS EOPBAL_INT, 
    NULL AS AVGBAL_CAP, NULL AS AVGBAL_INT, NULL AS PL, 'TAP' AS COD_INFO_SOURCE
FROM MIS_LOAD_TAP00201 a
WHERE a.DMLCYB >= 0 and TRIM(DMACCT) <> ''
;

----Aprovisionamiento de Pasivos Intereses
INSERT INTO MIS_APR_LIABILITIES
PARTITION (DATA_DATE='${var:periodo}')
SELECT 'CTA' AS COD_CONT, TRIM(CAST(CONCAT(a.DMACCT, a.DMTYP) AS STRING)) AS IDF_CTO, NULL AS COD_GL, NULL AS DES_GL, TRIM(CAST(a.DMBRCH AS STRING)) AS COD_ACCO_CENT, DMBRCH AS COD_OFFI, 'VIG' AS COD_BLCE_STATUS, 'INT' AS COD_VALUE, CASE WHEN CAST(DMCMCN AS STRING) = '0' THEN 'HNL' WHEN CAST(DMCMCN AS STRING) IN ('1','2') THEN 'USD' WHEN CAST(DMCMCN AS STRING) IN ('3','4') THEN 'EUR' ELSE 'HNL' END AS COD_CURRENCY, TRIM(CAST(a.DMBK AS STRING)) AS COD_ENTITY, 
CONCAT(TRIM(CAST(DMTYP AS STRING)),'_TAP') AS COD_PRODUCT, TRIM(CAST(a.DMTYPE AS STRING)) AS COD_SUBPRODUCT, IFNULL(NULL, '') AS COD_ACT_TYPE, CASE WHEN CAST(DMCMCN AS STRING) = '0' THEN CAST((a.DMPACC * -1) AS decimal(30, 10)) ELSE CAST((a.DMPACC * -1) * GBBKXR AS decimal(30, 10)) END AS EOPBAL_CAP,NULL AS EOPBAL_INT, NULL AS AVGBAL_CAP, NULL AS AVGBAL_INT, NULL AS PL, 'TAP' AS COD_INFO_SOURCE
FROM MIS_LOAD_TAP00201 a
LEFT JOIN (select * FROM mis_tmp_glc002 where data_date in (SELECT MAX(DATA_DATE) FROM mis_tmp_glc002)) b
ON CAST(DMCMCN AS STRING) = GBCODE
WHERE TRIM(DMACCT) <> ''
;

----Aprovisionamiento de Pasivos Resultados
INSERT INTO MIS_APR_LIABILITIES
PARTITION (DATA_DATE='${var:periodo}')
SELECT 'CTA' AS COD_CONT, TRIM(CAST(CONCAT(a.DMACCT, a.DMTYP) AS STRING)) AS IDF_CTO, NULL AS COD_GL, NULL AS DES_GL, TRIM(CAST(a.DMBRCH AS STRING)) AS COD_ACCO_CENT, DMBRCH AS COD_OFFI, 'VIG' AS COD_BLCE_STATUS, 'RSL' AS COD_VALUE, CASE WHEN CAST(DMCMCN AS STRING) = '0' THEN 'HNL' WHEN CAST(DMCMCN AS STRING) IN ('1','2') THEN 'USD' WHEN CAST(DMCMCN AS STRING) IN ('3','4') THEN 'EUR' ELSE 'HNL' END AS COD_CURRENCY, TRIM(CAST(a.DMBK AS STRING)) AS COD_ENTITY, 
CONCAT(TRIM(CAST(DMTYP AS STRING)),'_TAP') AS COD_PRODUCT, TRIM(CAST(a.DMTYPE AS STRING)) AS COD_SUBPRODUCT, IFNULL(NULL, '') AS COD_ACT_TYPE, NULL AS EOPBAL_CAP, NULL AS EOPBAL_INT, NULL AS AVGBAL_CAP, NULL AS AVGBAL_INT, CAST(a.DMMACC AS decimal(30, 10)) AS PL, 'TAP' AS COD_INFO_SOURCE
FROM MIS_LOAD_TAP00201 a 
--LEFT JOIN (select * FROM mis_tmp_glc002 where data_date in (SELECT MAX(DATA_DATE) FROM mis_tmp_glc002)) b
--ON CAST(DMCMCN AS STRING) = GBCODE
WHERE TRIM(DMACCT) <> ''
;

--COMPUTE STATS MIS_LOAD_CUP00901;

DROP TABLE IF EXISTS MIS_TMP_CUP00901;
CREATE TABLE MIS_TMP_CUP00901 AS
select cux1ac, max(cux1ap) as cux1ap, max(cux1cs) as cux1cs, max(cux1ty) as cux1ty, max(cuxbk) as cuxbk, max(cuxrec) as cuxrec, max(cuxrel) as cuxrel, fecha_control  
from mis_load_cup00901 group by cux1ac, fecha_control;

ALTER TABLE MIS_APR_CONTRACT_DT
DROP IF EXISTS PARTITION (DATA_DATE = '${var:periodo}', COD_INFO_SOURCE='TAP');

----Aprovisionamiento de Contratos asociados a cuentas
INSERT INTO MIS_APR_CONTRACT_DT 
PARTITION (DATA_DATE='${var:periodo}', COD_INFO_SOURCE='TAP') 
SELECT DISTINCT
 TRIM(CAST(CONCAT(a.DMACCT, a.DMTYP) AS STRING)) AS IDF_CTO, a.DMBK AS COD_ENTITY, CONCAT(TRIM(CAST(a.DMTYP AS STRING)),'_TAP') AS COD_PRODUCT, a.DMTYPE AS COD_SUBPRODUCT, IFNULL(NULL, '') AS COD_ACT_TYPE, CASE WHEN CAST(DMCMCN AS STRING) = '0' THEN 'HNL' WHEN CAST(DMCMCN AS STRING) IN ('1','2') THEN 'USD' WHEN CAST(DMCMCN AS STRING) IN ('3','4') THEN 'EUR' ELSE 'HNL' END AS COD_CURRENCY, isnull(isnull(isnull(isnull(TRIM(CAST(cl.CUX1CS AS STRING)),cl2.CUX1CS),cl3.CUX1CS),cl4.CUX1CS),'99999999') AS IDF_CLI, a.DMBRCH AS COD_ACCO_CENT, DMBRCH AS COD_OFFI, '360' AS COD_BCA_INT, NULL AS COD_AMRT_MET, 'A' AS COD_RATE_TYPE, CAST(a.DMINTR AS decimal(30, 10)) AS RATE_INT,
case when length(CAST(DMDOPN AS STRING)) = 6 then 
case when strright(DMDOPN,2) > substr('${var:periodo}',3,2) then 
concat('19',strright(DMDOPN,2),substr(DMDOPN,3,2), strleft(DMDOPN,2))
else concat('20',strright(DMDOPN,2),substr(DMDOPN,3,2), strleft(DMDOPN,2))
end
else 
case when strright(DMDOPN,2) > substr('${var:periodo}',3,2) then 
concat('19',strright(DMDOPN,2),substr(DMDOPN,2,2), lpad(strleft(DMDOPN,1),2,'0'))
else concat('20',strright(DMDOPN,2),substr(DMDOPN,2,2), lpad(strleft(DMDOPN,1),2,'0'))
end end AS DATE_ORIGIN, NULL AS DATE_LAST_REV, NULL AS DATE_PRX_REV, NULL AS EXP_DATE, 
    CAST(DMINFR AS BIGINT) AS FREQ_INT_PAY, DMINFR AS COD_UNI_FREQ_INT_PAY, NULL AS FRE_REV_INT, NULL AS COD_UNI_FRE_REV_INT, 
    NULL AS AMRT_TRM, NULL AS COD_UNI_AMRT_TRM, NULL AS INI_AM, NULL AS CUO_AM, NULL AS CREDIT_LIM_AM, 
    NULL AS PREDEF_RATE_IND, NULL AS PREDEF_RATE, NULL AS IND_CHANNEL, NULL AS COD_TYP_LIC, NULL AS COD_SELLER, NULL AS DES_SELLER, NULL AS COU_CAR_OFF, NULL AS COD_CONV, a.DMOFF AS COD_EXEC_CTO, NULL AS COD_COVID_PORT, 
case when length(CAST(DMDOPN AS STRING)) = 6 then 
case when strright(DMDOPN,2) > substr('${var:periodo}',3,2) then 
concat('19',strright(DMDOPN,2),substr(DMDOPN,3,2), strleft(DMDOPN,2))
else concat('20',strright(DMDOPN,2),substr(DMDOPN,3,2), strleft(DMDOPN,2))
end
else 
case when strright(DMDOPN,2) > substr('${var:periodo}',3,2) then 
concat('19',strright(DMDOPN,2),substr(DMDOPN,2,2), lpad(strleft(DMDOPN,1),2,'0'))
else concat('20',strright(DMDOPN,2),substr(DMDOPN,2,2), lpad(strleft(DMDOPN,1),2,'0'))
end end AS DATE_DISB, NULL AS FIELD1_CTO, NULL AS FIELD2_CTO, NULL AS FIELD3_CTO, NULL AS FIELD4_CTO, NULL AS FIELD5_CTO, NULL AS FIELD6_CTO, NULL AS FIELD7_CTO, NULL AS FIELD8_CTO, NULL AS FIELD9_CTO, NULL AS FIELD10_CTO, NULL AS CARD_NUMBER, NULL AS COD_PROG_CARD, NULL AS DES_PROG_CARD
FROM MIS_LOAD_TAP00201 a 
LEFT JOIN MIS_TMP_CUP00901 cl 
ON CAST(a.DMACCT AS STRING) = strright(cl.CUX1AC,length(CAST(cl.CUX1AC AS STRING))-1)
LEFT JOIN MIS_TMP_CUP00901 cl2
ON CAST(a.DMACCT AS STRING) = CAST(cl2.CUX1AC AS string)
LEFT JOIN MIS_TMP_CUP00901 cl3
ON CAST(a.DMACCT AS STRING) = strright(cl3.CUX1AC,length(CAST(cl3.CUX1AC AS STRING))-2)
LEFT JOIN MIS_TMP_CUP00901 cl4
ON CAST(a.DMACCT AS STRING) = strright(cl4.CUX1AC,length(CAST(cl4.CUX1AC AS STRING))-3)
WHERE TRIM(DMACCT) <> ''
;

COMPUTE INCREMENTAL STATS MIS_APR_CONTRACT_DT partition (data_date = '${var:periodo}');

DROP TABLE IF EXISTS MIS_TMP_CONTRACT;
CREATE TABLE MIS_TMP_CONTRACT AS
select idf_cto, cod_entity, cod_product, cod_subproduct, cod_act_type, cod_currency, max(idf_cli), cod_acco_cent, cod_offi, cod_bca_int, cod_amrt_met, cod_rate_type,rate_int, date_origin, date_last_rev, date_prx_rev, exp_date, freq_int_pay, cod_uni_freq_int_pay, fre_rev_int, cod_uni_fre_rev_int, amrt_trm, cod_uni_amrt_trm,ini_am, cuo_am, credit_lim_am, predef_rate_ind, predef_rate, ind_channel, cod_typ_lic, cod_seller, des_seller, cou_car_off, cod_conv, cod_exec_cto, cod_covid_port, DATE_DISB, FIELD1_CTO, FIELD2_CTO, FIELD3_CTO, FIELD4_CTO, FIELD5_CTO, FIELD6_CTO, FIELD7_CTO, FIELD8_CTO, FIELD9_CTO, FIELD10_CTO, CARD_NUMBER, COD_PROG_CARD, DES_PROG_CARD
from mis_apr_contract_dt 
where data_date = '${var:periodo}' and cod_info_source = 'TAP'
group by idf_cto, cod_entity, cod_product, cod_subproduct, cod_act_type, cod_currency, cod_acco_cent, cod_offi, cod_bca_int, cod_amrt_met, cod_rate_type,rate_int, date_origin, date_last_rev, date_prx_rev, exp_date, freq_int_pay, cod_uni_freq_int_pay, fre_rev_int, cod_uni_fre_rev_int, amrt_trm, cod_uni_amrt_trm,ini_am, cuo_am, credit_lim_am, predef_rate_ind, predef_rate, ind_channel, cod_typ_lic, cod_seller, des_seller, cou_car_off, cod_conv, cod_exec_cto, cod_covid_port, DATE_DISB, FIELD1_CTO, FIELD2_CTO, FIELD3_CTO, FIELD4_CTO, FIELD5_CTO, FIELD6_CTO, FIELD7_CTO, FIELD8_CTO, FIELD9_CTO, FIELD10_CTO, CARD_NUMBER, COD_PROG_CARD, DES_PROG_CARD;

ALTER TABLE MIS_APR_CONTRACT_DT
DROP IF EXISTS PARTITION (DATA_DATE = '${var:periodo}', COD_INFO_SOURCE='TAP');

--COMPUTE STATS MIS_TMP_CONTRACT;

INSERT INTO MIS_APR_CONTRACT_DT PARTITION (DATA_DATE='${var:periodo}', COD_INFO_SOURCE='TAP') SELECT * FROM MIS_TMP_CONTRACT;

ALTER TABLE MIS_APR_CONTRACT_DT
DROP IF EXISTS PARTITION (DATA_DATE = '${var:periodo}', COD_INFO_SOURCE='TMP');

----Aprovisionamiento de Contratos asociados a depositos
INSERT INTO MIS_APR_CONTRACT_DT 
PARTITION (DATA_DATE='${var:periodo}', COD_INFO_SOURCE='TMP') 
SELECT DISTINCT
a.TMACCT AS IDF_CTO, a.TMBK AS COD_ENTITY, CONCAT(TRIM(CAST(TMTYPE AS STRING)),'_TMP') AS COD_PRODUCT, a.TMTYPE AS COD_SUBPRODUCT, IFNULL(NULL, '') AS COD_ACT_TYPE, CASE WHEN CAST(TMCMCN AS STRING) = '0' THEN 'HNL' WHEN CAST(TMCMCN AS STRING) IN ('1','2') THEN 'USD' WHEN CAST(TMCMCN AS STRING) IN ('3','4') THEN 'EUR' ELSE 'HNL' END AS COD_CURRENCY, isnull(TRIM(CAST(cl.CUX1CS AS STRING)),'99999999') AS IDF_CLI, CAST(TMBRCH AS STRING) AS COD_ACCO_CENT, CAST(TMBRCH AS STRING) AS COD_OFFI, '360' AS COD_BCA_INT, NULL AS COD_AMRT_MET, 'A' AS COD_RATE_TYPE, CAST(a.TMFRTE AS decimal(30, 10)) AS RATE_INT,
case when length(CAST(TMOPDT AS STRING)) = 6 then 
case when strright(CAST(TMOPDT AS STRING),2) > substr('${var:periodo}',3,2) then 
concat('19',strright(CAST(TMOPDT AS STRING),2),substr(CAST(TMOPDT AS STRING),3,2), strleft(CAST(TMOPDT AS STRING),2))
else concat('20',strright(CAST(TMOPDT AS STRING),2),substr(CAST(TMOPDT AS STRING),3,2), strleft(CAST(TMOPDT AS STRING),2))
end
else 
case when strright(CAST(TMOPDT AS STRING),2) > substr('${var:periodo}',3,2) then 
concat('19',strright(CAST(TMOPDT AS STRING),2),substr(CAST(TMOPDT AS STRING),2,2), lpad(strleft(CAST(TMOPDT AS STRING),1),2,'0'))
else concat('20',strright(CAST(TMOPDT AS STRING),2),substr(CAST(TMOPDT AS STRING),2,2), lpad(strleft(CAST(TMOPDT AS STRING),1),2,'0'))
end end AS DATE_ORIGIN, NULL AS DATE_LAST_REV, NULL AS DATE_PRX_REV, 
case when length(CAST(TMMTDT AS STRING)) = 6 then 
concat('20',strright(CAST(TMMTDT AS STRING),2),substr(CAST(TMMTDT AS STRING),3,2), strleft(CAST(TMMTDT AS STRING),2))
else 
concat('20',strright(CAST(TMMTDT AS STRING),2),substr(CAST(TMMTDT AS STRING),2,2), lpad(strleft(CAST(TMMTDT AS STRING),1),2,'0'))
end AS EXP_DATE, 
    CAST(TMTPER AS BIGINT) AS FREQ_INT_PAY, TMTPER AS COD_UNI_FREQ_INT_PAY, NULL AS FRE_REV_INT, NULL AS COD_UNI_FRE_REV_INT, 
    NULL AS AMRT_TRM, NULL AS COD_UNI_AMRT_TRM, TMFACE AS INI_AM, NULL AS CUO_AM, NULL AS CREDIT_LIM_AM, 
    NULL AS PREDEF_RATE_IND, NULL AS PREDEF_RATE, NULL AS IND_CHANNEL, NULL AS COD_TYP_LIC, NULL AS COD_SELLER, NULL AS DES_SELLER, NULL AS COU_CAR_OFF, NULL AS COD_CONV, TMOFF AS COD_EXEC_CTO, NULL AS COD_COVID_PORT, 
case when length(CAST(TMOPDT AS STRING)) = 6 then 
case when strright(CAST(TMOPDT AS STRING),2) > substr('${var:periodo}',3,2) then 
concat('19',strright(CAST(TMOPDT AS STRING),2),substr(CAST(TMOPDT AS STRING),3,2), strleft(CAST(TMOPDT AS STRING),2))
else concat('20',strright(CAST(TMOPDT AS STRING),2),substr(CAST(TMOPDT AS STRING),3,2), strleft(CAST(TMOPDT AS STRING),2))
end
else 
case when strright(CAST(TMOPDT AS STRING),2) > substr('${var:periodo}',3,2) then 
concat('19',strright(CAST(TMOPDT AS STRING),2),substr(CAST(TMOPDT AS STRING),2,2), lpad(strleft(CAST(TMOPDT AS STRING),1),2,'0'))
else concat('20',strright(CAST(TMOPDT AS STRING),2),substr(CAST(TMOPDT AS STRING),2,2), lpad(strleft(CAST(TMOPDT AS STRING),1),2,'0'))
end end AS DATE_DISB, NULL AS FIELD1_CTO, NULL AS FIELD2_CTO, NULL AS FIELD3_CTO, NULL AS FIELD4_CTO, NULL AS FIELD5_CTO, NULL AS FIELD6_CTO, NULL AS FIELD7_CTO, NULL AS FIELD8_CTO, NULL AS FIELD9_CTO, NULL AS FIELD10_CTO, NULL AS CARD_NUMBER, NULL AS COD_PROG_CARD, NULL AS DES_PROG_CARD
FROM MIS_LOAD_TMP003 a 
LEFT JOIN MIS_TMP_CUP00901 cl 
ON CAST(a.TMACCT AS STRING) = CAST(cl.CUX1AC AS string) 
WHERE TMSTAT NOT IN ('4')
;