--------------------------------------------------------------- MIS_APR_LIABILITIES -------------------------------------------------------

--- Comando que apunta a la base de datos apropiada ---
USE ${var:base_datos};
SET DECIMAL_V2=FALSE;

----Carga de tablas load

TRUNCATE TABLE IF EXISTS MIS_LOAD_CNTRLRTE; 
LOAD DATA INPATH '${var:ruta_fuentes_pasivos}/CNTRLRTE.CSV' INTO TABLE MIS_LOAD_CNTRLRTE;

ALTER TABLE MIS_APR_LIABILITIES
DROP IF EXISTS PARTITION (DATA_DATE = '${var:periodo}');

----Aprovisionamiento de Pasivos Capital (CUENTAS DE AHORRO)
INSERT INTO MIS_APR_LIABILITIES
PARTITION (DATA_DATE='${var:periodo}') 
SELECT 'CTA' AS COD_CONT, CAST(a.ACMACC AS string) AS IDF_CTO, CAST(a.ACMGLN AS string) AS COD_GL, NULL AS DES_GL,
CAST(a.ACMCCN AS string) AS COD_ACCO_CENT, TRIM(a.ACMBRN) AS COD_OFFI, 
'0' AS COD_BLCE_STATUS, 'CAP' AS COD_VALUE, a.ACMCCY AS COD_CURRENCY,
a.ACMBNK AS COD_ENTITY, CASE WHEN b.IDF_CTO IS NOT NULL 
THEN b.COD_PRODUCT ELSE TRIM(a.ACMATY) END AS COD_PRODUCT, 
TRIM(a.ACMPRO) AS COD_SUBPRODUCT, 
a.ACMIND AS COD_ACT_TYPE,
CAST(a.ACMGBL AS DECIMAL(30,10)) AS EOPBAL_CAP, NULL AS EOPBAL_INT, CAST(a.ACMNAV AS DECIMAL(30,10)) AS AVGBAL_CAP, NULL AS AVGBAL_INT, 
NULL AS PL, 'ACMST' AS COD_INFO_SOURCE 
FROM MIS_LOAD_ACMST a
LEFT JOIN MIS_PAR_REL_PROD_SPE b 
ON CAST(a.ACMACC AS string) = B.IDF_CTO
WHERE ((a.ACMAST NOT IN ('D','I','N','C')) 
OR (a.ACMAST IN ('N','C') AND CAST(a.ACMGBL AS DECIMAL(30,10)) <> 0)) AND TRIM(a.ACMATY) like 'CAH%'
;

INSERT INTO MIS_APR_LIABILITIES
PARTITION (DATA_DATE='${var:periodo}') 
SELECT 'CTA' AS COD_CONT, CAST(a.ACMACC AS string) AS IDF_CTO, CAST(d.GLMX19 AS string) AS COD_GL, NULL AS DES_GL,
CAST(a.ACMCCN AS string) AS COD_ACCO_CENT, TRIM(a.ACMBRN) AS COD_OFFI, 
'0' AS COD_BLCE_STATUS, 'CAP' AS COD_VALUE, a.ACMCCY AS COD_CURRENCY,
 a.ACMBNK AS COD_ENTITY, CASE WHEN b.IDF_CTO IS NOT NULL 
THEN b.COD_PRODUCT ELSE TRIM(a.ACMATY) END AS COD_PRODUCT, 
TRIM(a.ACMPRO) AS COD_SUBPRODUCT, 
a.ACMIND AS COD_ACT_TYPE,
CAST(a.ACMGBL AS DECIMAL(30,10)) AS EOPBAL_CAP, NULL AS EOPBAL_INT, NULL AS AVGBAL_CAP, NULL AS AVGBAL_INT, 
NULL AS PL, 'ACMST' AS COD_INFO_SOURCE 
FROM MIS_LOAD_ACMST a
LEFT JOIN MIS_PAR_REL_PROD_SPE b 
ON CAST(a.ACMACC AS string) = B.IDF_CTO
LEFT JOIN (SELECT * FROM MIS_LOAD_GLMST WHERE GLMCCY = 'USD') d
ON a.ACMGLN = d.GLMGLN
LEFT JOIN MIS_LOAD_SOBDT c
ON CAST(c.SOBACC AS string) = CAST(a.ACMACC AS string)
WHERE c.SOBACC IS NULL AND a.ACMAST IN ('D','I') 
AND CAST(a.ACMGBL AS DECIMAL(30,10)) <> 0 AND TRIM(a.ACMATY) like 'CAH%'
;

----Aprovisionamiento de Pasivos Capital (CUENTAS CORRIENTE)
INSERT INTO MIS_APR_LIABILITIES
PARTITION (DATA_DATE='${var:periodo}') 
SELECT 'CTA' AS COD_CONT, CAST(a.ACMACC AS string) AS IDF_CTO, CAST(a.ACMGLN AS string) AS COD_GL, NULL AS DES_GL,
CAST(a.ACMCCN AS string) AS COD_ACCO_CENT, TRIM(a.ACMBRN) AS COD_OFFI, 
'0' AS COD_BLCE_STATUS, 'CAP' AS COD_VALUE, a.ACMCCY AS COD_CURRENCY,
a.ACMBNK AS COD_ENTITY, CASE WHEN b.IDF_CTO IS NOT NULL 
THEN b.COD_PRODUCT ELSE TRIM(a.ACMATY) END AS COD_PRODUCT, 
TRIM(a.ACMPRO) AS COD_SUBPRODUCT, 
a.ACMIND AS COD_ACT_TYPE,
CAST(a.ACMGBL AS DECIMAL(30,10)) AS EOPBAL_CAP, NULL AS EOPBAL_INT, CAST(a.ACMNAV AS DECIMAL(30,10)) AS AVGBAL_CAP, NULL AS AVGBAL_INT, 
NULL AS PL, 'ACMST' AS COD_INFO_SOURCE 
FROM MIS_LOAD_ACMST a
LEFT JOIN MIS_PAR_REL_PROD_SPE b 
ON CAST(a.ACMACC AS string) = B.IDF_CTO
WHERE a.ACMAST NOT IN ('D','I') 
AND CAST(a.ACMGBL AS DECIMAL(30,10)) < 0 AND TRIM(a.ACMATY) like  'CCT%'
;

INSERT INTO MIS_APR_LIABILITIES
PARTITION (DATA_DATE='${var:periodo}') 
SELECT 'CTA' AS COD_CONT, CAST(a.ACMACC AS string) AS IDF_CTO, CAST(d.GLMX19 AS string) AS COD_GL, NULL AS DES_GL,
CAST(a.ACMCCN AS string) AS COD_ACCO_CENT, TRIM(a.ACMBRN) AS COD_OFFI, 
'0' AS COD_BLCE_STATUS, 'CAP' AS COD_VALUE, a.ACMCCY AS COD_CURRENCY,
 a.ACMBNK AS COD_ENTITY, CASE WHEN b.IDF_CTO IS NOT NULL 
THEN b.COD_PRODUCT ELSE TRIM(a.ACMATY) END AS COD_PRODUCT, 
TRIM(a.ACMPRO) AS COD_SUBPRODUCT, 
a.ACMIND AS COD_ACT_TYPE,
CAST(a.ACMGBL AS DECIMAL(30,10)) AS EOPBAL_CAP, NULL AS EOPBAL_INT, NULL AS AVGBAL_CAP, NULL AS AVGBAL_INT, 
NULL AS PL, 'ACMST' AS COD_INFO_SOURCE 
FROM MIS_LOAD_ACMST a
LEFT JOIN MIS_PAR_REL_PROD_SPE b 
ON CAST(a.ACMACC AS string) = B.IDF_CTO
LEFT JOIN (SELECT * FROM MIS_LOAD_GLMST WHERE GLMCCY = 'USD') d
ON a.ACMGLN = d.GLMGLN
LEFT JOIN MIS_LOAD_SOBDT c
ON CAST(c.SOBACC AS string) = CAST(a.ACMACC AS string)
WHERE c.SOBACC IS NULL AND a.ACMAST IN ('D','I') 
AND CAST(a.ACMGBL AS DECIMAL(30,10)) < 0 AND TRIM(a.ACMATY) like  'CCT%'
;

----Aprovisionamiento de Pasivos Intereses (CUENTAS DE AHORRO)
/*INSERT INTO MIS_APR_LIABILITIES
PARTITION (DATA_DATE='${var:periodo}') 
SELECT 'CTA' AS COD_CONT, CAST(a.ACMACC AS string) AS IDF_CTO, CAST(d.GLMX19 AS string) AS COD_GL, NULL AS DES_GL,
CAST(a.ACMCCN AS string) AS COD_ACCO_CENT, TRIM(a.ACMBRN) AS COD_OFFI, 
'0' AS COD_BLCE_STATUS, 'INT' AS COD_VALUE, a.ACMCCY AS COD_CURRENCY,
 a.ACMBNK AS COD_ENTITY, CASE WHEN b.IDF_CTO IS NOT NULL 
THEN b.COD_PRODUCT ELSE TRIM(a.ACMATY) END AS COD_PRODUCT, 
TRIM(a.ACMPRO) AS COD_SUBPRODUCT, 
a.ACMIND AS COD_ACT_TYPE,
CAST(a.ACMIAC-a.ACMIPL AS DECIMAL(30,10)) AS EOPBAL_CAP, NULL AS EOPBAL_INT, NULL AS AVGBAL_CAP, NULL AS AVGBAL_INT, 
NULL AS PL, 'ACMST' AS COD_INFO_SOURCE 
FROM MIS_LOAD_ACMST a
LEFT JOIN MIS_PAR_REL_PROD_SPE b 
ON CAST(a.ACMACC AS string) = B.IDF_CTO
LEFT JOIN (SELECT * FROM MIS_LOAD_GLMST WHERE GLMCCY = 'USD') d
ON a.ACMGLN = d.GLMGLN
;*/


--- Aprovisionamiento de Pasivos Resultados (CUENTAS DE AHORRO)
INSERT INTO MIS_APR_LIABILITIES
PARTITION (DATA_DATE='${var:periodo}') 
SELECT 'CTA' AS COD_CONT, CAST(a.ACMACC AS string) AS IDF_CTO, CAST(d.GLMXIE AS string) AS COD_GL, NULL AS DES_GL,
CAST(a.ACMCCN AS string) AS COD_ACCO_CENT, TRIM(a.ACMBRN) AS COD_OFFI, 
'0' AS COD_BLCE_STATUS, 'RSL' AS COD_VALUE, a.ACMCCY AS COD_CURRENCY,
 a.ACMBNK AS COD_ENTITY, CASE WHEN b.IDF_CTO IS NOT NULL 
THEN b.COD_PRODUCT ELSE TRIM(a.ACMATY) END AS COD_PRODUCT, 
TRIM(a.ACMPRO) AS COD_SUBPRODUCT, 
a.ACMIND AS COD_ACT_TYPE,
NULL AS EOPBAL_CAP, NULL AS EOPBAL_INT, NULL AS AVGBAL_CAP, NULL AS AVGBAL_INT, 
CAST(ROUND(CAST(a.ACMMIA AS DECIMAL(30,10)),10) AS DECIMAL(30,10)) AS PL, 'ACMST' AS COD_INFO_SOURCE 
FROM MIS_LOAD_ACMST a
LEFT JOIN MIS_PAR_REL_PROD_SPE b 
ON CAST(a.ACMACC AS string) = B.IDF_CTO
LEFT JOIN (SELECT * FROM MIS_LOAD_GLMST WHERE GLMCCY = 'USD') d
ON a.ACMGLN = d.GLMGLN
AND CAST(a.ACMMIA  AS DECIMAL(30,10))<> 0
;

----Aprovisionamiento de Contratos asociados a Pasivos

ALTER TABLE MIS_APR_CONTRACT_DT
DROP IF EXISTS PARTITION (DATA_DATE = '${var:periodo}', COD_INFO_SOURCE='ACMST');

INSERT INTO MIS_APR_CONTRACT_DT 
PARTITION (DATA_DATE='${var:periodo}', COD_INFO_SOURCE='ACMST') 
SELECT DISTINCT CAST(a.ACMACC AS string) AS IDF_CTO, REGEXP_REPLACE(a.ACMBNK, '"', '') AS COD_ENTITY, 
CASE WHEN b.IDF_CTO IS NOT NULL THEN b.COD_PRODUCT ELSE  REGEXP_REPLACE(TRIM(a.ACMATY), '"', '') END AS COD_PRODUCT, REGEXP_REPLACE(TRIM(a.ACMPRO), '"', '')AS COD_SUBPRODUCT, a.ACMIND AS COD_ACT_TYPE, REGEXP_REPLACE(a.ACMCCY, '"', '') AS COD_CURRENCY, CAST(a.ACMCUN AS string) AS IDF_CLI,
CAST(a.ACMCCN AS string) AS COD_ACCO_CENT, TRIM(a.ACMBRN) AS COD_OFFI, NULL AS COD_BCA_INT, NULL AS COD_AMRT_MET, 
'A' AS COD_RATE_TYPE, CAST(((a.ACMOI1)/100) AS decimal(30, 10)) AS RATE_INT, 
CONCAT(CASE WHEN CAST(STRRIGHT(CAST(YEAR(NOW()) AS string), 2) AS smallint) < CAST(a.ACMOPY AS SMALLINT) 
THEN CONCAT('19', LPAD(CAST(a.ACMOPY AS string), 2, '0')) ELSE CONCAT('2', LPAD(CAST(a.ACMOPY AS string), 3, '0')) END, 
LPAD(CAST(a.ACMOPM AS string), 2, '0'), LPAD(CAST(a.ACMOPD  AS string), 2, '0')) AS DATE_ORIGIN, 
NULL AS DATE_LAST_REV, 
NULL AS DATE_PRX_REV,
NULL AS EXP_DATE, 
NULL AS FREQ_INT_PAY, NULL AS COD_UNI_FREQ_INT_PAY, CAST(a.ACMRPT AS BIGINT) AS FRE_REV_INT, NULL AS COD_UNI_FRE_REV_INT, NULL AS AMRT_TRM, NULL AS COD_UNI_AMRT_TRM,
NULL AS INI_AM, NULL AS CUO_AM, NULL AS CREDIT_LIM_AM, NULL AS PREDEF_RATE_IND, NULL AS PREDEF_RATE, NULL AS IND_CHANNEL, NULL AS COD_TYP_LIC, NULL AS COU_CAR_OFF, NULL AS COD_CONV, NULL AS COD_EXEC_CTO, NULL AS COD_COVID_PORT, NULL AS FIELD1_CTO, NULL AS FIELD2_CTO, NULL AS FIELD3_CTO, NULL AS FIELD4_CTO, NULL AS FIELD5_CTO, NULL AS FIELD6_CTO, NULL AS FIELD7_CTO, NULL AS FIELD8_CTO, NULL AS FIELD9_CTO, NULL AS FIELD10_CTO, CONCAT(CASE WHEN CAST(STRRIGHT(CAST(YEAR(NOW()) AS string), 2) AS smallint) < CAST(a.ACMOPY AS SMALLINT) 
THEN CONCAT('19', LPAD(CAST(a.ACMOPY AS string), 2, '0')) ELSE CONCAT('2', LPAD(CAST(a.ACMOPY AS string), 3, '0')) END, 
LPAD(CAST(a.ACMOPM AS string), 2, '0'), LPAD(CAST(a.ACMOPD  AS string), 2, '0')) AS DATE_DISB, NULL AS CARD_NUMBER, NULL AS COD_PROG_CARD, NULL AS DES_PROG_CARD
FROM MIS_LOAD_ACMST a
LEFT JOIN MIS_PAR_REL_PROD_SPE b 
ON CAST(a.ACMACC AS string) = B.IDF_CTO;

--- Aprovisionamiento de Pasivos Capital (CDTs)
INSERT INTO MIS_APR_LIABILITIES 
PARTITION (DATA_DATE='${var:periodo}') 
SELECT 'PLZ' AS COD_CONT, CAST(a.DEAACC AS string) AS IDF_CTO, CAST(a.DEAGLN AS string) AS COD_GL, NULL AS DES_GL,
CAST(a.DEACCN AS string) AS COD_ACCO_CENT, TRIM(a.DEABRN) AS COD_OFFI, 
'1' AS COD_BLCE_STATUS, 'CAP' AS COD_VALUE, REGEXP_REPLACE(a.DEACCY, '"', '') AS COD_CURRENCY,
 REGEXP_REPLACE(a.DEABNK, '"', '') AS COD_ENTITY, CASE WHEN b.IDF_CTO IS NOT NULL 
THEN b.COD_PRODUCT ELSE REGEXP_REPLACE(TRIM(a.DEATYP), '"', '') END AS COD_PRODUCT, 
CASE WHEN c.COD_NEW_SUBPRODUCT IS NOT NULL THEN c.COD_NEW_SUBPRODUCT ELSE REGEXP_REPLACE(TRIM(a.DEAPRO), '"', '') END AS COD_SUBPRODUCT, 
IFNULL(CAST(REGEXP_REPLACE(a.DEAICD, '"', '') AS string), '') AS COD_ACT_TYPE,
CAST(-1*a.DEAPRI AS DECIMAL(30,10)) AS EOPBAL_CAP, NULL AS EOPBAL_INT, CAST(a.DEAAVP*-1 AS DECIMAL(30,10)) AS AVGBAL_CAP, NULL AS AVGBAL_INT, 
NULL AS PL, 'DEALS' AS COD_INFO_SOURCE 
FROM MIS_LOAD_DEALS a
LEFT JOIN MIS_PAR_REL_PROD_SPE b 
ON CAST(a.DEAACC AS string) = B.IDF_CTO
LEFT JOIN MIS_PAR_REL_SUBPROD_OPER c
ON REGEXP_REPLACE(a.DEABNK, '"', '') = c.COD_ENTITY AND REGEXP_REPLACE(TRIM(a.DEATYP), '"', '') = c.COD_PRODUCT AND REGEXP_REPLACE(TRIM(a.DEAPRO), '"', '') = c.COD_SUBPRODUCT AND REGEXP_REPLACE(a.DEAICD, '"', '') = C.COD_ACT_TYPE
LEFT JOIN (SELECT * FROM MIS_LOAD_GLMST WHERE GLMCCY = 'USD') d
ON a.DEAGLN = d.GLMGLN  
WHERE TRIM(a.DEASTS) <> 'C'
AND TRIM(a.DEACLF) <> 'G'
AND strleft(a.DEAGLN,2) = '21'
AND TRIM(CAST(a.DEAACD AS STRING)) IN ('11', '13', '10');

----Aprovisionamiento de Pasivos Intereses (CDTs)
INSERT INTO MIS_APR_LIABILITIES 
PARTITION (DATA_DATE='${var:periodo}') 
SELECT 'PLZ' AS COD_CONT, CAST(a.DEAACC AS string) AS IDF_CTO, CAST(d.GLMXCR AS STRING) AS COD_GL, NULL AS DES_GL, CAST(a.DEACCN AS string) AS COD_ACCO_CENT, TRIM(a.DEABRN) AS COD_OFFI, 
'1' AS COD_BLCE_STATUS, 'INT' AS COD_VALUE, REGEXP_REPLACE(a.DEACCY, '"', '') AS COD_CURRENCY, REGEXP_REPLACE(a.DEABNK, '"', '') AS COD_ENTITY,
CASE WHEN b.IDF_CTO IS NOT NULL THEN b.COD_PRODUCT ELSE  REGEXP_REPLACE(TRIM(a.DEATYP), '"', '') END AS COD_PRODUCT,
CASE WHEN c.COD_NEW_SUBPRODUCT IS NOT NULL THEN c.COD_NEW_SUBPRODUCT ELSE REGEXP_REPLACE(TRIM(a.DEAPRO), '"', '') END AS COD_SUBPRODUCT, IFNULL(CAST(REGEXP_REPLACE(a.DEAICD, '"', '') AS string), '') AS COD_ACT_TYPE, CAST(a.DEAMEI*-1 AS DECIMAL(30,10)) AS EOPBAL_CAP,
NULL AS EOPBAL_INT, NULL AS AVGBAL_CAP, NULL AS AVGBAL_INT, NULL AS PL, 'DEALS' AS COD_INFO_SOURCE
FROM MIS_LOAD_DEALS a
LEFT JOIN MIS_PAR_REL_PROD_SPE b 
ON CAST(a.DEAACC AS string) = B.IDF_CTO
LEFT JOIN MIS_PAR_REL_SUBPROD_OPER c
ON REGEXP_REPLACE(a.DEABNK, '"', '') = c.COD_ENTITY AND REGEXP_REPLACE(TRIM(a.DEATYP), '"', '') = c.COD_PRODUCT AND REGEXP_REPLACE(TRIM(a.DEAPRO), '"', '') = c.COD_SUBPRODUCT AND REGEXP_REPLACE(a.DEAICD, '"', '') = C.COD_ACT_TYPE
LEFT JOIN (SELECT * FROM MIS_LOAD_GLMST WHERE GLMCCY = 'USD') d
ON a.DEAGLN = d.GLMGLN  
WHERE TRIM(a.DEASTS) <> 'C'
AND TRIM(a.DEACLF) <> 'G'
AND strleft(a.DEAGLN,2) = '21'
AND TRIM(CAST(a.DEAACD AS STRING)) IN ('11', '13', '10');


----Aprovisionamiento de Pasivos Resultados (CDTs)
INSERT INTO MIS_APR_LIABILITIES 
PARTITION (DATA_DATE='${var:periodo}') 
SELECT 'PLZ' AS COD_CONT, CAST(a.DEAACC AS string) AS IDF_CTO, CAST(d.GLMXDR AS STRING) AS COD_GL, NULL AS DES_GL, CAST(a.DEACCN AS string) AS COD_ACCO_CENT, TRIM(a.DEABRN) AS COD_OFFI,
'1' AS COD_BLCE_STATUS, 'RSL' AS COD_VALUE, REGEXP_REPLACE(a.DEACCY, '"', '') AS COD_CURRENCY, REGEXP_REPLACE(a.DEABNK, '"', '') AS COD_ENTITY,
CASE WHEN b.IDF_CTO IS NOT NULL THEN b.COD_PRODUCT
ELSE  REGEXP_REPLACE(TRIM(a.DEATYP), '"', '') END AS COD_PRODUCT, CASE WHEN c.COD_NEW_SUBPRODUCT IS NOT NULL THEN c.COD_NEW_SUBPRODUCT ELSE REGEXP_REPLACE(TRIM(a.DEAPRO), '"', '') END AS COD_SUBPRODUCT, IFNULL(CAST(REGEXP_REPLACE(a.DEAICD, '"', '') AS string), '') AS COD_ACT_TYPE,
NULL AS EOPBAL_CAP, NULL AS EOPBAL_INT, NULL AS AVGBAL_CAP, NULL AS AVGBAL_INT, CAST(a.DEAINM AS DECIMAL(30,10)) AS PL, 'DEALS' AS COD_INFO_SOURCE 
FROM MIS_LOAD_DEALS a
LEFT JOIN MIS_PAR_REL_PROD_SPE b 
ON CAST(a.DEAACC AS string) = B.IDF_CTO
LEFT JOIN MIS_PAR_REL_SUBPROD_OPER c
ON REGEXP_REPLACE(a.DEABNK, '"', '') = c.COD_ENTITY AND REGEXP_REPLACE(TRIM(a.DEATYP), '"', '') = c.COD_PRODUCT AND REGEXP_REPLACE(TRIM(a.DEAPRO), '"', '') = c.COD_SUBPRODUCT AND REGEXP_REPLACE(a.DEAICD, '"', '') = C.COD_ACT_TYPE
LEFT JOIN (SELECT * FROM MIS_LOAD_GLMST WHERE GLMCCY = 'USD') d
ON a.DEAGLN = d.GLMGLN  
WHERE TRIM(a.DEASTS) <> 'C'
AND TRIM(a.DEACLF) <> 'G'
AND strleft(a.DEAGLN,2) = '21'
AND TRIM(CAST(a.DEAACD AS STRING)) IN ('11', '13', '10');

----Aprovisionamiento de Contratos asociados a Pasivos (CDTs)

ALTER TABLE MIS_APR_CONTRACT_DT
DROP IF EXISTS PARTITION (DATA_DATE = '${var:periodo}', COD_INFO_SOURCE='DEALSCDT');

INSERT INTO MIS_APR_CONTRACT_DT 
PARTITION (DATA_DATE='${var:periodo}', COD_INFO_SOURCE='DEALSCDT') 
SELECT DISTINCT CAST(a.DEAACC AS string) AS IDF_CTO, REGEXP_REPLACE(a.DEABNK, '"', '') AS COD_ENTITY, 
CASE WHEN b.IDF_CTO IS NOT NULL THEN b.COD_PRODUCT ELSE  REGEXP_REPLACE(TRIM(a.DEATYP), '"', '') END AS COD_PRODUCT, CASE WHEN c.COD_NEW_SUBPRODUCT IS NOT NULL THEN c.COD_NEW_SUBPRODUCT ELSE REGEXP_REPLACE(TRIM(a.DEAPRO), '"', '') END AS COD_SUBPRODUCT,
IFNULL(CAST(REGEXP_REPLACE(a.DEAICD, '"', '') AS string), '') AS COD_ACT_TYPE, REGEXP_REPLACE(a.DEACCY, '"', '') AS COD_CURRENCY, CAST(a.DEACUN AS string) AS IDF_CLI,
CAST(a.DEACCN AS string) AS COD_ACCO_CENT, TRIM(a.DEABRN) AS COD_OFFI, NULL AS COD_BCA_INT, NULL AS COD_AMRT_MET, 
CASE WHEN REGEXP_REPLACE(TRIM(a.DEARRP), '"', '')='' AND a.DEARRD=0 THEN 'F' ELSE 'V' END AS COD_RATE_TYPE, CAST(((a.DEARTE+a.DEAFRT)/100) AS decimal(30, 10)) AS RATE_INT, 
CONCAT(CASE WHEN CAST(STRRIGHT(CAST(YEAR(NOW()) AS string), 2) AS smallint) < a.DEAODY 
THEN CONCAT('19', LPAD(CAST(a.DEAODY AS string), 2, '0')) ELSE CONCAT('2', LPAD(CAST(a.DEAODY AS string), 3, '0')) END, 
LPAD(CAST(a.DEAODM AS string), 2, '0'), LPAD(CAST(a.DEAODD  AS string), 2, '0')) AS DATE_ORIGIN, 
CASE WHEN a.DEAREY=0 AND a.DEARCM=0 AND a.DEARCO=0 THEN CONCAT(CASE WHEN CAST(STRRIGHT(CAST(YEAR(NOW()) AS string), 2) AS smallint) < a.DEAODY 
THEN CONCAT('19', LPAD(CAST(a.DEAODY AS string), 2, '0')) 
ELSE CONCAT('2', LPAD(CAST(a.DEAODY AS string), 3, '0')) END, 
LPAD(CAST(a.DEAODM AS string), 2, '0'), LPAD(CAST(a.DEAODD  AS string), 2, '0'))
ELSE CONCAT(CASE WHEN CAST(STRRIGHT(CAST(YEAR(NOW()) AS string), 2) AS smallint) < a.DEAREY 
THEN CONCAT('19', LPAD(CAST(a.DEAREY AS string), 2, '0')) 
ELSE CONCAT('2', LPAD(CAST(a.DEAREY AS string), 3, '0')) END, 
LPAD(CAST(a.DEARCM AS string), 2, '0'), LPAD(CAST(a.DEARCO  AS string), 2, '0')) END AS DATE_LAST_REV, 
CASE WHEN a.DEARDY=0 AND a.DEARDM=0 AND a.DEARDD=0 THEN NULL ELSE CONCAT(CONCAT('2', LPAD(CAST(a.DEARRY AS string), 3, '0')), 
LPAD(CAST(a.DEARRM AS string), 2, '0'), LPAD(CAST(a.DEARRD  AS string), 2, '0')) END AS DATE_PRX_REV,
CASE WHEN a.DEAMAY=0 AND a.DEAMAM=0 AND a.DEAMAD=0 THEN NULL ELSE CONCAT(CONCAT('2', LPAD(CAST(a.DEAMAY AS string), 3, '0')), 
LPAD(CAST(a.DEAMAM AS string), 2, '0'), LPAD(CAST(a.DEAMAD  AS string), 2, '0')) END AS EXP_DATE, 
CAST(REGEXP_REPLACE(a.DEAIPD, '"', '') AS BIGINT) AS FREQ_INT_PAY, NULL AS COD_UNI_FREQ_INT_PAY, NULL AS FRE_REV_INT, NULL AS COD_UNI_FRE_REV_INT, NULL AS AMRT_TRM, NULL AS COD_UNI_AMRT_TRM,
CAST(a.DEAOAM * -1 AS DECIMAL(30,10)) AS INI_AM, NULL AS CUO_AM, NULL AS CREDIT_LIM_AM, NULL AS PREDEF_RATE_IND, NULL AS PREDEF_RATE, NULL AS IND_CHANNEL, NULL AS COD_TYP_LIC, NULL AS COU_CAR_OFF, NULL AS COD_CONV, NULL AS COD_EXEC_CTO, NULL AS COD_COVID_PORT, NULL AS FIELD1_CTO, NULL AS FIELD2_CTO, NULL AS FIELD3_CTO, NULL AS FIELD4_CTO, NULL AS FIELD5_CTO, NULL AS FIELD6_CTO, NULL AS FIELD7_CTO, NULL AS FIELD8_CTO, NULL AS FIELD9_CTO, NULL AS FIELD10_CTO, CONCAT(CASE WHEN CAST(STRRIGHT(CAST(YEAR(NOW()) AS string), 2) AS smallint) < a.DEAODY 
THEN CONCAT('19', LPAD(CAST(a.DEAODY AS string), 2, '0')) ELSE CONCAT('2', LPAD(CAST(a.DEAODY AS string), 3, '0')) END, 
LPAD(CAST(a.DEAODM AS string), 2, '0'), LPAD(CAST(a.DEAODD  AS string), 2, '0')) AS DATE_DISB, NULL AS CARD_NUMBER, NULL AS COD_PROG_CARD, NULL AS DES_PROG_CARD
FROM MIS_LOAD_DEALS a
LEFT JOIN MIS_PAR_REL_PROD_SPE b 
ON CAST(a.DEAACC AS string) = B.IDF_CTO
LEFT JOIN MIS_PAR_REL_SUBPROD_OPER c
ON REGEXP_REPLACE(a.DEABNK, '"', '') = c.COD_ENTITY AND REGEXP_REPLACE(TRIM(a.DEATYP), '"', '') = c.COD_PRODUCT AND REGEXP_REPLACE(TRIM(a.DEAPRO), '"', '') = c.COD_SUBPRODUCT AND REGEXP_REPLACE(a.DEAICD, '"', '') = C.COD_ACT_TYPE 
WHERE TRIM(a.DEASTS) <> 'C'
AND TRIM(a.DEACLF) <> 'G'
AND strleft(a.DEAGLN,2) = '21'
AND TRIM(CAST(a.DEAACD AS STRING)) IN ('11', '13', '10');