USE ${var:base_datos};

--- calculo de estadisticas de las tablas --

ALTER TABLE MIS_APR_CONTRACT_DT
ADD IF NOT EXISTS PARTITION (DATA_DATE = '${var:periodo}', COD_INFO_SOURCE = 'DEALS');

ALTER TABLE MIS_APR_CLIENT_DT
ADD IF NOT EXISTS PARTITION (DATA_DATE = '${var:periodo}');

ALTER TABLE MIS_APR_ASSETS
ADD IF NOT EXISTS PARTITION (DATA_DATE = '${var:periodo}');

ALTER TABLE MIS_APR_ACCOUNTING
ADD IF NOT EXISTS PARTITION (DATA_DATE = '${var:periodo}');

ALTER TABLE MIS_APR_LIABILITIES 
ADD IF NOT EXISTS PARTITION (DATA_DATE = '${var:periodo}');

ALTER TABLE MIS_APR_FEES
ADD IF NOT EXISTS PARTITION (DATA_DATE = '${var:periodo}');

ALTER TABLE MIS_APR_OFF_BALANCE 
ADD IF NOT EXISTS PARTITION (DATA_DATE = '${var:periodo}');

ALTER TABLE MIS_APR_PROVISIONS 
ADD IF NOT EXISTS PARTITION (DATA_DATE = '${var:periodo}');

ALTER TABLE MIS_DWH_ASSETS
ADD IF NOT EXISTS PARTITION (DATA_DATE = '${var:periodo}', COD_INFO_SOURCE = 'DEALS');

ALTER TABLE MIS_DWH_ACCOUNTING
ADD IF NOT EXISTS PARTITION (DATA_DATE = '${var:periodo}');

ALTER TABLE MIS_DWH_LIABILITIES 
ADD IF NOT EXISTS PARTITION (DATA_DATE = '${var:periodo}', COD_INFO_SOURCE = 'ACMST');

ALTER TABLE MIS_DWH_FEES
ADD IF NOT EXISTS PARTITION (DATA_DATE = '${var:periodo}', COD_INFO_SOURCE = 'TRANS');

ALTER TABLE MIS_DWH_OFF_BALANCE 
ADD IF NOT EXISTS PARTITION (DATA_DATE = '${var:periodo}', COD_INFO_SOURCE = 'LCMST');

ALTER TABLE MIS_DWH_PROVISIONS 
ADD IF NOT EXISTS PARTITION (DATA_DATE = '${var:periodo}', COD_INFO_SOURCE = 'WFDLRES');

ALTER TABLE MIS_DWH_RECONCILIATION
ADD IF NOT EXISTS PARTITION (DATA_DATE = '${var:periodo}', COD_CONT = 'CTBP');

ALTER TABLE MIS_DM_BALANCE_RESULT
ADD IF NOT EXISTS PARTITION (DATA_DATE = '${var:periodo}');

COMPUTE INCREMENTAL STATS MIS_APR_CONTRACT_DT PARTITION (DATA_DATE = '${var:periodo}');
COMPUTE INCREMENTAL STATS MIS_APR_CLIENT_DT PARTITION (DATA_DATE = '${var:periodo}');
COMPUTE INCREMENTAL STATS MIS_APR_ASSETS PARTITION (DATA_DATE = '${var:periodo}');
COMPUTE INCREMENTAL STATS MIS_APR_ACCOUNTING PARTITION (DATA_DATE = '${var:periodo}');
COMPUTE INCREMENTAL STATS MIS_APR_LIABILITIES PARTITION (DATA_DATE = '${var:periodo}');
COMPUTE INCREMENTAL STATS MIS_APR_FEES PARTITION (DATA_DATE = '${var:periodo}');
COMPUTE INCREMENTAL STATS MIS_APR_OFF_BALANCE PARTITION (DATA_DATE = '${var:periodo}');
COMPUTE INCREMENTAL STATS MIS_APR_PROVISIONS PARTITION (DATA_DATE = '${var:periodo}');

COMPUTE INCREMENTAL STATS MIS_DWH_ASSETS PARTITION (DATA_DATE = '${var:periodo}');
COMPUTE INCREMENTAL STATS MIS_DWH_ACCOUNTING PARTITION (DATA_DATE = '${var:periodo}');
COMPUTE INCREMENTAL STATS MIS_DWH_LIABILITIES PARTITION (DATA_DATE = '${var:periodo}');
COMPUTE INCREMENTAL STATS MIS_DWH_FEES PARTITION (DATA_DATE = '${var:periodo}');
COMPUTE INCREMENTAL STATS MIS_DWH_OFF_BALANCE PARTITION (DATA_DATE = '${var:periodo}');
COMPUTE INCREMENTAL STATS MIS_DWH_PROVISIONS PARTITION (DATA_DATE = '${var:periodo}');
COMPUTE INCREMENTAL STATS MIS_DWH_RECONCILIATION PARTITION (DATA_DATE = '${var:periodo}');

COMPUTE INCREMENTAL STATS MIS_DM_BALANCE_RESULT PARTITION (DATA_DATE = '${var:periodo}');