USE ${var:base_datos};

--- calculo de estadisticas de las tablas --

COMPUTE STATS MIS_APR_CONTRACT_DT;
COMPUTE STATS MIS_APR_CLIENT_DT;
COMPUTE STATS MIS_APR_ASSETS;
COMPUTE STATS MIS_APR_ACCOUNTING;
COMPUTE STATS MIS_APR_LIABILITIES;
COMPUTE STATS MIS_APR_FEES;
COMPUTE STATS MIS_APR_OFF_BALANCE;
COMPUTE STATS MIS_APR_PROVISIONS;

COMPUTE STATS MIS_DWH_ASSETS;
COMPUTE STATS MIS_DWH_ACCOUNTING;
COMPUTE STATS MIS_DWH_LIABILITIES;
COMPUTE STATS MIS_DWH_FEES;
COMPUTE STATS MIS_DWH_OFF_BALANCE;
COMPUTE STATS MIS_DWH_PROVISIONS;
COMPUTE STATS MIS_DWH_RECONCILIATION;

COMPUTE STATS MIS_DM_BALANCE_RESULT;