USE ${var:base_datos};

--- calculo de estadisticas de las tablas --

ALTER TABLE MIS_DWH_ASSETS_M
ADD IF NOT EXISTS PARTITION (DATA_DATE = '${var:periodo}', COD_INFO_SOURCE = 'DEALS');

ALTER TABLE MIS_DWH_ACCOUNTING_M
ADD IF NOT EXISTS PARTITION (DATA_DATE = '${var:periodo}');

ALTER TABLE MIS_DWH_LIABILITIES_M
ADD IF NOT EXISTS PARTITION (DATA_DATE = '${var:periodo}', COD_INFO_SOURCE = 'ACMST');

ALTER TABLE MIS_DWH_FEES_M
ADD IF NOT EXISTS PARTITION (DATA_DATE = '${var:periodo}', COD_INFO_SOURCE = 'TRANS');

ALTER TABLE MIS_DWH_OFF_BALANCE_M
ADD IF NOT EXISTS PARTITION (DATA_DATE = '${var:periodo}', COD_INFO_SOURCE = 'LCMST');

ALTER TABLE MIS_DWH_RECONCILIATION_M
ADD IF NOT EXISTS PARTITION (DATA_DATE = '${var:periodo}', COD_CONT = 'CTBP');

ALTER TABLE MIS_DM_BALANCE_RESULT_M
ADD IF NOT EXISTS PARTITION (DATA_DATE = '${var:periodo}', COD_INFO_SOURCE = 'DEALS');

COMPUTE INCREMENTAL STATS MIS_DWH_ASSETS_M PARTITION (DATA_DATE = '${var:periodo}');
COMPUTE INCREMENTAL STATS MIS_DWH_ACCOUNTING_M PARTITION (DATA_DATE = '${var:periodo}');
COMPUTE INCREMENTAL STATS MIS_DWH_LIABILITIES_M PARTITION (DATA_DATE = '${var:periodo}');
COMPUTE INCREMENTAL STATS MIS_DWH_FEES_M PARTITION (DATA_DATE = '${var:periodo}');
COMPUTE INCREMENTAL STATS MIS_DWH_OFF_BALANCE_M PARTITION (DATA_DATE = '${var:periodo}');
COMPUTE INCREMENTAL STATS MIS_DWH_RECONCILIATION_M PARTITION (DATA_DATE = '${var:periodo}');

COMPUTE INCREMENTAL STATS MIS_DM_BALANCE_RESULT_M PARTITION (DATA_DATE = '${var:periodo}');