--------------------------------------------------------------- MIS_APR_ASSETS ------------------------------------------------------------

--- Comando que apunta a la base de datos apropiada ---
USE ${var:base_datos};
SET DECIMAL_V2=FALSE;

----Carga de tablas load
TRUNCATE TABLE IF EXISTS MIS_LOAD_DLAHI; 
LOAD DATA INPATH '${var:ruta_fuentes_activos}/DLAHI.CSV' INTO TABLE MIS_LOAD_DLAHI;

TRUNCATE TABLE IF EXISTS MIS_LOAD_DEALS; 
LOAD DATA INPATH '${var:ruta_fuentes_activos}/DEALS.CSV' INTO TABLE MIS_LOAD_DEALS;

TRUNCATE TABLE IF EXISTS MIS_LOAD_VPSCUENT; 
LOAD DATA INPATH '${var:ruta_fuentes_activos}/VPSCUENT.CSV' INTO TABLE MIS_LOAD_VPSCUENT;

TRUNCATE TABLE IF EXISTS MIS_LOAD_VPSATSMP; 
LOAD DATA INPATH '${var:ruta_fuentes_activos}/VPSATSMP.CSV' INTO TABLE MIS_LOAD_VPSATSMP;

TRUNCATE TABLE IF EXISTS MIS_LOAD_VPSPLAN; 
LOAD DATA INPATH '${var:ruta_fuentes_activos}/VPSPLAN.CSV' INTO TABLE MIS_LOAD_VPSPLAN;

TRUNCATE TABLE IF EXISTS MIS_LOAD_GLSOB; 
LOAD DATA INPATH '${var:ruta_fuentes_activos}/GLSOB.CSV' INTO TABLE MIS_LOAD_GLSOB;

TRUNCATE TABLE IF EXISTS MIS_LOAD_CREMST; 
LOAD DATA INPATH '${var:ruta_fuentes_activos}/CREMST.CSV' INTO TABLE MIS_LOAD_CREMST;

TRUNCATE TABLE IF EXISTS MIS_LOAD_SOBDT; 
LOAD DATA INPATH '${var:ruta_fuentes_activos}/SOBDT.CSV' INTO TABLE MIS_LOAD_SOBDT;

TRUNCATE TABLE IF EXISTS MIS_LOAD_ACMST; 
LOAD DATA INPATH '${var:ruta_fuentes_activos}/ACMST.CSV' INTO TABLE MIS_LOAD_ACMST;

--- Catálogo de Extrafinanciamiento ---
ALTER TABLE MIS_LOAD_CSEXTMSTF
DROP IF EXISTS PARTITION (DATA_DATE = '${var:periodo}');

ALTER TABLE MIS_LOAD_CSEXTMSTF
ADD IF NOT EXISTS PARTITION (DATA_DATE = '${var:periodo}');

LOAD DATA INPATH '${var:ruta_fuentes_activos}/CSEXTMSTF.CSV' INTO TABLE MIS_LOAD_CSEXTMSTF PARTITION (DATA_DATE = '${var:periodo}');

-------------------------------------------------------------------------------------------------------------------------------------

TRUNCATE TABLE IF EXISTS MIS_LOAD_CSPLNINTF; 
LOAD DATA INPATH '${var:ruta_fuentes_activos}/CSPLNINTF.CSV' INTO TABLE MIS_LOAD_CSPLNINTF;

/*TRUNCATE TABLE IF EXISTS MIS_LOAD_CSD533GLF; 
LOAD DATA INPATH '${var:ruta_fuentes_activos}/MIS_LOAD_CSD533GLF.CSV' INTO TABLE MIS_LOAD_CSD533GLF;*/

INSERT INTO MIS_PAR_TTI_SPE
(IDF_CTO, COD_VALUE, RATE_TTI)
PARTITION (DATA_DATE)
SELECT CAST(DEAACC AS STRING) AS IDF_CTO, 'CAP' AS COD_VALUE, CAST(DEAFRT * 0.01 AS DECIMAL(30,10)) AS RATE_TTI, 
'${var:periodo}' AS DATA_DATE
FROM MIS_LOAD_DEALS
WHERE DEATYP='REDA' AND DEAFTB<>'01' AND TRIM(DEASTS) <> 'C' AND TRIM(CAST(DEAACD AS STRING)) <> '11'
AND TRIM(DEACLF) <> 'G' AND STRLEFT(DEAGLN,2) <> '21' 
AND CAST(DEAACC AS STRING) NOT IN (SELECT DISTINCT IDF_CTO FROM MIS_PAR_TTI_SPE WHERE DATA_DATE = '${var:periodo}')
;

INSERT INTO MIS_PAR_TTI_SPE
(IDF_CTO, COD_VALUE, RATE_TTI)
PARTITION (DATA_DATE)
SELECT CAST(DEAACC AS STRING) AS IDF_CTO, 'CAP' AS COD_VALUE, CAST(((DEARTE+DEAFRT)/100) AS DECIMAL(30, 10)) AS RATE_TTI, 
'${var:periodo}' AS DATA_DATE
FROM MIS_LOAD_DEALS 
LEFT JOIN MIS_PAR_REL_PROD_SPE
ON CAST(DEAACC AS STRING) = IDF_CTO
WHERE DEATYP = 'REDE' AND DEAPRO <> 'WCCP' AND IDF_CTO IS NULL
AND CAST(DEAACC AS STRING) NOT IN (SELECT DISTINCT IDF_CTO FROM MIS_PAR_TTI_SPE WHERE DATA_DATE = '${var:periodo}')
;

ALTER TABLE MIS_APR_ASSETS
DROP IF EXISTS PARTITION (DATA_DATE = '${var:periodo}');

----Aprovisionamiento de Activos Capital
INSERT INTO MIS_APR_ASSETS 
PARTITION (DATA_DATE='${var:periodo}') 
SELECT 'PREST' AS COD_CONT, CAST(a.DEAACC AS string) AS IDF_CTO, CAST(a.DEAGLN AS string) AS COD_GL, NULL AS DES_GL,
CAST(a.DEACCN AS string) AS COD_ACCO_CENT, TRIM(a.DEABRN) AS COD_OFFI, 
CASE WHEN STRLEFT(a.DEAGLN,4) IN ('1141','1142') THEN 'VIG' WHEN STRLEFT(a.DEAGLN,4) IN ('1148') THEN 'VEN' ELSE '1' END AS COD_BLCE_STATUS,
'CAP' AS COD_VALUE, a.DEACCY AS COD_CURRENCY,
a.DEABNK AS COD_ENTITY, CASE WHEN b.IDF_CTO IS NOT NULL THEN b.COD_PRODUCT 
WHEN a.DEAPRO = 'EXTR' THEN ISNULL(STRLEFT(d.EXTTAR,1),'TAR') ELSE TRIM(a.DEATYP) END AS COD_PRODUCT,
CASE WHEN (c.COD_NEW_SUBPRODUCT IS NOT NULL AND a.DEAPRO <> 'EXTR') THEN CONCAT(TRIM(c.COD_NEW_SUBPRODUCT), IF((TRIM(e.CRETPA) IS NULL OR TRIM(e.CRETPA) = ""), "", "_"), ISNULL(TRIM(e.CRETPA),""))
WHEN a.DEAPRO = 'EXTR' THEN ISNULL(CONCAT(STRLEFT(d.EXTTAR,8), '_EXT'), 'EXTR')
ELSE CONCAT(TRIM(a.DEAPRO), IF((TRIM(e.CRETPA) IS NULL OR TRIM(e.CRETPA) = ""), "", "_"), ISNULL(TRIM(e.CRETPA),"")) END AS COD_SUBPRODUCT, 
IFNULL(CAST(a.DEAICD AS string), '') AS COD_ACT_TYPE,
a.DEAPRI AS EOPBAL_CAP, NULL AS EOPBAL_INT, a.DEAAVP AS AVGBAL_CAP, NULL AS AVGBAL_INT, 
NULL AS PL, 'DEALS' AS COD_INFO_SOURCE 
FROM MIS_LOAD_DEALS a
LEFT JOIN MIS_PAR_REL_PROD_SPE b 
ON CAST(a.DEAACC AS string) = B.IDF_CTO 
LEFT JOIN MIS_PAR_REL_SUBPROD_OPER c
ON REGEXP_REPLACE(a.DEABNK, '"', '') = c.COD_ENTITY AND REGEXP_REPLACE(TRIM(a.DEATYP), '"', '') = c.COD_PRODUCT AND REGEXP_REPLACE(TRIM(a.DEAPRO), '"', '') = c.COD_SUBPRODUCT AND REGEXP_REPLACE(a.DEAICD, '"', '') = C.COD_ACT_TYPE
LEFT JOIN (SELECT EXTACC, MIN(EXTTAR) EXTTAR FROM MIS_LOAD_CSEXTMSTF GROUP BY EXTACC) d
ON CAST(a.DEAACC AS STRING) = d.EXTACC
LEFT JOIN MIS_LOAD_CREMST e
ON CAST(a.DEAACC AS STRING) = e.CREACC
WHERE STRLEFT(CAST(a.DEAGLN AS string),1) <> '9' AND  TRIM(a.DEASTS) <> 'C'
AND TRIM(CAST(a.DEAACD AS STRING)) <> '11'
AND TRIM(a.DEACLF) <> 'G'
AND STRLEFT(a.DEAGLN,2) <> '21'
;

----Aprovisionamiento de Activos Intereses
INSERT INTO MIS_APR_ASSETS 
PARTITION (DATA_DATE='${var:periodo}') 
SELECT 'PREST' AS COD_CONT, CAST(a.DEAACC AS string) AS IDF_CTO, CAST(d.GLMXDR AS STRING) AS COD_GL, NULL AS DES_GL, CAST(a.DEACCN AS string) AS COD_ACCO_CENT, TRIM(a.DEABRN) AS COD_OFFI, 
'1' AS COD_BLCE_STATUS, 'INT' AS COD_VALUE, REGEXP_REPLACE(a.DEACCY, '"', '') AS COD_CURRENCY, REGEXP_REPLACE(a.DEABNK, '"', '') AS COD_ENTITY,
CASE WHEN b.IDF_CTO IS NOT NULL THEN b.COD_PRODUCT 
WHEN a.DEAPRO = 'EXTR' THEN ISNULL(STRLEFT(e.EXTTAR,1),'TAR') ELSE TRIM(a.DEATYP) END AS COD_PRODUCT,
CASE WHEN (c.COD_NEW_SUBPRODUCT IS NOT NULL AND a.DEAPRO <> 'EXTR') THEN CONCAT(TRIM(c.COD_NEW_SUBPRODUCT), IF((TRIM(f.CRETPA) IS NULL OR TRIM(f.CRETPA) = ""), "", "_"), ISNULL(TRIM(f.CRETPA),"")) 
WHEN a.DEAPRO = 'EXTR' THEN ISNULL(CONCAT(STRLEFT(e.EXTTAR,8), '_EXT'), 'EXTR')
ELSE CONCAT(TRIM(a.DEAPRO), IF((TRIM(f.CRETPA) IS NULL OR TRIM(f.CRETPA) = ""), "", "_"), ISNULL(TRIM(f.CRETPA),"")) END AS COD_SUBPRODUCT, IFNULL(CAST(a.DEAICD AS string), '') AS COD_ACT_TYPE, a.DEAMEI AS EOPBAL_CAP,
NULL AS EOPBAL_INT, NULL AS AVGBAL_CAP, NULL AS AVGBAL_INT, NULL AS PL, 'DEALS' AS COD_INFO_SOURCE
FROM MIS_LOAD_DEALS a
LEFT JOIN MIS_PAR_REL_PROD_SPE b 
ON CAST(a.DEAACC AS string) = B.IDF_CTO
LEFT JOIN MIS_PAR_REL_SUBPROD_OPER c
ON REGEXP_REPLACE(a.DEABNK, '"', '') = c.COD_ENTITY AND REGEXP_REPLACE(TRIM(a.DEATYP), '"', '') = c.COD_PRODUCT AND REGEXP_REPLACE(TRIM(a.DEAPRO), '"', '') = c.COD_SUBPRODUCT AND REGEXP_REPLACE(a.DEAICD, '"', '') = C.COD_ACT_TYPE
LEFT JOIN (SELECT * FROM MIS_LOAD_GLMST WHERE GLMCCY = 'USD') d
ON a.DEAGLN = d.GLMGLN  
LEFT JOIN (SELECT EXTACC, MIN(EXTTAR) EXTTAR FROM MIS_LOAD_CSEXTMSTF GROUP BY EXTACC) e
ON CAST(a.DEAACC AS STRING) = e.EXTACC
LEFT JOIN MIS_LOAD_CREMST f
ON CAST(a.DEAACC AS STRING) = f.CREACC
WHERE STRLEFT(CAST(a.DEAGLN AS string),1) <> '9' AND REGEXP_REPLACE(TRIM(a.DEASTS), '"', '') <> 'C'
AND REGEXP_REPLACE(TRIM(CAST(a.DEAACD AS STRING)), '"', '') <> '11'
AND REGEXP_REPLACE(TRIM(a.DEACLF), '"', '') <> 'G'
AND strleft(a.DEAGLN,2) <> '21'
;


----Aprovisionamiento de Activos Resultados
INSERT INTO MIS_APR_ASSETS 
PARTITION (DATA_DATE='${var:periodo}') 
SELECT 'PREST' AS COD_CONT, CAST(a.DEAACC AS string) AS IDF_CTO, CAST(d.GLMXCR AS STRING) AS COD_GL, NULL AS DES_GL, CAST(a.DEACCN AS string) AS COD_ACCO_CENT, TRIM(a.DEABRN) AS COD_OFFI,
'1' AS COD_BLCE_STATUS, 'RSL' AS COD_VALUE, REGEXP_REPLACE(a.DEACCY, '"', '') AS COD_CURRENCY, REGEXP_REPLACE(a.DEABNK, '"', '') AS COD_ENTITY,
CASE WHEN b.IDF_CTO IS NOT NULL THEN b.COD_PRODUCT 
WHEN a.DEAPRO = 'EXTR' THEN ISNULL(STRLEFT(e.EXTTAR,1),'TAR') ELSE TRIM(a.DEATYP) END AS COD_PRODUCT,
CASE WHEN (c.COD_NEW_SUBPRODUCT IS NOT NULL AND a.DEAPRO <> 'EXTR') THEN CONCAT(TRIM(c.COD_NEW_SUBPRODUCT), IF((TRIM(f.CRETPA) IS NULL OR TRIM(f.CRETPA) = ""), "", "_"), ISNULL(TRIM(f.CRETPA),"")) 
WHEN a.DEAPRO = 'EXTR' THEN ISNULL(CONCAT(STRLEFT(e.EXTTAR,8), '_EXT'), 'EXTR')
ELSE CONCAT(TRIM(a.DEAPRO), IF((TRIM(f.CRETPA) IS NULL OR TRIM(f.CRETPA) = ""), "", "_"), ISNULL(TRIM(f.CRETPA),"")) END AS COD_SUBPRODUCT, IFNULL(CAST(a.DEAICD AS string), '') AS COD_ACT_TYPE,
NULL AS EOPBAL_CAP, NULL AS EOPBAL_INT, NULL AS AVGBAL_CAP, NULL AS AVGBAL_INT, CAST(a.DEAINM*-1 AS DECIMAL(30,10)) AS PL, 'DEALS' AS COD_INFO_SOURCE 
FROM MIS_LOAD_DEALS a
LEFT JOIN MIS_PAR_REL_PROD_SPE b 
ON CAST(a.DEAACC AS string) = B.IDF_CTO
LEFT JOIN MIS_PAR_REL_SUBPROD_OPER c
ON REGEXP_REPLACE(a.DEABNK, '"', '') = c.COD_ENTITY AND REGEXP_REPLACE(TRIM(a.DEATYP), '"', '') = c.COD_PRODUCT AND REGEXP_REPLACE(TRIM(a.DEAPRO), '"', '') = c.COD_SUBPRODUCT AND REGEXP_REPLACE(a.DEAICD, '"', '') = C.COD_ACT_TYPE
LEFT JOIN (SELECT * FROM MIS_LOAD_GLMST WHERE GLMCCY = 'USD') d
ON a.DEAGLN = d.GLMGLN  
LEFT JOIN (SELECT EXTACC, MIN(EXTTAR) EXTTAR FROM MIS_LOAD_CSEXTMSTF GROUP BY EXTACC) e
ON CAST(a.DEAACC AS STRING) = e.EXTACC
LEFT JOIN MIS_LOAD_CREMST f
ON CAST(a.DEAACC AS STRING) = f.CREACC
WHERE STRLEFT(CAST(a.DEAGLN AS string),1) <> '9' AND TRIM(a.DEASTS) <> 'C'
AND REGEXP_REPLACE(TRIM(CAST(a.DEAACD AS STRING)), '"', '') <> '11'
AND REGEXP_REPLACE(TRIM(a.DEACLF), '"', '') <> 'G'
AND strleft(a.DEAGLN,2) <> '21'
;

----Aprovisionamiento de Contratos asociados a Activos

ALTER TABLE MIS_APR_CONTRACT_DT
DROP IF EXISTS PARTITION (DATA_DATE = '${var:periodo}', COD_INFO_SOURCE='DEALS');

INSERT INTO MIS_APR_CONTRACT_DT 
PARTITION (DATA_DATE='${var:periodo}', COD_INFO_SOURCE='DEALS') 
SELECT DISTINCT CAST(a.DEAACC AS string) AS IDF_CTO, a.DEABNK AS COD_ENTITY, 
CASE WHEN b.IDF_CTO IS NOT NULL THEN b.COD_PRODUCT 
WHEN a.DEAPRO = 'EXTR' THEN ISNULL(STRLEFT(d.EXTTAR,1),'TAR') ELSE TRIM(a.DEATYP) END AS COD_PRODUCT,
CASE WHEN (c.COD_NEW_SUBPRODUCT IS NOT NULL AND a.DEAPRO <> 'EXTR') THEN CONCAT(TRIM(c.COD_NEW_SUBPRODUCT), IF((TRIM(e.CRETPA) IS NULL OR TRIM(e.CRETPA) = ""), "", "_"), ISNULL(TRIM(e.CRETPA),"")) 
WHEN a.DEAPRO = 'EXTR' THEN ISNULL(CONCAT(STRLEFT(d.EXTTAR,8), '_EXT'), 'EXTR')
ELSE CONCAT(TRIM(a.DEAPRO), IF((TRIM(e.CRETPA) IS NULL OR TRIM(e.CRETPA) = ""), "", "_"), ISNULL(TRIM(e.CRETPA),"")) END AS COD_SUBPRODUCT,
IFNULL(CAST(a.DEAICD AS string), '') AS COD_ACT_TYPE, a.DEACCY AS COD_CURRENCY, CAST(CAST(a.DEACUN AS INT) AS string) AS IDF_CLI,
CAST(a.DEACCN AS string) AS COD_ACCO_CENT, TRIM(a.DEABRN) AS COD_OFFI, NULL AS COD_BCA_INT, NULL AS COD_AMRT_MET, 
CASE WHEN TRIM(a.DEATYP) IN ('ADVI', 'CONS','PTMS','REDA','PGR1') THEN 'A' WHEN TRIM(a.DEAFTB)='01' THEN 'A' WHEN TRIM(a.DEAFTB)='FX' THEN 'F' WHEN TRIM(a.DEAFTB)<>'01' AND TRIM(a.DEARRP) = '999' THEN 'A' ELSE 'V' END AS COD_RATE_TYPE, CAST(((a.DEARTE+a.DEAFRT)/100) AS decimal(30, 10)) AS RATE_INT, 
CONCAT(CASE WHEN CAST(STRRIGHT(CAST(YEAR(NOW()) AS string), 2) AS smallint) < a.DEAODY 
THEN CONCAT('19', LPAD(CAST(a.DEAODY AS string), 2, '0')) ELSE CONCAT('2', LPAD(CAST(a.DEAODY AS string), 3, '0')) END, 
LPAD(CAST(a.DEAODM AS string), 2, '0'), LPAD(CAST(a.DEAODD  AS string), 2, '0')) AS DATE_ORIGIN, 
CASE WHEN a.DEAREY=0 AND a.DEARCM=0 AND a.DEARCO=0 THEN CONCAT(CASE WHEN CAST(STRRIGHT(CAST(YEAR(NOW()) AS string), 2) AS smallint) < a.DEAODY 
THEN CONCAT('19', LPAD(CAST(a.DEAODY AS string), 2, '0')) 
ELSE CONCAT('2', LPAD(CAST(a.DEAODY AS string), 3, '0')) END, 
LPAD(CAST(a.DEAODM AS string), 2, '0'), LPAD(CAST(a.DEAODD  AS string), 2, '0'))
ELSE CONCAT(CASE WHEN CAST(STRRIGHT(CAST(YEAR(NOW()) AS string), 2) AS smallint) < a.DEAREY 
THEN CONCAT('19', LPAD(CAST(a.DEAREY AS string), 2, '0')) 
ELSE CONCAT('2', LPAD(CAST(a.DEAREY AS string), 3, '0')) END, 
LPAD(CAST(a.DEARCM AS string), 2, '0'), LPAD(CAST(a.DEARCO  AS string), 2, '0')) END AS DATE_LAST_REV, 
CASE WHEN a.DEARRY=0 AND a.DEARRM=0 AND a.DEARRD=0 THEN NULL ELSE CONCAT(CONCAT('2', LPAD(CAST(a.DEARRY AS string), 3, '0')), 
LPAD(CAST(a.DEARRM AS string), 2, '0'), LPAD(CAST(a.DEARRD  AS string), 2, '0')) END AS DATE_PRX_REV,
CASE WHEN a.DEAMAY=0 AND a.DEAMAM=0 AND a.DEAMAD=0 THEN NULL ELSE CONCAT(CONCAT('2', LPAD(CAST(a.DEAMAY AS string), 3, '0')), 
LPAD(CAST(a.DEAMAM AS string), 2, '0'), LPAD(CAST(a.DEAMAD  AS string), 2, '0')) END AS EXP_DATE, 
CAST(a.DEAIPD AS BIGINT) AS FREQ_INT_PAY, NULL AS COD_UNI_FREQ_INT_PAY, NULL AS FRE_REV_INT, NULL AS COD_UNI_FRE_REV_INT, NULL AS AMRT_TRM, NULL AS COD_UNI_AMRT_TRM,
a.DEAOAM AS INI_AM, NULL AS CUO_AM, NULL AS CREDIT_LIM_AM, NULL AS PREDEF_RATE_IND, NULL AS PREDEF_RATE, NULL AS IND_CHANNEL, NULL AS COD_TYP_LIC, NULL AS COU_CAR_OFF, NULL AS COD_CONV, NULL AS COD_EXEC_CTO, NULL AS COD_COVID_PORT, NULL AS FIELD1_CTO, NULL AS FIELD2_CTO, NULL AS FIELD3_CTO, NULL AS FIELD4_CTO, NULL AS FIELD5_CTO, NULL AS FIELD6_CTO, NULL AS FIELD7_CTO, NULL AS FIELD8_CTO, NULL AS FIELD9_CTO, NULL AS FIELD10_CTO, CONCAT(CASE WHEN CAST(STRRIGHT(CAST(YEAR(NOW()) AS string), 2) AS smallint) < a.DEAODY 
THEN CONCAT('19', LPAD(CAST(a.DEAODY AS string), 2, '0')) ELSE CONCAT('2', LPAD(CAST(a.DEAODY AS string), 3, '0')) END, 
LPAD(CAST(a.DEAODM AS string), 2, '0'), LPAD(CAST(a.DEAODD  AS string), 2, '0')) AS DATE_DISB, d.EXTTAR AS CARD_NUMBER, NULL AS COD_PROG_CARD, NULL AS DES_PROG_CARD
FROM MIS_LOAD_DEALS a
LEFT JOIN MIS_PAR_REL_PROD_SPE b 
ON CAST(a.DEAACC AS string) = B.IDF_CTO
LEFT JOIN MIS_PAR_REL_SUBPROD_OPER c
ON REGEXP_REPLACE(a.DEABNK, '"', '') = c.COD_ENTITY AND REGEXP_REPLACE(TRIM(a.DEATYP), '"', '') = c.COD_PRODUCT AND REGEXP_REPLACE(TRIM(a.DEAPRO), '"', '') = c.COD_SUBPRODUCT AND REGEXP_REPLACE(a.DEAICD, '"', '') = C.COD_ACT_TYPE
LEFT JOIN (SELECT EXTACC, MIN(EXTTAR) EXTTAR FROM MIS_LOAD_CSEXTMSTF GROUP BY EXTACC) d
ON CAST(a.DEAACC AS STRING) = d.EXTACC
LEFT JOIN MIS_LOAD_CREMST e
ON CAST(a.DEAACC AS STRING) = e.CREACC
WHERE REGEXP_REPLACE(TRIM(a.DEASTS), '"', '') <> 'C'
AND REGEXP_REPLACE(TRIM(CAST(a.DEAACD AS STRING)), '"', '') <> '11'
AND REGEXP_REPLACE(TRIM(a.DEACLF), '"', '') <> 'G'
AND strleft(a.DEAGLN,2) <> '21'
;

----Aprovisionamiento de Activos Capital Tarjetas
INSERT INTO MIS_APR_ASSETS 
PARTITION (DATA_DATE='${var:periodo}') 
SELECT 'PREST' AS COD_CONT, REGEXP_REPLACE(CAST(CAST(a.CUE003 AS BIGINT) AS string), '"', '') AS IDF_CTO, NULL AS COD_GL, NULL AS DES_GL, NULL AS COD_ACCO_CENT, NULL AS COD_OFFI, 
CASE WHEN a.CUE075 < 91 THEN 'VIG' ELSE 'VEN' END AS COD_BLCE_STATUS, 'CAP' AS COD_VALUE, 'USD' AS COD_CURRENCY, '01' AS COD_ENTITY, CASE WHEN b.IDF_CTO IS NOT NULL 
THEN b.COD_PRODUCT ELSE SUBSTR(REGEXP_REPLACE(CAST(a.CUE003 AS string), '"', ''),4,1) END AS COD_PRODUCT, SUBSTR(REGEXP_REPLACE(CAST(a.CUE003 AS string), '"', ''),4,8) AS COD_SUBPRODUCT, NULL AS COD_ACT_TYPE,
CAST(IFNULL(c.PLN040 - c.PLN020,0) AS DECIMAL(30,10)) AS EOPBAL_CAP, NULL AS EOPBAL_INT, NULL AS AVGBAL_CAP, NULL AS AVGBAL_INT, NULL AS PL, 'VPSCUENT' AS COD_INFO_SOURCE 
FROM MIS_LOAD_VPSCUENT a
LEFT JOIN MIS_PAR_REL_PROD_SPE b 
ON REGEXP_REPLACE(CAST(a.CUE003 AS string), '"', '') = b.IDF_CTO
LEFT JOIN (SELECT PLN002, CAST(SUM(PLN040) AS DECIMAL(30,10)) AS PLN040, CAST(SUM(PLN020) AS DECIMAL(30,10)) AS PLN020 FROM MIS_LOAD_VPSPLAN GROUP BY PLN002) c
ON REGEXP_REPLACE(CAST(a.CUE003 AS string), '"', '') = REGEXP_REPLACE(CAST(c.PLN002 AS string), '"', '')
WHERE REGEXP_REPLACE(CAST(a.CUE005 AS string), '"', '') IN ('A','D')
;

--- Aprovisionamiento de Capital Intrafinanciamiento ---
INSERT INTO MIS_APR_ASSETS 
PARTITION (DATA_DATE='${var:periodo}') 
SELECT 'PREST' AS COD_CONT,
CAST(TRIM(INTNCUE) AS STRING) AS IDF_CTO, 
'1141040101030516' AS COD_GL, NULL AS DES_GL,
NULL AS COD_ACCO_CENT, NULL AS COD_OFFI, 
'VIG' AS COD_BLCE_STATUS, 'CAP' AS COD_VALUE, 'USD' AS COD_CURRENCY,
'01' AS COD_ENTITY, CASE WHEN b.IDF_CTO IS NOT NULL 
THEN b.COD_PRODUCT ELSE SUBSTR(CAST(a.INTNCUE1 AS string),4,1) END AS COD_PRODUCT, 
CONCAT(SUBSTR(CAST(a.INTNCUE1 AS string),4,8), '_INT') AS COD_SUBPRODUCT, 
NULL AS COD_ACT_TYPE,
CAST(a.MONCUO AS DECIMAL(30,10)) AS EOPBAL_CAP, NULL AS EOPBAL_INT, NULL AS AVGBAL_CAP, 
NULL AS AVGBAL_INT, 
NULL AS PL, 'CSPLNINTF' AS COD_INFO_SOURCE 
FROM (SELECT CONCAT(LPAD(INTTRDT,6,'0'), LPAD(INTTRHO,8,'0'), LPAD(INTNCUO,2,'0'), LPAD(INTREFES,5,'0'), CAST(CAST(INTNCUE AS BIGINT) AS STRING), LPAD(INTHOSA,8,'0')) AS INTNCUE, INTNCUE AS INTNCUE1, SUM(MONCUO) MONCUO 
FROM MIS_LOAD_CSPLNINTF WHERE INTSTS <> 'P' 
GROUP BY INTNCUE1, CONCAT(LPAD(INTTRDT,6,'0'), LPAD(INTTRHO,8,'0'), LPAD(INTNCUO,2,'0'), LPAD(INTREFES,5,'0'), CAST(CAST(INTNCUE AS BIGINT) AS STRING), LPAD(INTHOSA,8,'0'))) a
LEFT JOIN MIS_PAR_REL_PROD_SPE b 
ON CAST(a.INTNCUE AS string) = B.IDF_CTO
INNER JOIN (SELECT * FROM MIS_LOAD_VPSCUENT WHERE REGEXP_REPLACE(CAST(CUE005 AS string), '"', '') IN ('A','D')) vps
ON CAST(a.INTNCUE1 AS BIGINT) = CAST(vps.CUE003 AS BIGINT)
WHERE CAST(TRIM(INTNCUE) AS STRING) <> '2204030000010060000100000000';

----Aprovisionamiento de Activos Intereses Tarjetas
INSERT INTO MIS_APR_ASSETS 
PARTITION (DATA_DATE='${var:periodo}') 
SELECT 'PREST' AS COD_CONT, REGEXP_REPLACE(CAST(CAST(a.CUE003 AS BIGINT) AS string), '"', '') AS IDF_CTO, NULL AS COD_GL, NULL AS DES_GL, NULL AS COD_ACCO_CENT, NULL AS COD_OFFI, 
CASE WHEN a.CUE075 < 91 THEN 'VIG' ELSE 'VEN' END AS COD_BLCE_STATUS, 'INT' AS COD_VALUE, 'USD' AS COD_CURRENCY, '01' AS COD_ENTITY, CASE WHEN b.IDF_CTO IS NOT NULL 
THEN b.COD_PRODUCT ELSE SUBSTR(REGEXP_REPLACE(CAST(a.CUE003 AS string), '"', ''),4,1) END AS COD_PRODUCT,  SUBSTR(REGEXP_REPLACE(CAST(a.CUE003 AS string), '"', ''),4,8) AS COD_SUBPRODUCT, NULL AS COD_ACT_TYPE,
IFNULL(c.PLN020,0) AS EOPBAL_CAP, NULL AS EOPBAL_INT, NULL AS AVGBAL_CAP, NULL AS AVGBAL_INT, NULL AS PL, 'VPSCUENT' AS COD_INFO_SOURCE 
FROM MIS_LOAD_VPSCUENT a
LEFT JOIN MIS_PAR_REL_PROD_SPE b 
ON REGEXP_REPLACE(CAST(a.CUE003 AS string), '"', '') = b.IDF_CTO
LEFT JOIN (SELECT PLN002, CAST(SUM(PLN040) AS DECIMAL(30,10)) AS PLN040, CAST(SUM(PLN020) AS DECIMAL(30,10)) AS PLN020 FROM MIS_LOAD_VPSPLAN GROUP BY PLN002) c
ON REGEXP_REPLACE(CAST(a.CUE003 AS string), '"', '') = REGEXP_REPLACE(CAST(c.PLN002 AS string), '"', '')
WHERE REGEXP_REPLACE(CAST(a.CUE005 AS string), '"', '') IN ('A','D')
;

/*----Aprovisionamiento de Activos Resultado (P&G) Tarjetas
INSERT INTO MIS_APR_ASSETS 
PARTITION (DATA_DATE='${var:periodo}') 
SELECT 'PREST' AS COD_CONT, CAST(a.CSD_TAR AS string) AS IDF_CTO, NULL AS COD_GL, NULL AS DES_GL, NULL AS COD_ACCO_CENT, NULL AS COD_OFFI, 
CASE WHEN a.CUE075 < 91 THEN 'VIG' ELSE 'VEN' END AS COD_BLCE_STATUS, 'RSL' AS COD_VALUE, 'USD' AS COD_CURRENCY, '01' AS COD_ENTITY, CASE WHEN b.IDF_CTO IS NOT NULL 
THEN b.COD_PRODUCT ELSE SUBSTR(REGEXP_REPLACE(CAST(a.CUE003 AS string), '"', ''),4,1) END AS COD_PRODUCT,  SUBSTR(REGEXP_REPLACE(CAST(a.CUE003 AS string), '"', ''),4,8) AS COD_SUBPRODUCT, NULL AS COD_ACT_TYPE,
IFNULL(c.PLN020,0) AS EOPBAL_CAP, NULL AS EOPBAL_INT, NULL AS AVGBAL_CAP, NULL AS AVGBAL_INT, NULL AS PL, 'VPSCUENT' AS COD_INFO_SOURCE 
FROM MIS_LOAD_CSD533GLF a
LEFT JOIN MIS_PAR_REL_PROD_SPE b 
ON REGEXP_REPLACE(CAST(a.CUE003 AS string), '"', '') = b.IDF_CTO
LEFT JOIN (SELECT PLN002, CAST(SUM(PLN040) AS DECIMAL(30,10)) AS PLN040, CAST(SUM(PLN020) AS DECIMAL(30,10)) AS PLN020 FROM MIS_LOAD_VPSPLAN GROUP BY PLN002) c
ON REGEXP_REPLACE(CAST(a.CUE003 AS string), '"', '') = REGEXP_REPLACE(CAST(c.PLN002 AS string), '"', '')
WHERE REGEXP_REPLACE(CAST(a.CUE005 AS string), '"', '') <> 'Z'
;*/

----Aprovisionamiento de Contratos asociados a Tarjetas

ALTER TABLE MIS_APR_CONTRACT_DT
DROP IF EXISTS PARTITION (DATA_DATE = '${var:periodo}', COD_INFO_SOURCE='VPSCUENT');

INSERT INTO MIS_APR_CONTRACT_DT 
PARTITION (DATA_DATE='${var:periodo}', COD_INFO_SOURCE='VPSCUENT') 
SELECT DISTINCT CAST(CAST(a.CUE003 AS BIGINT) AS string) AS IDF_CTO, '01' AS COD_ENTITY, 
CASE WHEN b.IDF_CTO IS NOT NULL 
THEN b.COD_PRODUCT ELSE SUBSTR(CAST(a.CUE003 AS string),4,1) END AS COD_PRODUCT,  SUBSTR(CAST(a.CUE003 AS string),4,8) AS COD_SUBPRODUCT, NULL AS COD_ACT_TYPE, 'USD' AS COD_CURRENCY, 
CAST(CAST(STRLEFT(REGEXP_REPLACE(CAST(a.CUE006 AS string), '"', ''),15) AS INT) AS STRING) AS IDF_CLI,
NULL AS COD_ACCO_CENT, CAST(a.CUE031 AS STRING) AS COD_OFFI, NULL AS COD_BCA_INT, NULL AS COD_AMRT_MET, 
'A' AS COD_RATE_TYPE, NULL AS RATE_INT, 
FROM_TIMESTAMP(CAST(a.CUE050 AS string), 'yyyyMMdd') AS DATE_ORIGIN, 
NULL DATE_LAST_REV, NULL AS DATE_PRX_REV, NULL AS EXP_DATE, NULL AS FREQ_INT_PAY, NULL AS COD_UNI_FREQ_INT_PAY, NULL AS FRE_REV_INT, NULL AS COD_UNI_FRE_REV_INT, NULL AS AMRT_TRM,
NULL AS COD_UNI_AMRT_TRM, NULL AS INI_AM, NULL AS CUO_AM, a.CUE094 AS CREDIT_LIM_AM, NULL AS PREDEF_RATE_IND, NULL AS PREDEF_RATE, NULL AS IND_CHANNEL, NULL AS COD_TYP_LIC, NULL AS COU_CAR_OFF, NULL AS COD_CONV, NULL AS COD_EXEC_CTO, NULL AS COD_COVID_PORT, NULL AS FIELD1_CTO, NULL AS FIELD2_CTO, NULL AS FIELD3_CTO, NULL AS FIELD4_CTO, NULL AS FIELD5_CTO, NULL AS FIELD6_CTO, NULL AS FIELD7_CTO, NULL AS FIELD8_CTO, NULL AS FIELD9_CTO, NULL AS FIELD10_CTO, FROM_TIMESTAMP(CAST(a.CUE050 AS string), 'yyyyMMdd') AS DATE_DISB, CAST(CAST(ISNULL(pla.NUMTARJETA,a.CUE003) AS BIGINT) AS STRING) AS CARD_NUMBER, CASE WHEN CUE002 = 5 AND CUE012 = '007' THEN NULL ELSE CAST(CUE002 AS STRING) END AS COD_PROG_CARD, CASE WHEN CUE002 = 5 AND CUE012 = '007' THEN NULL ELSE 'DAVIPUNTOS' END AS DES_PROG_CARD
FROM MIS_LOAD_VPSCUENT a
LEFT JOIN MIS_PAR_REL_PROD_SPE b 
ON CAST(a.CUE003 AS string) = b.IDF_CTO
LEFT JOIN (SELECT NUMCUENTA, MAX(NUMTARJETA) AS NUMTARJETA FROM MIS_LOAD_VPSPLAST
WHERE CARDHOLDER_TYPE = '1' AND TRIM(CODBLOQUE) IN ('','T','S') GROUP BY NUMCUENTA) pla
ON a.CUE003 = pla.NUMCUENTA
WHERE REGEXP_REPLACE(CAST(a.CUE005 AS string), '"', '') IN ('A','D');

/*
INSERT INTO MIS_APR_CONTRACT_DT 
PARTITION (DATA_DATE='${var:periodo}', COD_INFO_SOURCE='VPSCUENT') 
SELECT DISTINCT CAST(CAST(a.CUE003 AS BIGINT) AS string) AS IDF_CTO, '01' AS COD_ENTITY, 
CASE WHEN b.IDF_CTO IS NOT NULL 
THEN b.COD_PRODUCT ELSE SUBSTR(CAST(a.CUE003 AS string),4,1) END AS COD_PRODUCT,  SUBSTR(CAST(a.CUE003 AS string),4,8) AS COD_SUBPRODUCT, NULL AS COD_ACT_TYPE, 'USD' AS COD_CURRENCY, 
CAST(CAST(STRLEFT(REGEXP_REPLACE(CAST(a.CUE006 AS string), '"', ''),15) AS INT) AS STRING) AS IDF_CLI,
NULL AS COD_ACCO_CENT, CAST(a.CUE031 AS STRING) AS COD_OFFI, NULL AS COD_BCA_INT, NULL AS COD_AMRT_MET, 
'A' AS COD_RATE_TYPE, NULL AS RATE_INT, 
FROM_TIMESTAMP(CAST(a.CUE050 AS string), 'yyyyMMdd') AS DATE_ORIGIN, 
NULL DATE_LAST_REV, NULL AS DATE_PRX_REV, NULL AS EXP_DATE, NULL AS FREQ_INT_PAY, NULL AS COD_UNI_FREQ_INT_PAY, NULL AS FRE_REV_INT, NULL AS COD_UNI_FRE_REV_INT, NULL AS AMRT_TRM,
NULL AS COD_UNI_AMRT_TRM, NULL AS INI_AM, NULL AS CUO_AM, a.CUE094 AS CREDIT_LIM_AM, NULL AS PREDEF_RATE_IND, NULL AS PREDEF_RATE, NULL AS IND_CHANNEL, NULL AS COD_TYP_LIC, NULL AS COU_CAR_OFF, NULL AS COD_CONV, NULL AS COD_EXEC_CTO, NULL AS COD_COVID_PORT, NULL AS FIELD1_CTO, NULL AS FIELD2_CTO, NULL AS FIELD3_CTO, NULL AS FIELD4_CTO, NULL AS FIELD5_CTO, NULL AS FIELD6_CTO, NULL AS FIELD7_CTO, NULL AS FIELD8_CTO, NULL AS FIELD9_CTO, NULL AS FIELD10_CTO, FROM_TIMESTAMP(CAST(a.CUE050 AS string), 'yyyyMMdd') AS DATE_DISB, CAST(CAST(ISNULL(pla.NUMTARJETA,a.CUE003) AS BIGINT) AS STRING) AS CARD_NUMBER, CASE WHEN CUE002 = 5 AND CUE012 = '007' THEN NULL ELSE CAST(CUE002 AS STRING) END AS COD_PROG_CARD, CASE WHEN CUE002 = 5 AND CUE012 = '007' THEN NULL ELSE 'DAVIPUNTOS' END AS DES_PROG_CARD
FROM MIS_LOAD_VPSCUENT a
LEFT JOIN MIS_PAR_REL_PROD_SPE b 
ON CAST(a.CUE003 AS string) = b.IDF_CTO

INNER JOIN (SELECT NUMCUENTA, MAX(NUMTARJETA) AS NUMTARJETA FROM MIS_LOAD_VPSPLAST a2
           LEFT JOIN(
                     SELECT *
                     FROM MIS_LOAD_VPSCUENT a3
                     LEFT JOIN (SELECT NUMCUENTA, MAX(NUMTARJETA) AS NUMTARJETA FROM MIS_LOAD_VPSPLAST
                     WHERE CARDHOLDER_TYPE = '1' AND TRIM(CODBLOQUE) IN ('','T','S') GROUP BY NUMCUENTA) pla3
                     ON a3.CUE003 = pla3.NUMCUENTA
                     WHERE REGEXP_REPLACE(CAST(a3.CUE005 AS string), '"', '') IN ('A','D') AND pla3.NUMCUENTA IS NOT NULL
                     ) pla2
           ON pla2.CUE003 = a2.NUMCUENTA
           WHERE CARDHOLDER_TYPE = '0' AND TRIM(CODBLOQUE) IN ('','T','S') GROUP BY NUMCUENTA) pla
ON a.CUE003 = pla.NUMCUENTA

WHERE REGEXP_REPLACE(CAST(a.CUE005 AS string), '"', '') IN ('A','D') AND REGEXP_REPLACE(CAST(a.CUE017 AS string), '"', '') IN ('','S','T') AND REGEXP_REPLACE(CAST(a.CUE018 AS string), '"', '') IN ('','A','B','C');
*/

--- Aprovisionamiento de Capital de Sobregiros ---
INSERT INTO MIS_APR_ASSETS 
PARTITION (DATA_DATE='${var:periodo}') 
SELECT 'PREST' AS COD_CONT, CAST(a.SOBACC AS string) AS IDF_CTO, CAST(a.SOBGLN AS string) AS COD_GL, NULL AS DES_GL,
NULL AS COD_ACCO_CENT, NULL AS COD_OFFI, 
CASE WHEN STRLEFT(a.SOBGLN,4) IN ('1141','1142') THEN 'VIG' WHEN STRLEFT(a.SOBGLN,4) IN ('1148') THEN 'VEN' ELSE '1' END AS COD_BLCE_STATUS, 'CAP' AS COD_VALUE, 'USD' AS COD_CURRENCY,
 '01' AS COD_ENTITY, CASE WHEN b.IDF_CTO IS NOT NULL 
THEN b.COD_PRODUCT ELSE 'SOB' END AS COD_PRODUCT, 
'SOB' AS COD_SUBPRODUCT, 
c.ACMIND AS COD_ACT_TYPE,
a.SOBGBL AS EOPBAL_CAP, NULL AS EOPBAL_INT, NULL AS AVGBAL_CAP, NULL AS AVGBAL_INT, 
NULL AS PL, 'SOBDT' AS COD_INFO_SOURCE 
FROM MIS_LOAD_SOBDT a
LEFT JOIN MIS_PAR_REL_PROD_SPE b 
ON CAST(a.SOBACC AS string) = B.IDF_CTO
LEFT JOIN MIS_LOAD_ACMST c
ON CAST(a.SOBACC AS string) = CAST(c.ACMACC AS string);

/*
--- Aprovisionamiento de Intereses de Sobregiros ---
INSERT INTO MIS_APR_ASSETS 
PARTITION (DATA_DATE='${var:periodo}')
SELECT 'PREST' AS COD_CONT, CAST(a.DLAACC AS string) AS IDF_CTO, CAST(a.DLAGLN AS string) AS COD_GL, NULL AS DES_GL,
NULL AS COD_ACCO_CENT, NULL AS COD_OFFI, 
'1' AS COD_BLCE_STATUS, 'RSL' AS COD_VALUE, 'USD' AS COD_CURRENCY,
 '01' AS COD_ENTITY, CASE WHEN b.IDF_CTO IS NOT NULL 
THEN b.COD_PRODUCT ELSE 'SOB' END AS COD_PRODUCT, 
'SOB' AS COD_SUBPRODUCT, 
ac.ACMIND AS COD_ACT_TYPE,
NULL AS EOPBAL_CAP, NULL AS EOPBAL_INT, NULL AS AVGBAL_CAP, NULL AS AVGBAL_INT, 
CAST(CASE WHEN a.DLADCC = 'D' THEN  a.DLAAMT ELSE -1 * a.DLAAMT END + ISNULL(c.PL,0) AS DECIMAL(30,10)) AS PL, 'DLAHI' AS COD_INFO_SOURCE 
FROM MIS_LOAD_DLAHI a
LEFT JOIN MIS_PAR_REL_PROD_SPE b 
ON CAST(a.DLAACC AS string) = B.IDF_CTO
LEFT JOIN (SELECT * FROM MIS_APR_ASSETS WHERE STRLEFT(DATA_DATE,6) = STRLEFT('${var:periodo}',6) AND TO_TIMESTAMP(DATA_DATE,'yyyyMMdd') = DATE_SUB(TO_TIMESTAMP('${var:periodo}','yyyyMMdd'), 1) AND COD_INFO_SOURCE = 'DLAHI' AND COD_SUBPRODUCT = 'SOB' AND COD_VALUE = 'RSL') c
ON a.DLAGLN = c.COD_GL AND a.DLAACC = c.IDF_CTO
LEFT JOIN MIS_LOAD_ACMST ac
ON a.DLAACC = ac.ACMACC
WHERE a.DLATCD LIKE '%C%'
AND CONCAT(CONCAT('2', LPAD(CAST(a.DLABYY AS string), 3, '0')), LPAD(CAST(a.DLABMM AS string), 2, '0')) = STRLEFT('${var:periodo}',6)
AND STRLEFT(a.DLAGLN,1) IN ('1')
;
*/

--- Aprovisionamiento de Intereses de Sobregiros cuenta 6110010100140000---
INSERT INTO MIS_APR_ASSETS
PARTITION (DATA_DATE='${var:periodo}')
SELECT 'PREST' AS COD_CONT, CAST(a.DLAACC AS string) AS IDF_CTO, CAST(a.DLAGLN AS string) AS COD_GL, NULL AS DES_GL,
NULL AS COD_ACCO_CENT, NULL AS COD_OFFI, 
'1' AS COD_BLCE_STATUS, 'RSL' AS COD_VALUE, 'USD' AS COD_CURRENCY,
 '01' AS COD_ENTITY, CASE WHEN b.IDF_CTO IS NOT NULL 
THEN b.COD_PRODUCT ELSE 'SOB' END AS COD_PRODUCT, 
'SOB' AS COD_SUBPRODUCT, 
ac.ACMIND AS COD_ACT_TYPE,
NULL AS EOPBAL_CAP, NULL AS EOPBAL_INT, NULL AS AVGBAL_CAP, NULL AS AVGBAL_INT, 
CAST(CASE WHEN a.DLADCC = 'D' THEN a.DLAAMT ELSE -1 * a.DLAAMT END + ISNULL(c.PL,0) AS DECIMAL(30,10)) AS PL, 'DLAHI' AS COD_INFO_SOURCE 
FROM MIS_LOAD_DLAHI a
INNER JOIN (SELECT * FROM MIS_APR_ASSETS WHERE data_date = '${var:periodo}' AND cod_value = 'CAP' and strleft(cod_gl,4) <> '1148') b
on a.dlaacc = b.idf_cto
LEFT JOIN (SELECT * FROM MIS_APR_ASSETS 
WHERE STRLEFT(DATA_DATE,6) = STRLEFT('${var:periodo}',6) AND TO_TIMESTAMP(DATA_DATE,'yyyyMMdd') = DATE_SUB(TO_TIMESTAMP('${var:periodo}','yyyyMMdd'), 1)
AND COD_INFO_SOURCE = 'DLAHI' AND cod_gl = '6110010100140000' AND COD_VALUE = 'RSL') c
ON a.DLAGLN = c.COD_GL AND a.DLAACC = c.IDF_CTO
LEFT JOIN MIS_LOAD_ACMST ac
ON a.DLAACC = ac.ACMACC
WHERE DLATCD LIKE 'OA' AND DLAGLN IN ('6110010100140000') AND DLABYY = SUBSTRING('${var:periodo}', 3, 2) AND LPAD(DLABMM,2,'0') = SUBSTRING('${var:periodo}', 5, 2) 
AND LPAD(DLABDD,2,'0') = SUBSTRING('${var:periodo}', 7, 2)
;

--- Aprovisionamiento de Intereses de Sobregiros cuenta 6110010100140000 que no vienen el día actual para acumular ---
INSERT INTO MIS_APR_ASSETS
PARTITION (DATA_DATE='${var:periodo}')
SELECT 'PREST' AS COD_CONT, a.IDF_CTO, a.COD_GL, a.DES_GL, a.COD_ACCO_CENT, a.COD_OFFI, 
a.COD_BLCE_STATUS, 'RSL' AS COD_VALUE, a.COD_CURRENCY, a.COD_ENTITY, a.COD_PRODUCT, a.COD_SUBPRODUCT, 
a.COD_ACT_TYPE, NULL AS EOPBAL_CAP, NULL AS EOPBAL_INT, NULL AS AVGBAL_CAP, NULL AS AVGBAL_INT, 
a.PL, a.COD_INFO_SOURCE
FROM MIS_APR_ASSETS a
LEFT JOIN (SELECT * FROM MIS_APR_ASSETS WHERE DATA_DATE = '${var:periodo}' AND COD_VALUE = 'RSL' AND COD_GL = '6110010100140000') b 
on a.IDF_CTO = b.IDF_CTO
WHERE RIGHT('${var:periodo}',2) <> '01' AND TO_TIMESTAMP(a.DATA_DATE, 'yyyyMMdd') = DATE_SUB(TO_TIMESTAMP('${var:periodo}','yyyyMMdd'), 1) 
AND a.COD_VALUE = 'RSL' AND a.COD_GL = '6110010100140000' AND b.IDF_CTO is null
;

--- Aprovisionamiento de Intereses de Mora Cartera ---
INSERT INTO MIS_APR_ASSETS 
PARTITION (DATA_DATE='${var:periodo}') 
SELECT 'PREST' AS COD_CONT, CAST(a.DLAACC AS string) AS IDF_CTO, CAST(a.DLAGLN AS string) AS COD_GL, NULL AS DES_GL,
NULL AS COD_ACCO_CENT, NULL AS COD_OFFI, 
'1' AS COD_BLCE_STATUS, 'RSL' AS COD_VALUE, CAST(a.DLACCY AS string) AS COD_CURRENCY,
CAST(a.DLABNK AS string) AS COD_ENTITY, 
CASE WHEN b.IDF_CTO IS NOT NULL 
THEN b.COD_PRODUCT ELSE TRIM(f.DEATYP) END AS COD_PRODUCT, 
CONCAT(CAST (a.DLAPRO AS string),'_', CAST(e.CRETPA AS STRING)) AS COD_SUBPRODUCT, 
TRIM(f.DEAICD) AS COD_ACT_TYPE,
NULL AS EOPBAL_CAP, NULL AS EOPBAL_INT, NULL AS AVGBAL_CAP, NULL AS AVGBAL_INT, 
CAST(SUM(CASE WHEN DLADCC = 'D' THEN -1 * DLAAMT ELSE DLAAMT END + ISNULL(c.PL,0)) AS DECIMAL(30,10)) AS PL, 'DLAHI' AS COD_INFO_SOURCE 
FROM MIS_LOAD_DLAHI a
LEFT JOIN MIS_PAR_REL_PROD_SPE b 
ON CAST(a.DLAACC AS string) = B.IDF_CTO
LEFT JOIN (SELECT * FROM MIS_APR_ASSETS WHERE STRLEFT(DATA_DATE,6) = STRLEFT('${var:periodo}',6) AND TO_TIMESTAMP(DATA_DATE,'yyyyMMdd') = DATE_SUB(TO_TIMESTAMP('${var:periodo}','yyyyMMdd'), 1) AND COD_INFO_SOURCE = 'DLAHI' AND COD_SUBPRODUCT <> 'SOB' AND COD_VALUE = 'RSL') c
ON a.DLAGLN = c.COD_GL AND a.DLAPRO = c.COD_SUBPRODUCT AND a.DLAACC = c.IDF_CTO
LEFT JOIN MIS_LOAD_CREMST e
ON CAST(a.DLAACC AS STRING) = e.CREACC
LEFT JOIN MIS_LOAD_DEALS f
ON CAST(f.DEAACC AS string) = CAST(a.DLAACC AS string)
WHERE a.DLAAPC = 'L' 
AND CONCAT(CONCAT('2', LPAD(CAST(a.DLABYY AS string), 3, '0')), LPAD(CAST(a.DLABMM AS string), 2, '0')) = STRLEFT('${var:periodo}',6)
AND a.DLAGLN IN ('6110010100111000','6110010100120001')
GROUP BY a.DLAACC, a.DLAGLN, a.DLACCY, a.DLABNK, CASE WHEN b.IDF_CTO IS NOT NULL THEN b.COD_PRODUCT ELSE TRIM(f.DEATYP) END, 
a.DLAPRO, e.CRETPA, f.DEAICD;


--- Aprovisionamiento Tarjetas Intrafinanciamiento 

INSERT INTO MIS_APR_CONTRACT_DT
PARTITION (DATA_DATE,COD_INFO_SOURCE) 
SELECT CONCAT(LPAD(INTTRDT,6,'0'), LPAD(INTTRHO,8,'0'), LPAD(INTNCUO,2,'0'), LPAD(INTREFES,5,'0'), CAST(CAST(INTNCUE AS BIGINT) AS STRING), LPAD(INTHOSA,8,'0')) as IDF_CTO, b.cod_entity,
SUBSTR(CAST(a.INTNCUE AS string),4,1) AS COD_PRODUCT, CONCAT(SUBSTR(CAST(a.INTNCUE AS string),4,8), '_INT') AS COD_SUBPRODUCT,
b.cod_act_type, b.cod_currency, b.idf_cli, b.cod_acco_cent, b.cod_offi, b.cod_bca_int, b.cod_amrt_met, b.cod_rate_type, b.rate_int,
concat('20',inttrdt) as date_origin, b.date_last_rev, b.date_prx_rev, b.exp_date, b.freq_int_pay, b.cod_uni_freq_int_pay, b.fre_rev_int, b.cod_uni_fre_rev_int,
b.amrt_trm, b.cod_uni_amrt_trm, b.ini_am, b.cuo_am, b.credit_lim_am, b.predef_rate_ind, b.predef_rate, b.ind_channel, b.cod_typ_lic,
b.cou_car_off, b.cod_conv, b.cod_exec_cto,b.cod_covid_port,b.field1_cto,b.field2_cto,b.field3_cto,b.field4_cto,b.field5_cto,
b.field6_cto,b.field7_cto,b.field8_cto,b.field9_cto,b.field10_cto,concat('20',inttrdt) as date_disb,cast(cast(a.INTNTAR as BIGINT) AS STRING) as card_number,cod_prog_card,des_prog_card,data_date,cod_info_source
FROM mis_apr_contract_dt b
INNER JOIN (select distinct INTNCUE, INTTRDT, INTTRHO, INTNCUO, INTREFES, INTHOSA, INTNTAR from MIS_LOAD_CSPLNINTF WHERE INTSTS <> 'P') a
ON b.idf_cto = CAST(CAST(a.INTNCUE as BIGINT) AS STRING)
WHERE data_date='${var:periodo}';

/*SELECT DLABDD, DLAGLN, DLATCD, DLAAPC, SUM(CASE WHEN DLADCC = 'D' THEN DLAAMT ELSE -1*DLAAMT END) SUMA, COUNT(*) 
FROM SV_PROT_MIS.MIS_LOAD_DLAHI
LEFT JOIN (SELECT IDF_CTO, STRLEFT(COD_GL,4) CUENTA FROM MIS_APR_ASSETS WHERE DATA_DATE = '20210630' AND COD_vALUE = 'CAP') B
ON MIS_LOAD_DLAHI.DLAACC = B.IDF_CTO 
WHERE DLATCD LIKE 'OA' 
--AND DLABDD = ('29') 
--AND DLABMM = '3' 
AND DLAGLN IN ('6110010100140000')
AND B.CUENTA IN ('1141','1142')
GROUP BY DLABDD, DLAGLN, DLATCD, DLAAPC order by DLAGLN;*/