--------------------------------------------------------------- MIS_APR_OFF_BALANCE ---------------------------------------------------------------

--- Comando que apunta a la base de datos apropiada ---
USE ${var:base_datos};
SET DECIMAL_V2=FALSE;

----Carga de tablas load
TRUNCATE TABLE IF EXISTS MIS_LOAD_LCMST; 
LOAD DATA INPATH '${var:ruta_fuentes_contingencias}/LCMST.CSV' INTO TABLE MIS_LOAD_LCMST;

ALTER TABLE MIS_APR_OFF_BALANCE
DROP IF EXISTS PARTITION (DATA_DATE = '${var:periodo}');

----Aprovisionamiento de Contingentes Capital
INSERT INTO MIS_APR_OFF_BALANCE
PARTITION (DATA_DATE='${var:periodo}') 
SELECT 'CTG' AS COD_CONT, CAST(a.LCMACC AS string) AS IDF_CTO, CAST(a.LCMGLN AS string) AS COD_GL, NULL AS DES_GL,
CAST(a.LCMCCN AS string) AS COD_ACCO_CENT, TRIM(a.LCMBRN) AS COD_OFFI, 
'1' AS COD_BLCE_STATUS, 'CAP' AS COD_VALUE, a.LCMCCY AS COD_CURRENCY,
 a.LCMBNK AS COD_ENTITY, CASE WHEN b.IDF_CTO IS NOT NULL 
THEN b.COD_PRODUCT ELSE TRIM(a.LCMATY) END AS COD_PRODUCT, 
TRIM(a.LCMPRO) AS COD_SUBPRODUCT, 
TRIM(LCMIND) AS COD_ACT_TYPE,
CAST(a.LCMAMN AS DECIMAL(30,10)) AS EOPBAL_CAP, NULL AS EOPBAL_INT, NULL AS AVGBAL_CAP, NULL AS AVGBAL_INT, 
NULL AS PL, 'LCMST' AS COD_INFO_SOURCE 
FROM MIS_LOAD_LCMST a
LEFT JOIN MIS_PAR_REL_PROD_SPE b 
ON CAST(a.LCMACC AS string) = B.IDF_CTO
WHERE a.LCMSTS <> 'C'
AND a.LCMCCY = 'USD'
;

----Aprovisionamiento de Contingentes Capital DEALS
INSERT INTO MIS_APR_OFF_BALANCE 
PARTITION (DATA_DATE='${var:periodo}') 
SELECT 'CTG' AS COD_CONT, CAST(a.DEAACC AS string) AS IDF_CTO, CAST(a.DEAGLN AS string) AS COD_GL, NULL AS DES_GL,
CAST(a.DEACCN AS string) AS COD_ACCO_CENT, TRIM(a.DEABRN) AS COD_OFFI, 
'1' AS COD_BLCE_STATUS, 'CAP' AS COD_VALUE, a.DEACCY AS COD_CURRENCY,
 a.DEABNK AS COD_ENTITY, CASE WHEN b.IDF_CTO IS NOT NULL THEN b.COD_PRODUCT 
WHEN a.DEAPRO = 'EXTR' THEN ISNULL(STRLEFT(d.EXTTAR,1),'TAR') ELSE TRIM(a.DEATYP) END AS COD_PRODUCT,
CASE WHEN (c.COD_NEW_SUBPRODUCT IS NOT NULL AND a.DEAPRO <> 'EXTR') THEN CONCAT(TRIM(c.COD_NEW_SUBPRODUCT), IF((TRIM(e.CRETPA) IS NULL OR TRIM(e.CRETPA) = ""), "", "_"), ISNULL(TRIM(e.CRETPA),""))
WHEN a.DEAPRO = 'EXTR' THEN ISNULL(CONCAT(STRLEFT(d.EXTTAR,8), '_EXT'), 'EXTR')
ELSE CONCAT(TRIM(a.DEAPRO), IF((TRIM(e.CRETPA) IS NULL OR TRIM(e.CRETPA) = ""), "", "_"), ISNULL(TRIM(e.CRETPA),"")) END AS COD_SUBPRODUCT, 
IFNULL(CAST(a.DEAICD AS string), '') AS COD_ACT_TYPE,
a.DEAPRI AS EOPBAL_CAP, NULL AS EOPBAL_INT, a.DEAAVP AS AVGBAL_CAP, NULL AS AVGBAL_INT, 
NULL AS PL, 'DEALS' AS COD_INFO_SOURCE 
FROM MIS_LOAD_DEALS a
LEFT JOIN MIS_PAR_REL_PROD_SPE b 
ON CAST(a.DEAACC AS string) = B.IDF_CTO 
LEFT JOIN MIS_PAR_REL_SUBPROD_OPER c
ON REGEXP_REPLACE(a.DEABNK, '"', '') = c.COD_ENTITY AND REGEXP_REPLACE(TRIM(a.DEATYP), '"', '') = c.COD_PRODUCT AND REGEXP_REPLACE(TRIM(a.DEAPRO), '"', '') = c.COD_SUBPRODUCT AND REGEXP_REPLACE(a.DEAICD, '"', '') = C.COD_ACT_TYPE
LEFT JOIN (SELECT EXTACC, MIN(EXTTAR) EXTTAR FROM MIS_LOAD_CSEXTMSTF GROUP BY EXTACC) d
ON CAST(a.DEAACC AS STRING) = d.EXTACC
LEFT JOIN MIS_LOAD_CREMST e
ON CAST(a.DEAACC AS STRING) = e.CREACC
WHERE STRLEFT(CAST(a.DEAGLN AS string),1) = '9' AND  TRIM(a.DEASTS) <> 'C'
AND TRIM(CAST(a.DEAACD AS STRING)) <> '11'
AND TRIM(a.DEACLF) <> 'G'
AND STRLEFT(a.DEAGLN,2) <> '21'
;

----Aprovisionamiento de Activos Intereses
INSERT INTO MIS_APR_OFF_BALANCE 
PARTITION (DATA_DATE='${var:periodo}') 
SELECT 'PREST' AS COD_CONT, CAST(a.DEAACC AS string) AS IDF_CTO, CAST(d.GLMXDR AS STRING) AS COD_GL, NULL AS DES_GL, CAST(a.DEACCN AS string) AS COD_ACCO_CENT, TRIM(a.DEABRN) AS COD_OFFI, 
'1' AS COD_BLCE_STATUS, 'INT' AS COD_VALUE, REGEXP_REPLACE(a.DEACCY, '"', '') AS COD_CURRENCY, REGEXP_REPLACE(a.DEABNK, '"', '') AS COD_ENTITY,
CASE WHEN b.IDF_CTO IS NOT NULL THEN b.COD_PRODUCT 
WHEN a.DEAPRO = 'EXTR' THEN ISNULL(STRLEFT(e.EXTTAR,1),'TAR') ELSE TRIM(a.DEATYP) END AS COD_PRODUCT,
CASE WHEN (c.COD_NEW_SUBPRODUCT IS NOT NULL AND a.DEAPRO <> 'EXTR') THEN CONCAT(TRIM(c.COD_NEW_SUBPRODUCT), IF((TRIM(f.CRETPA) IS NULL OR TRIM(f.CRETPA) = ""), "", "_"), ISNULL(TRIM(f.CRETPA),"")) 
WHEN a.DEAPRO = 'EXTR' THEN ISNULL(CONCAT(STRLEFT(e.EXTTAR,8), '_EXT'), 'EXTR')
ELSE CONCAT(TRIM(a.DEAPRO), IF((TRIM(f.CRETPA) IS NULL OR TRIM(f.CRETPA) = ""), "", "_"), ISNULL(TRIM(f.CRETPA),"")) END AS COD_SUBPRODUCT, IFNULL(CAST(a.DEAICD AS string), '') AS COD_ACT_TYPE, a.DEAMEI AS EOPBAL_CAP,
NULL AS EOPBAL_INT, NULL AS AVGBAL_CAP, NULL AS AVGBAL_INT, NULL AS PL, 'DEALS' AS COD_INFO_SOURCE
FROM MIS_LOAD_DEALS a
LEFT JOIN MIS_PAR_REL_PROD_SPE b 
ON CAST(a.DEAACC AS string) = B.IDF_CTO
LEFT JOIN MIS_PAR_REL_SUBPROD_OPER c
ON REGEXP_REPLACE(a.DEABNK, '"', '') = c.COD_ENTITY AND REGEXP_REPLACE(TRIM(a.DEATYP), '"', '') = c.COD_PRODUCT AND REGEXP_REPLACE(TRIM(a.DEAPRO), '"', '') = c.COD_SUBPRODUCT AND REGEXP_REPLACE(a.DEAICD, '"', '') = C.COD_ACT_TYPE
LEFT JOIN (SELECT * FROM MIS_LOAD_GLMST WHERE GLMCCY = 'USD') d
ON a.DEAGLN = d.GLMGLN  
LEFT JOIN (SELECT EXTACC, MIN(EXTTAR) EXTTAR FROM MIS_LOAD_CSEXTMSTF GROUP BY EXTACC) e
ON CAST(a.DEAACC AS STRING) = e.EXTACC
LEFT JOIN MIS_LOAD_CREMST f
ON CAST(a.DEAACC AS STRING) = f.CREACC
WHERE STRLEFT(CAST(a.DEAGLN AS string),1) = '9' AND REGEXP_REPLACE(TRIM(a.DEASTS), '"', '') <> 'C'
AND REGEXP_REPLACE(TRIM(CAST(a.DEAACD AS STRING)), '"', '') <> '11'
AND REGEXP_REPLACE(TRIM(a.DEACLF), '"', '') <> 'G'
AND strleft(a.DEAGLN,2) <> '21'
;


----Aprovisionamiento de Activos Resultados
INSERT INTO MIS_APR_OFF_BALANCE 
PARTITION (DATA_DATE='${var:periodo}') 
SELECT 'PREST' AS COD_CONT, CAST(a.DEAACC AS string) AS IDF_CTO, CAST(d.GLMXCR AS STRING) AS COD_GL, NULL AS DES_GL, CAST(a.DEACCN AS string) AS COD_ACCO_CENT, TRIM(a.DEABRN) AS COD_OFFI,
'1' AS COD_BLCE_STATUS, 'RSL' AS COD_VALUE, REGEXP_REPLACE(a.DEACCY, '"', '') AS COD_CURRENCY, REGEXP_REPLACE(a.DEABNK, '"', '') AS COD_ENTITY,
CASE WHEN b.IDF_CTO IS NOT NULL THEN b.COD_PRODUCT 
WHEN a.DEAPRO = 'EXTR' THEN ISNULL(STRLEFT(e.EXTTAR,1),'TAR') ELSE TRIM(a.DEATYP) END AS COD_PRODUCT,
CASE WHEN (c.COD_NEW_SUBPRODUCT IS NOT NULL AND a.DEAPRO <> 'EXTR') THEN CONCAT(TRIM(c.COD_NEW_SUBPRODUCT), IF((TRIM(f.CRETPA) IS NULL OR TRIM(f.CRETPA) = ""), "", "_"), ISNULL(TRIM(f.CRETPA),"")) 
WHEN a.DEAPRO = 'EXTR' THEN ISNULL(CONCAT(STRLEFT(e.EXTTAR,8), '_EXT'), 'EXTR')
ELSE CONCAT(TRIM(a.DEAPRO), IF((TRIM(f.CRETPA) IS NULL OR TRIM(f.CRETPA) = ""), "", "_"), ISNULL(TRIM(f.CRETPA),"")) END AS COD_SUBPRODUCT, IFNULL(CAST(a.DEAICD AS string), '') AS COD_ACT_TYPE,
NULL AS EOPBAL_CAP, NULL AS EOPBAL_INT, NULL AS AVGBAL_CAP, NULL AS AVGBAL_INT, CAST(a.DEAINM*-1 AS DECIMAL(30,10)) AS PL, 'DEALS' AS COD_INFO_SOURCE 
FROM MIS_LOAD_DEALS a
LEFT JOIN MIS_PAR_REL_PROD_SPE b 
ON CAST(a.DEAACC AS string) = B.IDF_CTO
LEFT JOIN MIS_PAR_REL_SUBPROD_OPER c
ON REGEXP_REPLACE(a.DEABNK, '"', '') = c.COD_ENTITY AND REGEXP_REPLACE(TRIM(a.DEATYP), '"', '') = c.COD_PRODUCT AND REGEXP_REPLACE(TRIM(a.DEAPRO), '"', '') = c.COD_SUBPRODUCT AND REGEXP_REPLACE(a.DEAICD, '"', '') = C.COD_ACT_TYPE
LEFT JOIN (SELECT * FROM MIS_LOAD_GLMST WHERE GLMCCY = 'USD') d
ON a.DEAGLN = d.GLMGLN  
LEFT JOIN (SELECT EXTACC, MIN(EXTTAR) EXTTAR FROM MIS_LOAD_CSEXTMSTF GROUP BY EXTACC) e
ON CAST(a.DEAACC AS STRING) = e.EXTACC
LEFT JOIN MIS_LOAD_CREMST f
ON CAST(a.DEAACC AS STRING) = f.CREACC
WHERE STRLEFT(CAST(a.DEAGLN AS string),1) = '9' AND TRIM(a.DEASTS) <> 'C'
AND REGEXP_REPLACE(TRIM(CAST(a.DEAACD AS STRING)), '"', '') <> '11'
AND REGEXP_REPLACE(TRIM(a.DEACLF), '"', '') <> 'G'
AND strleft(a.DEAGLN,2) <> '21'
;

----Aprovisionamiento de Contratos asociados a Contingentes

ALTER TABLE MIS_APR_CONTRACT_DT
DROP IF EXISTS PARTITION (DATA_DATE = '${var:periodo}', COD_INFO_SOURCE='LCMST');

INSERT INTO MIS_APR_CONTRACT_DT 
PARTITION (DATA_DATE='${var:periodo}', COD_INFO_SOURCE='LCMST') 
SELECT DISTINCT CAST(a.LCMACC AS string) AS IDF_CTO, a.LCMBNK AS COD_ENTITY, 
CASE WHEN b.IDF_CTO IS NOT NULL THEN b.COD_PRODUCT ELSE  TRIM(a.LCMATY) END AS COD_PRODUCT, TRIM(a.LCMPRO) AS COD_SUBPRODUCT,
TRIM(LCMIND) AS COD_ACT_TYPE, a.LCMCCY AS COD_CURRENCY, CAST(a.LCMCUN AS string) AS IDF_CLI,
CAST(a.LCMCCN AS string) AS COD_ACCO_CENT, TRIM(a.LCMBRN) AS COD_OFFI, NULL AS COD_BCA_INT, NULL AS COD_AMRT_MET, 
NULL AS COD_RATE_TYPE, CAST(((a.LCMOFX)/100) AS decimal(30, 10)) AS RATE_INT, 
CONCAT(CASE WHEN CAST(STRRIGHT(CAST(YEAR(NOW()) AS string), 2) AS smallint) < CAST(a.LCMODY AS SMALLINT) 
THEN CONCAT('19', LPAD(CAST(a.LCMODY AS string), 2, '0')) ELSE CONCAT('2', LPAD(CAST(a.LCMODY AS string), 3, '0')) END, 
LPAD(CAST(a.LCMODM AS string), 2, '0'), LPAD(CAST(a.LCMODD  AS string), 2, '0')) AS DATE_ORIGIN, 
NULL AS DATE_LAST_REV, 
CONCAT(CONCAT('2', LPAD(CAST(a.LCMODY AS string), 3, '0')), 
LPAD(CAST(a.LCMODM AS string), 2, '0'), LPAD(CAST(a.LCMODD  AS string), 2, '0')) AS DATE_PRX_REV,
CONCAT(CONCAT('2', LPAD(CAST(a.LCMODY AS string), 3, '0')), 
LPAD(CAST(a.LCMODM AS string), 2, '0'), LPAD(CAST(a.LCMODD  AS string), 2, '0')) AS EXP_DATE, 
NULL AS FREQ_INT_PAY, NULL AS COD_UNI_FREQ_INT_PAY, CAST(a.LCMLFX AS BIGINT) AS FRE_REV_INT, a.LCMLFX AS COD_UNI_FRE_REV_INT, NULL AS AMRT_TRM, NULL AS COD_UNI_AMRT_TRM,
CAST(a.LCMOAM AS DECIMAL(30,10)) AS INI_AM, NULL AS CUO_AM, NULL AS CREDIT_LIM_AM, NULL AS PREDEF_RATE_IND, NULL AS PREDEF_RATE, NULL AS IND_CHANNEL, NULL AS COD_TYP_LIC, NULL AS COU_CAR_OFF, NULL AS COD_CONV, NULL AS COD_EXEC_CTO, NULL AS COD_COVID_PORT,  NULL AS FIELD1_CTO, NULL AS FIELD2_CTO, NULL AS FIELD3_CTO, NULL AS FIELD4_CTO, NULL AS FIELD5_CTO, NULL AS FIELD6_CTO, NULL AS FIELD7_CTO, NULL AS FIELD8_CTO, NULL AS FIELD9_CTO, NULL AS FIELD10_CTO, CONCAT(CASE WHEN CAST(STRRIGHT(CAST(YEAR(NOW()) AS string), 2) AS smallint) < CAST(a.LCMODY AS SMALLINT) 
THEN CONCAT('19', LPAD(CAST(a.LCMODY AS string), 2, '0')) ELSE CONCAT('2', LPAD(CAST(a.LCMODY AS string), 3, '0')) END, 
LPAD(CAST(a.LCMODM AS string), 2, '0'), LPAD(CAST(a.LCMODD  AS string), 2, '0')) AS DATE_DISB, NULL AS CARD_NUMBER, NULL AS COD_PROG_CARD, NULL AS DES_PROG_CARD
FROM MIS_LOAD_LCMST a
LEFT JOIN MIS_PAR_REL_PROD_SPE b 
ON CAST(a.LCMACC AS string) = B.IDF_CTO
WHERE a.LCMSTS <> 'C'
;