--------------------------------------------------------- MIS_APR_OFF_BALANCE --------------------------------------------------------
USE ${var:base_datos};
SET DECIMAL_V2=FALSE;

----Carga de tablas load
--/home/countries/PA/PA_PROTOTIPADO/landings/fuentes/pa_prot_contingencias
TRUNCATE TABLE IF EXISTS MIS_LOAD_LCMST; 
LOAD DATA INPATH '${var:ruta_fuentes_contingencias}/LCMST.CSV' INTO TABLE MIS_LOAD_LCMST;

ALTER TABLE MIS_APR_OFF_BALANCE 
DROP IF EXISTS PARTITION (DATA_DATE = '${var:periodo}');

----Aprovisionamiento de Contingentes Capital
INSERT INTO MIS_APR_OFF_BALANCE 
PARTITION (DATA_DATE='${var:periodo}') 
SELECT 'CTG' AS COD_CONT, a.LCMACC AS IDF_CTO, NULL AS COD_GL, NULL AS DES_GL, CAST(a.LCMCCN AS string) AS COD_ACCO_CENT, 
    a.LCMBRN AS COD_OFFI, '1' AS COD_BLCE_STATUS, 'CAP' AS COD_VALUE, a.LCMCCY AS COD_CURRENCY, a.LCMBNK AS COD_ENTITY, 
    CONCAT(TRIM(a.LCMATY),
        CASE cl.COD_SECTOR
            WHEN 'INTERNACIONAL' THEN '_I'
            WHEN 'LOCAL' THEN '_L'
            ELSE '_L' END) AS COD_PRODUCT, 
    TRIM(a.LCMPRO) AS COD_SUBPRODUCT, '' AS COD_ACT_TYPE, 
    a.LCMAMN AS EOPBAL_CAP, NULL AS EOPBAL_INT, a.LCMMAG AS AVGBAL_CAP, NULL AS AVGBAL_INT, NULL AS PL, 'LCMST' AS COD_INFO_SOURCE
FROM MIS_LOAD_LCMST a
LEFT JOIN MIS_APR_CLIENT_DT cl 
ON cl.DATA_DATE = '${var:periodo}' AND cl.IDF_CLI = CAST(a.LCMCUN AS string)
WHERE a.LCMBNK <> '02';


ALTER TABLE MIS_APR_CONTRACT_DT
DROP IF EXISTS PARTITION (DATA_DATE = '${var:periodo}', COD_INFO_SOURCE='LCMST');

----Aprovisionamiento de Contratos asociados a Contingentes
INSERT INTO MIS_APR_CONTRACT_DT 
PARTITION (DATA_DATE='${var:periodo}', COD_INFO_SOURCE='LCMST') 
SELECT a.LCMACC AS IDF_CTO, a.LCMBNK AS COD_ENTITY, 
    CONCAT(TRIM(a.LCMATY),
        CASE cl.COD_SECTOR
            WHEN 'INTERNACIONAL' THEN '_I'
            WHEN 'LOCAL' THEN '_L'
            ELSE '_L' END) AS COD_PRODUCT, 
    TRIM(a.LCMPRO) AS COD_SUBPRODUCT, 
    NULL AS COD_ACT_TYPE, a.LCMCCY AS COD_CURRENCY, a.LCMCUN AS IDF_CLI, CAST(a.LCMCCN AS string) AS COD_ACCO_CENT, a.LCMBRN AS COD_OFFI, 
    NULL AS COD_BCA_INT, NULL AS COD_AMRT_MET, NULL AS COD_RATE_TYPE, CAST(a.LCMOFX/100 AS decimal(30, 10)) AS RATE_INT, --RATE INT SIEMPRE ES CERO
    CASE WHEN a.LCMODY=0 AND a.LCMODM=0 AND a.LCMODD=0 THEN NULL
        ELSE CONCAT(CONCAT('2', LPAD(CAST(a.LCMODY AS string), 3, '0')), 
                    LPAD(CAST(a.LCMODM AS string), 2, '0'), LPAD(CAST(a.LCMODD  AS string), 2, '0'))
        END AS DATE_ORIGIN,
    NULL AS DATE_LAST_REV, 
    NULL AS DATE_PRX_REV, 
    CASE WHEN a.LCMEXY=0 AND a.LCMEXM=0 AND a.LCMEXD=0 THEN NULL
        ELSE CONCAT(CONCAT('2', LPAD(CAST(a.LCMEXY AS string), 3, '0')), 
                    LPAD(CAST(a.LCMEXM AS string), 2, '0'), LPAD(CAST(a.LCMEXD  AS string), 2, '0'))
        END AS EXP_DATE,
    NULL AS FREQ_INT_PAY, NULL AS COD_UNI_FREQ_INT_PAY, NULL AS FRE_REV_INT, NULL AS COD_UNI_FRE_REV_INT, 
    NULL AS AMRT_TRM, NULL AS COD_UNI_AMRT_TRM, a.LCMOAM AS INI_AM, NULL AS CUO_AM, 
    NULL AS CREDIT_LIM_AM, NULL AS PREDEF_RATE_IND, NULL AS PREDEF_RATE, NULL AS IND_CHANNEL, NULL AS COD_TYP_LIC,
    TRIM(a.LCMSST) AS COD_SELLER, TRIM(b.CNODSC) AS DES_SELLER, NULL AS COU_CAR_OFF, NULL AS COD_CONV, a.LCMOFN AS COD_EXEC_CTO, CASE WHEN cov.IDF_CTO IS NULL THEN 'N' ELSE 'Y' END AS COD_COVID_PORT, 
    CASE WHEN a.LCMODY=0 AND a.LCMODM=0 AND a.LCMODD=0 THEN NULL
        ELSE CONCAT(CONCAT('2', LPAD(CAST(a.LCMODY AS string), 3, '0')), 
                    LPAD(CAST(a.LCMODM AS string), 2, '0'), LPAD(CAST(a.LCMODD  AS string), 2, '0'))
        END AS DATE_DISB, NULL AS CARD_NUMBER, NULL AS COD_PROG_CARD, NULL AS DES_PROG_CARD
FROM MIS_LOAD_LCMST a
LEFT JOIN (SELECT CNOCFL, CNORCD, MAX(CNODSC) AS CNODSC FROM MIS_LOAD_CNOFC GROUP BY CNORCD, CNOCFL) b
ON TRIM(b.CNOCFL) = '65' AND TRIM(a.LCMSST) = TRIM(b.CNORCD)
LEFT JOIN MIS_APR_CLIENT_DT cl 
ON cl.DATA_DATE = '${var:periodo}' AND cl.IDF_CLI = CAST(a.LCMCUN AS string)
LEFT JOIN (SELECT * FROM MIS_PAR_REL_CAR_COVID WHERE STRLEFT(DATA_DATE,6) = STRLEFT('${var:periodo}',6)) cov
ON a.LCMACC = cov.IDF_CTO
WHERE a.LCMBNK <> '02';