--------------------------------------------------------- MIS_APR_OFF_BALANCE --------------------------------------------------------

USE ${var:base_datos};
SET DECIMAL_V2=FALSE;

----Carga de tablas load
TRUNCATE TABLE IF EXISTS MIS_LOAD_SCTAF87; 
LOAD DATA INPATH '${var:ruta_fuentes_contingencias}/SCTAF87.csv' INTO TABLE MIS_LOAD_SCTAF87;

ALTER TABLE MIS_APR_OFF_BALANCE 
DROP IF EXISTS PARTITION (DATA_DATE = '${var:periodo}');

/*
----Aprovisionamiento de Contingentes Capital
INSERT INTO MIS_APR_OFF_BALANCE 
PARTITION (DATA_DATE='${var:periodo}') 
SELECT 'CTG' AS COD_CONT, a.NUMGAR AS IDF_CTO, NULL AS COD_GL, NULL AS DES_GL, NULL AS COD_ACCO_CENT, 
NULL AS COD_OFFI, a.STATUS AS COD_BLCE_STATUS, 'CAP' AS COD_VALUE, CASE WHEN a.MONEDA = '0' THEN 'HNL' WHEN a.MONEDA = '1' THEN 'USD' ELSE 'HNL' END AS COD_CURRENCY, '1' AS COD_ENTITY, 
CAST(a.TIPCTA AS STRING) AS COD_PRODUCT, 'GAR' AS COD_SUBPRODUCT, IFNULL(NULL, '') AS COD_ACT_TYPE, CAST(a.CANTID AS DECIMAL(30,10)) AS EOPBAL_CAP,
NULL AS EOPBAL_INT, NULL AS AVGBAL_CAP, NULL AS AVGBAL_INT, NULL AS PL, 'SCTAF87' AS COD_INFO_SOURCE
FROM MIS_LOAD_SCTAF87 a
WHERE a.cobrar = 'Y' AND cast(a.anoliq as string) = strleft('${var:periodo}',4) AND cast(a.mesliq as string) = substr('${var:periodo}',6,1)
GROUP BY a.NUMGAR, a.STATUS, a.MONEDA, a.TIPCTA
;
*/

----Aprovisionamiento de Contingentes Resultados
INSERT INTO MIS_APR_OFF_BALANCE 
PARTITION (DATA_DATE='${var:periodo}')
SELECT 'COM' AS COD_CONT, a.NUMGAR AS IDF_CTO, NULL AS COD_GL, NULL AS DES_GL, NULL AS COD_ACCO_CENT, 
NULL AS COD_OFFI, 'VIG' AS COD_BLCE_STATUS, 'RSL' AS COD_VALUE, CASE WHEN a.MONEDA = '0' THEN 'HNL' WHEN a.MONEDA = '1' THEN 'USD' ELSE 'HNL' END AS COD_CURRENCY, '1' AS COD_ENTITY, 
CAST(a.TIPCTA AS STRING) AS COD_PRODUCT, 'GAR_ANT' AS COD_SUBPRODUCT, IFNULL(NULL, '') AS COD_ACT_TYPE, 0 AS EOPBAL_CAP,
0 AS EOPBAL_INT, 0 AS AVGBAL_CAP, 0 AS AVGBAL_INT, CAST(SUM(a.comis1 * -1) AS DECIMAL(30,10)) AS PL, 'SCTAF87' AS COD_INFO_SOURCE
FROM MIS_LOAD_SCTAF87 a
WHERE a.cobrar = 'Y' AND cast(a.anoliq as string) = strleft('${var:periodo}',4) AND cast(a.mesliq as string) = substr('${var:periodo}',6,1)
GROUP BY a.NUMGAR, a.STATUS, a.MONEDA, a.TIPCTA
;

----Aprovisionamiento de Contingentes Resultados
INSERT INTO MIS_APR_OFF_BALANCE 
PARTITION (DATA_DATE='${var:periodo}')
SELECT 'COM' AS COD_CONT, a.NUMGAR AS IDF_CTO, NULL AS COD_GL, NULL AS DES_GL, NULL AS COD_ACCO_CENT, 
NULL AS COD_OFFI, 'VIG' AS COD_BLCE_STATUS, 'RSL' AS COD_VALUE, CASE WHEN a.MONEDA = '0' THEN 'HNL' WHEN a.MONEDA = '1' THEN 'USD' ELSE 'HNL' END AS COD_CURRENCY, '1' AS COD_ENTITY, 
CAST(a.TIPCTA AS STRING) AS COD_PRODUCT, 'GAR_EMI' AS COD_SUBPRODUCT, IFNULL(NULL, '') AS COD_ACT_TYPE, 0 AS EOPBAL_CAP,
0 AS EOPBAL_INT, 0 AS AVGBAL_CAP, 0 AS AVGBAL_INT, CAST(SUM(a.comisi * -1) AS DECIMAL(30,10)) AS PL, 'SCTAF87' AS COD_INFO_SOURCE
FROM MIS_LOAD_SCTAF87 a
WHERE a.cobrar = 'Y' AND cast(a.anoliq as string) = strleft('${var:periodo}',4) AND cast(a.mesliq as string) = substr('${var:periodo}',6,1)
GROUP BY a.NUMGAR, a.STATUS, a.MONEDA, a.TIPCTA
;

----Aprovisionamiento de contingentes CR01
INSERT INTO MIS_APR_OFF_BALANCE
PARTITION (DATA_DATE='${var:periodo}') 
SELECT 'CTG' AS COD_CONT, CAST(a.CR01_04 AS string) AS IDF_CTO, NULL AS COD_GL, NULL AS DES_GL, CAST(a.CR01_56 AS string) AS COD_ACCO_CENT, 
     CAST(a.CR01_56 AS string) AS COD_OFFI, CAST(a.CR01_37 AS string) AS COD_BLCE_STATUS, 'CAP' AS COD_VALUE, 'HNL' AS COD_CURRENCY, '1' AS COD_ENTITY,
    TRIM(a.CR01_55) AS COD_PRODUCT, TRIM(a.CR01_14) AS COD_SUBPRODUCT, IFNULL(NULL, '') AS COD_ACT_TYPE, CAST(a.CR01_45 AS DECIMAL(30,10)) AS EOPBAL_CAP, 
    NULL AS EOPBAL_INT, NULL AVGBAL_CAP, NULL AS AVGBAL_INT, NULL AS PL, 'CR01' AS COD_INFO_SOURCE 
FROM MIS_LOAD_CR01 a
WHERE to_timestamp(a.CR01_75,'yyyyMMdd') = last_day(to_timestamp('${var:periodo}','yyyyMMdd')) AND strleft(CR01_04,2) <> 'EF' AND a.CR01_14 like '240%'
;

ALTER TABLE MIS_APR_CONTRACT_DT
DROP IF EXISTS PARTITION (DATA_DATE = '${var:periodo}', COD_INFO_SOURCE='SCTAF87');

INSERT INTO MIS_APR_CONTRACT_DT 
PARTITION (DATA_DATE='${var:periodo}', COD_INFO_SOURCE='SCTAF87') 
SELECT DISTINCT CAST(a.CR01_04 AS string) AS IDF_CTO, '1' AS COD_ENTITY, 
TRIM(a.CR01_55) AS COD_PRODUCT, CONCAT(IFNULL(TRIM(a.CR01_14),''),'_',IFNULL(TRIM(a.CR01_17),'')) AS COD_SUBPRODUCT, IFNULL(NULL, '') AS COD_ACT_TYPE, 'HNL' AS COD_CURRENCY, CAST(a.CR01_54 AS string) AS IDF_CLI, CAST(a.CR01_56 AS string) AS COD_ACCO_CENT, 
    CAST(a.CR01_56 AS string) AS COD_OFFI, NULL AS COD_BCA_INT, NULL AS COD_AMRT_MET, 
    'A' AS COD_RATE_TYPE, CAST(a.CR01_22/100 AS decimal(30, 10)) AS RATE_INT, a.CR01_05 AS DATE_ORIGIN, 
    NULL AS DATE_LAST_REV, NULL DATE_PRX_REV, a.CR01_06 AS EXP_DATE, NULL AS FREQ_INT_PAY, NULL AS COD_UNI_FREQ_INT_PAY, 
    NULL AS FRE_REV_INT, NULL AS COD_UNI_FRE_REV_INT, CAST(a.CR01_23 as BIGINT) AS AMRT_TRM, NULL AS COD_UNI_AMRT_TRM, a.CR01_47 AS INI_AM, a.CR01_58 AS CUO_AM, NULL AS CREDIT_LIM_AM, NULL AS PREDEF_RATE_IND, NULL AS PREDEF_RATE, 
    NULL AS IND_CHANNEL, NULL COD_TYP_LIC, NULL AS COD_SELLER, NULL AS DES_SELLER, NULL AS COU_CAR_OFF, NULL AS COD_CONV, NULL AS COD_EXEC_CTO, NULL AS COD_COVID_PORT, a.CR01_05 AS DATE_DISB, NULL AS FIELD1_CTO, NULL AS FIELD2_CTO, NULL AS FIELD3_CTO, NULL AS FIELD4_CTO, NULL AS FIELD5_CTO, NULL AS FIELD6_CTO, NULL AS FIELD7_CTO, NULL AS FIELD8_CTO, NULL AS FIELD9_CTO, NULL AS FIELD10_CTO, NULL AS CARD_NUMBER, NULL AS COD_PROG_CARD, NULL AS DES_PROG_CARD
FROM MIS_LOAD_CR01 a
WHERE to_timestamp(a.CR01_75,'yyyyMMdd') = last_day(to_timestamp('${var:periodo}','yyyyMMdd')) AND strleft(CR01_04,2) <> 'EF' AND a.CR01_14 like '240%';

INSERT INTO MIS_APR_CONTRACT_DT 
PARTITION (DATA_DATE='${var:periodo}', COD_INFO_SOURCE='SCTAF87') 
SELECT a.NUMGAR AS IDF_CTO, '1' AS COD_ENTITY, CAST(a.TIPCTA AS STRING) AS COD_PRODUCT, 'GAR' AS COD_SUBPRODUCT, IFNULL(NULL, '') AS COD_ACT_TYPE, CASE WHEN a.MONEDA = '0' THEN 'HNL' WHEN a.MONEDA = '1' THEN 'USD' ELSE 'HNL' END AS COD_CURRENCY, NUMCIF AS IDF_CLI, IFNULL(NULL, '') AS COD_ACCO_CENT, IFNULL(NULL, '') AS COD_OFFI, NULL AS COD_BCA_INT, NULL AS COD_AMRT_MET, 
'A' AS COD_RATE_TYPE, NULL AS RATE_INT, CONCAT(CAST(ANOAPR AS STRING), LPAD(CAST(MESAPR AS STRING),2,'0'), LPAD(CAST(DIAAPR AS STRING),2,'0')) AS DATE_ORIGIN, 
    NULL AS DATE_LAST_REV, NULL DATE_PRX_REV,CONCAT(CAST(ANOVEN AS STRING), LPAD(CAST(MESVEN AS STRING),2,'0'), LPAD(CAST(diaven AS STRING),2,'0')) AS EXP_DATE, NULL AS FREQ_INT_PAY, NULL AS COD_UNI_FREQ_INT_PAY, 
    NULL AS FRE_REV_INT, NULL AS COD_UNI_FRE_REV_INT, NULL AS AMRT_TRM, NULL AS COD_UNI_AMRT_TRM, NULL AS INI_AM, NULL AS CUO_AM, NULL AS CREDIT_LIM_AM, NULL AS PREDEF_RATE_IND, NULL AS PREDEF_RATE, 
    NULL AS IND_CHANNEL, NULL COD_TYP_LIC, NULL AS COD_SELLER, NULL AS DES_SELLER, NULL AS COU_CAR_OFF, NULL AS COD_CONV, NULL AS COD_EXEC_CTO, NULL AS COD_COVID_PORT, 
CONCAT(CAST(ANOAPR AS STRING), LPAD(CAST(MESAPR AS STRING),2,'0'), LPAD(CAST(DIAAPR AS STRING),2,'0')) AS DATE_DISB, NULL AS FIELD1_CTO, NULL AS FIELD2_CTO, NULL AS FIELD3_CTO, NULL AS FIELD4_CTO, NULL AS FIELD5_CTO, NULL AS FIELD6_CTO, NULL AS FIELD7_CTO, NULL AS FIELD8_CTO, NULL AS FIELD9_CTO, NULL AS FIELD10_CTO, NULL AS CARD_NUMBER, NULL AS COD_PROG_CARD, NULL AS DES_PROG_CARD
FROM MIS_LOAD_SCTAF87 a
WHERE a.cobrar = 'Y' AND cast(a.anoliq as string) = strleft('${var:periodo}',4) AND cast(a.mesliq as string) = substr('${var:periodo}',6,1) AND a.NUMGAR NOT IN (SELECT DISTINCT IDF_CTO FROM MIS_APR_CONTRACT_DT WHERE DATA_DATE = '${var:periodo}');