--------------------------------------------------------------- MIS_APR_PROVISIONS --------------------------------------------------------
USE ${var:base_datos};


----Carga de tablas load
TRUNCATE TABLE IF EXISTS MIS_LOAD_TA_CONT; 
LOAD DATA INPATH '${var:ruta_fuentes_provisiones}/TA_CONT_PAN.CSV' INTO TABLE MIS_LOAD_TA_CONT;

ALTER TABLE MIS_LOAD_PROV_INV DROP IF EXISTS PARTITION (DATA_DATE = '${var:periodo}');
ALTER TABLE MIS_LOAD_PROV_INV ADD IF NOT EXISTS PARTITION (DATA_DATE = '${var:periodo}');
LOAD DATA INPATH '${var:ruta_fuentes_provisiones}/PROV_INV.CSV' INTO TABLE MIS_LOAD_PROV_INV PARTITION (DATA_DATE = '${var:periodo}');

--Limpieza de partición del día en ejecución
ALTER TABLE MIS_APR_PROVISIONS_M
DROP IF EXISTS PARTITION (DATA_DATE = '${var:periodo}');

----Aprovisionamiento de Provisiones Capital
INSERT INTO MIS_APR_PROVISIONS_M 
PARTITION (DATA_DATE='${var:periodo}') 
SELECT 'PROV' AS COD_CONT, CAST(CAST(a.OBLIGACION AS bigint) AS STRING) AS IDF_CTO, NULL AS COD_GL, NULL AS DES_GL, b.COD_ACCO_CENT, 
	b.COD_OFFI, '0' AS COD_BLCE_STATUS, 'CAP_PROV' AS COD_VALUE, 'USD' AS COD_CURRENCY, ISNULL(b.COD_ENTITY,'99') AS COD_ENTITY, 
	b.COD_PRODUCT, b.COD_SUBPRODUCT, b.COD_ACT_TYPE, CAST(-1*a.DET_SALDO_CAPITAL AS DECIMAL(30,10)) AS EOPBAL_CAP, 
	NULL AS EOPBAL_INT, NULL AS AVGBAL_CAP, NULL AS AVGBAL_INT, NULL AS PL, 'TA_CONT_PA_CARTERA' AS COD_INFO_SOURCE
FROM MIS_LOAD_TA_CONT a
LEFT JOIN MIS_APR_CONTRACT_DT b
ON b.DATA_DATE = '${var:periodo}' AND CAST(CAST(a.OBLIGACION AS bigint) AS STRING)  = b.IDF_CTO
WHERE COD_ENTITY <> '02';


----Aprovisionamiento de Provisiones Intereses
INSERT INTO MIS_APR_PROVISIONS_M 
PARTITION (DATA_DATE='${var:periodo}') 
SELECT 'PROV' AS COD_CONT, CAST(CAST(a.OBLIGACION AS bigint) AS STRING) AS IDF_CTO, NULL AS COD_GL, NULL AS DES_GL, b.COD_ACCO_CENT, 
	b.COD_OFFI, '0' AS COD_BLCE_STATUS, 'INT_PROV' AS COD_VALUE, 'USD' AS COD_CURRENCY, ISNULL(b.COD_ENTITY,'99') AS COD_ENTITY, 
	b.COD_PRODUCT, b.COD_SUBPRODUCT, b.COD_ACT_TYPE, CAST(-1 * a.DET_SALDO_INT_CTE AS DECIMAL(30,10)) AS EOPBAL_CAP, 
	NULL AS EOPBAL_INT, NULL AS AVGBAL_CAP, NULL AS AVGBAL_INT, NULL AS PL, 'TA_CONT_PA_CARTERA' AS COD_INFO_SOURCE
FROM MIS_LOAD_TA_CONT a
LEFT JOIN MIS_APR_CONTRACT_DT b
ON b.DATA_DATE = '${var:periodo}' AND CAST(CAST(a.OBLIGACION AS bigint) AS STRING)  = b.IDF_CTO
WHERE COD_ENTITY <> '02';


----Aprovisionamiento de Provisiones Riesgo Pais
INSERT INTO MIS_APR_PROVISIONS_M 
PARTITION (DATA_DATE='${var:periodo}') 
SELECT 'PROV' AS COD_CONT, CAST(CAST(a.OBLIGACION AS bigint) AS STRING) AS IDF_CTO, NULL AS COD_GL, NULL AS DES_GL, b.COD_ACCO_CENT, 
	b.COD_OFFI, '0' AS COD_BLCE_STATUS, 'RPA_PROV' AS COD_VALUE, 'USD' AS COD_CURRENCY, ISNULL(b.COD_ENTITY,'99') AS COD_ENTITY, 
	b.COD_PRODUCT, b.COD_SUBPRODUCT, b.COD_ACT_TYPE, CAST(-1*a.PROVISION_RIESGO_PAIS AS DECIMAL(30,10)) AS EOPBAL_CAP, 
	NULL AS EOPBAL_INT, NULL AS AVGBAL_CAP, NULL AS AVGBAL_INT, NULL AS PL, 'TA_CONT_PA_CARTERA' AS COD_INFO_SOURCE
FROM MIS_LOAD_TA_CONT a
LEFT JOIN MIS_APR_CONTRACT_DT b
ON b.DATA_DATE = '${var:periodo}' AND CAST(CAST(a.OBLIGACION AS bigint) AS STRING)  = b.IDF_CTO
WHERE COD_ENTITY <> '02';


----Aprovisionamiento de Provisiones Resultados - capital

INSERT INTO MIS_APR_PROVISIONS_M 
PARTITION (DATA_DATE) 
SELECT isnull(a.COD_CONT,b.COD_CONT), isnull(a.IDF_CTO,b.IDF_CTO), isnull(a.COD_GL,b.COD_GL), isnull(a.DES_GL,b.DES_GL), isnull(a.COD_ACCO_CENT,b.COD_ACCO_CENT),
    isnull(a.COD_OFFI,b.COD_OFFI), isnull(a.COD_BLCE_STATUS,b.COD_BLCE_STATUS), 'CAP_RSL_PROV' AS COD_VALUE, isnull(a.COD_CURRENCY,b.COD_CURRENCY), isnull(a.COD_ENTITY,b.COD_ENTITY),
    isnull(a.COD_PRODUCT,b.COD_PRODUCT), ISNULL(d.COD_SUBPRODUCT,e.COD_SUBPRODUCT), isnull(a.COD_ACT_TYPE,b.COD_ACT_TYPE), NULL AS EOPBAL_CAP, NULL AS EOPBAL_INT, a.AVGBAL_CAP, a.AVGBAL_INT, 
    CAST(((ISNULL(a.EOPBAL_CAP,0) - IFNULL(b.EOPBAL_CAP, 0))) * -1 + isnull(c.VAL_CASTIGADO,0) AS decimal(30, 10)) AS PL, isnull(a.COD_INFO_SOURCE,b.COD_INFO_SOURCE), '${var:periodo}'  --PL=CAP_ACTUAL-CAP_ANTERIOR
FROM (
	SELECT *
	FROM MIS_APR_PROVISIONS_M
	WHERE DATA_DATE = '${var:periodo}' AND COD_VALUE = 'CAP_PROV') a 
LEFT JOIN (SELECT * from MIS_APR_CONTRACT_DT WHERE DATA_DATE = '${var:periodo}') d
ON a.IDF_CTO = d.IDF_CTO
FULL JOIN (SELECT * FROM MIS_APR_PROVISIONS_M WHERE TO_TIMESTAMP(DATA_DATE, 'yyyyMMdd') = DATE_SUB(TRUNC(TO_TIMESTAMP('${var:periodo}', 'yyyyMMdd'),'MM'), 1) AND COD_VALUE = 'CAP_PROV') b
ON a.COD_VALUE = b.COD_VALUE
    AND a.IDF_CTO = b.IDF_CTO AND a.COD_ENTITY = b.COD_ENTITY AND a.COD_CURRENCY = b.COD_CURRENCY
LEFT JOIN (SELECT * from MIS_APR_CONTRACT_DT WHERE TO_TIMESTAMP(DATA_DATE, 'yyyyMMdd') = DATE_SUB(TRUNC(TO_TIMESTAMP('${var:periodo}', 'yyyyMMdd'),'MM'), 1)) e
ON b.IDF_CTO = e.IDF_CTO
LEFT JOIN (SELECT * FROM MIS_PAR_CASTIGOS WHERE strleft(fecha_castigo,6) = strleft('${var:periodo}',6)) c
ON b.IDF_cTO = c.CONTRATO
;

----Aprovisionamiento de Provisiones Resultados - interes
INSERT INTO MIS_APR_PROVISIONS_M 
PARTITION (DATA_DATE) 
SELECT isnull(a.COD_CONT,b.COD_CONT), isnull(a.IDF_CTO,b.IDF_CTO), isnull(a.COD_GL,b.COD_GL), isnull(a.DES_GL,b.DES_GL), isnull(a.COD_ACCO_CENT,b.COD_ACCO_CENT),
    isnull(a.COD_OFFI,b.COD_OFFI), isnull(a.COD_BLCE_STATUS,b.COD_BLCE_STATUS), 'INT_RSL_PROV' AS COD_VALUE, isnull(a.COD_CURRENCY,b.COD_CURRENCY), isnull(a.COD_ENTITY,b.COD_ENTITY),
    isnull(a.COD_PRODUCT,b.COD_PRODUCT), isnull(d.COD_SUBPRODUCT,e.COD_SUBPRODUCT), isnull(a.COD_ACT_TYPE,b.COD_ACT_TYPE), NULL AS EOPBAL_CAP, NULL AS EOPBAL_INT, a.AVGBAL_CAP, a.AVGBAL_INT, 
    CAST((ISNULL(a.EOPBAL_CAP,0) - IFNULL(b.EOPBAL_CAP, 0)) * -1 AS decimal(30, 10)) AS PL, isnull(a.COD_INFO_SOURCE,b.COD_INFO_SOURCE), '${var:periodo}'  --PL=CAP_ACTUAL-CAP_ANTERIOR
FROM (
	SELECT *
	FROM MIS_APR_PROVISIONS_M
	WHERE DATA_DATE = '${var:periodo}' AND COD_VALUE = 'INT_PROV') a 
LEFT JOIN (SELECT * FROM MIS_APR_CONTRACT_DT WHERE DATA_DATE = '${var:periodo}') d
ON a.IDF_CTO  = d.IDF_CTO
FULL JOIN (SELECT * FROM MIS_APR_PROVISIONS_M WHERE TO_TIMESTAMP(DATA_DATE, 'yyyyMMdd') = DATE_SUB(TRUNC(TO_TIMESTAMP('${var:periodo}', 'yyyyMMdd'),'MM'), 1) AND COD_VALUE = 'INT_PROV') b
ON a.COD_VALUE = b.COD_VALUE
    AND a.IDF_CTO = b.IDF_CTO AND a.COD_ENTITY = b.COD_ENTITY AND a.COD_CURRENCY = b.COD_CURRENCY
LEFT JOIN (SELECT * from MIS_APR_CONTRACT_DT WHERE TO_TIMESTAMP(DATA_DATE, 'yyyyMMdd') = DATE_SUB(TRUNC(TO_TIMESTAMP('${var:periodo}', 'yyyyMMdd'),'MM'), 1)) e
ON b.IDF_CTO = e.IDF_CTO
;

----Aprovisionamiento de Provisiones Resultados - riesgo pais
INSERT INTO MIS_APR_PROVISIONS_M 
PARTITION (DATA_DATE) 
SELECT isnull(a.COD_CONT,b.COD_CONT), isnull(a.IDF_CTO,b.IDF_CTO), isnull(a.COD_GL,b.COD_GL), isnull(a.DES_GL,b.DES_GL), isnull(a.COD_ACCO_CENT,b.COD_ACCO_CENT),
    isnull(a.COD_OFFI,b.COD_OFFI), isnull(a.COD_BLCE_STATUS,b.COD_BLCE_STATUS), 'RPA_RSL_PROV' AS COD_VALUE, isnull(a.COD_CURRENCY,b.COD_CURRENCY), isnull(a.COD_ENTITY,b.COD_ENTITY),
    isnull(a.COD_PRODUCT,b.COD_PRODUCT), isnull(d.COD_SUBPRODUCT,e.COD_SUBPRODUCT), isnull(a.COD_ACT_TYPE,b.COD_ACT_TYPE), NULL AS EOPBAL_CAP, NULL AS EOPBAL_INT, a.AVGBAL_CAP, a.AVGBAL_INT, 
    CAST((ISNULL(a.EOPBAL_CAP,0) - IFNULL(b.EOPBAL_CAP, 0)) * -1 AS decimal(30, 10)) AS PL, isnull(a.COD_INFO_SOURCE,b.COD_INFO_SOURCE), '${var:periodo}'  --PL=CAP_ACTUAL-CAP_ANTERIOR
FROM (
	SELECT *
	FROM MIS_APR_PROVISIONS_M
	WHERE DATA_DATE = '${var:periodo}' AND COD_VALUE = 'RPA_PROV') a 
LEFT JOIN (SELECT * FROM MIS_APR_CONTRACT_DT WHERE DATA_DATE = '${var:periodo}') d
ON a.IDF_CTO  = d.IDF_CTO
FULL JOIN (SELECT * FROM MIS_APR_PROVISIONS_M WHERE TO_TIMESTAMP(DATA_DATE, 'yyyyMMdd') = DATE_SUB(TRUNC(TO_TIMESTAMP('${var:periodo}', 'yyyyMMdd'),'MM'), 1) AND COD_VALUE = 'RPA_PROV') b
ON a.COD_VALUE = b.COD_VALUE
    AND a.IDF_CTO = b.IDF_CTO AND a.COD_ENTITY = b.COD_ENTITY AND a.COD_CURRENCY = b.COD_CURRENCY
LEFT JOIN (SELECT * from MIS_APR_CONTRACT_DT WHERE TO_TIMESTAMP(DATA_DATE, 'yyyyMMdd') = DATE_SUB(TRUNC(TO_TIMESTAMP('${var:periodo}', 'yyyyMMdd'),'MM'), 1)) e
ON b.IDF_CTO = e.IDF_CTO
;

--- Registros de Capital (Deterioro) ---

INSERT INTO MIS_APR_PROVISIONS_M
PARTITION (DATA_DATE='${var:periodo}')
SELECT 'PROV' AS COD_CONT, a.CONTRATO AS IDF_CTO, NULL AS COD_GL, NULL AS DES_GL, NULL AS COD_ACCO_CENT, NULL AS COD_OFFI,
    '1' AS COD_BLCE_STATUS, 'CAP_PROV_INV' AS COD_VALUE, 'USD' AS COD_CURRENCY, c.COD_ENTITY AS COD_ENTITY, c.COD_PRODUCT AS COD_PRODUCT, C.COD_SUBPRODUCT AS COD_SUBPRODUCT, C.COD_ACT_TYPE AS COD_ACT_TYPE,
    CAST(a.DETERIORO * -1 AS DECIMAL(30,10)) AS EOPBAL_CAP,
    NULL AS EOPBAL_INT, NULL AS AVGBAL_CAP, NULL AVGBAL_INT, NULL AS PL, 'PROV_INT' COD_INFO_SOURCE 
FROM (
	SELECT a.*
	FROM MIS_LOAD_PROV_INV a
	WHERE DATA_DATE = '${var:periodo}' AND DETERIORO IS NOT NULL) a 
LEFT JOIN 
(
	SELECT a.*
	FROM MIS_LOAD_PROV_INV a
	WHERE DETERIORO IS NOT NULL AND TO_TIMESTAMP(DATA_DATE,'yyyyMMdd') = DAYS_SUB(TRUNC(TO_TIMESTAMP('${var:periodo}','yyyyMMdd'),'MM'),1)) b
	ON a.CONTRATO = b.CONTRATO
LEFT JOIN (SELECT DISTINCT IDF_CTO, COD_PRODUCT, COD_SUBPRODUCT, COD_ENTITY, COD_ACT_TYPE
           FROM MIS_APR_CONTRACT_DT
           WHERE DATA_DATE = '${var:periodo}'
           ) c
           ON a.CONTRATO = c.IDF_CTO
    WHERE c.IDF_CTO IS NOT NULL
	;


--- Registros de P&G (Deterioro) ---

INSERT INTO MIS_APR_PROVISIONS_M
PARTITION (DATA_DATE='${var:periodo}')
SELECT 'PROV' AS COD_CONT, isnull(a.CONTRATO,b.CONTRATO) AS IDF_CTO, NULL AS COD_GL, NULL AS DES_GL, NULL AS COD_ACCO_CENT, NULL AS COD_OFFI,
    '1' AS COD_BLCE_STATUS, 'RSL_PROV_INV' AS COD_VALUE, 'USD' AS COD_CURRENCY, isnull(c.COD_ENTITY,d.COD_ENTITY) AS COD_ENTITY, 
    isnull(c.COD_PRODUCT,d.COD_PRODUCT) AS COD_PRODUCT, isnull(c.COD_SUBPRODUCT,d.COD_SUBPRODUCT) AS COD_SUBPRODUCT, isnull(c.COD_ACT_TYPE,d.COD_ACT_TYPE) AS COD_ACT_TYPE,
    NULL AS EOPBAL_CAP,
    NULL AS EOPBAL_INT, NULL AS AVGBAL_CAP, NULL AVGBAL_INT, CAST((IFNULL(a.DETERIORO,0)-IFNULL(b.DETERIORO,0)) AS DECIMAL(30,10)) AS PL, 'PROV_INT' COD_INFO_SOURCE 
FROM (
	SELECT a.*
	FROM MIS_LOAD_PROV_INV a
	WHERE DATA_DATE = '${var:periodo}' AND DETERIORO IS NOT NULL) a 
LEFT JOIN (SELECT DISTINCT IDF_CTO, COD_PRODUCT, COD_SUBPRODUCT, COD_ENTITY, COD_ACT_TYPE 
           FROM MIS_APR_CONTRACT_DT
           WHERE DATA_DATE = '${var:periodo}'
           ) c
           ON a.CONTRATO = c.IDF_CTO
FULL JOIN 
(
	SELECT a.*
	FROM MIS_LOAD_PROV_INV a
	WHERE DETERIORO IS NOT NULL AND TO_TIMESTAMP(DATA_DATE,'yyyyMMdd') = DAYS_SUB(TRUNC(TO_TIMESTAMP('${var:periodo}','yyyyMMdd'),'MM'),1)
	) b
	ON a.CONTRATO = b.CONTRATO
LEFT JOIN (SELECT DISTINCT IDF_CTO, COD_PRODUCT, COD_SUBPRODUCT, COD_ENTITY, COD_ACT_TYPE 
           FROM MIS_APR_CONTRACT_DT
           WHERE TO_TIMESTAMP(DATA_DATE,'yyyyMMdd') = DAYS_SUB(TRUNC(TO_TIMESTAMP('${var:periodo}','yyyyMMdd'),'MM'),1)
           ) d
           ON b.CONTRATO = d.IDF_CTO	
	;

--- Registros de Capital (RPT) ---

INSERT INTO MIS_APR_PROVISIONS_M
PARTITION (DATA_DATE='${var:periodo}')
SELECT 'PROV' AS COD_CONT, a.CONTRATO AS IDF_CTO, NULL AS COD_GL, NULL AS DES_GL, NULL AS COD_ACCO_CENT, NULL AS COD_OFFI,
    '1' AS COD_BLCE_STATUS, 'RPT_CAP_PROV_INV' AS COD_VALUE, 'USD' AS COD_CURRENCY, c.COD_ENTITY AS COD_ENTITY, c.COD_PRODUCT AS COD_PRODUCT, C.COD_SUBPRODUCT AS COD_SUBPRODUCT, C.COD_ACT_TYPE AS COD_ACT_TYPE,
    CAST(a.RIESGO_PAIS_VS_NIIF * -1 AS DECIMAL(30,10)) AS EOPBAL_CAP,
    NULL AS EOPBAL_INT, NULL AS AVGBAL_CAP, NULL AVGBAL_INT, NULL AS PL, 'PROV_INT' COD_INFO_SOURCE 
FROM (
	SELECT a.*
	FROM MIS_LOAD_PROV_INV a
	WHERE DATA_DATE = '${var:periodo}' AND RIESGO_PAIS_VS_NIIF IS NOT NULL) a 
LEFT JOIN 
(
	SELECT a.*
	FROM MIS_LOAD_PROV_INV a
	WHERE RIESGO_PAIS_VS_NIIF IS NOT NULL AND TO_TIMESTAMP(DATA_DATE,'yyyyMMdd') = DAYS_SUB(TRUNC(TO_TIMESTAMP('${var:periodo}','yyyyMMdd'),'MM'),1)) b
	ON a.CONTRATO = b.CONTRATO
LEFT JOIN (SELECT DISTINCT IDF_CTO, COD_PRODUCT, COD_SUBPRODUCT, COD_ENTITY, COD_ACT_TYPE 
           FROM MIS_APR_CONTRACT_DT
           WHERE DATA_DATE = '${var:periodo}'
           ) c
           ON a.CONTRATO = c.IDF_CTO
    WHERE c.IDF_CTO IS NOT NULL
	;


--- Registros de P&G (RPT) ---

INSERT INTO MIS_APR_PROVISIONS_M
PARTITION (DATA_DATE='${var:periodo}')
SELECT 'PROV' AS COD_CONT, isnull(a.CONTRATO,b.CONTRATO) AS IDF_CTO, NULL AS COD_GL, NULL AS DES_GL, NULL AS COD_ACCO_CENT, NULL AS COD_OFFI,
    '1' AS COD_BLCE_STATUS, 'RPT_RSL_PROV_INV' AS COD_VALUE, 'USD' AS COD_CURRENCY, isnull(c.COD_ENTITY,d.COD_ENTITY) AS COD_ENTITY, 
    isnull(c.COD_PRODUCT,d.COD_PRODUCT) AS COD_PRODUCT, isnull(c.COD_SUBPRODUCT,d.COD_SUBPRODUCT) AS COD_SUBPRODUCT, isnull(c.COD_ACT_TYPE,d.COD_ACT_TYPE) AS COD_ACT_TYPE,
    NULL AS EOPBAL_CAP,
    NULL AS EOPBAL_INT, NULL AS AVGBAL_CAP, NULL AVGBAL_INT, CAST((IFNULL(a.RIESGO_PAIS_VS_NIIF,0)-IFNULL(b.RIESGO_PAIS_VS_NIIF,0)) AS DECIMAL(30,10)) AS PL, 'PROV_INT' COD_INFO_SOURCE 
FROM (
	SELECT a.*
	FROM MIS_LOAD_PROV_INV a
	WHERE DATA_DATE = '${var:periodo}' AND RIESGO_PAIS_VS_NIIF IS NOT NULL) a 
LEFT JOIN (SELECT DISTINCT IDF_CTO, COD_PRODUCT, COD_SUBPRODUCT, COD_ENTITY, COD_ACT_TYPE 
           FROM MIS_APR_CONTRACT_DT
           WHERE DATA_DATE = '${var:periodo}'
           ) c
           ON a.CONTRATO = c.IDF_CTO
FULL JOIN 
(
	SELECT a.*
	FROM MIS_LOAD_PROV_INV a
	WHERE RIESGO_PAIS_VS_NIIF IS NOT NULL AND TO_TIMESTAMP(DATA_DATE,'yyyyMMdd') = DAYS_SUB(TRUNC(TO_TIMESTAMP('${var:periodo}','yyyyMMdd'),'MM'),1)) b
	ON a.CONTRATO = b.CONTRATO
LEFT JOIN (SELECT DISTINCT IDF_CTO, COD_PRODUCT, COD_SUBPRODUCT, COD_ENTITY, COD_ACT_TYPE 
           FROM MIS_APR_CONTRACT_DT
           WHERE DATA_DATE = '${var:periodo}'
           ) d
           ON b.CONTRATO = d.IDF_CTO
	;