--------------------------------------------------------------- MIS_APR_PROVISIONS --------------------------------------------------------

USE ${var:base_datos};
SET DECIMAL_V2=FALSE;

----Carga de tablas load
TRUNCATE TABLE IF EXISTS MIS_LOAD_DISTRI_CTAS_NIFF; 
LOAD DATA INPATH '${var:ruta_fuentes_provisiones}/TBL_DISTRI_CTAS_NIFF.csv' INTO TABLE MIS_LOAD_DISTRI_CTAS_NIFF;

TRUNCATE TABLE IF EXISTS mis_load_reporte_final_hist_bc; 
LOAD DATA INPATH '${var:ruta_fuentes_provisiones}/TBL_REPORTE_FINAL_HIST_BC.csv' INTO TABLE mis_load_reporte_final_hist_bc;

--Limpieza de partición del día en ejecución
ALTER TABLE MIS_APR_PROVISIONS_M
DROP IF EXISTS PARTITION (DATA_DATE = '${var:periodo}');

--COMPUTE STATS MIS_LOAD_DISTRI_CTAS_NIFF;
--COMPUTE STATS mis_load_reporte_final_hist_bc;

----Aprovisionamiento de Provisiones Capital
INSERT INTO MIS_APR_PROVISIONS_M
PARTITION (DATA_DATE='${var:periodo}') 
SELECT 'PROV' AS COD_CONT, a.IDF_CTO, RPAD(strleft(CTA_CONSOL_CAP,12),16,'0') AS COD_GL, NULL AS DES_GL, strright(CTA_CONSOL_CAP,3) AS COD_ACCO_CENT, strright(CTA_CONSOL_CAP,3) AS COD_OFFI, ESTATUS AS COD_BLCE_STATUS, 'CAP' AS COD_VALUE, 'HNL' AS COD_CURRENCY, '1' AS COD_ENTITY, 
CASE WHEN a.COD_SUBPRODUCT LIKE '130%' THEN b.COD_PRODUCT ELSE a.COD_PRODUCT END AS COD_PRODUCT, 
CASE WHEN a.COD_SUBPRODUCT LIKE '130%' THEN CONCAT(b.COD_SUBPRODUCT,'_PROV') ELSE a.COD_SUBPRODUCT END AS COD_SUBPRODUCT, IFNULL(NULL, '') COD_ACT_TYPE, CAST(-1 * EOPBAL_CAP AS DECIMAL(30,10)) AS EOPBAL_CAP, 
NULL AS EOPBAL_INT, NULL AS AVGBAL_CAP, NULL AS AVGBAL_INT, NULL AS PL, 'NIFF' AS COD_INFO_SOURCE
FROM MIS_LOAD_DISTRI_CTAS_NIFF a
LEFT JOIN (SELECT * FROM MIS_APR_CONTRACT_DT WHERE DATA_DATE = '${var:periodo}') b
ON a.IDF_CTO = b.IDF_CTO
;

----Aprovisionamiento de Provisiones Intereses
INSERT INTO MIS_APR_PROVISIONS_M
PARTITION (DATA_DATE='${var:periodo}') 
SELECT 'PROV' AS COD_CONT, a.IDF_CTO, RPAD(strleft(CTA_CONSOL_INT,12),16,'0') AS COD_GL, NULL AS DES_GL, strright(CTA_CONSOL_INT,3) AS COD_ACCO_CENT, strright(CTA_CONSOL_INT,3) AS COD_OFFI, ESTATUS AS COD_BLCE_STATUS, 'INT' AS COD_VALUE, 'HNL' AS COD_CURRENCY, '1' AS COD_ENTITY, 
CASE WHEN a.COD_SUBPRODUCT LIKE '130%' THEN b.COD_PRODUCT ELSE a.COD_PRODUCT END AS COD_PRODUCT, 
CASE WHEN a.COD_SUBPRODUCT LIKE '130%' THEN CONCAT(b.COD_SUBPRODUCT,'_PROV') ELSE a.COD_SUBPRODUCT END AS COD_SUBPRODUCT, IFNULL(NULL, '') COD_ACT_TYPE, CAST(-1 * EOPBAL_INT AS DECIMAL(30,10)) AS EOPBAL_CAP, 
NULL AS EOPBAL_INT, NULL AS AVGBAL_CAP, NULL AS AVGBAL_INT, NULL AS PL, 'NIFF' AS COD_INFO_SOURCE
FROM MIS_LOAD_DISTRI_CTAS_NIFF a
LEFT JOIN (SELECT * FROM MIS_APR_CONTRACT_DT WHERE DATA_DATE = '${var:periodo}') b
ON a.IDF_CTO = b.IDF_CTO
;

----Aprovisionamiento de Provisiones Resultados
INSERT INTO MIS_APR_PROVISIONS_M 
PARTITION (DATA_DATE='${var:periodo}') 
SELECT 'PROV' AS COD_CONT, NUMERO_OPERACION AS IDF_CTO, NULL AS COD_GL, NULL AS DES_GL, CENTRO_COSTO AS COD_ACCO_CENT, CENTRO_COSTO AS COD_OFFI, 'VIG' AS COD_BLCE_STATUS, 'RSL' AS COD_VALUE, 'HNL' AS COD_CURRENCY, '1' AS COD_ENTITY, 
CASE WHEN UPPER(CARTERA) LIKE 'TAR%' THEN b.COD_PRODUCT ELSE a.PRODUCTO END AS COD_PRODUCT, 
CASE WHEN UPPER(CARTERA) LIKE 'TAR%' THEN CONCAT(b.COD_SUBPRODUCT,'_PROV') ELSE CONCAT('PROV_',STRLEFT(CARTERA,3)) END AS COD_SUBPRODUCT, IFNULL(NULL, '') COD_ACT_TYPE, NULL AS EOPBAL_CAP, 
NULL AS EOPBAL_INT, NULL AS AVGBAL_CAP, NULL AS AVGBAL_INT, CAST(ISNULL(TOTAL_GASTO,0) AS DECIMAL(30,10)) AS PL, 'NIFF' AS COD_INFO_SOURCE
FROM MIS_LOAD_REPORTE_FINAL_HIST_BC a
LEFT JOIN (SELECT * FROM MIS_APR_CONTRACT_DT WHERE DATA_DATE = '${var:periodo}') b
ON a.NUMERO_OPERACION = b.IDF_CTO
WHERE FECHA_DE_PROCESO_F = '${var:periodo}'
;