---------- MOTOR DE GESTION DE INFORMACION ----------

--- Uso de la base de datos correcta ---
USE ${var:base_datos};
SET DECIMAL_V2=FALSE;

--- Borrado de Tablas Diarias ---
ALTER TABLE MIS_REJECTIONS_DIMENSIONS 
DROP IF EXISTS PARTITION (DATA_DATE = '${var:periodo}');

TRUNCATE TABLE IF EXISTS MIS_REJECTIONS_DIMENSIONS_NULL;

ALTER TABLE MIS_APR_MV
DROP IF EXISTS PARTITION (DATA_DATE = FROM_TIMESTAMP(ADD_MONTHS(TO_TIMESTAMP('${var:periodo}','yyyyMMdd'),-13),'yyyyMMdd'));

ALTER TABLE MIS_PAR_EXCH_RATE
DROP IF EXISTS PARTITION (DATA_DATE = FROM_TIMESTAMP(ADD_MONTHS(TO_TIMESTAMP('${var:periodo}','yyyyMMdd'),-13),'yyyyMMdd'));

ALTER TABLE MIS_APR_ACCOUNTING
DROP IF EXISTS PARTITION (DATA_DATE = FROM_TIMESTAMP(ADD_MONTHS(TO_TIMESTAMP('${var:periodo}','yyyyMMdd'),-13),'yyyyMMdd'));

ALTER TABLE MIS_APR_ASSETS
DROP IF EXISTS PARTITION (DATA_DATE = FROM_TIMESTAMP(ADD_MONTHS(TO_TIMESTAMP('${var:periodo}','yyyyMMdd'),-13),'yyyyMMdd'));

ALTER TABLE MIS_APR_LIABILITIES
DROP IF EXISTS PARTITION (DATA_DATE = FROM_TIMESTAMP(ADD_MONTHS(TO_TIMESTAMP('${var:periodo}','yyyyMMdd'),-13),'yyyyMMdd'));

ALTER TABLE MIS_APR_FEES
DROP IF EXISTS PARTITION (DATA_DATE = FROM_TIMESTAMP(ADD_MONTHS(TO_TIMESTAMP('${var:periodo}','yyyyMMdd'),-13),'yyyyMMdd'));

ALTER TABLE MIS_APR_OFF_BALANCE
DROP IF EXISTS PARTITION (DATA_DATE = FROM_TIMESTAMP(ADD_MONTHS(TO_TIMESTAMP('${var:periodo}','yyyyMMdd'),-13),'yyyyMMdd'));

ALTER TABLE MIS_APR_CLIENT_DT
DROP IF EXISTS PARTITION (DATA_DATE = FROM_TIMESTAMP(ADD_MONTHS(TO_TIMESTAMP('${var:periodo}','yyyyMMdd'),-13),'yyyyMMdd'));

ALTER TABLE MIS_APR_CONTRACT_DT
DROP IF EXISTS PARTITION (DATA_DATE = FROM_TIMESTAMP(ADD_MONTHS(TO_TIMESTAMP('${var:periodo}','yyyyMMdd'),-13),'yyyyMMdd'));

ALTER TABLE MIS_DM_BALANCE_RESULT
DROP IF EXISTS PARTITION (DATA_DATE = FROM_TIMESTAMP(ADD_MONTHS(TO_TIMESTAMP('${var:periodo}','yyyyMMdd'),-24),'yyyyMMdd'));

ALTER TABLE MIS_DWH_ACCOUNTING
DROP IF EXISTS PARTITION (DATA_DATE = FROM_TIMESTAMP(ADD_MONTHS(TO_TIMESTAMP('${var:periodo}','yyyyMMdd'),-13),'yyyyMMdd'));

ALTER TABLE MIS_DWH_ASSETS
DROP IF EXISTS PARTITION (DATA_DATE = FROM_TIMESTAMP(ADD_MONTHS(TO_TIMESTAMP('${var:periodo}','yyyyMMdd'),-13),'yyyyMMdd'));

ALTER TABLE MIS_DWH_LIABILITIES
DROP IF EXISTS PARTITION (DATA_DATE = FROM_TIMESTAMP(ADD_MONTHS(TO_TIMESTAMP('${var:periodo}','yyyyMMdd'),-13),'yyyyMMdd'));

ALTER TABLE MIS_DWH_FEES
DROP IF EXISTS PARTITION (DATA_DATE = FROM_TIMESTAMP(ADD_MONTHS(TO_TIMESTAMP('${var:periodo}','yyyyMMdd'),-13),'yyyyMMdd'));

ALTER TABLE MIS_DWH_OFF_BALANCE
DROP IF EXISTS PARTITION (DATA_DATE = FROM_TIMESTAMP(ADD_MONTHS(TO_TIMESTAMP('${var:periodo}','yyyyMMdd'),-13),'yyyyMMdd'));

ALTER TABLE MIS_DWH_RECONCILIATION
DROP IF EXISTS PARTITION (DATA_DATE = FROM_TIMESTAMP(ADD_MONTHS(TO_TIMESTAMP('${var:periodo}','yyyyMMdd'),-13),'yyyyMMdd'));