--------------------------------------------------- MOTOR DE TARJETAS ADICIONALES -----------------------------------------------------------



USE ${var:base_datos};
SET DECIMAL_V2=FALSE;


/*
TRUNCATE TABLE IF EXISTS MIS_LOAD_TARJETAS_ADICIONALES; 
LOAD DATA INPATH '${var:ruta_fuentes_activos}/TarjetasAdicionales.csv' INTO TABLE MIS_LOAD_TARJETAS_ADICIONALES;


INSERT INTO MIS_DM_BALANCE_RESULT 
    (IDF_CTO, CARD_NUMBER, COD_PRODUCT, DES_PROG_CARD, NOM_NAME, NUM_DOC_ID, DATE_DISB, INI_AM, COD_MANAGER, COD_EXEC_CTO, COD_BLCE_PROD, COD_INFO_SOURCE)
PARTITION (DATA_DATE)
SELECT 
    CONCAT(a.CUENTA_TARJETA, '_A') AS IDF_CTO, a.TARJETA AS CARD_NUMBER, a.TIPO AS COD_PRODUCT, a.PROGRAMA AS DES_PROG_CARD, a.NOMBRE AS 
    NOM_NAME, a.CEDULA AS NUM_DOC_ID, a.FECHA AS DATE_DISB, a.MONTO AS INI_AM, a.ENTE_TC AS COD_MANAGER, a.ENTE_TC AS COD_EXEC_CTO, 
    UPPER(TRIM(b.NOMBRE_BIN)) AS COD_BLCE_PROD, 'VPSPLAST' AS COD_INFO_SOURCE, '${var:periodo}' AS DATA_DATE
FROM MIS_LOAD_TARJETAS_ADICIONALES a
LEFT JOIN MIS_LOAD_INFO_TRABAJO b
ON STRLEFT(TRIM(a.TARJETA), 6) = TRIM(b.BIN)
;
*/