---------- MOTOR DE GESTION DE INFORMACION ----------


--- Uso de la base de datos correcta ---
USE ${var:base_datos};
SET DECIMAL_V2=FALSE;

--- Borrado de Tablas Diarias ---
TRUNCATE TABLE MIS_REJECTIONS_DIMENSIONS;

ALTER TABLE MIS_APR_ACCOUNTING
DROP IF EXISTS PARTITION (DATA_DATE = FROM_TIMESTAMP(ADD_MONTHS(TO_TIMESTAMP('${var:periodo}','yyyyMMdd'),-2),'yyyyMMdd'));

ALTER TABLE MIS_APR_ASSETS
DROP IF EXISTS PARTITION (DATA_DATE = FROM_TIMESTAMP(ADD_MONTHS(TO_TIMESTAMP('${var:periodo}','yyyyMMdd'),-2),'yyyyMMdd'));

ALTER TABLE MIS_APR_CLIENT_DT
DROP IF EXISTS PARTITION (DATA_DATE = FROM_TIMESTAMP(ADD_MONTHS(TO_TIMESTAMP('${var:periodo}','yyyyMMdd'),-2),'yyyyMMdd'));

ALTER TABLE MIS_APR_CONTRACT_DT
DROP IF EXISTS PARTITION (DATA_DATE = FROM_TIMESTAMP(ADD_MONTHS(TO_TIMESTAMP('${var:periodo}','yyyyMMdd'),-2),'yyyyMMdd'));

ALTER TABLE MIS_DM_BALANCE_RESULT
DROP IF EXISTS PARTITION (DATA_DATE = FROM_TIMESTAMP(ADD_MONTHS(TO_TIMESTAMP('${var:periodo}','yyyyMMdd'),-12),'yyyyMMdd'));

ALTER TABLE MIS_DWH_ACCOUNTING
DROP IF EXISTS PARTITION (DATA_DATE = FROM_TIMESTAMP(ADD_MONTHS(TO_TIMESTAMP('${var:periodo}','yyyyMMdd'),-2),'yyyyMMdd'));

ALTER TABLE MIS_DWH_ASSETS
DROP IF EXISTS PARTITION (DATA_DATE = FROM_TIMESTAMP(ADD_MONTHS(TO_TIMESTAMP('${var:periodo}','yyyyMMdd'),-2),'yyyyMMdd'));

ALTER TABLE MIS_DWH_RECONCILIATION
DROP IF EXISTS PARTITION (DATA_DATE = FROM_TIMESTAMP(ADD_MONTHS(TO_TIMESTAMP('${var:periodo}','yyyyMMdd'),-2),'yyyyMMdd'));


--- Borrado de Tablas Mensuales ---
ALTER TABLE MIS_APR_ACCOUNTING_M
DROP IF EXISTS PARTITION (DATA_DATE = FROM_TIMESTAMP(ADD_MONTHS(TO_TIMESTAMP('${var:periodo}','yyyyMMdd'),-12),'yyyyMMdd'));

ALTER TABLE MIS_APR_ASSETS_M
DROP IF EXISTS PARTITION (DATA_DATE = FROM_TIMESTAMP(ADD_MONTHS(TO_TIMESTAMP('${var:periodo}','yyyyMMdd'),-12),'yyyyMMdd'));

ALTER TABLE MIS_APR_CLIENT_DT_M
DROP IF EXISTS PARTITION (DATA_DATE = FROM_TIMESTAMP(ADD_MONTHS(TO_TIMESTAMP('${var:periodo}','yyyyMMdd'),-12),'yyyyMMdd'));

ALTER TABLE MIS_APR_CONTRACT_DT_M
DROP IF EXISTS PARTITION (DATA_DATE = FROM_TIMESTAMP(ADD_MONTHS(TO_TIMESTAMP('${var:periodo}','yyyyMMdd'),-12),'yyyyMMdd'));

ALTER TABLE MIS_DM_BALANCE_RESULT_M
DROP IF EXISTS PARTITION (DATA_DATE = FROM_TIMESTAMP(ADD_MONTHS(TO_TIMESTAMP('${var:periodo}','yyyyMMdd'),-60),'yyyyMMdd'));

ALTER TABLE MIS_DWH_ACCOUNTING_M
DROP IF EXISTS PARTITION (DATA_DATE = FROM_TIMESTAMP(ADD_MONTHS(TO_TIMESTAMP('${var:periodo}','yyyyMMdd'),-12),'yyyyMMdd'));

ALTER TABLE MIS_DWH_ASSETS_M
DROP IF EXISTS PARTITION (DATA_DATE = FROM_TIMESTAMP(ADD_MONTHS(TO_TIMESTAMP('${var:periodo}','yyyyMMdd'),-12),'yyyyMMdd'));

ALTER TABLE MIS_DWH_RECONCILIATION_M
DROP IF EXISTS PARTITION (DATA_DATE = FROM_TIMESTAMP(ADD_MONTHS(TO_TIMESTAMP('${var:periodo}','yyyyMMdd'),-12),'yyyyMMdd'));