--------------------------------------------------------------- MIS_APR_EXPENSES ---------------------------------------------------------------

--- Seleccion de Base de datos de Ejecución ---
USE ${var:base_datos};
SET DECIMAL_V2=FALSE;

--- Eliminacion y Carga diaria de la tabla TRANS ---
TRUNCATE TABLE IF EXISTS MIS_LOAD_TRANS;
LOAD DATA INPATH '${var:ruta_fuentes_gastos}/TRANS.CSV' INTO TABLE MIS_LOAD_TRANS;

--- Eliminacion y Carga diaria de la tabla TRANSAJU ---
TRUNCATE TABLE IF EXISTS MIS_LOAD_TRANSAJU;
LOAD DATA INPATH '${var:ruta_fuentes_gastos}/TRANSAJU.CSV' INTO TABLE MIS_LOAD_TRANSAJU;

--- Limpieza de partición ----
ALTER TABLE MIS_APR_EXPENSES 
DROP IF EXISTS PARTITION (DATA_DATE = '${var:periodo}');

--- Aprovisionamiento de Información de P&G (Gastos) en la tabla definitiva ---
INSERT INTO MIS_APR_EXPENSES
PARTITION (DATA_DATE = '${var:periodo}')
SELECT a.COD_CONT, a.COD_GL, a.DES_GL, a.COD_ACCO_CENT, a.COD_EXPENSE, a.COD_OFFI, NULL AS COD_NAR, a.COD_BLCE_STATUS,
a.COD_CURRENCY, a.COD_ENTITY, NULL AS EOPBAL_CAP, NULL AS EOPBAL_INT, NULL AS AVGBAL_CAP, NULL AS AVGBAL_INT,
    CAST(SUM(a.PL) AS decimal(30, 10)) AS PL, a.COD_INFO_SOURCE
FROM (
SELECT 'EXP' AS COD_CONT, a.TRAGLN AS COD_GL, NULL AS DES_GL, a.TRACCN AS COD_ACCO_CENT, '' AS COD_EXPENSE, a.TRABRN AS COD_OFFI, NULL AS COD_NAR, 
	NULL AS COD_BLCE_STATUS, a.TRACCY AS COD_CURRENCY, a.TRABNK AS COD_ENTITY, 
	CAST((CASE WHEN TRIM(TRADCC) = '5' THEN TRAAMT*-1 ELSE TRAAMT END) AS decimal(30, 10)) AS PL, 'TRANS' COD_INFO_SOURCE 
FROM (
	SELECT a.TRAGLN, a.TRADCC, a.TRACCN, a.TRABRN, a.TRACCY, a.TRABNK, SUM(a.TRAAMT) AS TRAAMT 
	FROM MIS_LOAD_TRANS a
	WHERE STRLEFT(a.TRAGLN, 2) IN ('81')
	GROUP BY a.TRAGLN, a.TRADCC, a.TRACCN, a.TRABRN, a.TRACCY, a.TRABNK) a
UNION ALL
SELECT 'EXP' AS COD_CONT, a.TRAGLN AS COD_GL, NULL AS DES_GL, a.TRACCN AS COD_ACCO_CENT, '' AS COD_EXPENSE, a.TRABRN AS COD_OFFI, NULL AS COD_NAR, 
	NULL AS COD_BLCE_STATUS, a.TRACCY AS COD_CURRENCY, a.TRABNK AS COD_ENTITY, 
	CAST((CASE WHEN TRIM(TRADCC) = '5' THEN TRAAMT*-1 ELSE TRAAMT END) AS decimal(30, 10)) AS PL, 'TRANSAJU' COD_INFO_SOURCE FROM
	(
	SELECT a.TRAGLN, a.TRADCC, a.TRACCN, a.TRABRN, a.TRACCY, a.TRABNK, SUM(a.TRAAMT) AS TRAAMT 
	FROM MIS_LOAD_TRANSAJU a
	WHERE STRLEFT(a.TRAGLN, 2) IN ('81')
        AND CONCAT('20',a.TRAVDY, STRRIGHT(CONCAT('0',a.TRAVDM),2), STRRIGHT(CONCAT('0', a.TRAVDD),2)) = '${var:periodo}' 
	GROUP BY a.TRAGLN, a.TRADCC, a.TRACCN, a.TRABRN, a.TRACCY, a.TRABNK) AS a
UNION ALL
    --Contabilidad Gastos registrados en el dia anterior
    SELECT a.COD_CONT, a.COD_GL, a.DES_GL, a.COD_ACCO_CENT, a.COD_EXPENSE, a.COD_OFFI, a.COD_NAR, a.COD_BLCE_STATUS,
    a.COD_CURRENCY, a.COD_ENTITY, a.PL, a.COD_INFO_SOURCE
    FROM MIS_APR_EXPENSES a
    WHERE a.COD_INFO_SOURCE = 'TRANS' AND  
        DAY(TO_TIMESTAMP('${var:periodo}', 'yyyyMMdd')) > 1 AND 
        TO_TIMESTAMP(a.DATA_DATE, 'yyyyMMdd') = DAYS_SUB(TO_TIMESTAMP('${var:periodo}', 'yyyyMMdd'), 1)
) AS a 
GROUP BY a.COD_CONT, a.COD_GL, a.DES_GL, a.COD_ACCO_CENT, a.COD_EXPENSE, a.COD_OFFI, a.COD_NAR, a.COD_BLCE_STATUS,
a.COD_CURRENCY, a.COD_ENTITY, a.COD_INFO_SOURCE
;