--------------------------------------------------------------- MIS_APR_CLIENT_DT ---------------------------------------------------------------

--- Comando que dirige las consultas a la base de datos apropiada ---
USE ${var:base_datos};

----Carga de tablas load
TRUNCATE TABLE IF EXISTS MIS_LOAD_CUMST;  
LOAD DATA INPATH '${var:ruta_fuentes_clientes}/CUMST.CSV' INTO TABLE MIS_LOAD_CUMST;

TRUNCATE TABLE IF EXISTS MIS_LOAD_WFCUMST; 
LOAD DATA INPATH '${var:ruta_fuentes_clientes}/WFCUMST.CSV' INTO TABLE MIS_LOAD_WFCUMST;


ALTER TABLE MIS_APR_CLIENT_DT
DROP IF EXISTS PARTITION (DATA_DATE = '${var:periodo}');

----Aprovisionamiento de Clientes
INSERT INTO MIS_APR_CLIENT_DT
PARTITION (DATA_DATE='${var:periodo}')
SELECT TRIM(a.CUSCUN) AS IDF_CLI, TRIM(a.CUSTID) AS TYP_DOC_ID, TRIM(a.CUSLN3) AS NUM_DOC_ID,
 CASE WHEN cusinc in ('0404') AND cuslgt = '2' THEN CONCAT(TRIM(a.CUSFNA)," ",TRIM(a.CUSFN2)) ELSE TRIM(CUSNA1) END AS NOM_NAME, CASE WHEN cusinc in ('0404') AND cuslgt = '2' THEN CONCAT(TRIM(a.CUSLN1)," ",TRIM(a.CUSLN2)) ELSE NULL END AS NOM_LASTN,
  TRIM(a.CUSCTR) AS COD_RES_COUNT, a.CUSLGT AS COD_TYP_CLNT, a.CUSSTS AS COD_COND_CLNT, 
NULL AS COD_ENG, TRIM(a.CUSSEX) AS VAL_SEX, NULL AS COD_COUNTRY, NULL AS COD_SECTOR, NULL AS DES_SECTOR, c.CATEGORY AS COD_SEGMENT, c.CATEGORY AS DES_SEGMENT, 
NULL AS COD_SUBSEGMENT, NULL AS DES_SUBSEGMENT, TRIM(a.CUSSTF) AS IND_EMPL_GRUP, CASE WHEN a.CUSIDY=0 AND a.CUSIDM=0 AND a.CUSIDD=0 THEN NULL WHEN a.CUSIDM>12 OR a.CUSIDD>31 THEN NULL 
ELSE CONCAT(CASE WHEN CAST(STRRIGHT(CAST(YEAR(NOW()) AS string), 2) AS smallint) < a.CUSIDY 
THEN CONCAT('19', LPAD(CAST(a.CUSIDY AS string), 2, '0')) ELSE CONCAT('2', LPAD(CAST(a.CUSIDY AS string), 3, '0')) END, 
LPAD(CAST(a.CUSIDM AS string), 2, '0'), LPAD(CAST(a.CUSIDD  AS string), 2, '0')) END AS DATE_CLNT_REG, 
CASE WHEN a.CUSLDY=0 AND a.CUSLDM=0 AND a.CUSLDD=0 THEN NULL WHEN a.CUSLDM>12 OR a.CUSLDD>31 THEN NULL 
ELSE CONCAT(CASE WHEN CAST(STRRIGHT(CAST(YEAR(NOW()) AS string), 2) AS smallint) < a.CUSLDY 
THEN CONCAT('19', LPAD(CAST(a.CUSLDY AS string), 2, '0')) 
ELSE CONCAT('2', LPAD(CAST(a.CUSLDY AS string), 3, '0')) END, 
LPAD(CAST(a.CUSLDM AS string), 2, '0'), LPAD(CAST(a.CUSLDD  AS string), 2, '0')) END AS DATE_CLNT_WITHDRAW, TRIM(a.CUSOFC) AS COD_MANAGER, TRIM(b.CNODSC) AS DES_MANAGER,
TRIM(a.CUSRSL) AS RATING_CLI, NULL AS COD_GROUP_EC, a.CUSGRP AS ID_ECO_GRO, 'SV' AS COU_ECO_GRO, NULL AS IND_MUL_LAT, NULL AS FIELD1_CLI, NULL AS FIELD2_CLI, NULL AS FIELD3_CLI, NULL AS FIELD4_CLI, NULL AS FIELD5_CLI,
 NULL AS FIELD6_CLI, NULL AS FIELD7_CLI, NULL AS FIELD8_CLI, NULL AS FIELD9_CLI, NULL AS FIELD10_CLI, d.WFDU12 AS COD_SECTOR_LOCAL, NULL AS COD_SECTOR_REG, NULL AS DES_SECTOR_LOCAL, NULL AS DES_SECTOR_REG
FROM MIS_LOAD_CUMST a
LEFT JOIN (SELECT CNOOFC, CNODSC FROM MIS_LOAD_CNOFC WHERE CNOBNK IN ('10','15')) b
ON a.CUSOFC = b.CNOOFC
LEFT JOIN (SELECT DISTINCT CUSCUN, CATEGORY FROM SV_PRD_MIS.SEG_CUSTOMER WHERE DATA_DATE = '${var:periodo}') c
ON a.CUSCUN = c.CUSCUN
LEFT JOIN MIS_LOAD_WFCUMST d 
on  a.CUSCUN = d.WFCCUN 
;
