--------------------------------------------------------------- MIS_APR_ACCOUNTING_M ---------------------------------------------------------------

--- Comando que apunta a la base de datos apropiada ---
USE ${var:base_datos};
SET DECIMAL_V2=FALSE;

----Carga de tablas load
TRUNCATE TABLE IF EXISTS MIS_LOAD_BALCO;
LOAD DATA INPATH '${var:ruta_fuentes_contabilidad}/BALCO.CSV' INTO TABLE MIS_LOAD_BALCO;
TRUNCATE TABLE IF EXISTS MIS_LOAD_BAL_SEGUROS; 
LOAD DATA INPATH '${var:ruta_fuentes_contabilidad}/BAL_SEGUROS.CSV' INTO TABLE MIS_LOAD_BAL_SEGUROS;


--- Limpieza de partición ----
ALTER TABLE MIS_APR_ACCOUNTING_M 
DROP IF EXISTS PARTITION (DATA_DATE = '${var:periodo}');

--- PL_YTD: Acumulación del saldo PL anual ---
TRUNCATE TABLE IF EXISTS MIS_TMP_ACC_PL_M;
DROP TABLE IF EXISTS MIS_TMP_ACC_PL_M;
CREATE TABLE MIS_TMP_ACC_PL_M AS
SELECT A.COD_ENTITY, A.COD_GL, CAST(ROUND(SUM(A.PL), 10) AS decimal(30, 10)) AS PL 
FROM MIS_APR_ACCOUNTING_M A
INNER JOIN (
    SELECT DISTINCT FROM_TIMESTAMP(LAST_DAY(TO_TIMESTAMP(TMP.DATA_DATE, 'yyyyMMdd')), 'yyyyMMdd') AS LAST_MONTHS
    FROM MIS_APR_ACCOUNTING_M TMP
    WHERE YEAR(TO_TIMESTAMP(TMP.DATA_DATE, 'yyyyMMdd')) = YEAR(TO_TIMESTAMP('${var:periodo}', 'yyyyMMdd')) 
        AND MONTH(TO_TIMESTAMP(TMP.DATA_DATE, 'yyyyMMdd')) < MONTH(TO_TIMESTAMP('${var:periodo}', 'yyyyMMdd'))    
) AS B
ON A.DATA_DATE = B.LAST_MONTHS
GROUP BY A.COD_ENTITY, A.COD_GL
HAVING SUM(IFNULL(PL, 0)) != 0;

--- Aprovisionamiento de la entidad 4-Banco ---
INSERT INTO MIS_APR_ACCOUNTING_M
PARTITION (DATA_DATE = '${var:periodo}')
SELECT 'CONT' AS COD_CONT, RPAD(TRIM(a.CUENTA_LOCAL), 16, '0') AS COD_GL, TRIM(a.DESCRIPCION) AS DES_GL, 
    NULL AS COD_ACCO_CENT, NULL AS COD_OFFI, NULL AS COD_NAR, NULL AS COD_BLCE_STATUS, 'CRC' AS COD_CURRENCY, '4' AS COD_ENTITY,
    IF(STRLEFT(TRIM(a.CUENTA_LOCAL), 1) IN ('4', '5'), NULL, a.SALDO_BANEX) AS EOPBAL_CAP, 
    NULL AS EOPBAL_INT, NULL AS AVGBAL_CAP, NULL AS AVGBAL_INT,
    IF(STRLEFT(TRIM(a.CUENTA_LOCAL), 1) IN ('4', '5'), CAST((a.SALDO_BANEX) - IFNULL(b.PL, 0) AS decimal(30, 10)), NULL) AS PL, 
    'BALCO_BX' AS COD_INFO_SOURCE
FROM MIS_LOAD_BALCO a
LEFT JOIN MIS_TMP_ACC_PL_M b
ON RPAD(TRIM(a.CUENTA_LOCAL), 16, '0') = b.COD_GL AND b.COD_ENTITY = '4' 
WHERE TRIM(a.MOV) = 'S' 
;

--- Aprovisionamiento de la entidad 6-Corporación individual ---
INSERT INTO MIS_APR_ACCOUNTING_M
PARTITION (DATA_DATE = '${var:periodo}')
SELECT 'CONT' AS COD_CONT, RPAD(TRIM(a.CUENTA_LOCAL), 16, '0') AS COD_GL, TRIM(a.DESCRIPCION) AS DES_GL, 
    NULL AS COD_ACCO_CENT, NULL AS COD_OFFI, NULL AS COD_NAR, NULL AS COD_BLCE_STATUS, 'CRC' AS COD_CURRENCY, '6' AS COD_ENTITY,
    IF(STRLEFT(TRIM(a.CUENTA_LOCAL), 1) IN ('4', '5'), NULL, a.SALDO_CORP) AS EOPBAL_CAP, 
    NULL AS EOPBAL_INT, NULL AS AVGBAL_CAP, NULL AS AVGBAL_INT,
    IF(STRLEFT(TRIM(a.CUENTA_LOCAL), 1) IN ('4', '5'), CAST((a.SALDO_CORP) - IFNULL(b.PL, 0) AS decimal(30, 10)), NULL) AS PL, 
    'BALCO_BX' AS COD_INFO_SOURCE
FROM MIS_LOAD_BALCO a
LEFT JOIN MIS_TMP_ACC_PL_M b
ON RPAD(TRIM(a.CUENTA_LOCAL), 16, '0') = b.COD_GL AND b.COD_ENTITY = '6' 
WHERE TRIM(a.MOV) = 'S' 
;

--- Aprovisionamiento de la entidad 9-Corredora Seguros ---
INSERT INTO MIS_APR_ACCOUNTING_M
PARTITION (DATA_DATE = '${var:periodo}')
SELECT 'CONT' AS COD_CONT, RPAD(TRIM(a.CUENTA_LOCAL), 16, '0') AS COD_GL, TRIM(a.DESCRIPCION) AS DES_GL, 
    NULL AS COD_ACCO_CENT, NULL AS COD_OFFI, NULL AS COD_NAR, NULL AS COD_BLCE_STATUS, 'CRC' AS COD_CURRENCY, '9' AS COD_ENTITY,
    IF(STRLEFT(TRIM(a.CUENTA_LOCAL), 1) IN ('4', '5'), NULL, a.SALDO_SEGUR) AS EOPBAL_CAP, 
    NULL AS EOPBAL_INT, NULL AS AVGBAL_CAP, NULL AS AVGBAL_INT,
    IF(STRLEFT(TRIM(a.CUENTA_LOCAL), 1) IN ('4', '5'), CAST((a.SALDO_SEGUR) - IFNULL(b.PL, 0) AS decimal(30, 10)), NULL) AS PL, 
    'BALCO_BX' AS COD_INFO_SOURCE
FROM MIS_LOAD_BALCO a
LEFT JOIN MIS_TMP_ACC_PL_M b
ON RPAD(TRIM(a.CUENTA_LOCAL), 16, '0') = b.COD_GL AND b.COD_ENTITY = '9' 
WHERE TRIM(a.MOV) = 'S' 
;

--- Aprovisionamiento de la entidad 11-Puesto de bolsa ---
INSERT INTO MIS_APR_ACCOUNTING_M
PARTITION (DATA_DATE = '${var:periodo}')
SELECT 'CONT' AS COD_CONT, RPAD(TRIM(a.CUENTA_LOCAL), 16, '0') AS COD_GL, TRIM(a.DESCRIPCION) AS DES_GL, 
    NULL AS COD_ACCO_CENT, NULL AS COD_OFFI, NULL AS COD_NAR, NULL AS COD_BLCE_STATUS, 'CRC' AS COD_CURRENCY, '11' AS COD_ENTITY,
    IF(STRLEFT(TRIM(a.CUENTA_LOCAL), 1) IN ('4', '5'), NULL, a.SALDO_VALOR) AS EOPBAL_CAP, 
    NULL AS EOPBAL_INT, NULL AS AVGBAL_CAP, NULL AS AVGBAL_INT,
    IF(STRLEFT(TRIM(a.CUENTA_LOCAL), 1) IN ('4', '5'), CAST((a.SALDO_VALOR) - IFNULL(b.PL, 0) AS decimal(30, 10)), NULL) AS PL, 
    'BALCO_BX' AS COD_INFO_SOURCE
FROM MIS_LOAD_BALCO a
LEFT JOIN MIS_TMP_ACC_PL_M b
ON RPAD(TRIM(a.CUENTA_LOCAL), 16, '0') = b.COD_GL AND b.COD_ENTITY = '11' 
WHERE TRIM(a.MOV) = 'S' 
;

--- Aprovisionamiento de la entidad 15-Davivienda Leasing ---
INSERT INTO MIS_APR_ACCOUNTING_M
PARTITION (DATA_DATE = '${var:periodo}')
SELECT 'CONT' AS COD_CONT, RPAD(TRIM(a.CUENTA_LOCAL), 16, '0') AS COD_GL, TRIM(a.DESCRIPCION) AS DES_GL, 
    NULL AS COD_ACCO_CENT, NULL AS COD_OFFI, NULL AS COD_NAR, NULL AS COD_BLCE_STATUS, 'CRC' AS COD_CURRENCY, '15' AS COD_ENTITY,
    IF(STRLEFT(TRIM(a.CUENTA_LOCAL), 1) IN ('4', '5'), NULL, a.SALDO_ARREN) AS EOPBAL_CAP, 
    NULL AS EOPBAL_INT, NULL AS AVGBAL_CAP, NULL AS AVGBAL_INT,
    IF(STRLEFT(TRIM(a.CUENTA_LOCAL), 1) IN ('4', '5'), CAST((a.SALDO_ARREN) - IFNULL(b.PL, 0) AS decimal(30, 10)), NULL) AS PL, 
    'BALCO_BX' AS COD_INFO_SOURCE
FROM MIS_LOAD_BALCO a
LEFT JOIN MIS_TMP_ACC_PL_M b
ON RPAD(TRIM(a.CUENTA_LOCAL), 16, '0') = b.COD_GL AND b.COD_ENTITY = '15' 
WHERE TRIM(a.MOV) = 'S' 
;

--- Aprovisionamiento de la entidad 23-Grupo del Itsmo ---
INSERT INTO MIS_APR_ACCOUNTING_M
PARTITION (DATA_DATE = '${var:periodo}')
SELECT 'CONT' AS COD_CONT, RPAD(TRIM(a.CUENTA_LOCAL), 16, '0') AS COD_GL, TRIM(a.DESCRIPCION) AS DES_GL, 
    NULL AS COD_ACCO_CENT, NULL AS COD_OFFI, NULL AS COD_NAR, NULL AS COD_BLCE_STATUS, 'CRC' AS COD_CURRENCY, '23' AS COD_ENTITY,
    IF(STRLEFT(TRIM(a.CUENTA_LOCAL), 1) IN ('4', '5'), NULL, a.SALDO_GRPI) AS EOPBAL_CAP, 
    NULL AS EOPBAL_INT, NULL AS AVGBAL_CAP, NULL AS AVGBAL_INT,
    IF(STRLEFT(TRIM(a.CUENTA_LOCAL), 1) IN ('4', '5'), CAST((a.SALDO_GRPI) - IFNULL(b.PL, 0) AS decimal(30, 10)), NULL) AS PL, 
    'BALCO_BX' AS COD_INFO_SOURCE
FROM MIS_LOAD_BALCO a
LEFT JOIN MIS_TMP_ACC_PL_M b
ON RPAD(TRIM(a.CUENTA_LOCAL), 16, '0') = b.COD_GL AND b.COD_ENTITY = '23' 
WHERE TRIM(a.MOV) = 'S' 
;

--- Aprovisionamiento de la entidad 21-Davivienda Seguros ---
INSERT INTO MIS_APR_ACCOUNTING_M
PARTITION (DATA_DATE = '${var:periodo}')
SELECT 'CONT' AS COD_CONT, RPAD(TRIM(a.CUENTA), 16, '0') AS COD_GL, TRIM(a.DESCRIPCION) AS DES_GL, 
    NULL AS COD_ACCO_CENT, NULL AS COD_OFFI, NULL AS COD_NAR, NULL AS COD_BLCE_STATUS, 'CRC' AS COD_CURRENCY, '21' AS COD_ENTITY,
    IF(STRLEFT(TRIM(a.CUENTA), 1) IN ('4', '5'), NULL, a.SALDO_ACTUAL) AS EOPBAL_CAP, 
    NULL AS EOPBAL_INT, NULL AS AVGBAL_CAP, NULL AS AVGBAL_INT,
    IF(STRLEFT(TRIM(a.CUENTA), 1) IN ('4', '5'), CAST((a.SALDO_ACTUAL) - IFNULL(b.PL, 0) AS decimal(30, 10)), NULL) AS PL, 
    'BAL_SEGUROS' AS COD_INFO_SOURCE
FROM MIS_LOAD_BAL_SEGUROS a
LEFT JOIN MIS_TMP_ACC_PL_M b
ON RPAD(TRIM(a.CUENTA), 16, '0') = b.COD_GL AND b.COD_ENTITY = '21' 
WHERE a.LARGO = 15 
;

--- Limpieza de tablas temporales --- 
TRUNCATE TABLE IF EXISTS MIS_TMP_ACC_PL_M;
DROP TABLE IF EXISTS MIS_TMP_ACC_PL_M;