--------------------------------------------------------------- ASIG. DIM. CONTABLE ---------------------------------------------------------------

USE ${var:base_datos};
SET DECIMAL_V2=FALSE;

------------ Asignación del Agrupador Contable ------------
TRUNCATE TABLE IF EXISTS MIS_TMP_STG_${var:tabla}_M_1;
DROP TABLE IF EXISTS MIS_TMP_STG_${var:tabla}_M_1;
CREATE TABLE MIS_TMP_STG_${var:tabla}_M_1 AS
SELECT APR.*, CAF.COD_GL_GROUP, CAT.DES_GL_GROUP, CAT.ACCOUNT_CONCEPT 
FROM (
    SELECT TMP.* 
    FROM MIS_APR_${var:tabla}_M TMP 
    WHERE TMP.DATA_DATE='${var:periodo}') APR 
LEFT JOIN MIS_PAR_REL_CAF_ACC CAF
ON APR.COD_GL = CAF.COD_GL AND APR.COD_ENTITY = CAF.COD_ENTITY AND APR.COD_CURRENCY = CAF.COD_CURRENCY
LEFT JOIN MIS_PAR_CAT_CAF CAT
ON CAF.COD_GL_GROUP = CAT.COD_GL_GROUP;

------------ Insercion Tabla de Rechazos de Agrupador Contable ------------
INSERT INTO MIS_REJECTIONS_DIMENSIONS_M (DIM_REJ, COD_ENTITY, COD_CURRENCY, COD_GL, COD_GL_GROUP, COD_ACT_TYPE, COD_PRODUCT, COD_SUBPRODUCT, COD_RATE_TYPE, COD_BLCE_STATUS, COD_VALUE, 
    COD_BLCE_PROD, COD_MANAGER, TYP_DOC_ID, COD_SEGMENT, COD_COUNTRY, AMO_EOPBAL, AMO_PL) 
PARTITION (DATA_DATE, COD_CONT)
SELECT 'AGRUPADOR CONTABLE' AS DIM_REJ, DWH.COD_ENTITY, DWH.COD_CURRENCY, DWH.COD_GL, 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 
    'N/A', 'N/A', 'N/A', 'N/A', 'N/A', CAST(SUM(DWH.EOPBAL_CAP) AS DECIMAL(30,10)) AS AMO_EOPBAL, CAST(SUM(DWH.PL) AS DECIMAL(30,10)) AS AMO_PL, DWH.DATA_DATE, DWH.COD_CONT 
FROM MIS_TMP_STG_${var:tabla}_M_1 DWH 
WHERE DWH.COD_GL_GROUP IS NULL
GROUP BY DWH.DATA_DATE, DWH.COD_CONT, DWH.COD_ENTITY, DWH.COD_CURRENCY, DWH.COD_GL
HAVING SUM(DWH.EOPBAL_CAP) <> 0 OR SUM(DWH.PL) <> 0; --Inicamente se guardan rechazos con saldos diferente de cero

--- Limpieza de partición ----
ALTER TABLE MIS_DWH_${var:tabla}_M
DROP IF EXISTS PARTITION (DATA_DATE = '${var:periodo}');

------------ Insercion de registros en tabla DWH ------------
INSERT INTO MIS_DWH_${var:tabla}_M PARTITION (DATA_DATE)
SELECT DWH.COD_CONT, DWH.COD_GL, DWH.DES_GL, DWH.COD_ACCO_CENT, DWH.COD_OFFI, DWH.COD_NAR, DWH.COD_BLCE_STATUS, DWH.COD_CURRENCY, 
    DWH.COD_ENTITY, DWH.EOPBAL_CAP, DWH.EOPBAL_INT, DWH.AVGBAL_CAP, DWH.AVGBAL_INT, DWH.PL, DWH.COD_INFO_SOURCE, 
    DWH.COD_GL_GROUP, DWH.DES_GL_GROUP, DWH.ACCOUNT_CONCEPT, DWH.DATA_DATE 
FROM MIS_TMP_STG_${var:tabla}_M_1 DWH 
WHERE DWH.COD_GL_GROUP IS NOT NULL;

------ Eliminación de tablas temporales ------
TRUNCATE TABLE IF EXISTS MIS_TMP_STG_${var:tabla}_M_1;
DROP TABLE IF EXISTS MIS_TMP_STG_${var:tabla}_M_1;